### ISSUE TITLE
CJ4: Failure of LNAV to track route

### ISSUE THREAD

**Issue by Swagbasket** [Working-Title-MSFS-Mods/fspackages#1000]
Issue description: Although LNAV and AP are engaged, the plane does not fly to and then track the magenta line. The flight director does not point the plane towards the magenta line when this error occurs. I have observed the error on a SID and STAR, but I have not seen it during cruise. I initially thought it might occur while trying to complete a procedure turn (not yet implemented), but it also happened simply flying from waypoint to waypoint in a straight line. 

Replication: I can replicate the bug simply by taking a flight with a SID and/or STAR. 

Included images show the PFD and MFD shortly after the error occurs.
![Screenshot (37)](https://user-images.githubusercontent.com/80488569/110856433-3cf2cc80-827d-11eb-99d0-29498f1193fd.png)
![Screenshot (34)](https://user-images.githubusercontent.com/80488569/110856452-42e8ad80-827d-11eb-88fa-23e4e1008f88.png)
![Screenshot (32)](https://user-images.githubusercontent.com/80488569/110856475-4b40e880-827d-11eb-9009-151d1d2e9a8f.png)

**Comment by Swagbasket** [comment]
Removal of the only community addons I have (a32nx, a32nx liveries, and Navigraph navdata) allowed me to fly the problem SID without issue.

**Comment by MoemenShahawy** [comment]
The A32x is causing a lot of issues with all Working Title mods after the last update

**Comment by dga711** [comment]
Will close for now as 11.2 should have fixed a possible case of that.

Feel free to reopen if issue persists.
