### ISSUE TITLE
Avionics master CJ4

### ISSUE THREAD

**Issue by Bomberpj** [Working-Title-MSFS-Mods/fspackages#1008]
Battery turns on avionics but avionic switch inactive as is FMS 1 only co pilot active but with keyboard input from captain fms used No Navigraph 
![Microsoft Flight Simulator 13_03_2021 3_02_23 PM](https://user-images.githubusercontent.com/71881863/111022347-35622d80-840d-11eb-8b4f-2fda84ca424c.png)
for access

**Comment by slip664** [comment]
Either the mod is not installed correctly or you have a mod conflict.
-Be sure to delete the old version COMPLETELY from your community folder.
-Download the latest version, 0.11.1, from our Github
-Make sure to restart the sim after adding any mods.
-If the problem persists, remove all mods from the community folder and add them back in one by one until you find out which one is causing a problem.

**Comment by Bomberpj** [comment]
Completed all steps, cleaned out comm folder.(only WC cj4 in there)
same issue .
Reloaded a copy from github and put direct into comm folder. Not only no
change it actually had a CTD

**Comment by Bomberpj** [comment]
Found it, the bravo throttle had switch engaged for avionics master but
only on /off not despatch. Deleted binding and all good.
