### ISSUE TITLE
CJ4 v0.11.2 Arm emergency lights when using ctrl-e to start engines?

### ISSUE THREAD

**Issue by hallidave** [Working-Title-MSFS-Mods/fspackages#1010]
I noticed when I start the engines with ctrl-e that there was an EMER LIGHTS NOT ARMED warning. Should the emergency lights be armed automatically when the engines are started this way so that there are no warnings after start?

**Comment by dga711** [comment]
since 11.2 the EMER LIGHT switch is not inop anymore. so you have to flip it to ARMED as per checklist 
![image](https://user-images.githubusercontent.com/2995606/111053511-ada80d80-8464-11eb-8de1-267456513d8e.png)
