### ISSUE TITLE
Missing traffic display

### ISSUE THREAD

**Issue by SpaceBanana930** [Working-Title-MSFS-Mods/fspackages#1011]
I've just noticed that in the TBM 930, on the MFD map view I used to be able to see other planes (traffic but not players) when zoomed to 50NM or less, I can see the traffic in game, but not on the MFD. Is this a bug on my end, a new version incompatibility or a known issue with the mod? Has anyone noticed this too? I don't know how long ago this has started since I've been flying in areas of no traffic for the last few weeks

**Comment by cywang90** [comment]
The traffic display has been temporarily disabled pending the implementation of one that is more accurate to the real unit.

**Comment by SpaceBanana930** [comment]
> The traffic display has been temporarily disabled pending the implementation of one that is more accurate to the real unit.

Thanks for the info. Glad it isn’t an issue on my end

**Comment by cywang90** [comment]
Resolved with v0.6.0
