### ISSUE TITLE
CJ4 v0.11.2: Strange PFD Displays

### ISSUE THREAD

**Issue by munala** [Working-Title-MSFS-Mods/fspackages#1012]
I downloaded the latest version [v0.11.2](https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.11.2) and installed following the install instructions, including deleting the previous version from community folder. When I switch on avionics the  PFDs look like this:
![Microsoft Flight Simulator Screenshot 2021 03 14 - 13 30 36 83](https://user-images.githubusercontent.com/22608948/111066950-c818d000-84d2-11eb-936e-d73560327dee.png)

I decided to reinstall v0.11.1 to see if it will have the same issue. I deleted v0.11.2, downloaded v0.11.1 and installed v0.11.1. This time when I switch on the avionics they are blank. I can see the brightness increase but everything is blank.

I then decided to reinstall v0.11.1 (deleting from community folder first) but using the ZIP file I downloaded 4 days ago. This time everything worked as expected.

Last night I did a flight without any issues on v0.11.1. The only thing I did to the sim after is to update the CJ4 to v0.11.2.
This issue is the kind of issue you expect from user error but I can't remember doing anything between last night's flight and today other than updating the CJ4.

**Comment by dga711** [comment]
Hey. That is an issue that came up with the latest sim update. The instruments sometimes don't initialize properly on flight start.
Just restarting the flight or starting a new one should solve it.

**Comment by dga711** [comment]
In addition. As @mattnischan just reminde me, it even was listed as a known issue in the MSFS Changelog

![image](https://user-images.githubusercontent.com/2995606/111068481-2c369680-84c9-11eb-914b-c54f34b13bcd.png)

**Comment by munala** [comment]
Thanks
