### ISSUE TITLE
Feature Request: CJ4 | Independent Flight displays and FMCs

### ISSUE THREAD

**Issue by rkmyers** [Working-Title-MSFS-Mods/fspackages#1015]
Hi WT Dev Team,

I’ve mentioned this and tbf, kindly received a response to this idea in the discord channel. 

By posting a feature request, I’m by no means not accepting that answer. On the contrary, it explains why the feature hasn’t been implemented to date. Performance resulting in a considerable (15-20) FPS hit. 

My specific idea would be to implement this as an option in the ‘MOD Set’ menu. I do fully appreciate that most people would not be willing/able to accept that performance hit, and thus it makes it hard to justify the dev time for a feature that’s unlikely to be used. 

Just wanted to float the idea here though as this is the place for feature requests. 

The benefits I’m looking to achieve really are related to the FMC but could include the PFD and MFDs too. The ability to have the tuning page on the r/h FMC to make ATC comms easier. Charts open on one MFD whilst maintaining a navigational display such as PPOS on the other. Etc etc. 

Thanks for all the hard work and congrats on the Flight Simulator Partnership. 👏👏👏

**Comment by K20017** [comment]
It's currently not possible to have this as a toggle-able feature, it either needs to be split or not.  Performance will be investigated in the future. 👍

**Comment by rkmyers** [comment]
Great, thank you for the response 😊
