### ISSUE TITLE
CJ4: Possible bug with procedure transitions

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#102]
From this avsim post
https://www.avsim.com/forums/topic/585217-cj4-community-mod-by-working-title-released/?do=findComment&comment=4355672

"SBRJ airport, IH1C procedure, i can't select any transition that this procedure allows you to (BITAK, NAXOP, SIDUR, UMBAD waypoints)"

Would like to see if this is repeatable, is widespread, impacts only departures or also arrivals/approaches?

**Comment by dga711** [comment]
Should be fixed in 0.4.0
