### ISSUE TITLE
CJ4: Issues copying files to Community folder (v0.11.3)

### ISSUE THREAD

**Issue by JRHorse** [Working-Title-MSFS-Mods/fspackages#1024]
When copying the contents of the fspackages-cj4-v0.11.3 folder to my FS Community folder, I get errors that the following files cannot be copied:

AttitudeIndicator.js
XMLEngineDisplay.js
ICON_TSC_WAYPOINT_AIRPORT_PAVED_NONTOWERED_NONSERVICED.svg
AttitudeIndicator.js
XMLEngineDisplay.js

The error for each file is:
Error 0x80010135: Path Too Long

**Comment by slip664** [comment]
This is not the correct file. The current version is 0.11.2 and can be found here at the bottom of the page. Download the .ZIP and not the source code.

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.11.2

**Comment by JRHorse** [comment]
Thank you for the heads up. The link to the current version did take me to 0.11.3 this morning.
