### ISSUE TITLE
CJ4 Issues A/P Disconnects,Panel Lights & NO Small degree Increments when selecting heading / Altitude with mouse wheel 

### ISSUE THREAD

**Issue by Ayotteted123** [Working-Title-MSFS-Mods/fspackages#1026]
Just did 2 flights with the latest Mod, one was a 3-hour flight and it was great for 2 hours 45 mins and the other was a 45 min flight and it switched off after 30 mins ... both times the A/P disconnects I will not turn on.

NO A/P Panel lights to let me know what A/P modes are on 

And not able to select small heading increments and altitude levels with the Mouse wheel 

Tried adjusting sensitivity of the wheel in settings but no good

**Comment by mattnischan** [comment]
@Ayotteted123 

When you say the A/P disconnects, what do you mean?

> NO A/P Panel lights to let me know what A/P modes are on

The CJ4, both in the sim and in real life, have no lights on the AP panel buttons. The current AP mode is displayed on the top of the PFD.

> And not able to select small heading increments and altitude levels with the Mouse wheel

This is a sim issue and not an issue with the CJ4. Please see https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173

**Comment by Ayotteted123** [comment]
It just goes off and announces Autopilot ... I then cant switch it back on

**Comment by mattnischan** [comment]
@Ayotteted123 We don't have any code that automatically turns the autopilot on or off, it can only be controlled by a key or a controller. Please check your control bindings and ensure that you don't accidentally have something bound to AP disconnect.

**Comment by Ayotteted123** [comment]
Will do

**Comment by K20017** [comment]
Does it disconnect automatically?  If so, maybe you have a rogue hardware binding somewhere.  Also check the position of the AP/YD disconnect bar that is beneath the AP button.  It's a toggle and the AP will not re-engage unless that bar is in the up position.

**Comment by Ayotteted123** [comment]
> Does it disconnect automatically? If so, maybe you have a rogue hardware binding somewhere. Also check the position of the AP/YD disconnect bar that is beneath the AP button. It's a toggle and the AP will not re-engage unless that bar is in the up position.

YES thanks

**Comment by Ayotteted123** [comment]
OK i think it was the A/P Y/D switch that I must have it by mistake

**Comment by Ayotteted123** [comment]
Just the small increment problem now when selecting Hdg or Alt ?

**Comment by mattnischan** [comment]
@Ayotteted123 Please take a look at the link provided in my first reply. The increment problem is a MSFS issue that we can't address.

**Comment by Ayotteted123** [comment]
Thanks, I will check that too

**Comment by Ayotteted123** [comment]
> @Ayotteted123
> 
> When you say the A/P disconnects, what do you mean?
> 
> > NO A/P Panel lights to let me know what A/P modes are on
> 
> The CJ4, both in the sim and in real life, have no lights on the AP panel buttons. The current AP mode is displayed on the top of the PFD.
> 
> > And not able to select small heading increments and altitude levels with the Mouse wheel
> 
> This is a sim issue and not an issue with the CJ4. Please see https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173

Brilliant and thanks
