### ISSUE TITLE
CJ4 0.11.3 LNAV Chasing Magenta Line, Random Left Turns

### ISSUE THREAD

**Issue by nomad1227** [Working-Title-MSFS-Mods/fspackages#1030]
I am having an issue where the LNAV is chasing the magenta line after advancing to the next waypoint again. Cycled LNAV, tried straightening out by using a heading and then turning LNAV back on, nothing fixes it. In the latter example, I got reestablished on the correct track with HDG mode, and when I turned LNAV back on, I went into a 30 degree left bank. Then it started chasing again. Also, with live weather on and a hard left crosswind, the aircraft crabbed appropriately to stay on track, the randomly banked 15-20 degrees left for no reason. The last one may only be associated with live wx, I still need to test that theory.

**Comment by mattnischan** [comment]
This is caused by one of two issues:

1) Please ensure that your flight model is set to Modern and not Legacy
2) Make sure you have sufficient deadzone in your yoke and rudder sensitivity settings in the sim. I would try at least 10%. This ensures that there are no phantom small inputs being fed into the sim that cause the AP to apply continuous trim to even out, eventually resulting in a max bank scenario

**Comment by nomad1227** [comment]
Ok, I added new dead zones and verified the modern flight model. I will test further.

**Comment by nomad1227** [comment]
So, as of now, there don't seem to be any phantom small inputs. Dead Zones 15-20%. The left turns have gotten smaller, but now I snake back and forth when it should track straight/level and every now and again I lose or gain about 1000 feet at random, but the aircraft realizes it and corrects. I can provide a screen grab of that issue, if necessary.

**Comment by K20017** [comment]
If you disconnect your hardware completely, does the issue go away?  It seems strange for your altitude to change, that could be the result of the weather (barometric pressure in this case) instantly changing as well.

**Comment by nomad1227** [comment]
Yup, i think so too, after a little deeper digging. I'm gonna close this and chalk it up to live wx issues. Thanks y'all.
