### ISSUE TITLE
Throttle key binding does not work

### ISSUE THREAD

**Issue by N6112FJ** [Working-Title-MSFS-Mods/fspackages#1031]
I sent my keyboard number keys 1-9 to correspond with 10% through 90% throttle. In CJ4 pressing 5 for example advances throttles but only while I hold 5. Once I release 5 throttle go back to idle. If I do the same in TBM throttles remain at 50%

**Comment by dga711** [comment]
Duplicate of #892

**Comment by N6112FJ** [comment]
Thank you!
