### ISSUE TITLE
Throttle

### ISSUE THREAD

**Issue by SlowbirdDC** [Working-Title-MSFS-Mods/fspackages#1033]
I am not able to move the throttle levers, not with the X52 nor with the mouse. Anyone having similar issues? 

Could it be some of the other mods? I have some sceneries activated with the Addon Linker as FBW A320, Longitude mod, WT G1000, WT G3000 (+roaddata), Trees_Distance_Draw_Fix, GAIST_MSFS and few liveries.

**Comment by dga711** [comment]
There is usually 2 possible reasons for this
1. You are using a incompatible livery
2. There is as simconnect.cfg in the Documents folder on your PC. There was a problem with tools like Kinetic Gliders in the past where this file was created and renders simconnect things inop
