### ISSUE TITLE
Simbrief connection and loading of flightplan issue

### ISSUE THREAD

**Issue by rh5588** [Working-Title-MSFS-Mods/fspackages#1037]
![image](https://user-images.githubusercontent.com/78756249/111888077-35e06280-89d1-11eb-9d70-32d7151cfba3.png)

When I try and recall my flight plan it comes up with this message above even though I have definitely put the right username in.

**Comment by flymypi** [comment]
username or pilot Id?

[See point 1](https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Frequently-Asked-Questions)
