### ISSUE TITLE
Cannot catch ILS in NAV mode = WT JC4 with WT G3000 current MODS

### ISSUE THREAD

**Issue by ahs712d** [Working-Title-MSFS-Mods/fspackages#1038]
Thank you for the great products and congrats on the engagement with Microsoft

Im am not using the FMS yet. First I want to check that the A/C flies reasonably well with these 2 mods from WT.
- I can fly OK using the  Flight Guidance Panel and PFD using LNAV as "selected navigation source".
- I tune radios using the TUN button in the FMS. (ILS freq for example)
- I can see in the PFD CDI display that the ILS freq has been tuned
- When I press APPR in the AP the APPR LOC and GP vertical seem to arm but as I fly closer to the runway It's evident that neither becomes active. So, I disengage the AP and land by hand. Often I have to go around because I end up too high waiting the ILS to become active.

I would appreciate guidance on how to make this work, This works well with the TBM9 having the same WT G300 MOD.

Regards
AHS712D Alvaro Escorcia KSGR
AirHispania virtual airlines.

**Comment by mattnischan** [comment]
@ahs712d Right now you can't fly an ILS approach unless you have that approach selected in the FMS. So, I would do that and see if you still have issues.

**Comment by ahs712d** [comment]
Dear Matt, Awesome prompt support.
You guys bring tremendous value both to the community and going forward to the core product line.
Let me go back and study the documentation to learn the FMS
Regards
AHS712D Alvaro Escorcia KSGR
AirHispania Virtual Airlines.
