### ISSUE TITLE
CJ4 fuel flow and power curve issue

### ISSUE THREAD

**Issue by nrcrate** [Working-Title-MSFS-Mods/fspackages#1039]
This may be known but I noticed while pulling the power back to descend I go from about 350lbs/hr/side at 80% N1 to 750lbs/hr/side at 75% N1 and back down as I continue reducing. This was at FL400. I noticed that additionally I will get a power surge related to the fuel flow but NOT indicated by N1 or N2. I kept testing this during the descent and noticed it continued to happen, albeit at higher fuel flow values as I continued descending.

**Comment by nrcrate** [comment]
I have created a video to demonstrate the problem.

https://www.youtube.com/watch?v=7cWOAiDq3gQ

**Comment by K20017** [comment]
Fixed internally.
