### ISSUE TITLE
CTD FBW A320 dev 12e8314 Flight egll to eham crash to desktop

### ISSUE THREAD

**Issue by MicroCire** [Working-Title-MSFS-Mods/fspackages#1040]
I can not predict when the crash happens but I did the flight twice and I have the sound which disappears a few seconds before and then back to the windows desktop. MFS 2020 box premium deluxe and nothing in the community i join the two file debug of windows report.
![Capture d’écran 2021-03-22 112249](https://user-images.githubusercontent.com/81158113/111975522-fd3fa680-8b00-11eb-8a64-28b07f22bb00.png)
![Capture d’écran 2021-03-22 112352](https://user-images.githubusercontent.com/81158113/111975625-1a747500-8b01-11eb-8a7e-c007f8de0953.png)
If you need another things ask to me. Sorry for my poor langage...

**Comment by mattnischan** [comment]
@MicroCire Why are you reporting this CTD here? This is not a support board for either general MSFS issues nor FlyByWire issues, so I think you may have landed in the wrong place by accident.

I would recommend filing this on the FlyByWire GitHub or the MSFS Zendesk.

**Comment by MicroCire** [comment]
Yes it is a wrong landing ! sorry!

**Comment by mattnischan** [comment]
@MicroCire No worries at all! :-)
