### ISSUE TITLE
Future Ideas 

### ISSUE THREAD

**Issue by FSAviator** [Working-Title-MSFS-Mods/fspackages#1041]
Curious if you are can add in the visual fixes for visual approaches. As of now you have a 5 nm tail which you can edit to 3 nm (preferred). I would like to be able to add a base leg in IDX/FIX in the FMC. Also, would like to edit the approach slope to match the airports papi etc. Thank you.

**Comment by FSAviator** [comment]
This is for the CJ4. Also, wanted to mention the airport ring in fms would be a nice feature as well.

**Comment by K20017** [comment]
You can already do that.  I have it highlighted here: https://www.youtube.com/watch?v=yABK_u3udXQ

You can change the approach slope angle by changing the VPA in VNAV SETUP.

**Comment by FSAviator** [comment]
Well I’ll be.... Perfect! I appreciate it!
