### ISSUE TITLE
working title CJ4 create a lot of problems

### ISSUE THREAD

**Issue by papinou57** [Working-Title-MSFS-Mods/fspackages#1046]
without "working title CJ4  0.11.3"  FMS is black -throttles ok- 

with "working title CJ4 0.11.3 : FMS is OK  but inoperative throttle levers and  connection network VATSIM impossible ((

**Comment by mattnischan** [comment]
@papinou57 Please ensure you are using a compatible livery. You may also have a rogue simconnect.cfg in your Documents folder that interferes with our FADEC.

I'm not sure what you mean by being unable to connect to VATSIM. There are no APIs for us to talk to the network from aircraft code.
