### ISSUE TITLE
CJ4 and the Honeycomb Alpha Yoke

### ISSUE THREAD

**Issue by gnkidwell** [Working-Title-MSFS-Mods/fspackages#1052]
So I know the autopilot keybinds are an issue with say other hardware like the Homeycomb Bravo, but I just noticed ever since I got the Alpha, my heading bug was going up by 10 and altitude by the 1000.... In order to resolve this I had to completely unbind the magneto switch off, left, right, both, start... And I cannot use any of the light switches, battery master, alternator switch, or avionics switches or this behaviour returns. Not sure if this is a similar bug, but can this be documented as an issue? So other people with the Alpha know these items cannot be used and the magneto switch must be unbound 100%?

**Comment by dga711** [comment]
Hi. This is an ongoing issue with the sim https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173
