### ISSUE TITLE
[G3000] PFD ETE displays "Infinity+NaN" while GS is 0

### ISSUE THREAD

**Issue by Nezz** [Working-Title-MSFS-Mods/fspackages#1059]
Loading into any flight with a flight plan and not moving should trigger the issue. The MFD's display is correctly displays `__:__`.
![Image](https://user-images.githubusercontent.com/431167/112767315-b41ab580-901e-11eb-8e92-aff200d936c7.png)

**Comment by cywang90** [comment]
Fixed with v0.5.1.
