### ISSUE TITLE
[G3000] PFD speed tape displays 40 when stopped

### ISSUE THREAD

**Issue by Nezz** [Working-Title-MSFS-Mods/fspackages#1060]
It should display `---` until an IAS of 40 knots is reached. The airspeed trend vector should also not be displayed at such low speeds. Once you reach 40 knots the trend vector immediately pops in.
![Speed tape](https://user-images.githubusercontent.com/431167/112767483-add90900-901f-11eb-8bea-4508fe978ff2.png)

**Comment by cywang90** [comment]
Fixed with v0.5.1.
