### ISSUE TITLE
[G3000] UTC is a timer; does not display UTC

### ISSUE THREAD

**Issue by apolinski** [Working-Title-MSFS-Mods/fspackages#1061]
UTC field on PFD does not display UTC instead seems to show a timer. (using Longitude mod by Dakfly)   It starts a timer immediately upon aircraft load.  G3000_0.5.0

**Comment by cywang90** [comment]
Not sure what you mean. The UTC field in the longitude is working as intended with or without dakfly's mod. If the time displayed isn't in sync with real-world time, make sure you have "Live" time enabled in the sim.

**Comment by apolinski** [comment]
I always have Live time enabled. When I loaded in the UTC time was 00:00:00 and started counting up as soon as I turned on the battery.  I've just tested with 0.5.1 and now it seems to work properly.
