### ISSUE TITLE
[CJ4] VNAV not meeting "At or below" constraints

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#1064]
EAGUL6 arrival into KPHX, starting at GUP. Cruise altitude FL400.
![msedge_nlIfaloghc](https://user-images.githubusercontent.com/72550869/112824789-949c8080-9050-11eb-85f7-18da6b1484ad.png)
First constraint is a FL330B at TINIZ. This screenshot shows ALT selector 7000, VNAV armed. At this point, no runway is selected, haven't picked up ATIS, and ATC hasn't advised whether landing east or west:
![explorer_sByARKzyWZ](https://user-images.githubusercontent.com/72550869/112825328-3e7c0d00-9051-11eb-9e3d-79512201ec50.png)
Now expecting "landing east", so RWY 7R selected, and the FMS loads the appropriate fork of the STAR. Note how the TOD has moved (this seems to be where the problems begin):
![explorer_5qUIcuB4b3](https://user-images.githubusercontent.com/72550869/112825667-a9c5df00-9051-11eb-9b3c-e93eea460656.png)
Approaching TINIZ, VNAV has just started the descent, so not going to make the FL330B constraint:
![explorer_geM8uk0SzW](https://user-images.githubusercontent.com/72550869/112825877-e7c30300-9051-11eb-86f9-2352fd69d8c9.png)
PAYSO has a FL240A/FL300B constraint, crossed at just below FL330:
![explorer_h326FD3RKE](https://user-images.githubusercontent.com/72550869/112826119-307abc00-9052-11eb-80db-04a1e3fc4059.png)
The next point with an "At or below" constraint on the arrival is HOMRR 17000B, here about to cross HOMRR, well above 17000:
![explorer_IVRIXq5X8N](https://user-images.githubusercontent.com/72550869/112826336-7768b180-9052-11eb-95c1-43bfc4abc332.png)

At this point I stopped the test. This was a recreation of a prior flight so I could gather screenshots, so the result was the same on two different flights.

**Comment by luciopl** [comment]
I found a TOD calculation in this route: SBSV RWY 10 - SID KIBIX 1A Trans. ELEFA - UZ17 to APINO - STAR OCELO 3A Trans. APINO - ILS Y RWY 11L.  There is a constrain FL180B but TOD is way far from this fix.   I posted more details here: https://discord.com/channels/750764704175226992/767761280366805022/851562064459595816
