### ISSUE TITLE
Missing Barber Poll on Speed Tape

### ISSUE THREAD

**Issue by SoCalDude** [Working-Title-MSFS-Mods/fspackages#1067]
On the secondary/backup airspeed indicator, there is the over speed "barber poll", but is it not on the PFD airspeed indicator. (see image below)

I'm flying the TBM-930 with the G3000 mod v0.5.1 and the Mugz TBM-930 improvement project mod, v0.5.11.

![Microsoft Flight Simulator Screenshot 2021 03 29 - 19 58 50 54](https://user-images.githubusercontent.com/7506541/112936408-9f035c80-90da-11eb-81d2-c9b3f072c7d1.png)

**Comment by cywang90** [comment]
The standby airspeed indicator is incorrect. Please see the known issues section in the README.md file.

**Comment by SoCalDude** [comment]
> Please see the known issues section in the README.md file.

I missed that. I was looking at the readme file in the “docs” link on [your main GitHub page](https://github.com/Working-Title-MSFS-Mods/fspackages), which does not point to the latest readme file.
