### ISSUE TITLE
[G3000] Longitude does not respond to altimeter controls

### ISSUE THREAD

**Issue by Nezz** [Working-Title-MSFS-Mods/fspackages#1073]
Now that the Longitude's standby altimeter is now slaved to the PFD altimeter, the controls to set the altimeter stopped working:
![Controls](https://user-images.githubusercontent.com/431167/113044579-7d6fa700-91a6-11eb-941d-9e3fdc9da71a.png)

**Comment by cywang90** [comment]
Fixed with v0.6.0.
