### ISSUE TITLE
CJ4 11.3 Displays not on

### ISSUE THREAD

**Issue by paq99** [Working-Title-MSFS-Mods/fspackages#1074]
I just upgraded from v10.0 to 11.3 and on first start-up, battery switch on but not none of displays are activating.  Is this a new thing that requires turning on a switch somewhere?  I didn't see anything about it in the manual.  I don't see any obvious switches either.

Note I also installed the CJ4 interior textures mod.  Could that have something to do with it.

**Comment by dga711** [comment]
Nothing we have heard of yet. Do you use a hardware binding or just flipping the switch with the mouse?

**Comment by paq99** [comment]
Just flipping switch with mouse.  So I closed MSFS and removed the CJ4 textures mod and now I get displays.  However, now flight plan from game won't load - just get's stuck on FP loading.  I am trying a PC restart to see if that helps at all.

**Comment by dga711** [comment]
Did you completely remove the workingtitle-cj4 folder before putting the 11.3 in?

**Comment by paq99** [comment]
I deleted it to recycling bin. Does that qualify as "completely remove"?

**Comment by paq99** [comment]
Update:  restart seems to have helped.  FP now loads.
Will hold off on reinstalling texture mod for a while.
Thanks for help.

**Comment by dga711** [comment]
The mod should be fine, but yeah, whatever works.
