### ISSUE TITLE
[CJ4] Terrain radar appears to have stopped updating as altitude gets higher

### ISSUE THREAD

**Issue by septemptus** [Working-Title-MSFS-Mods/fspackages#1078]
Flying out of VNLK in Himalayas and climbing I notice that as I climb the weather radar on MFD updates as I climb higher removing some of the terrain which I'd now fly above, indicating no collision. Now as I circle around the Himalayas and keep climbing to FL450 I notice that at some point the radar stops updating and starts showing the same image regardless of my altitude.

![image](https://user-images.githubusercontent.com/1033306/113494790-03178d80-94ec-11eb-8b8a-7d14456c2de4.png)

This image was taken at FL370ish well above the mountains but the radar still shows that the mountains are in the path.

To reproduce take of at VNLK, fly left along the valley climbing to FL450 then fly left again as you exit the valley keeping the mountains within the radar.

Feel free to close the issue if this is working as intended, but I'd be grateful if someone could explain why it works this way.

**Comment by mattnischan** [comment]
@septemptus This is actually working as intended. At a certain altitude, the PL21 terrain display stops being relative and just shows high peaks. I'm not totally sure why it is this way (the intention behind it isn't in the books anywhere), but my guess is that they wanted it to show at least something at cruise to give an indication of the terrain below.
