### ISSUE TITLE
SimBrief ID in CJ4 not working after installing G1000

### ISSUE THREAD

**Issue by pbrad74** [Working-Title-MSFS-Mods/fspackages#1080]
I have been thoroughly enjoying the WT CJ4 mod the past few days and have not had any issues with my SB ID. So I thought I'd install the G1000 mod for when I want to fly the C172 but now I get an error that my SB ID is wrong when I try to upload my fp from simbrief. I can uninstall the G1000 and reinstall the CJ4 and it works again. Anybody else having this issue?

**Comment by dga711** [comment]
Hm. Afaik there is no reason these mods would intersect on any of that.

Can you check in MOD SET if there is a whitespace before your PilotId? Does it work after setting it again?

**Comment by pbrad74** [comment]
OK, I went back and looked to see if there was, lo and behold thee was! I'm not sure how but I deleted it and re-entered it and now it's working again. Not sure why this time and not the 4 - 6 other times I tried it. Thanks!
