### ISSUE TITLE
G3000 0.5.1 works only once

### ISSUE THREAD

**Issue by rnovaes1973** [Working-Title-MSFS-Mods/fspackages#1081]
The first time i have installed de WT G3000 was at MSFS 1.14.6.0. It was very difficult to work but i get once at TBM 930 improvement mod. I did one flight but i crash at landing. After that i do not get to G3000 work again at TBM 930. Do you have any advice to G3000 works at TBM 930?

**Comment by cywang90** [comment]
What exactly do you mean when you say it doesn't work? My advice for now would be to try using the mod with an otherwise empty Community folder to rule out any mod conflicts.

**Comment by rnovaes1973** [comment]
I have done that. I left the Community folder empty and the TBM 930 doesn´t turn on the PFD screens, the two edge screens. This start after the MSFS upgrade 1.14.5. When i put the G3000 0.5.1 mod in Community folder the PFD screens turn on but the small two below screens do not turn on. But when i put the TBM 930 improvement V0.5.11 mod by Mugz, sometime the Glass Cockpit turn on, other time do not. I hope i get to explain what i mean....

**Comment by cywang90** [comment]
If the issue persists even without any mods, then it's likely related to the black screen on start-up issue in the base sim introduced with 1.14.5.0 (it was in the known issues in the patch notes). The workaround is to restart the flight.

**Comment by rnovaes1973** [comment]
Thank you. The restart the flight solve the problem. Now i can fly the TBM 930 with G3000 mod.
