### ISSUE TITLE
N-S-E-W buttons in the TBM9 FMS G3000

### ISSUE THREAD

**Issue by ahs712d** [Working-Title-MSFS-Mods/fspackages#1082]
Can someone point me to a doc or tell me how ro use the N-S-E-W buttons in the TBM9 FMS ? is it to enter the coordinates of a point one wants in the FP?  What's the syntaxis to type the coordinates? How to add it?
[https://i.imgur.com/YJVYRKw.jpg?1](url)
![TBM9 NSEW FMC](https://user-images.githubusercontent.com/72442099/113510679-95865400-9521-11eb-81c2-4b819f50b021.JPG)

**Comment by mattnischan** [comment]
@cywang90 can correct me if I'm wrong, but I don't believe that custom latitude/longitude fixes work presently on the G3000, due to its reliance on the stock flight plan system.

**Comment by ahs712d** [comment]
Dar Matt, 
Many thanks for reading this. 
It would be nice to know if this is somewhere on the WT + MSFS roadmap to be implemented
Regards, 
AHS712D Alvaro Escorcia KSGR
AirHispania Virtual Airline

**Comment by cywang90** [comment]
As far as we can tell, the default asobo flight plan manager does not easily allow custom waypoints to be entered into the flight plan. Therefore, as long as the garmins continue to use the default FPM, in all likelihood custom waypoints will not be supported.
