### ISSUE TITLE
CJ4 VNAV issue 0.12 on above and below alt restrictions

### ISSUE THREAD

**Issue by ed42t** [Working-Title-MSFS-Mods/fspackages#1086]
I'm having an issue with VNAV in 0.12 is not taking above xx but below xx constraints into account. 

Just been on LANUR 3P to ENBR and VNAV path didn't get us down for the constraints at BR734 or RATUG. It was on the right path to hit the FAF at the right alt though as a continuous decent (GODID at 4000). Could it be that the VNAV is just treating the 8000B6500A as just a 6500A restriction?

Navigraph database data in case that is relevant

Cheers for the work you do! It's an amazing mod!

**Comment by nrcrate** [comment]
I had this issue with the previous version but have not been able to test the current version yet. I'll report back...
