### ISSUE TITLE
CJ4 v0.12.0 COM frequency tuning decimal point

### ISSUE THREAD

**Issue by KOLMAN13** [Working-Title-MSFS-Mods/fspackages#1087]
Hello,

the previous versions did not require to enter a decimal point when tuning the COM frequency. Seems that this has changed with the latest version. I can live with both options, but I am still curious how this works in the real plane.

Regards
Gerhard

**Comment by dga711** [comment]
HI. Nothing should have changed here between 0.11 and 0.12

Are you referring to that problem which exists for a longer time now  #890  ?

**Comment by KOLMAN13** [comment]
Just double checked and reinstalled v0.11.3 which was the previous version I was using.
Here I can enter 12498 or 124980 in the scratchpad to change the COM frequency.
If I do the same thing in v0.12.0 an “INVALID ENTRY” message shows up in the scratchpad.
Only 124.98 or 124.980 works.

**Comment by slip664** [comment]
I'll look into this.
