### ISSUE TITLE
CJ4: expose additional plane data and behavior to SIMCONNECT, LVAR and EVENTS 

### ISSUE THREAD

**Issue by frankkopp** [Working-Title-MSFS-Mods/fspackages#1088]
Hi,

awesome update with version 0.12!

A few small things around  setting up my Logitech Multipanel (Autopilot, Pitch, Flaps) and Pro Switch Panel with SPAD.NeXt.
Most things work although variables used seem to be a bit inconsistent.

These things don't work and it would be great if they could be added or fixed:
* APPR Mode on is missing: WT_CJ4_APR_HOLD_ON (LVAR) --> there is a event so switching works but reading status does't
* Also misses corresponding PRESSED event: WT_CJ4_APR_HOLD_PRESSED (EVENT)
* Selected Altitude is not exposed correctly: SIMCONNECT:AUTOPILOT ALTITUDE LOCK VAR changes when alt is changes but reverts to a nonsensible number (mostly -5000). 
![image](https://user-images.githubusercontent.com/16833201/113597053-6ebc4080-963b-11eb-9f9f-2b0e47dc0f5b.png)
* also turning on/off the panel lights doesn't work as expected. After switching they turn back to what is set on the knob. The knob and its potentiometer settings can be changed but revert to the current knob setting instead of moving the knob. 
![image](https://user-images.githubusercontent.com/16833201/113607544-9b775480-9649-11eb-83a2-77af9cdb4c5e.png)

Thanks

**Comment by dga711** [comment]
Try these

For approach: `H:WT_CJ4_AP_APPR_PRESSED` is our custom H Event to trigger APPR
For appr status: `A:AUTOPILOT APPROACH HOLD` should still work

For alt preselect: Since 0.12 it is managed in index 1 of that var. But I am not sure if spad.next can handle indexed vars I am afraid.  So it would be `AUTOPILOT ALTITUDE LOCK VAR:1`

For panel light try `L:LIGHTING_Knob_Master` from 0-100 (100 is default btw)

**Comment by dga711** [comment]
Sorry, Matt just reminded me that `A:AUTOPILOT APPROACH HOLD` doesnt work anymore because we fly it on our own atm. So that would be missing atm

**Comment by frankkopp** [comment]
Thanks for your quick response.

> For approach: `H:WT_CJ4_AP_APPR_PRESSED` is our custom H Event to trigger APPR
> ~For appr status: `A:AUTOPILOT APPROACH HOLD` should still work~

Yep - I figured. So maybe this could get onto the wishlist :)

> For alt preselect: Since 0.12 it is managed in index 1 of that var. But I am not sure if spad.next can handle indexed vars I am afraid. So it would be `AUTOPILOT ALTITUDE LOCK VAR:1`

Tried that. Unfortunately SPAD.neXt (Alpha) see the variable but it is 0. See screenshot of 41.000ft:
![image](https://user-images.githubusercontent.com/16833201/113625068-b903e880-9660-11eb-8a54-fc5c13e972c1.png)

> For panel light try `L:LIGHTING_Knob_Master` from 0-100 (100 is default btw)
 That worked - although 100% is OFF and 90% if full on is weired - but looking at the knob it makes sense :)

> Also see here https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables
I actually went through them before I created the ticket - but thanks of course. 

Thanks so much for your help

**Comment by dga711** [comment]
> That worked - although 100% is OFF and 90% if full on is weired - but looking at the knob it makes sense :)
Yeah sorry, should have clarified. 100 is the DAY setting which practically is all lights off. Then its 90-0 from there ;)

Are you sure spad.next supports indexed variables? I don't know about that.

**Comment by frankkopp** [comment]
> > That worked - although 100% is OFF and 90% if full on is weired - but looking at the knob it makes sense :)
> > Yeah sorry, should have clarified. 100 is the DAY setting which practically is all lights off. Then its 90-0 from there ;)
> 
> Are you sure spad.next supports indexed variables? I don't know about that.

No I'm not :) - trying to find out right know - as my screenshot shows - it at least sees the VAR:1

**Comment by frankkopp** [comment]
Looking at all other values I need for the Logitech Multipanel the AUTOPILOT ALTITUDE LOCK VAR is the only one that does not work. When changing altitude is changes as well to the selected value back quickly changes back to -5000 as if something immediately overwrites the new value. I think this might be a bug - or why would you set this back to -5000 deliberately?

All others (AUTOPILOT VERTICAL HOLD VAR, AUTOPILOT AIRSPEED VAR, etc.) work as expected (without :1).

As far as I could find out, SPAD.neXt supports indexed vars - but the AUTOPILOT ALTITUDE LOCK VAR:1 does not have the correct value when read via SPAD.neXt:

The selected alt for this screenshot is 21.300:
![image](https://user-images.githubusercontent.com/16833201/113728388-5bba7680-96f6-11eb-8482-16da4e547556.png)

**Comment by dga711** [comment]
Here is something from the #hardware channel in our Discord

![image](https://user-images.githubusercontent.com/2995606/113728888-c79cdf00-96f6-11eb-8f0f-6a03afd736b0.png)

Maybe that clarifies it better.

**Comment by frankkopp** [comment]
> Here is something from the #hardware channel in our Discord
> 
> ![image](https://user-images.githubusercontent.com/2995606/113728888-c79cdf00-96f6-11eb-8f0f-6a03afd736b0.png)
> 
> Maybe that clarifies it better.

Thanks - haven't seen this!

**Comment by woodstock327** [comment]
Indeed, indexed vars are supposed to work in spad.next, but at least that particular one doesn't seem to right now, so it's definitely not an issue on WT side.

**Comment by woodstock327** [comment]
spad.next dev confirmed, fix is on the way 🙂

**Comment by frankkopp** [comment]
Fix is coming from SPAD.neXt. Closing this.
 Thanks for the great help.
