### ISSUE TITLE
CJ4: AP text in PFD is a bit close to the frame

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#109]
The text at the top of the PFD is a bit close to the display frame. It's obscured by the frame if you look from what I consider to be a normal head position.

**Comment by K20017** [comment]
We are in the process of changing the PFD/MFD font sizing and positions for better readability so this will be addressed in the coming updates.

**Comment by mattnischan** [comment]
This should have been addressed in #133, which was in 0.3.1. Let us know if it still needs adjustment.

Thanks for the report!
