### ISSUE TITLE
Missing variables in Sim variables wiki entry

### ISSUE THREAD

**Issue by blindye** [Working-Title-MSFS-Mods/fspackages#1090]
https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables

`H:WT_CJ4_AP_APPR_PRESSED` missing from AP mode triggers section

`H:Generic_Lwr_MENU_ADV_DEC` and `H:Generic_Lwr_MENU_ADV_INC` are missing from Lower panel (below MFD) section.

**Comment by dga711** [comment]
Added. Thanks
