### ISSUE TITLE
CJ4 v0.12.0 LWR MENU PLAN no route

### ISSUE THREAD

**Issue by KOLMAN13** [Working-Title-MSFS-Mods/fspackages#1091]
Hello!

Today I tried to check my route with MFD ADV and therefore switched the LWR MENU to PLAN but suddenly the route disappeared. When I go back to PPOS the route shows up again.

Regards
Gerhard

![CJ4 LWR MENU PLAN no route](https://user-images.githubusercontent.com/80632843/113669499-2a20bb80-96b4-11eb-9cb5-505dfcf6a61a.jpg)

**Comment by dga711** [comment]
Did you try pressing TO WPT on MFD ADV?

**Comment by KOLMAN13** [comment]
Thanks, you are right I should have tried TO WPT. Maybe my flightplan was just out of range. A minute ago I completed a different route and was not able to reproduce the problem anyway. So please disregard for now, I will continue checking on my next flights.
