### ISSUE TITLE
Please update/extend Sim Variables documentation

### ISSUE THREAD

**Issue by frankkopp** [Working-Title-MSFS-Mods/fspackages#1094]
I'm missing some variables in the doucmentation and I would like to suggest to add these to the docs page.
(suggested changes in bold and italics)

AP Mode indicators
The indication for active AP modes is run via LVars (read-only)

HDG - L:WT_CJ4_HDG_ON
**SELECTED HDG** _(this should either be AUTOPILTE HEADING LOCK DIR or  AUTOPILTE HEADING LOCK DIR:1)_
LNAV - L:WT_CJ4_NAV_ON
APPR - n/a
VNAV - L:WT_CJ4_VNAV_ON
VS - L:WT_CJ4_VS_ON
**SELECTED V/S** _(this should either be AUTOPILTE VERTICAL LOCK DIR or  AUTOPILTE VERTICAL LOCK DIR:1)_
FLC - L:WT_CJ4_FLC_ON
**SELECTED IAS** _(this should either be AUTOPILTE AIRSPEED LOCK DIR or  AUTOPILTE AIRSPEED LOCK DIR:1)_
ALT - L:WT_CJ4_ALT_HOLD
**SELECTED** ALT - AUTOPILOT ALTITUDE LOCK VAR:1 (is now indexed to get preselect altitude)

**Comment by dga711** [comment]
Added. Thank you
