### ISSUE TITLE
CJ4 leg drawn wrong at Intl Date Line

### ISSUE THREAD

**Issue by MTBehnke** [Working-Title-MSFS-Mods/fspackages#1097]
Legs that cross International Date Line don't continue across line, but instead get drawn as if they continue on same side of the date line.  Image below shows example, and after crossing date line it repeated same issue, but mirrored on east side of line.

![CJ4 Intl Date Line Issue](https://user-images.githubusercontent.com/22116435/114102328-ba195d80-988c-11eb-9da8-bbd253fd3628.png)

**Comment by flymypi** [comment]
This is a known sim issue but it should only be a visual bug. Feel free to reopen the issue should there be abnormal autopilot behaviour connected to this.
