### ISSUE TITLE
CJ4: AP disconnecting mid flight

### ISSUE THREAD

**Issue by julianpoma** [Working-Title-MSFS-Mods/fspackages#110]
This is a very weird one.

I was on a flight on the cruise phase, FL290 and following the FMS1 flightplan. I left the computer for 5 minutes and when I came back, I see my plane turning in circles and descending slighly. I noticed that the AP was disconnected.

Not big deal, I switch it on again and continue with the flight. 

About 40 seconds later, same thing. This time I was on the chair and I noticed that the avionics where switching off and on again. For a brief second the PDF would go black and on again. And the AP was disconnected. It was like if the avionics BUS were resetting itself.

I'm just throwing this here for future ref or if anyone experience the same thing. I have the Carenado Mooney and I experienced the bug where the avionics would die mid flight. So probably this is a bug of the sim itself.

Thanks for the mod and the outstanding work!

**Comment by K20017** [comment]
Hmm, I have not come across this issue yet.  There are so many bugs in the base game that it's hard to determine if the bug was introduced by us, which I would be surprised since we haven't really messed with anything regarding autopilot logic, or has always been there.  We will take note though.

**Comment by cwburnett** [comment]
It seems that sometimes the sim switches to the next waypoint before arriving at the previous one and sometimes it is too soon and leaves the AP without a TO waypoint and this cases LNAV mode to swap to ROL mode. I haven't found the cause of this yet, but it is on our list. Tagging as enhancement since this isn't a bug with the mod.
