### ISSUE TITLE
G1000 and G3000 CTD with 1.15.7.0 version

### ISSUE THREAD

**Issue by telemakox** [Working-Title-MSFS-Mods/fspackages#1107]
It seems that the G1000 mod v3.4 and the G3000 mod v5.1 cause the CTD of the FS2020 version 1.15.7.0

**Comment by mattnischan** [comment]
@telemakox There is currently an issue with some WASM modules (which neither of those mods use) which cause a CTD. Please remove Axis and Ohs, MobiFlight, Spad.next, YourControls, or anything else that uses a standalone WASM module.

**Comment by telemakox** [comment]
Thanks Matt, for your kind answer!

Bruno

Inviato da Posta per Windows 10

Da: Matt Nischan
Inviato: martedì 13 aprile 2021 21:36
A: Working-Title-MSFS-Mods/fspackages
Cc: telemakox; Mention
Oggetto: Re: [Working-Title-MSFS-Mods/fspackages] G1000 and G3000 CTD with 1.15.7.0 version (#1107)

@telemakox There is currently an issue with some WASM modules (which neither of those mods use) which cause a CTD. Please remove Axis and Ohs, MobiFlight, Spad.next, YourControls, or anything else that uses a standalone WASM module.
