### ISSUE TITLE
Garmin Map no longer works after update

### ISSUE THREAD

**Issue by JennyD73** [Working-Title-MSFS-Mods/fspackages#1108]
Map doesnt work in any aircraft if i remove the Garmin mods the default map is working

![ad46121f039f6be0b3cf4b4fc1bb7f8f](https://user-images.githubusercontent.com/75444078/114617767-78c7ea00-9ca0-11eb-992b-3980a39f4614.jpg)

**Comment by hrafnkelle** [comment]
Same issue here.

**Comment by metalunna** [comment]
Same here..I can remove the WTg1000 from the community folder and the stock comes back.
Seems to only affect the MFD

**Comment by jfwharton3975** [comment]
Add my name to the list.

**Comment by JohanBak** [comment]
Likewise. The whole "enable AP and fly straight into the ground" issue returned the first flight after I removed the mod. I forgot how good we had it with this great mod!

**Comment by metalunna** [comment]
One of the devs on their discord server said they are aware of it and are attempting to coordinate with friends at Asobo.
No eta, but will keep us updated

**Comment by paq99** [comment]
CJ4 mod also not working as previously outlined.  Can't import FPL as outlined in tutorial, so didn't try going further.

**Comment by mattnischan** [comment]
@paq99 The CJ4 is currently fully functional. If you have a specific issue I would try our Discord or please open another issue with more details.

**Comment by paq99** [comment]
> 
> 
> @paq99 The CJ4 is currently fully functional. If you have a specific issue I would try our Discord or please open another issue with more details.

My bad.  CJ4 mod had not loaded properly in my Community folder along with the other WT mods.  Sorry for mistaken info.  Have reloaded/restarted and all seems in order so far.  

Again, my apologies.

**Comment by mattnischan** [comment]
@paq99 No worries at all!

**Comment by JennyD73** [comment]
just to add it seems its only the G1000 map not working? the g3000 seemed to be ok can anyone confirm this

**Comment by kaosfere** [comment]
The G1000 map is functional again with our just-released 0.3.5. :)

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g1000-v0.3.5

As always, please let us know if you run into any further trouble.
