### ISSUE TITLE
[CJ4 v0.12.0] Wing Anti-Ice Without Effect

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#1109]
There is no visible icing effect on windows and leading edges despite being in related weather and _Dev Mode > Options > Visual Icing_ progressing to 1.0. This applies to both settings "ON" and "VISUAL ONLY".

Without the mod installed visual icing effect does occur.

Has the effect been disabled for the mod?

![2021 04 13-22 40_01](https://user-images.githubusercontent.com/71787933/114618650-e1679480-9ca9-11eb-9070-71735bb4d9f1.png)

**Comment by slip664** [comment]
Windshield heating is now on automatically when the battery is turned on so you will not see icing on the windshield. This was changed several months ago.

**Comment by sfdeham** [comment]
@slip664 Thanks for your response.

I'm now concentrating on the wing leading edges where I can see icing. However it appears that the WING/ENG ANTI-ICE has no effect, i.e. in related conditions it will build up icing at same speed, regardless if set OFF or ON. You can also see this on the speed the Dev Mode Visual Icing slider moves.

Does this relate to known limitations (bugs) in MSFS or the mod?

**Comment by mattnischan** [comment]
Unfortunately, aircraft code has no ability to change or adjust the icing model at all. We can only tell the sim whether or not deice is on or off. Any icing model inconsistencies would be simulator issues.
