### ISSUE TITLE
FMS on longitude

### ISSUE THREAD

**Issue by richard1000xx** [Working-Title-MSFS-Mods/fspackages#1111]
Sorry if this has been discussed elsewhere

Both screens of the FMS insist on mirroring each other. Cannot find anyway to use them separately. Would be very useful when one is being used to scroll the map - as can be done in the TBM

Richard

**Comment by cywang90** [comment]
Unfortunately, this is the way the instruments are set up in the Longitude. This may be changed at some point in the future, but I don't have an ETA on when it will happen.

**Comment by cywang90** [comment]
Going to close this for now since it's a base sim limitation and we are not planning to address it in the near future.
