### ISSUE TITLE
MFD is not Working with Cerenado Cessna 182

### ISSUE THREAD

**Issue by Mauflo** [Working-Title-MSFS-Mods/fspackages#1112]
Since update of the MSFS to 1.15.7.0 the MOD is not work properly. I tested it with the Cessnas. If I turn off the mod all work properly. When the MFD in the Cerenado Cessna182 and the Asobo 172 is started its not working. It does'nt stay blank but the data's and the maps will not work if you turn it off the PFD is still working!

**Comment by mattnischan** [comment]
We posted a new release which addresses this about 12 hours ago. Please update to the latest release 0.3.5.
