### ISSUE TITLE
TBM 930 G3000 AOA and Wind Indicator inaccurate

### ISSUE THREAD

**Issue by glaurian** [Working-Title-MSFS-Mods/fspackages#1115]
In v5.1 AOA is a negative value and both AOA and Wind widgets are not sized correctly.

Almost seems like these are the stock MSFS indicators from the initial release.

I deleted and replaced the files in the community folder, same result.

**Comment by cywang90** [comment]
Can you please post a screenshot? Thanks.

**Comment by glaurian** [comment]
Attached as requested.

Thanks for your awesome product , Greg

![G3000_AOA_Wind_Indicators_051](https://user-images.githubusercontent.com/72989452/115041510-3406a380-9e98-11eb-838f-c5a63dfedd70.jpg)

**Comment by cywang90** [comment]
They both look fine to me. Keep in mind the tick mark on the AoA indicator is not meant to represent 0 AoA. It's like that in the default sim, but that is actually incorrect. The AoA indicator in the G3000 reports normalized AoA, where 0 (bottom of scale) is equal to zero-lift AoA and 1 (top of scale) represents critical (stall) AoA.

**Comment by glaurian** [comment]
At one point the AOA issue was corrected. It’s impossible to have a negative AOA.

The needle should rest at the intersection of the white and red marking.

Below is a pic of an actual TBM PFD.
***@***.***D732A9.34031CC0]

Greg

**Comment by mattnischan** [comment]
@glaurian The white tick mark represents 0.6 AoA (60% of critical stall AoA), not 0. At low airspeeds (below about V1 - 20 or so) it will show 0.6, due to inadequate airflow to the systems that read AoA. However, once sufficient speed is reached, the indicator is reliable.

Here is a picture of the indicator at speed:

![image](https://user-images.githubusercontent.com/1650544/115047668-5a2f4200-9e9e-11eb-8dff-1f677a321191.png)

**Comment by glaurian** [comment]
Please see pic of the Garmin G3000 manual.

![G3000_Manual_AOA](https://user-images.githubusercontent.com/72989452/115050112-083beb80-9ea1-11eb-9cc4-0373c835ca50.jpg)

**Comment by mattnischan** [comment]
@glaurian I appreciate the source reference material, but we do have that, thanks. The two pictures on the page are not showing 0 and max, they're just indicating where you might see a white arrow vs where you might see a red arrow.

The correct indication for the AoA indicator is as I described it. 0 is the bottom, 0.6 is the white line, and 1.0 is the top. This indication style is extremely common on multiple avionics stacks (Collins, Honeywell, etc) especially for high speed aircraft. This 0.6 indication is there to give the pilot an additional indicator for approach speeds, which are aligned with 60% critical angle of attack. This indication style is also ubiquitous on physical AoA indicators, where the green circle is 0.6.

Additionally, looking at various source material, the wind speed box looks to be in the correct position.

Hopefully that clarifies things! We appreciate the questions and feedback.

**Comment by mattnischan** [comment]
One more clarification: the picture I posted above was from an actual TBM 930 at speed, not from the sim.

**Comment by glaurian** [comment]
Ok. Thanks for the clarification.
