### ISSUE TITLE
TBM930 Unable to modify Rudder Trim

### ISSUE THREAD

**Issue by coleoptere91** [Working-Title-MSFS-Mods/fspackages#1116]
Unfortunatly, my TBM930 Rudder Trim is not centered.
Unable du center it
With not modified TBM this is triggered with yaw/pitch trim on left yoke
With moded TBM that command is not active
Any other action available ?

**Comment by mattnischan** [comment]
Is this in regards to the Mugz TBM mod? We don't have a specific TBM mod.

**Comment by coleoptere91** [comment]
yes Working Title G3000 V0.5.1

**Comment by mattnischan** [comment]
I would report this issue to the TBM mod team, then. The WT G3000 doesn't affect any cockpit click spot assignments.

**Comment by coleoptere91** [comment]
Ok I understand
Thank's
