### ISSUE TITLE
KIAD not able to be entered on Longitude FMS with Flightbeam KIAD

### ISSUE THREAD

**Issue by Nerbulus** [Working-Title-MSFS-Mods/fspackages#1118]
Was on 1R at KIAD and was trying to enter KIAD as the destination. Kept saying "duplicates found" and as such was unable to enter it. Had to go "direct to" and enter KIAD there to get it to work. This was flightbeam KIAD but I don't think that should affect anything.

**Comment by cywang90** [comment]
I just tested this and was able to insert KIAD in the flight plan (as origin, destination, or enroute waypoint) without issue. I don't have flightbeam KIAD but I don't think having third party scenery would have any affect on nav data. Are you also using navigraph beta?

**Comment by Nerbulus** [comment]
Hmm. I will disable the flightbeam KIAD and report back. I'm not using navigraph at all.

**Comment by Nerbulus** [comment]
Not running flightbeam KIAD. Using Dakfly's longitude mod+g3000 0.5.1. The main thing im not sure you tested is that im sitting on the runway at KIAD itself. Shouldn't make a difference but that's the only thing I can think of. I'll try loading in at KBDL and testing. 
![image](https://user-images.githubusercontent.com/72303381/115131946-0caff380-9fca-11eb-8bb8-3c35cba57650.png)

**Comment by Nerbulus** [comment]
Resolved on the discord, but turns out the default flight plan manager does NOT allow the same origin and destination. Will be fixed when the CJ4 flight plan manager is integrated, I hope. Thanks for the help.
