### ISSUE TITLE
G3000 Altitude readout

### ISSUE THREAD

**Issue by UberGeekDude** [Working-Title-MSFS-Mods/fspackages#1121]
No bug reports... A nice to have feature?

My brother sent me this image of a real G1000 while flying TBM 940.  To me, the altitude readout looks much better.  Can you increase the number of hundreds in the readout for G1000, G3000?

G1000 in TBM 940
![TBM940](https://user-images.githubusercontent.com/62158710/115159309-60145700-a047-11eb-86d7-1210d24c52df.jpg)

**Comment by slip664** [comment]
The TBM uses a G3000. That style has already been implemented. https://media.discordapp.net/attachments/765379847031226419/820841611742412840/pfd.png?width=1076&height=565

**Comment by UberGeekDude** [comment]
Cool. I am flying the Longitude... Doesn't that have the 3000?  Or is it the G5000?  That is where I must be mistaking.  The Longitude has increments of 500 foot.
![altitude](https://user-images.githubusercontent.com/62158710/115160134-7de3bb00-a04b-11eb-8421-bd27bce71ceb.jpg)

**Comment by mattnischan** [comment]
Do you have the G3000 mod installed?

**Comment by slip664** [comment]
In real life it uses the G5000 but it takes elements of the G3000 in the sim. That altitude style is accurate for the G3000/G5000 hybrid.
![PFD](https://user-images.githubusercontent.com/72432870/115160246-2265fd00-a04c-11eb-877d-46ff0a9ff835.jpg)
