### ISSUE TITLE
FS2020 G3000 on TBM930 - issue with speed tape

### ISSUE THREAD

**Issue by EUSSEVE** [Working-Title-MSFS-Mods/fspackages#1124]
When the TBM is accelerated beyond the Max cruise speed, a red warning color appears on the speed tape and the backup instrument. However, this mod does not produce this warning and is only visible on the backup instrument. is there a setting somewhere, or just something to be added later on another version?
![00-tbm930_LI](https://user-images.githubusercontent.com/82846657/115315492-74d71480-a145-11eb-88f5-4f7a7897c2bb.jpg)

**Comment by cywang90** [comment]
The standby airspeed indicator is incorrect. Vmo in the TBM is 266 KIAS. Please see the known issues section in the readme.
