### ISSUE TITLE
G3000 WX Radar Resizing Possible? 

### ISSUE THREAD

**Issue by BrianMac60** [Working-Title-MSFS-Mods/fspackages#1127]
Not really an issue, just a cosmetic thing on the G3000 current build with the TBM 930...Can the WX Radar display be made larger to fill up the MFD screen. Is there a user-adjustable value?

**Comment by cywang90** [comment]
This radar display will be made larger for the next release.

**Comment by BrianMac60** [comment]
Hi Charles, thanks very much for taking a look at that. It’s a tiny issue I
know, but I appreciate you working it.

Cheers,
Brian

**Comment by cywang90** [comment]
Resolved with v0.6.0
