### ISSUE TITLE
CJ4: Squawk is not recognized by ATC

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#113]
Sometimes the ATC tells me to verify my squawk even though it's correct in the FMS. After a while they terminate my IFR flight plan and tell me to squawk 7000. When I try my last IFR flight plan again one of two things happen depending on what I do:
- If I manually enter the squawk code they give me they loose me again and cancel my IFR flight
- If I acknowledge the squawk code but leave it on 7000 in the FMS everything seems fine

So apparently my squawk code is set automatically but in the FMS it's 7000

**Comment by AndersHogqvist** [comment]
If I don't enter the squawk code manually, the correct code is shown on the PFD, but not in the FMS

**Comment by dga711** [comment]
While we will test again what you described, I can remember that I often had this problem on the stock plane too. So I am not sure it is related to the mod.

What is possible though, that the modded FMS doesn't pull the new squawk code that got set by the sim or PFD. Will have a look at that. Thank you.

**Comment by K20017** [comment]
I can say that, we never touched anything regarding the inputs on the TUNE page, we just changed the format.  Perhaps Asobo did not link what ATC is seeing for a squawk code and what we have entered into the squawk code.  If that is the case, that broken connection might be somewhere deep in code.

**Comment by cwburnett** [comment]
This likely needs the same attention that we need to do to update the FMS for com freq changes from external sources. Marking as bug.

**Comment by dga711** [comment]
The update of the freq changes did get fixed in the latest 0.4.0 release. 

As stated, the squawk thing seems to be a bug with the game that also happens with the stock plane. Therefore I will close this issue.
