### ISSUE TITLE
Chart scrolling controller click spots

### ISSUE THREAD

**Issue by Fergus66** [Working-Title-MSFS-Mods/fspackages#1132]
Would it be possible to make the click spots on the chart scrolling controller a little bigger?

At the moment they seem very small and it can be a fiddly job to click on them to scroll around charts, 
especially if using track IR

**Comment by K20017** [comment]
I believe this would require a model change but the best way to move it now is to click and drag the mouse where you want to go.

**Comment by Fergus66** [comment]
I didn't know you could click and drag that controller. That's much easier.

Thank you.
