### ISSUE TITLE
G3000 v0.6 In the left/right MFD, "AT " is not written anymore to tell that autothrottle is armed

### ISSUE THREAD

**Issue by genbrien** [Working-Title-MSFS-Mods/fspackages#1138]
in version 5.1 when  you armed autothrottle you would get AT written in the top black line of the pilots mfd

in 0.6 its not there anymore

**Comment by cywang90** [comment]
The AT annunciation is still there for me. Can you provide more details for how to get it not to show?

**Comment by genbrien** [comment]
it just doesnt show...
here AT is armed, but nothing written
I'm using the modded Longitude, will try with the stock one soon
![long1](https://user-images.githubusercontent.com/72418819/116149168-cfc1bc00-a6af-11eb-824d-aecd913117d0.png)
