### ISSUE TITLE
G3000 v0.6 Problems with Flight Plan line

### ISSUE THREAD

**Issue by genbrien** [Working-Title-MSFS-Mods/fspackages#1139]
-Magenta line is not there for Flight plan. You only get the white line

+if you start with no FP loaded and you enter it manually, the line will not draw at all

**Comment by cywang90** [comment]
I'm unable to reproduce this. Can you provide more specifics about the flight plan you are trying to enter?

**Comment by genbrien** [comment]
dont have a specific flight plan. tried multiple times, at different airport around the globe, and it was not working.

**Comment by cywang90** [comment]
do you have navigraph data installed?

**Comment by genbrien** [comment]
yes, but not the charts. i could test with navigraph uninstalled
