### ISSUE TITLE
CJ4: Area SID problems

### ISSUE THREAD

**Issue by qpHalcy0n** [Working-Title-MSFS-Mods/fspackages#1141]
There appears to be an issue w/ selecting SID's w/ airports that have RNAV and area SID's. When an airport has area SID's, and you select a runway, the area SIDs will disappear and only the RNAV SIDs will appear. Mutually exclusive, if you select an area SID, the runways will disappear. A prime area for testing is the KDFW metro satellite airports (KADS, KTKI, KGKY). JPOOL2 is a good test area SID. 

One anomaly is that the last area SID sorted alphabetically before the first RNAV SID will appear. For example, sorted alphabetically, KING8 appears before KUSSO7 and is available in the SID list. KUSSO7 being the FIRST RNAV SID, but KING8 is an area departure. All of the rest are unavailable.

**Comment by dga711** [comment]
I think that was solved some versions ago.
