### ISSUE TITLE
G3000 Spam events

### ISSUE THREAD

**Issue by DecMoonFR** [Working-Title-MSFS-Mods/fspackages#1145]
It seems g3000 v0.5.1 (I roll back to this version because of lags with 0.6) spam some sim events

KOHLSMAN_SET (called in setBaroPressure). Don't know why this is called 2 t/s in external view, and 10t/s in cockpit view.

May provoke difficult to analyse logs, and eratics bugs when i set pressure with an another peripheric (keyboard with b, or with logitech radio panel). I need to try 2 or 3 times for work

25938 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16244 (0x00003f74) KOHLSMAN_SET
    26110 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16244 (0x00003f74) KOHLSMAN_SET
    26219 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16260 (0x00003f84) KOHLSMAN_SET
    26297 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16260 (0x00003f84) KOHLSMAN_SET
    26297 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    26438 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16292 (0x00003fa4) KOHLSMAN_SET
    26500 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    26688 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    26860 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    27078 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    27219 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16276 (0x00003f94) KOHLSMAN_SET
    27297 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16292 (0x00003fa4) KOHLSMAN_SET <== start increase with radio panel
    27328 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16308 (0x00003fb4) KOHLSMAN_SET
    27360 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16292 (0x00003fa4) KOHLSMAN_SET <== go to an old value
    27407 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16308 (0x00003fb4) KOHLSMAN_SET
    27500 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16308 (0x00003fb4) KOHLSMAN_SET
    27516 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    27641 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    27782 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    27938 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    28063 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    28219 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    28360 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    28485 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16324 (0x00003fc4) KOHLSMAN_SET
    28563 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16340 (0x00003fd4) KOHLSMAN_SET
    28625 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16340 (0x00003fd4) KOHLSMAN_SET
    28641 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16356 (0x00003fe4) KOHLSMAN_SET
    28766 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16356 (0x00003fe4) KOHLSMAN_SET
    28813 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    28922 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29063 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29203 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29360 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29485 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29625 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29750 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    29891 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30016 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30188 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30344 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30485 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30625 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30750 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    30875 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31000 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31125 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31282 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31407 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31532 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31672 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31797 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    31938 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32063 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32203 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32360 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32485 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32625 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32750 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    32891 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33016 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33141 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33282 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33422 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33547 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33688 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33828 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    33969 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET
    34094 *** EVENT: Cntrl= 66040 (0x000101f8), Param= 16372 (0x00003ff4) KOHLSMAN_SET

AP_AIRSPEED_ON (or AP_MACH_ON - depend the knob). Called 2 time/sec. It prevent to trigger event with an another peripheric (like stream deck).
If I send AP_MACH_HOLD with another sim event, it set back AP_AIRPEED_ON

Exemple below with envent spam (only 4 actions made)

217059546 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217060468 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217061484 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217062500 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217063546 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217063921 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON <== triggered with another sim event
217064578 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217065609 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217066609 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217067609 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217068609 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217069609 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217070625 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217071625 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217072625 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217073640 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217074687 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217075703 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON <== triggered in cockpit
217076734 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217077750 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217078750 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217079750 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217079812 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON <== triggered with another sim event
217080781 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217081796 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217082828 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217083828 *** EVENT: Cntrl= 66096 (0x00010230), Param= 0 (0x00000000) AP_MACH_ON
217084828 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON <== trigerred in cockppit
217085843 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217086875 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217087875 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217088875 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217089921 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON
217090953 *** EVENT: Cntrl= 66093 (0x0001022d), Param= 0 (0x00000000) AP_AIRSPEED_ON

**Comment by cywang90** [comment]
Which version of the mod are you using?

**Comment by DecMoonFR** [comment]
v0.5.1, i changed my 1st post

**Comment by cywang90** [comment]
0.6.0 fixes the kohlsman issue. I don't know what to make of the AP events. Nothing in the mod should be triggering those events.

**Comment by DecMoonFR** [comment]
Ok, i'll make another try this afternoon without mod to check speed problem.

**Comment by DecMoonFR** [comment]
ok, I'll wait performance 0.6.0 fix, for speed problem ot seems due to base plane (try withour any mod)
