### ISSUE TITLE
G3000 waypoint distance sometimes varies between PFD and Flight Plan

### ISSUE THREAD

**Issue by WaitingForGuacamole** [Working-Title-MSFS-Mods/fspackages#1148]
When flying an IFR flight plan from Rio to Brasilia (plan attached, flight deck screen shot attached), I noticed that sometimes the PFD distance to the next waypoint varies from the flight plan. In the attached example, the PFD correctly shows 113nm, where the flight plan shows 15nm.

The only thing I can say about this one is that it's the leg just prior to the leg that joins the arrival. Everything else in this flight looked OK. I'm using 0.6.1 of the G3000 in the Longitude.

[SBGLSBBR.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/6394249/SBGLSBBR.zip)

![Microsoft Flight Simulator Screenshot 2021 04 27 - 15 47 47 43](https://user-images.githubusercontent.com/11178016/116460324-2fd96f00-a824-11eb-9bbc-56af0436677b.png)

**Comment by cywang90** [comment]
Fixed with v0.7.0
