### ISSUE TITLE
G3000  version 6.1 loading time

### ISSUE THREAD

**Issue by telemakox** [Working-Title-MSFS-Mods/fspackages#1153]
The system takes a very  long time (about 5  minutes)  loading the Garmin G3000 system v. 6.1

**Comment by cywang90** [comment]
Do you have road data installed? Is your game (and mods) installed on an SSD? Does the mod function normally after it loads?

**Comment by telemakox** [comment]
Yes, I have installed road data  and mod on  SSD.  When the system has been loaded it works normally. Exiting the simulator also takes several minutes.

**Comment by cywang90** [comment]
I would try uninstalling just the road data and see if that improves load times. With road data, the mod has to load in 1.4 GB of data, which usually only takes an extra 15 or 20 seconds or so with an SSD but can potentially take longer depending on your specific hardware. If it does turn out to be the road data, and you still want to use it, you can selectively enable/disable loading of different regions in the mod config file to reduce load times.

The simulator taking longer to shut down with road data is a known issue. You can either wait for it to shut down on its own or end process it via task manager.

**Comment by telemakox** [comment]
Many thanks! For your kind answer I will try it,

Bruno

Inviato da Posta per Windows 10

Da: Charles Wang
Inviato: giovedì 29 aprile 2021 21:56
A: Working-Title-MSFS-Mods/fspackages
Cc: telemakox; Author
Oggetto: Re: [Working-Title-MSFS-Mods/fspackages] G3000 version 6.1 loading time (#1153)

I would try uninstalling just the road data and see if that improves load times. With road data, the mod has to load in 1.4 GB of data, which usually only takes an extra 15 or 20 seconds or so with an SSD but can potentially take longer depending on your specific hardware. If it does turn out to be the road data, and you still want to use it, you can selectively enable/disable loading of different regions in the mod config file to reduce load times.
The simulator taking longer to shut down with road data is a known issue. You can either wait for it to shut down on its own or end process it via task manager.

**Comment by telemakox** [comment]
Hi Charles, the problem has been solved. After several attempts I have identified the cause. The Navigraph Navdata mod significantly slows down the loading time of the G3000. By deleting Navigraph navdata the loading time is 10 seconds. In your opinion, is it possible to find a solution?  Thx.

**Comment by telemakox** [comment]
The final solution of the problem for those who have a slowdown in loading the G3000 with Navigraph Navdata mod is the following: delete the fs-base-nav file in the offical folder, restart the simulator. The AIRAC update will be downloaded again from ASOBO. Everything will work fine, with a loading time of 10 seconds

**Comment by cywang90** [comment]
I tested with navigraph data and did not observe unusually long loading times. Does this happen for you wherever you load or only when you load into certain parts of the world?

**Comment by telemakox** [comment]
I believe it is a conflict between the version of the ASOBO AIRAC in fs-base-nav and that of Navigraph Navdata, which arises when ASOBO updates the AIRAC. Now having deleted and reinstalled fs-base-nav everything works  very fine even if you install Navigraph Navdata. 
Thanks so much Charles

**Comment by cywang90** [comment]
Glad to hear you were able to resolve the problem.
