### ISSUE TITLE
Dev: FMC page refresh logic

### ISSUE THREAD

**Issue by dga711** [Working-Title-MSFS-Mods/fspackages#116]
We should think about, how to refresh pages when values change without using periodic refresh.

For one, we could just put the setTemplate call in a function and call it manually when a value changes.

Another solution I saw in Asobo's code which i quite liked. They use the onUpdate loop and a dirty flag to rerender/resync things.
```
    onUpdate(_deltaTime) {
        super.onUpdate(_deltaTime);
        if (this.symbolsToSimvar) {
            SimVar.SetSimVarValue("L:CJ4_MAP_SYMBOLS", "number", this.symbols);
            this.syncSymbols();
            this.symbolsToSimvar = false;
        ...
    }
```
So we could also do something like
```
    onUpdate(_deltaTime) {
        super.onUpdate(_deltaTime);
        if (this.pageDirty) {
            renderPage();
        }
    }
```

**Comment by K20017** [comment]
Good points.  On some pages though, such as FUEL MGMT, you don't really need it to update on any changes because the fuel flows can sometimes be erratic and that kind of data isn't necessary to be changed any faster than 1Hz.  The legs/prog page though should be real-time data.

**Comment by dga711** [comment]
> that kind of data isn't necessary to be changed any faster than 1Hz

that is the good thing about this solution. with the dirty flag you can control when stuff gets rerendered

**Comment by K20017** [comment]
Oh nice

**Comment by dga711** [comment]
Prototype implemented
