### ISSUE TITLE
BUG: [CJ4] Missing Line of Code

### ISSUE THREAD

**Issue by charles-vomacka** [Working-Title-MSFS-Mods/fspackages#1160]
There is a line of code missing in AltimeterIndicator.js. This creates a bug that requires different Y Position values to be used in order to place pressureSVG and pressureSVGUnits on the same Y axis (I think that it is erroneously picking up a Y value in similar code below in construct_A320_Neo()).

This code needs to be added above line 159:

this.pressureSVG = document.createElementNS(Avionics.SVG.NS, "text");

Then the code in line 162 can be changed from:

this.pressureSVG.setAttribute("y", (posY + 25).toString());

to this:

this.pressureSVG.setAttribute("y", (posY + 30).toString());

**Comment by charles-vomacka** [comment]
The line of code seems to exist. I found it in an if statement starting on line 110. But it seems that, as implemented, the bug described above exists. If, as described above, the line of code is added at line 159, the bug is corrected.

**Comment by K20017** [comment]
Will take a look

**Comment by charles-vomacka** [comment]
If you add the line of code as describe above, the bug is fixed. If you do not add the line of code, but instead, comment out lines 1488 through 1501 (in construct_A320_neo) the bug is also fixed. It seems as if the IF statement may be always evaluating to FALSE, and the conditional code is never executed - and the code in construct_A320_neo is being run. Hope this helps.

**Comment by K20017** [comment]
These files are local to the Cj4 mod so none of the other aircraft code is applied.

**Comment by charles-vomacka** [comment]
Yes, I know that it should not be, but think that the bug is causing it to be read; could be wrong.
