### ISSUE TITLE
[CJ4] unable to turn back on ground power after flight

### ISSUE THREAD

**Issue by r-flo-r** [Working-Title-MSFS-Mods/fspackages#1163]
hi,
i cannot turn back on the ground power after my landing. engines are shut down. the on/off option of the ground power setting in the IDX>mod setting is either greyed out or says unavail.
would like to turn it back on to prepare the next hop of my flight (currently i have to reload a new flight in order to turn again on the ground power).
using the latest release of the CJ4 package.
thanks for your tough work on this project!

**Comment by slip664** [comment]
You must be in a designated parking spot that allows for ground power. This has nothing to do with the mod, this is a limitation of MSFS. Unfortunately, there is no way to know which spots offer it aside from using developer tools.

**Comment by r-flo-r** [comment]
Thanks for the comment. So far on every parking spot I spawned within Msfs, I was able to turn on ground power. Either this was coincidence that this spawn points I choose allowed ground power, or every spawn point of msfs allows that. 
Thanks
