### ISSUE TITLE
G3000: Can't scroll in VR

### ISSUE THREAD

**Issue by philhzss** [Working-Title-MSFS-Mods/fspackages#1167]
I'm not 100% sure this bug is with your mod, it might be with mixMugz tbm930_project mod, but I figured it might be this one since it's avionics related.

I noticed, in VR, I can't scroll with the mouse scroll wheel nor click and drag with the mouse when looking at a list of STARS or approaches for example on the G3000, the only way to scroll is to disable VR, scroll on regular screen mode to select the approach, then re-enable VR.

Thank you!

**Comment by cywang90** [comment]
Fixed with v0.7.0

**Comment by philhzss** [comment]
Thank you very much
