### ISSUE TITLE
TBM darkened

### ISSUE THREAD

**Issue by Baldk9** [Working-Title-MSFS-Mods/fspackages#1179]
Went to light up the TBM and the G1000 panel displays would not display. Process of elimination the  G1000/3000  additions were found to the culprits. The TBM displays worked fine after those addons were deleted. But of course I lost the fine work that goes along with those additions. Any ideas would be appreciated,

**Comment by cywang90** [comment]
Are you using the most up to date versions of the mods? Also, do the screens work when you **only** have the g1000/g3000 mods in your Community folder?

**Comment by Baldk9** [comment]
Charles, yes I believe I have the up to date mods and no when the mods you mentioned were in my community folder the displays did not work. Sent from Mail for Windows 10 From: Charles WangSent: Wednesday, May 19, 2021 11:07To: Working-Title-MSFS-Mods/fspackagesCc: Baldk9; AuthorSubject: Re: [Working-Title-MSFS-Mods/fspackages] TBM darkened (#1179) Are you using the most up to date versions of the mods? Also, do the screens work when you only have the g1000/g3000 mods in your Community folder?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cywang90** [comment]
Did you try the mods individually? Remove everything from your community folder (including liveries) and only install g3000, see if it works, then do the same thing for g1000.

**Comment by kasiday1** [comment]
Same problem
