### ISSUE TITLE
Navigraph (maybe) Issue

### ISSUE THREAD

**Issue by gpbbarth** [Working-Title-MSFS-Mods/fspackages#1195]
Don't know if this is a valid problem, but after installing the latest version of the G3000 mod, I went about trying out all of the new bells and whistles. Including the Navigraph connection. I followed the instructions, lined to my Navigraph account and started forming a flight plan. Starting at KFXE and flying to KPFN, I tried dialing in the SID for Executive, and asked to show in on the map. It worked fine, so next I tried to pull up the chart for the SID, and it wouldn't let me do it...kept defaulting back to the map.

Now, my set-up has my Navigraph Charts installed on another computer, and uses Navigraph SimConnect to port the data over to my sim machine. I do this for flight-following on the Navigraph map on the other machine. I went over to that machine and tried pulling up the same chart, and it worked perfectly. So I know my Charts subscription is working, and that the G3000 mod successfully linked up to my account. Is the fact my Charts program is on another computer? I would think that, if I am linked directly to my Navigraph account on the G3000, it should be downloading the charts directly.

Definitely want it to work. BTW, I'm using it in the TBM 930, if that makes a difference.

-= Gary =-

**Comment by cywang90** [comment]
Which SID were you trying to pull up?

**Comment by gpbbarth** [comment]
It was the Fort Lauderdale 7 Departure. Came up in the list, I picked it, and it worked when I picked "Show on Map." But didn't when I picked Show Chart.
[FlightAware_FXE_DP_FORT LAUDERDALE SEVEN.PDF](https://github.com/Working-Title-MSFS-Mods/fspackages/files/6556915/FlightAware_FXE_DP_FORT.LAUDERDALE.SEVEN.PDF)

**Comment by cywang90** [comment]
This seems to be an issue with navigraph charts metadata. The chart for the departure is missing the procedure code that would normally identify it as belonging to that departure. Without the correct procedure code, the mod does not know to associate the chart with the departure.
