### ISSUE TITLE
G3000 TBM9 APP mode won't capture if in HDG mode

### ISSUE THREAD

**Issue by mgg4** [Working-Title-MSFS-Mods/fspackages#1208]
Not sure this is a WT issue.

When approaching an ILS localizer via radar vectors in HDG mode, with APP armed and LOC1 showing in white as the next mode to activate, the system does not capture the localizer.  It will capture the localizer if put into NAV mode first with the CDI nav source set to LOC1.  Only then can APP mode be activated and capture both the localizer and GS.

I'm not sure if this is an actual problem, or accurate modeling of the actual G3000.

**Comment by cywang90** [comment]
This is a base sim issue. As you were able to determine, the AP will only capture the GS and localizer if put into NAV mode before arming APR mode.
