### ISSUE TITLE
mod ordering issue

### ISSUE THREAD

**Issue by jonasbeaver** [Working-Title-MSFS-Mods/fspackages#121]
Since this mod will probably need to be first on the list loaded, would calling the release "a-working-title" or "1st-working-title" to help those without knowledge of mod order keep it alphabetically high on the list? 

This may reduce help required with troubleshooting for users when using other mods that may not be as finely tuned as this one.

**Comment by knighty** [comment]
With the way we're looking at organizing our files, it shouldn't matter as long as another mod doesn't modify the panel.cfg file, and if a mod does that then all bets are off regarding ordering.

**Comment by dga711** [comment]
As of #115 we will put in some measures to be more "protected" against unfriendly mods in the vfs.

Afaik it would it is better to be loaded in last as to override the other mods ;)

**Comment by jonasbeaver** [comment]
Awesome! Just a last minute thing I'd feel bad if I didn't mention, I was sure y'all had it covered the best way.

**Comment by dga711** [comment]
Thank you for the heads up. Hope you enjoy the CJ4! ;)
