### ISSUE TITLE
Not showing up in TBM 930 after re-install and placement of both Working Title G3000 Mods to Community

### ISSUE THREAD

**Issue by N987PL** [Working-Title-MSFS-Mods/fspackages#1211]
After reinstalling Windows 10 Pro, and then MSFS Pro Deluxe, I downloaded .071 and 2.0 Road Data to my community folder with other mods as well.  All the other mods in my Community Folder are working but Working Title G3000 is not.  I made sure after unzipping, that all files associated with the WT G3000 upgrade went to Community successfully, but still am getting stock G3000 on load of TBM 930.

**Comment by N987PL** [comment]
Never mind.  I removed both WT G3000 and Road Data, shut down, restarted and everything is where it's supposed to be.  Apologies.....

**Comment by cywang90** [comment]
No problem. Glad you were able to sort it out.

**Comment by kasiday1** [comment]
Black screens TBM930 version 7.2?

**Comment by kasiday1** [comment]
Removed all mods
Original asobo uninstalled and reinstalled for tbm930
Still blank screen
