### ISSUE TITLE
Citation CJ4 - Overshoot in thrust response to changes in commanded thrust

### ISSUE THREAD

**Issue by harishsaranathan** [Working-Title-MSFS-Mods/fspackages#1212]
Any time the thrust lever is advanced, the N1 overshoots the commanded value, and then settles down. It appears the thrust control loop is underdamped. Is this behavior representative of the real aircraft or is this a bug that needs to be fixed? I would be surprised if this is how the real aircraft behaves, although I will have learned something new.

I have also rarely observed the overshoot when reducing the commanded thrust. In this case, the actual N1 goes below the commanded value and then rises back to it.

**Comment by mattnischan** [comment]
We've done the best tuning we can here, but we're fighting another throttle PID inside the sim. Even without the mod you get significant overshoot, unfortunately. With the mod it is actually damped a bit more quickly, from what we saw when we were developing the FADEC.

So, it's something we'll have to live with for now.

**Comment by harishsaranathan** [comment]
I understand. I also tried playing around with the fuel flow controller gains in engines.cfg. Although I could reduce the peak overshoot, I was unable to remove the overshoot altogether entire envelope. In short, I don't think just one set of gains is going to cut it for all N1 ranges as the dynamics are significantly different at lower N1 when compared to higher N1. This might require some sort of gain scheduling.
