### ISSUE TITLE
Altitude on standby instrument displays interestingly if the altitude is a negative value

### ISSUE THREAD

**Issue by slimit75** [Working-Title-MSFS-Mods/fspackages#1219]
As the title suggests, if the altitude is negative, the display will appear as it does below. You can still change the altimeter setting and everything is fine once the value is positive.

![image](https://user-images.githubusercontent.com/45863722/120812329-e236dd00-c51a-11eb-863b-ec065eb18f58.png)

**Comment by slip664** [comment]
This has been fixed internally.
