### ISSUE TITLE
G3000 BRG field shows heading, not bearing to the waypoint

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#1223]
Approaching Rwy 20 in this shot, I intentionally turned 90 deg to the final approach course to watch the BRG field change along with the heading.

![InkedsAltUGQGEY_LI](https://user-images.githubusercontent.com/72550869/120932869-3679c280-c6bd-11eb-8e46-c9baeaaf098f.jpg)

**Comment by cywang90** [comment]
Fixed with v0.7.3.
