### ISSUE TITLE
CJ4 incompatible livery error

### ISSUE THREAD

**Issue by Gepetor** [Working-Title-MSFS-Mods/fspackages#1230]
When I start my Cj4 with the working title mod, it shows a incompatible livery error on the display.  There is something that I can do?
![image](https://user-images.githubusercontent.com/85656223/121451043-33a7f780-c973-11eb-81a3-c009f502f658.png)

**Comment by dga711** [comment]
That usually means you are using a incompatible livery which contains a panel.cfg that renders FADEC inop.

**Comment by dga711** [comment]
See also https://www.workingtitle.aero/packages/cj4/repaints

**Comment by Gepetor** [comment]
@dga711 I was using the default livery, I tried with some of the link you sent and still the error continues, could some file or a32nx livery be causing this?
