### ISSUE TITLE
Working Title CJ4 Maps

### ISSUE THREAD

**Issue by walt642** [Working-Title-MSFS-Mods/fspackages#1234]
Can't figure what I'm missing! Charts not showing up in MFD. I don't think the CJ4 is finding the navigraph charts. What are some of the things that would prevent the  charts from not showing up. Should I try reinstalling the CJ4? Simbrief Flight plan, is loaded. Legs show up in the CDU. Pilot ID is in. Shows Navigraph as linked (LS R6.)  Pulling my hair out trying to find out why. Thanks Walt

**Comment by dga711** [comment]
Hard to tell honestly.

When your Navigraph is properly linked it usually works for people.

Are you sure you have the Charts subscription and not just data?

**Comment by walt642** [comment]
Yes thank you. I have the Navigraph subscription and the Navigraph Chart subscription. So somewhere along the line I seem to be missing the link to the charts. Although....... in the CDU MOD on LS R5 or R6 it is showing "Linked" in green. 
    On Friday, June 11, 2021, 08:56:31 AM EDT, DG ***@***.***> wrote:  
 
 


Hard to tell honestly.

When your Navigraph is properly linked it usually works for people.

Are you sure you have the Charts subscription and not just data?

**Comment by riddymon** [comment]
You have to hit the charts button on the center console and then hit the lower menu button on the left for charts menu to actually show up. Recalling this from memory..my apologies if I'm not more specific.
