### ISSUE TITLE
FMC right does not work

### ISSUE THREAD

**Issue by DanP77** [Working-Title-MSFS-Mods/fspackages#1237]
FMC on right side is not "clickable".

Is it possible to enable this?

**Comment by slip664** [comment]
Not at this time as the FMCs cannot be operated independently.

**Comment by DanP77** [comment]
Not asking for an independent system (wow it would be amazing, and I hope one day...)
I only asking to have clickable right FMC (coping the left one)

**Comment by dga711** [comment]
Possible with 0.12.10
