### ISSUE TITLE
[CJ4] NAV Switching from VOR1/2 to FMS not possible

### ISSUE THREAD

**Issue by Philskills** [Working-Title-MSFS-Mods/fspackages#1243]
After selecting the VOR1 and a course for VOR tracking (without A/P), a switching back to FMS as NAV mode preset is not possible (VOR 1 in manual tune on FMS TUN page) even though a direct has been inserted. The NAV Pushbutton on the display control panel toggles only between VOR1 and VOR2.

**Comment by dga711** [comment]
You have to switch the preset maybe.
As per the guide:
![image](https://user-images.githubusercontent.com/2995606/122568869-7f7d2f80-d04a-11eb-8133-4778b2ad6d91.png)

**Comment by Philskills** [comment]
Thanks alot, next time I will read the description more carefully.
