### ISSUE TITLE
CJ4 (v0.3.0): From cold/dark, engine start lights already set to RUN

### ISSUE THREAD

**Issue by musurca** [Working-Title-MSFS-Mods/fspackages#125]
When starting up the aircraft from cold & dark in v0.3.0, I found that the engine start lights were already set to RUN before I had activated the starters. I had to press them twice (once to turn them off, the second time to start them) in order to start the engine.

Other than that, awesome work on this release!

**Comment by K20017** [comment]
Hmm, we will take a look.  Strange considering we haven't touched anything involving this issue.  (At least we don't think we did....)

**Comment by cwburnett** [comment]
I also noticed this with the default as well, we will have to dig into that part of the code that we haven't looked at yet, but definitely something we would like to fix.

**Comment by musurca** [comment]
It didn't happen on a subsequent restart-- so yes, possibly this is some intermittent thing that was baked in before. I'll keep an eye on it!
