### ISSUE TITLE
MSFS Flightplan Import fails

### ISSUE THREAD

**Issue by kakihara123** [Working-Title-MSFS-Mods/fspackages#1251]
When creating an automatic flightplan from EDQG to LFBI via Navigraph, Importing it into MSFS and then importing it to the Cj4 via the FMC only the SID and departure and destination show up. When tryin to manually enter the Flightplan it delets the waypoints as soon as an airway is entered (didnt test all combinations)

The route is this: EDQG/08 WUR1E WUR DCT TUDGA Z114 DONAB Y180 DIK UN857 GIMER UT300 EVX UT176 LGL UN859 BALAN DCT LFBI

**Comment by dga711** [comment]
Does it work for you to insert this flightplan from scratch into the FMC without using World Map?
