### ISSUE TITLE
CJ4 Mod corrupts cockpit view on standard edition Textron Aviation Citation Cessna CJ4

### ISSUE THREAD

**Issue by ivatt** [Working-Title-MSFS-Mods/fspackages#1253]
Having seen the excellent Youtube video by **Filbert Flies** on how to load a Simbried flight plan into the above aircraft using the working title CJ4 mod I decided to install the mod in my community folder.

Unfortunately, when I start the aircraft the cabin view is corrupted, I only see an outline of some components of the cabin. Removing the mod returns everything to normal.

Is the mod compatible with the above aircraft please?

**Comment by dga711** [comment]
@ivatt  Are you sure you downloaded the latest version and right package?
Try to download 12.5 from here again https://www.workingtitle.aero/packages/cj4/

**Comment by ivatt** [comment]
Hi, thanks for the reply. That's really strange as I had downloaded and installed the correct package as far as I was concerned at least three times and got the corruption but this time it looks as if it has worked. I will try to load a Simbrief flight plan as per the YouTube video to see if it works OK and post back afterward but might not be until tomorrow......fingers are crossed.
