### ISSUE TITLE
A and B contraints are inverted

### ISSUE THREAD

**Issue by psyonicus** [Working-Title-MSFS-Mods/fspackages#1254]
Hello everyone. 

I encountered a problem with version 0.12.5 and was directed from the discord server to make a report here. 
It is my first time reporting an issue (and in fact, logging in to github altogether), so please forgive anything wrong with this post.
 
And of course, it might be that I'm doing something wrong myself in the first place.

Here is a brief description of the problem:
1.- I need to input some altitude restrictions for my approach. In this case, between 16000 and 13000 ft. 
2.- What I type on the FMC is "/13000A16000B" (without the quotes).
3.- The FMC shows 16000A13000B (they are inverted, and make no sense).

Here is a screenshot, if it helps.
![Capture](https://user-images.githubusercontent.com/87275362/125203085-8576c280-e23c-11eb-9e67-ff723aaf934a.JPG)

Best regards!

**Comment by FiveMilesSep** [comment]
Try reversing the levels, I believe the format is 18000B16000A, as an example.

**Comment by psyonicus** [comment]
Oh, so the bellow constraint goes first.  I was doing it backwards.Need to re-read the user guide. Please pardon my newbness. Cheers!

**Comment by FiveMilesSep** [comment]
Not a problem, I tested this earlier in the Sim, but the Autopilot didn't seem to follow the constraint.  I'm pretty sure I had VNAV engaged.  Hopefully it works for you.

**Comment by psyonicus** [comment]
Actually, yeah.
I did a couple of tests yesterday, and by inputting the bellow constraint first (say, 26000B23000A), it does take them and it does display them correctly, but it does NOT follow them.
In addition, it will not take fligh level constraints (fl230). Only in feet (23000).
To add to my confusion, the user guide does say to enter the above constraint first (23000A26000B), so I guess my original post is still valid.

**Comment by dga711** [comment]
Yeah, there is an issue there and some confusion.
We will consolidate and fix that functionality

**Comment by psyonicus** [comment]
I can confirm the latest version 0.12.7 fixes this issue.
Thank you guys, you rock!
