### ISSUE TITLE
G3000 no altitudes in flight plan

### ISSUE THREAD

**Issue by Altycoder** [Working-Title-MSFS-Mods/fspackages#1256]
Flying the TBM 930 without the working title G3000 mod, if I plan a route using the FS2020 flight planner and then go flying, the flight plan has all the correct waypoints complete with altitudes.

Using the working title G3000 mod, the waypoints are there but the altitudes are not.  

Why don't the altitudes transfer correctly into the in-cockpit flightplan with the G3000 mod v0.7.3?

**Comment by fabianovm** [comment]
I also noticed that, also miss the altitude and I think, not 100% sure **it used to show altitude on previous G3000 versions** on TBM... I think maybe it is quite easy for WT team adjust that on next release, hope so!!! Everything else is perfect!

**Comment by cywang90** [comment]
This is by design. The altitudes are omitted from the FMS flight plan to avoid issues with the advisory VNAV feature when the sim decides to place bogus altitudes on certain legs.

If you need to view published alt constraints for procedures, you can load the procedures into the standby flight plan.

**Comment by Altycoder** [comment]
Not sure I understand the logic / why is the G3000 the only FMC to do this?  Surely altitudes should be transferred and a bug raised with MS regards anything bogus?

Altitudes transfer in the CJ4 and A320 that I also fly regularly and I don't really see anything bogus.

**Comment by truespirt14** [comment]
I totally agree with this.  At a minimum I would think they would put an option in the cfg file to enable altitudes, and let US decide if we want them or not.  If it's a VNAV issue, it is far easier to correct the occasional bogus altitude on a leg than having to ALWAYS put them in for every flight plan.
