### ISSUE TITLE
On CJ4 cannot monitor COM1 and COM2 simultaneously

### ISSUE THREAD

**Issue by agoldhammer** [Working-Title-MSFS-Mods/fspackages#1257]
On CJ4 pressing COM2 on audio panel switches off COM1.

**Comment by dga711** [comment]
When you press one of the buttons you switch TX between COM1 and COM2.
They are both on RX as long the knob below them is set to on.

**Comment by agoldhammer** [comment]
Perhaps my problem is that I'm using Pilot2ATC. If I tune an ATIS on COM2, I don't hear it until I push the button that lights the transmit light, and when I do that I no longer hear the traffic on COM1. Also can't switch on the transponder. When I set the squawk code on the FMS, it appears correctly in Pilot2ATC, but to turn on the transponder I have to use the Pilot2ATC control panel. There doesn't appear to be a switch to turn this on on the CJ4 panel or FMS.

**Comment by dga711** [comment]
Oh yeah. Hmm... I am not 100% sure on that, but I think I remember months ago seeing reports of Pilot2ATC not interpreting the SimVars correctly there.

The CJ4 sets the SimVars correctly (from our point of view). Which you can see (for example) in vPilot.

**Comment by agoldhammer** [comment]
Thanks for the feedback.

**Comment by agoldhammer** [comment]
Here's the reply from Pilot2ATC:
Currently P2A cannot “listen” to 2 channels at a time and does switch the Transmit/Rec from Com1 to Com2 when you select Com2.

 I will check, but it’s possible that there are some SimVars that are not being interpreted through FSUIPC correctly, or that P2A is not interpreting something in MSFS correctly from FSUIPC.

Given this, I'll close this issue.

**Comment by dga711** [comment]
Thats good information. Thanks for reporting back 👍
