### ISSUE TITLE
CJ4 performance degradation during flight

### ISSUE THREAD

**Issue by jinoss17** [Working-Title-MSFS-Mods/fspackages#1259]
Hello! I also wrote about this issue on Discord, but I read it's better to report it on github as well, so developers could look into it.

I've recently downloaded the CJ4 mod and it's absolutely brilliant: it completely changes the CJ4 and now it's one of the best aircraft for MSFS imho. 

The only issue I noticed it's some sort of performance degradation (I'm talking about fps and not aircraft performance) during flight I'm now going to explain. 

When I start a flight with the CJ4 my frames are around 60 and pretty steady as with any other aircraft I tried in MSFS. During cruise, fps start to drop a little going from 60 to 50 on average, but the real drop is noticeable on the final approach phase where fps go from 60 to 45/40 on average. 
During these tests I've also monitored hardware usage with RivaTuner and the funny thing is that when frame rate drops, also GPU use percentage drops which seems to be a contradiction. 

I made several tests on this and I came to the conclusion that:

1) It's not airport related: I've flown to different airports and the issue stays the same

2) It's not related to flight duration

3) It's specifically related to the CJ4 mod as I haven't had this problem on other aircrafts

Given that it's a gradual degrade of performance it makes me think it's a sort of "memory leak" or something. Moreover when I land and I switch off the aircraft avionics, performance goes back to 60 steady fps.

I hope I've explained the issue clearly so that developers could have a look.

**Comment by dga711** [comment]
Please check if you still see those issues after SU5 and feel free to reopen
