### ISSUE TITLE
G1000: Endurance and range NaN if fuel flow == 0

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#126]
Can we make this conditional such that when the fuel flow is, say < 0.1 we get the following indications

https://www.youtube.com/watch?v=NHZ1UEnVTEU&feature=youtu.be

(see from 0:40 in the vid)

![image](https://user-images.githubusercontent.com/11409383/94454334-0e42d700-01b2-11eb-85f2-0b539a359171.png)

**Comment by knighty** [comment]
Oopsie thats an issue with my maths not accounting for divide by zeros.

**Comment by knighty** [comment]
This is dealt with now, though it can be changed if there's realism issues. The "X" will not show as red for example but for now I think it'll do. Better than Infinity/NaN regardless.
