### ISSUE TITLE
ITT - FADEC - ITT above limits, so n1 % limited

### ISSUE THREAD

**Issue by nevs11** [Working-Title-MSFS-Mods/fspackages#1261]
Using latest working title, with a livery that has no custom panel file, when flying in cruise power, the ITT sky rockets above the red line which limits power, then 15 mins later, it resets back down, and i get power back again after 15 mins, keeps cycling...what is causing this?

thank you.

**Comment by nevs11** [comment]
I think i figured it out, MFS2020 is showing a ISA of +85! Something wrong with weather

**Comment by dga711** [comment]
we saw multiple reports of that happening today. indeed something seems to be off with the weather data in the sim right now
