### ISSUE TITLE
[G3000 v0.7.3] Change of Active Leg Upon Loading Approach

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#1264]
I am flying the following route:

`KMMH CROLI1 EHF WEESL1 KBUR`

On `EHF.WEESL1` between `BASKK` and `AMANY` I load the approach `MIKEI.RNAV Z Rwy 8`.

The aircraft then auto-activates the leg from `AMANY` to `WEESL` and tries to intercept the course, although I am still approx. 9 NM from the waypoint change.

I can only resolve the situation by manually re-activating the current leg from `BASKK` and `AMANY`.

For details see screenshot attached.

Does this bug relate to the one desribed on your page because I have `EHF` both as end of the SID and beginning of the STAR in my flightplan?

> ![2021 07 26-21 01_01](https://user-images.githubusercontent.com/71787933/127045001-b1bbcf39-0f1a-495c-8bce-490e8c545940.png)

**Comment by cywang90** [comment]
When you load an approach (or make any changes to the active flight plan), the sim will automatically attempt to recalculate the active leg. It tends to, for some reason, activate the leg one past the one you should be on. Currently, there's no good way to compensate for this, so the workaround is just to manually activate the correct leg.
