### ISSUE TITLE
[G3000 v0.7.3] Unable to Perform RNAV Approach

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#1265]
I am flying the following flightplan:

`KOXR SKIFF ROBOR VTU.RNAV-Z-8`

There is no consecutive double waypoints in the route.

The aircraft is showing the following behavior on the approach with APR & VNAV enabled:

- Between `SILEX` and `BUBNE` the Glideslope indicator remains level at 3000'
- Approaching `BUBNE` the Glideslope indicator moves all the way up
- At `BUBNE` the aircraft starts a quite rapid descend (-1200 FPM) despite the Glideslope indicator shuttling between 2,5° and 2° 
- The vertical path remains below Glideslope throughout the approach
- Between BUBNE and RW08 at approx. 1,3 NM the Course indicator starts rapidly chaning between 078° (Final Approach Course) and 258° (Backcourse) and the aircraft breaks out to the left.

Overall I'm unable to perform a safe approach, neighter laterally nor vertically.

![2021 07 26-21 51](https://user-images.githubusercontent.com/71787933/127051592-06bbf217-ccc4-43fd-aa05-91ae9da6b8c3.png)

![2021 07 26-21 53_02](https://user-images.githubusercontent.com/71787933/127051603-06540279-b5d5-4544-be73-06797ecefa83.png)

![2021 07 26-21 56](https://user-images.githubusercontent.com/71787933/127051613-f75c0faa-af0d-42bf-8709-e3ff1313073c.png)

**Comment by cywang90** [comment]
RNAV glidepaths can be messed up in certain approaches. It's not something the mod can fix because the data comes straight from the sim. The autopilot is also still the stock autopilot, so any issues with the AP tracking the glideslope/path likewise stem from the base sim.

**Comment by sfdeham** [comment]
Thanks for your fast response.

I just saw your preview video on your G1000 NXi. I assume you either have own logic outside MSFS or Asobo fixed the existing issues in-sim.

Could you comment if/when the same is coming for the G3000?

Would be a big step forward!
