### ISSUE TITLE
G1000: Eng pages unavailable in reversionary mode

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#127]
You can't access the engine pages on the PFD in reversionary mode.

This is possible in reality.

I'm referring to the vid again that Juicebox7535 made as reference for the G36 project. 

https://www.youtube.com/watch?v=NHZ1UEnVTEU&feature=youtu.be

**Comment by knighty** [comment]
Yep I haven't actually considered reversionary mode at all, was rather low priority versus getting it working in the MFD, thanks for nothing it though. That mode has been on the back of my mind a lot :)

**Comment by jonasbeaver** [comment]
careful, that is an NXi G1000 modeled, the engine page is not available in the same way on the actual G1000

**Comment by knighty** [comment]
Ah, well that would certainly make life easier then. Going to leave this here as a general "reversionary mode" reminder perhaps.
