### ISSUE TITLE
latest CJ4 fix and G3000 v1.74a

### ISSUE THREAD

**Issue by 39crauds33** [Working-Title-MSFS-Mods/fspackages#1274]
Installed latest CJ4 and G3000 fixes for Upgrade 5 and set mouse to legacy.  Unable to open engine start buttons or access any of the FMS controls or keyboard.  Also unable to switch on Pitot or Icing controls.  The mouse pointer does not respond when I try any of these buttons or switches.  It just remains in pointer mode.  All screen controls work in both PFD and MFD.  I have made no other changes in options.  I can start engines using CTL-E but cannot program the FMS.  

I tried to take an image of my mouse pointer over some of those buttons but the mouse pointer doesn't show up in the image.  You should be able to duplicate this.  I have restarted my computer and the sim twice and get the same problem.

**Comment by mattnischan** [comment]
Everything is working OK here, no issues with buttons.

Presently, there is a sim issue with buttons in general. Please try going to Controls in the sim, and setting your mouse control profile to Default.

**Comment by 39crauds33** [comment]
Same issue, Matt, unresolved.  I have set legacy and set mouse in controls
to "default".  I touched nothing else.  Mouse works for all controls except
FMS and the anti-icing, and pitot heat.  Also will not open the cover on
the "run" switches.  All other click spots work. But it is as though there
are no click spots on those areas.  Is there anything else that I can
check?   My mouse is working every place else but those portions of the
panel will not respond to my mouse. I have your most recent CJ4 fix and the
latest G3000 update installed.  The only other noticeable issue so far is
with the Cessna.  I cannot remove the yokes. I used to just click on them
and they would vanish.  Now as in the CJ4, it is as though there is no
click spot.

**Comment by dga711** [comment]
I've read on the forums some people say that you have to make sure to update all packages in the Content Manager of MSFS.
And maybe this https://forums.flightsimulator.com/t/sim-update-5-mouse-input-moves-ok-but-cannot-interact-other-threads-closed/428105/8

**Comment by 39crauds33** [comment]
I don't have an issue with my mouse on any other area of the panel.  Unlike
the poster in the link you sent me, my mouse operates normally in all
aspects, but for some reason it doesn't recognize the "click spots" in
those specific areas of your panel.  My next step is to remove everything
from my community folder except your v1.74a and the G3000 fix.  My thinking
is that if yours works then the only difference must be some interference
with another mod for something that I have in my community folder.  If it
works then I can, by trial and error, determine which of my other mods may
be interfering.  I will report back.

**Comment by 39crauds33** [comment]
Ok.  I removed everything from my community folder except your CJ4 fix and
the G3000 fix and everything works perfectly!   So I know that something in
my community file was interfering with the CJ4 mod and causing the issue.
That I can track down.  Thank you all for responding so quickly and
diligently to my problem.  Keep up the great work.
Craig
