### ISSUE TITLE
No 0.7.4 download for G3000?

### ISSUE THREAD

**Issue by Altycoder** [Working-Title-MSFS-Mods/fspackages#1276]
I can only see a source code download, where the actual download package for the community folder?

There's a CJ4 update ready to download, but not for G3000?

**Comment by dga711** [comment]
The link in the readme is not up to date. Sorry.
Get it here https://www.workingtitle.aero/packages/g3000/

**Comment by Altycoder** [comment]
The v0.7.4 link on this page: https://github.com/Working-Title-MSFS-Mods/fspackages points to a page (https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.7.4) with just the source files not a downloadable zip file.

**Comment by dga711** [comment]
> The v0.7.4 link on this page: https://github.com/Working-Title-MSFS-Mods/fspackages points to a page (https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.7.4) with just the source files not a downloadable zip file.

Yes. As I said, the link in the readme is not correct. So please use the link in my previous comment.
Or this one https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.7.4a
