### ISSUE TITLE
G1000 Direct-To and navigational problems

### ISSUE THREAD

**Issue by seglh** [Working-Title-MSFS-Mods/fspackages#1280]
Hi,

I have the G1000 that i got from the MSFS market place 27-July and i have several problems. 

Just made a flight in the C208 and i entered a SID (EHAM ARNEM3G) but i got a vectored departure and later i got direct NYKER. I selected Direct-To, i stepped in the FPL page to NYKER and pressed the ENT key but nothing happened regardless how many times i tried. 

I then used the inner scroll button to highlight NYKER in the Direct-To page and stepped across the characters to the one after the last one. Now i pressed ENT again and now i got the Activate button to light up and i could do the Direct-To. I activated NAV mode.

I reached NYKER and instead of continuing to the next waypoint ARNEM, the CDI needle started flickering wildly all over the place. Back to HDG-mode.
I selected Direct-To ARNEM and again had to repeat the highlighting procedure to do the Direct-To. Back to NAV-mode.
I reached ARNEM and instead of proceeding direct to the next waypoint TEBRO (enroute waypoint) the CDI needle pointed 90 degrees offset to the south. 

At this point i cancelled the flight as i was flying on VATSIM in a busy area.

I switched to use Working title's G1000 because the default G1000 was so buggy but this is worse than the default version.

Best Regards / Jan

**Comment by mattnischan** [comment]
Hello,

The new G1000 NXi is in early access and this is the first early access version, so it is known that there will be bugs and missing features (potentially many). We are not accepting bug reports for this product on this GitHub since this is not one of our open source mods, but feel free to report them on our Discord in the NXi channel.
