### ISSUE TITLE
G1000 NXi SID bug

### ISSUE THREAD

**Issue by Fynus** [Working-Title-MSFS-Mods/fspackages#1281]
Hey guys,

a bug occured regarding the SID of the UVEPI2X Depature out of ENOL (Orland, Norway). First of all the nxi draw a right turn intercept instead of a left turn, after takeoff the nxi draw a huge radius (could be circle, since I couldnt see all of it), but instead of flying to the next waypoint, it tried flying a backcourse from UTH to the 500ft marker. If you look at the pictures you see that the 500ft marker is before UTH, but implemented after UTH - that could cause the issue. Anyway the nxi didnt followed instruction of a left hand interecpt and draw a right hand intercept before depature.
![Microsoft Flight Simulator 29 07 2021 14_17_35](https://user-images.githubusercontent.com/77697495/127649543-a20d8bc1-5ece-476f-b9ee-84e47de9ec6b.png)
![Microsoft Flight Simulator 29 07 2021 14_17_30](https://user-images.githubusercontent.com/77697495/127649566-3b57456b-a680-48e8-bcf3-13ce4d9b3084.png)
![Microsoft Flight Simulator 29 07 2021 14_17_38](https://user-images.githubusercontent.com/77697495/127649525-36caf43d-35f7-4637-a8a0-3dce4af86bd5.png)

**Comment by dga711** [comment]
Hi. Since the NXI is not part of our mods on GitHub we don't accept reports on it here. Please use our Discord on MSFS forums.
I would suggest to check again with the update we will release very very soon and report again if the issue persists. Thank you.
