### ISSUE TITLE
First impressions SU5 & WT G1000 NXi

### ISSUE THREAD

**Issue by ftnet305** [Working-Title-MSFS-Mods/fspackages#1282]
Hello, I appreciate your efforts and know that work is in progess. So this list is intended not as critisism but to create awareness. After installing the NXi I stumbled upon these (very first and cherrypicked) issues making IFR flights not feasable at this time.

- On MFD the active flight plan will not disappear, pressing flight plan again just fills or removes content. The MFD stay obstucted with the FPL until a restart is done
- Also pressing CLR for a while will not reset / clear the monitor
- Pushing the heading bug will not set the current heading
- Autopilot misbehavior - when heading is constantly moved, the airplane does not follow the initial turn but goes opposite
- The diamond for wind correction is missing
- There is no 8,33 kHz spacing, also the VFR squawk is for the US (option to choose 1200, 7000 and individual would be good)
- On PFD when selecting a waypoint from FPL, then pressing direct to, the "direct to"-menu shows up under the flight plan instead of the FPL disappearing momentarily
- Trying to fly the RNAV09 approach into KEYW: Origin KMTH cannot be chosen, AP flies towards ATNAV then halfway begins to circle, approach cannot be activated from PROC page
- Autopilot is randomly disconnecting
- Minimums are not announced

**Comment by mattnischan** [comment]
Hello,

As the NXi is not one of our open source mods, we are not accepting reports for it on this GitHub. Please feel free to hop on our Discord and provide feedback in our NXi channel.
