### ISSUE TITLE
activate Approach

### ISSUE THREAD

**Issue by morpheus2939** [Working-Title-MSFS-Mods/fspackages#1284]
Hi, and thank you for the great enhancement!

just a question, after selecting an approach, I can only "load" it, but not "activate"

it is unresponsive on the activate item.

I am a real commercial Pilot with G1000 experience, please advice if it as bug or misoperation
thanks
Daniel

**Comment by mattnischan** [comment]
Hi there,

The NXi is not one of our open source mods so we are not accepting bug reports for it on GitHub. Feel free to drop by our Discord and provide feedback in our NXi channel.

At this time, Activate is not implemented, but will be in our next release.
