### ISSUE TITLE
CJ4  - List of things that appear to be broken after SU 5

### ISSUE THREAD

**Issue by Fergus66** [Working-Title-MSFS-Mods/fspackages#1290]
1. The controller used for panning around the charts is not working at all.

2. Various button click sounds and animations for buttons and knobs aren't working. 

3.  As already mentioned, any key or controller assignments for toggling the spoilers / speedbrakes won't work. 
The only way to activate spoilers /speedbrakes is by using the lever in cockpit.

4. As already mentioned, the long press of the button to choose alternative charts isn't working.

**Comment by fanatictentacle** [comment]
Most annoying is that the "push button" in the lower panel is not working

![image](https://user-images.githubusercontent.com/9592789/127783278-7b3a38b0-59d1-476b-a2ee-99176e437924.png)
In the upper panel is works as seen above

![image](https://user-images.githubusercontent.com/9592789/127783292-3dc457cf-80b7-474f-b845-375384d48df0.png)
This is the lower panel I'm referring to. As you can see the push part is not selectable

**Comment by dga711** [comment]
> Most annoying is that the "push button" in the panels are not working. If the button is pressed via mouse click, nothing happens

In Lock mode you have to hold the inner knob using the Left Mouse Button and press the Right Mouse Button

**Comment by dga711** [comment]
> 1. The controller used for panning around the charts is not working at all.
> 2. Various button click sounds and animations for buttons and knobs aren't working.
> 3. As already mentioned, any key or controller assignments for toggling the spoilers / speedbrakes won't work.
>    The only way to activate spoilers /speedbrakes is by using the lever in cockpit.
> 4. As already mentioned, the long press of the button to choose alternative charts isn't working.

1. Sadly only works in Lock mode right now
2. They should. Need specific examples to investigate
3. Need to check
4. See answer above

**Comment by mattnischan** [comment]
For 3, the toggle keybind is no longer working in SU5, globally.

**Comment by fanatictentacle** [comment]
> In Lock mode you have to hold the inner knob using the Left Mouse Button and press the Right Mouse Button

Seriously? Thanks, sorry for my misreporting
