### ISSUE TITLE
G3000 v7.4, Map Panel Covers Gauges in TBM930

### ISSUE THREAD

**Issue by manigoes** [Working-Title-MSFS-Mods/fspackages#1291]
TRQ, Prop, NG, ITT gauges are oversized.  Cannot read percentages.  Fuel, Flaps, Voltage, Pressure gauges covered by map/chart panel
![Screenshot 2021-07-31 091816](https://user-images.githubusercontent.com/88243852/127744486-adff9941-2533-4dae-bd0a-48c8e94482cd.png)

**Comment by mattnischan** [comment]
@manigoes Those do not look like the default gauges. Are you using an aircraft mod?

**Comment by manigoes** [comment]
I'm using the Working Title G3000 v7.4  I didn;t modify the gauges as far as I know other than what's included with the Working Title Mod.

**Comment by manigoes** [comment]
I figured it out.  I was using an addon livery.  The livery and its gauges are not compatible with Sim Update 5.
