### ISSUE TITLE
Refs, upper, lower menu, and many other buttons don’t work after sim update 5

### ISSUE THREAD

**Issue by CrashXDelta** [Working-Title-MSFS-Mods/fspackages#1293]
A number of buttons in the cockpit no longer trigger menus on the displays. The checklist button will bring up the checklist menu, but I’m unable to scroll or select items in the menu using the usual knob. The “pass brief” button has the same issue. The upper, lower, and refs menus make a clicking sound, but don’t bring up a menu in the displays.

**Comment by dga711** [comment]
Hey there, we've seen some reports of users having that issue. We are not sure where this stems from and if we can fix it on the mod end.
It seems like for some people it was resolved by fixing the Mouse profile.
Take a look here https://forums.flightsimulator.com/t/fixes-work-arounds-for-su5-in-game-ui-tool-tips-missing-mouse-cursor-issues/429362/3

Thank you
