### ISSUE TITLE
radio frequency resetting/not able to set

### ISSUE THREAD

**Issue by bubbleblowe** [Working-Title-MSFS-Mods/fspackages#1294]
I am unable to reset the radio frequency to anyone with COM1. I type 122.800 on the scratch pad, and try to tune it onto the active frequency, it resets to what it originally was. It does not tune it in.

**Comment by dga711** [comment]
Make sure you this option is off
![image](https://user-images.githubusercontent.com/2995606/127767709-576f90f8-b6de-40a3-8e61-b52c3ff9287f.png)
