### ISSUE TITLE
G1000 marketplace addon

### ISSUE THREAD

**Issue by 39crauds33** [Working-Title-MSFS-Mods/fspackages#1296]
I removed latest version of G1000 from my community folder and added the new one available in the market place.  It does have greater features (flight planning input) but it no longer has the display lighting control that you had before.  ASOBO has the PFD and MFD too light to view in daylight when in outside view over the dash during takeoff or landing.  Your latest download version had a special option in the PFD "menu" to control lighting as a %.  Any chance that this will be implemented again, or have you assigned this function elsewhere?  Seems engine leaning and many other menu functions no long working on MFD.  Will these be re-implemented?

**Comment by srmudry** [comment]
Autopilot doesn't track the gps course I have set using the marketplace addon.

**Comment by dga711** [comment]
Should have been solved by 0.3.0
