### ISSUE TITLE
Selecting approach doesn't work in first attempt G1000nxi

### ISSUE THREAD

**Issue by EComisso** [Working-Title-MSFS-Mods/fspackages#1297]
Whenever I enter the Select Approach page on PROC, the enter key won't work when I want to choose the approach. Scrolling in the list works fine, but when I press enter nothing happens. To make it work I have to leave the page, press PROC again, enter the Select Approach page again, scroll through the list again and then the enter key works.
Basically enter doesn't work the first time you visit the Select Approach page under PROC, you have to visit a second time.

**Comment by dga711** [comment]
Hi. Since the NXI is not part of our packages on GitHub we don't accept reports on it here.
But I can tell you, that this is a known bug that is already fixed for the coming update (very very soon)
