### ISSUE TITLE
CJ4: Incorrect weights / ZFW GWT

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#130]
Disregard, found the issue by myself!!!

**Comment by K20017** [comment]
Not sure I understand what you mean.  What were your fuel/passenger/cargo numbers?

**Comment by Jack737800** [comment]
I just add 100 people on board....this explains the wrong values!

**Comment by K20017** [comment]
We currently do not have any input checks on this page (For example, you shouldn't be able to enter more than 10 passengers or XXX amount of cargo.  Will be in the future though.
