### ISSUE TITLE
CJ4 W.T. - Discesa Errata

### ISSUE THREAD

**Issue by ste20fra** [Working-Title-MSFS-Mods/fspackages#1300]
La fase di discesa e di avvicinamento alla pista di atterraggio non è sincronizzata con i dati indicati dalla funzione LNAV. L'aereo scende sempre ad un rateo di discesa inferiore e di conseguenza per l'atterraggio si trova sempre molto alto rispetto all'altitudine consentita per poter effettuare un atterraggio. La discesa finale bisogna gestirla tramite joystick.

**Comment by dga711** [comment]
No one here speaks italian. Please formulate your report in English. Thanks ;)

**Comment by ste20fra** [comment]
The descent and finishing phase at the finish runway is not synchronized with the data indicated by the LNAV function. The plane always descends at a lower rate of descent and consequently for the landing it is always very high compared to the altitude allowed to be able to make a landing. The final descent must be managed by joystick.

**Comment by agoldhammer** [comment]
Here is an English translation:
The descent/approach phase is not synchronized with the data indicated in
the LNAV function. The plane always descends at a lower rate and is
therefore very high relative to the altitude necessary for landing. The
final descent needs to be controlled with the joystick.

(FWIW, I don't see this behavior when I fly the CJ4. I'm just providing you
with a translation of the original poster's issue.)
