### ISSUE TITLE
CJ4 WT - Wrong Airplane Descent

### ISSUE THREAD

**Issue by ste20fra** [Working-Title-MSFS-Mods/fspackages#1301]
The descent and finishing phase at the finish runway is not synchronized with the data indicated by the VNAV function. The plane always descends at a lower rate of descent and consequently for the landing it is always very high compared to the altitude allowed to be able to make a landing. The final descent must be managed by joystick.

**Comment by dga711** [comment]
This should usually not be the case.
If you can give us a specific example of an approach where that happens, we can look into it.
