### ISSUE TITLE
G1000 Range Knob Inop

### ISSUE THREAD

**Issue by TacticalBacon86** [Working-Title-MSFS-Mods/fspackages#1302]
The range knob/selector on the PFD/MFD seems to no longer be functioning after the update. The Marketplace version works, but my preference in your version here, and it's the one not functioning. Thanks to all of you for your work. You've added so much to this program.

**Comment by BradleyGother** [comment]
Also having issue with WT G1000 Range Selector Know not functioning :(

**Comment by TacticalBacon86** [comment]
I’m glad I’m not the only one then.

**Comment by srmudry** [comment]
Also having the same problem.  Plus stock g1000 mod from FS doesn't track the gps flight plan.

**Comment by TacticalBacon86** [comment]
You’re referring to the G1000 mod from the freeware marketplace? Yeah I ran
into that as well, which is why I prefer the one offered on GitHub.

**Comment by Koenig70** [comment]
Same here...I uninstalled the G1000 on the market because the lack of weather radar, then installed again this one from gihub and the range knob is not working. What a mess with this SU5 update :-/

**Comment by TacticalBacon86** [comment]
Yep. One step forward and two steps back with Asobo with every update.
About the time things get sorted out it’s time for another update again.
SMH

**Comment by a402245** [comment]
also have this issue

**Comment by Tombstone0074** [comment]
same here :(

**Comment by BradleyGother** [comment]
gUYS, UNINSTALL wORKING tITLE g1000 ADDON & INSTALL THE g1000nxi VERSION FROM THE MARKET IT WORKS. tHE OLD g1000 wt VERSION IS BROKEN SINCE su5.

**Comment by srmudry** [comment]
Neither work right, but the nxi works better since the patch.  Try flying over the ocean with bad visibility using the new one.  Find the horizon if you can.  The artificial horizon has the water and sky the same color.  The autopilot portion has a few problems too.

**Comment by TacticalBacon86** [comment]
I don’t like the NXI version in the marketplace though. I prefer the
version that’s been on GitHub.

**Comment by sonicviz** [comment]
Me 3. It's hard to tell if the NXI version is "better" than this, but it would be nice if the range/cursor knob worked on this. It's a pretty essential basic function!

**Comment by sonicviz** [comment]
> gUYS, UNINSTALL wORKING tITLE g1000 ADDON & INSTALL THE g1000nxi VERSION FROM THE MARKET IT WORKS. tHE OLD g1000 wt VERSION IS BROKEN SINCE su5.

THERE'S NO NEED TO SHOUT, AND WE KNOW ABOUT THE MARKETPLACE VERSION

**Comment by TacticalBacon86** [comment]
I think there are many of us who prefer the non-NXI version at this point.
The initial WT G1000 on GitHub has more features.

**Comment by mattnischan** [comment]
This has been resolved in 0.4.1.

**Comment by TacticalBacon86** [comment]
Awesome!!
