### ISSUE TITLE
WT CJ4 0.12.6 PFD menu，LOWER/UPPER menu bottom no response

### ISSUE THREAD

**Issue by uncasual** [Working-Title-MSFS-Mods/fspackages#1303]
I installed the 0.12.6 few days ago. However after that ,when I was doing the flight date input, the PFD menu bottom and the Lower/Upper menu bottoms are no longer function as it should be. When I click on the PFD menu bottom and try to change the PFD display, there's no response at all and even the menu page doesn't come out. I don't know if it's my individual problem or it's common among the new updates.

**Comment by dga711** [comment]
Hey there. These seems to be a sim issue that showed up with SU5 where people's mouse profile doesn't work anymore.
Try to go to the control options in the sim and reset the profile for the Mouse.

**Comment by uncasual** [comment]
Seems it's a common problem of SU5. Thanks for your reply!
