### ISSUE TITLE
CJ4 - Bugs with Lower CCP Joystick

### ISSUE THREAD

**Issue by Crunchmeister1** [Working-Title-MSFS-Mods/fspackages#1307]
1. I've been told the joystick only works in LOCK mode and not in Legacy. Not sure if this is intentional or not.

2. The joystick won't take SimConnect events when set it LEGACY mode, only LOCK mode. Again, not sure if this is intentional or a bug. It should be able to take SimConnect events in any mode. 

3.  When in LOCK mode: both H:Generic_Lwr_JOYSTICK_DOWN and H:Generic_Lwr_JOYSTICK_UP only scroll in the up direction. In the cockpit, both work correctly as up and down, but via SimConnect, both commands are mapped to UP only. I KNOW this one isn't intentional!

**Comment by dga711** [comment]
> 1. I've been told the joystick only works in LOCK mode and not in Legacy. Not sure if this is intentional or not.
> 2. The joystick won't take SimConnect events when set it LEGACY mode, only LOCK mode. Again, not sure if this is intentional or a bug. It should be able to take SimConnect events in any mode.
> 3. When in LOCK mode: both H:Generic_Lwr_JOYSTICK_DOWN and H:Generic_Lwr_JOYSTICK_UP only scroll in the up direction. In the cockpit, both work correctly as up and down, but via SimConnect, both commands are mapped to UP only. I KNOW this one isn't intentional!

1 and 2: This is not intentional but a bug with how it is setup in the Sim's Modelbehaviors. Maybe we can find a workaround, otherwise it is on Asobo to fix that
3: Have to look into that.

**Comment by Crunchmeister1** [comment]
Jut downloaded the latest CJ4. Joystick works fine in this one.  I guess we can close this bug report.
