### ISSUE TITLE
CJ4 ND range arcs not accurate

### ISSUE THREAD

**Issue by awaylands** [Working-Title-MSFS-Mods/fspackages#1320]
The range arcs on the ND understate the correct distance waypoints are from the aircraft. See attached photo.

![36D2042C-EED4-497D-8C5C-053006E64C16](https://user-images.githubusercontent.com/42011354/128638235-0c56b5e3-ba63-4de0-860c-4fddde4baab5.jpeg)

**Comment by dga711** [comment]
Should have been mostly fixed with 12.7
