### ISSUE TITLE
Legs blank on MFD

### ISSUE THREAD

**Issue by riddymon** [Working-Title-MSFS-Mods/fspackages#1321]
CJ4: Version 0.12.6

Not sure how to describe it but the line showing your entered flight plan is missing.  In fact, it disappeared shortly after I took off.  I'm assuming this is related to SU5 since there's a whole bunch of other things that aren't working correctly but just adding it here just in case. The only way I could see it to begin with was by hitting the Mem 2 button because the LWR MENU button is not working either. Screenshot attached:

![image](https://user-images.githubusercontent.com/1652538/128648619-d04493c3-02fa-472f-8f67-b77adf161f65.png)

UPDATE ok, so just out of curiosity, I hit MFD ADV and I was able to see the remaining legs and iterate through them.  So I guess it's stuck in plan mode but don't think I can get out of it.  Not with the current issues.  

![image](https://user-images.githubusercontent.com/1652538/128648749-7ebf7c75-3fca-4468-9da0-2bf39db6fb7f.png)

![image](https://user-images.githubusercontent.com/1652538/128648801-b2f1c6a7-3f6e-4745-a094-d908ea9726fc.png)

**Comment by dga711** [comment]
I think your MEM preset is not ok here. Maybe redo that one while in a good state.

If you can't press the other buttons on the panel, try to remove older versions of the G3000 from your community folder

**Comment by riddymon** [comment]
Thanks for the response! Pretty much never used the MEM presets personally so not to concerned about that.  I was just clicking around to see if anything would bring up something useful and that MEM 2 happened to do it for me.  Also, never installed the g3000 mod.  I also made sure I deleted the previous CJ4 installation before installing this new version.

**Comment by dga711** [comment]
Just saying all those buttons should work and do something. If that is not the case for you then something is bad with your sim.

**Comment by riddymon** [comment]
Interesting - well I'm experiencing issues similar to what was reported in issue #1290 that's currently open.  Everything was working pre-SU5 a few weeks ago when I last flew the CJ4. I think I'll just wait until the next hotfix for FS2020 comes out and try again with 0.12.7 ones that comes out (see the pull request open).  You can close this for now.  I can still fly it as is for the most part.

**Comment by dga711** [comment]
Yeah. Fixes for that I've seen are
a) make sure no old G3000 mod is installed
b) reset the mouse profile

maybe check https://forums.flightsimulator.com/t/fixes-work-arounds-for-su5-in-game-ui-tool-tips-missing-mouse-cursor-issues/429362

good luck!
