### ISSUE TITLE
CJ4 Fuel Setting Bug 

### ISSUE THREAD

**Issue by agoldhammer** [Working-Title-MSFS-Mods/fspackages#1323]
Prior to Sim Update 5, the Weight/Fuel Menu included a slider for setting the fuel in both tanks as well as separate sliders for left and right tanks. Now the both-tanks slider has disappeared, and trying to set fuel in either left or right tank affects the other tank and triggers a fuel imbalance warning. I was unable to equalize the fuel in the two tanks, hence could not fly the airplane.

**Comment by dga711** [comment]
Looks alright here 
![image](https://user-images.githubusercontent.com/2995606/128707572-ec950b0c-1daa-4fd9-824d-4b9f1bc4fce6.png)

Maybe you have some addon or mod installed that is screwing with it?
