### ISSUE TITLE
(CJ4) FMC buttons not clickable

### ISSUE THREAD

**Issue by ionutned** [Working-Title-MSFS-Mods/fspackages#1332]
All the buttons and features seem to work, except for the FMC: the buttons are not clickable, the mouse pointer doesn't change when going over the buttons. I can only see the initial status screen.
Tested with both legacy and lock mode( with tooltips both disabled and enabled).
Version: 0.12.7

Sample video clip:
https://drive.google.com/file/d/1NRFIH3hcIeS603pCaB4buoCMa3RfApuQ/view?usp=sharing

**Comment by indekt** [comment]
Exactly the same for me after a fresh installation of FS.

**Comment by riddymon** [comment]
A fresh install was what fixed all of my button issues. I sort of had the opposite...my FMC buttons were working but a lot of the MFD and glareshield buttons weren't.  When you do a fresh install, make sure you rename/delete the cache folder in AppData (where your community folder is).  My issues weren't fixed until I did that.  Unfortunately, that also means you'll have to reinstall all of your add-ons

**Comment by pavelzamyatin** [comment]
Can confirm, I've got the same problem with the FMC buttons.
Clearing cache didn't seem to do anything.

**Comment by ionutned** [comment]
I tested what @riddymon said and it worked for me, reinstalling the whole simulator from scratch did the trick.
I'm not sure where the FS files are on every installation, I put most of the stuff in a folder on a separate disk, but there still are a lot of files in `appdata\Roaming\Microsoft Flight Simulator`, which might affect the situation. When I removed the simulator for re-installation, these files were still there, so I deleted the whole folder manually. Maybe this is needed for a successful reinstallation.

**Comment by dga711** [comment]
One thing that came up is, that people that have the KingAir addon installed from the marketplace have issues since it seems to override and break some stuff.

**Comment by riddymon** [comment]
@ionutned Glad that did the trick.  Definitely not an ideal solution but it was the only one that worked for me.

**Comment by pavelzamyatin** [comment]
I completely reinstalled the game, including all the packages' folders. 
Didn't help in my case - the issue remains the same.

**Comment by asoft76** [comment]
Buttons not working at all for me with last release. Erasing mod fix the problem
