### ISSUE TITLE
FAQ: Incompatible liveries

### ISSUE THREAD

**Issue by StoffePro** [Working-Title-MSFS-Mods/fspackages#1336]
From the FAQ:

> If you are using a 3rd party livery or, as of MSFS patch 1.12.13.0 the new liveries for the CJ4, the panel.cfg file is overwriting our FADEC injection code. You can either remove that panel.cfg file from your custom livery or use the first default CJ4 livery.

Are you sure this is still the case? I've been using the new livieries from Asobo, and cant' see anything wrong.

**Comment by dga711** [comment]
In the meantime Asobo removed the panel.cfg/xml from most of their liveries, as it was unecessary in the first place.

With the new Livery01 they tried a new system that avoids this problem but it doesn't work as expected. So, at the moment all Default/Asobo Liveries should work, besides Livery01 (i suspect).
