### ISSUE TITLE
g1000-v0.4.1 blank screen (w g36)

### ISSUE THREAD

**Issue by crazycanuckd** [Working-Title-MSFS-Mods/fspackages#1338]
After updating to v0.4.1 crs knobs work. but PFD is completely blank.

**Comment by rob2791** [comment]
Blank for me too.  I have never installed NXi, so I don't think it's related to that.
Using 0.4.0 in the mean time.

**Comment by Shaha787** [comment]
Hi all!
On Diamond DA-40NG PFD and MFD are black and Blank. Whan you turn key to position ON no reaction.

**Comment by truoss** [comment]
For me the same 0.4.0 is working 0.4.1 has black screens.

**Comment by billw2012** [comment]
FYI fix is easy and you can do it yourself based on this: https://github.com/Working-Title-MSFS-Mods/fspackages/pull/1345
Basically just find `html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.html` and delete line 1007 (the one about FileHandler.js).
