### ISSUE TITLE
Related to G1000 NXI for Marketplace

### ISSUE THREAD

**Issue by 39crauds33** [Working-Title-MSFS-Mods/fspackages#1339]
I have v3.0 of the G1000 NXI from the Marketplace.  I have tried with several different aircraft but same issue.  When I flightplan an ILS approach, the localizer does not activate when I am on final and press APR.  Maybe that is strictly a G3000/G5000 function(?)  So in my subsequent attempts I loaded the frequency into NAV1 and manually switched the Source in PFD from FMS to NAV1.  The name of the ILS does not appear only NAV1 Loc and no DME unless I select the DME.  But a bigger issue is that the course does not automatically default to correct ILS course.   I can change CDI manually to correct course and then the autopilot will correctly follow the GS and LOC course.  But if I just press APR, the aircraft flies off in unpredictable direction.  If I press NAV then it turns to follow whatever course the CDI was set to in NAV1.   That would not be possible in RW since localizer has only one set course and is independent of anything else dialed into the CDI.  Please give this your attention.  Also would like the engine pages, etc,. to be added to the Marketplace version as soon as you can.    Thank you.  I am a great fan of your work!

**Comment by helmi44** [comment]
I have the same problem with the software from the marketplace, when I use the G1000 Ver. 0.4.1 both monitors remain black.
I have removed both versions and everything works reasonably well.

**Comment by dga711** [comment]
Please use Discord or MSFS forums to report issues you might have with the NXI. Thank you
