### ISSUE TITLE
CJ4/Navigraph

### ISSUE THREAD

**Issue by terryherenow** [Working-Title-MSFS-Mods/fspackages#1346]
Hi
The scroll function to scroll across the Navigraph charts for the in game function charts is not working neither in LOCK nor LEGACY mode.Charts appear just fine but you now cannot scroll left to right etc….Unable to do this means money spent with Navigraph cannot be fully utilised so waste of money.

Thanks ..Best Wishes Terry

**Comment by dga711** [comment]
Hi. It works fine for most people on LOCK mode, so there must be something wrong on your side.
Two things I can think of
- make sure you don't have an old version of the wt g3000 installed
- make sure you don't have the KingAir mod from the marketplace installed
- reset your mouse control profile to default

**Comment by davideo0** [comment]
Hi,
I'm having the same problem as terryherenow .
Tried all suggestions by dga711 but no joy.
Any other suggestions?
Thanks

**Comment by Glenranger** [comment]
I have the same problem.  In fact, in Lock mode, the mouse doesn't seem to work on ANY knobs or buttons!

**Comment by dga711** [comment]
Please check these https://github.com/Working-Title-MSFS-Mods/fspackages/issues/1346#issuecomment-905487729
Those are the common sources for that kind of problem

**Comment by Glenranger** [comment]
Aha!  I finally found out what was wrong.  It was the mouse settings in Control Options.  You MUST revert back to "default" for this to work correctly, then don't change any settings. Try it again in "Lock" mode and I think you'll find all is well. You can then alter any mouse bindings to your taste and you'll probably find that one will stop it working again.
