### ISSUE TITLE
G3000 0.7.4 missing download link

### ISSUE THREAD

**Issue by srpnor** [Working-Title-MSFS-Mods/fspackages#1347]
Hello,

The download link for the compiled/final version of G3000 0.7.4 is missing from https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.7.4 - only the source code downloads are available.

Thanks, Steve

**Comment by rabsp9** [comment]
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/g3000-v0.7.4a/workingtitle-g3000-v0.7.4.zip

**Comment by dga711** [comment]
Yeah there was a mishap on release so it shows up in a different release entry.
The safest thing path to get the right latest version is from our website https://www.workingtitle.aero/packages/g3000/
