### ISSUE TITLE
Glass Cockpit Issue after Japan Update

### ISSUE THREAD

**Issue by Bous3r** [Working-Title-MSFS-Mods/fspackages#135]
No working Glass Cockpit in CJ4 Mod after Japan update.

**Comment by cwburnett** [comment]
With the release of the MSFS 1.9.3.0 patch today, you can expect most if not all mods to require updates to work correctly. The Working Title team advises you to remove all mods, including our CJ4 and G1000 mods, from your Community folder until such time as they are updated. As has been the case with past updates from Asobo, there were significant changes to the codebase. In fact, this update is the most invasive from a file structure standpoint, with many files moving locations and quite a number of name changes. About 17,000 files were changed. We are currently in the process of assessing these differences and will shortly begin incorporating them into our code. We will try to get updates out as quickly as possible.

**Comment by Bous3r** [comment]
Thanks. By the way you guys doing a great job ! Keep on !
