### ISSUE TITLE
G1000 No Push Button Data Entry

### ISSUE THREAD

**Issue by MadMav24** [Working-Title-MSFS-Mods/fspackages#1353]
When it comes to entering flight plan data into the G1000 MFD I find that mine refuses to accept the "push" key strokes to bring up the Waypoint Information box. I can push the middle button twenty times and it might pop up if it feels like it. IF I am lucky enough to get the box to appear and touch the "keyboard" icon and enter the airport identifier then I can't get the data to transfer to the flight plan.

For some reason the inner knob just does not want to accept the "push" entry it is suppose to. I have tried the "enter" key as well. I have watch two videos on the this subject and I do not understand why the G1000 REFUSES TO WORK CORRECTLY.

**Comment by mattnischan** [comment]
@MadMav24 We do not accept issues on this GitHub for the NXi, which is not one of our open source projects. Please find us on our Discord, where you can leave feedback on the dedicated NXi channel.
