### ISSUE TITLE
WT CJ4 ChartFox Support

### ISSUE THREAD

**Issue by boomcreeper11** [Working-Title-MSFS-Mods/fspackages#1354]
I can't afford Navigraph and Chartfox is a good free alternative. I would like an option to sign into it with vatsim and choose to use that for my charts!

**Comment by mattnischan** [comment]
Unfortunately, we cannot support Chartfox because it doesn't really have an API we can use, and it only links to PDF versions of the charts, which cannot be displayed by the sim JS engine.

**Comment by boomcreeper11** [comment]
How does navigraph return charts from their api?

**Comment by mattnischan** [comment]
Navigraph has a big API with all the metadata we need (like what kind of chart it is, plate names so we can correlate them properly into the menu, etc), which Chartfox doesn't have at all. Additionally, we would require the charts as an image file (PNG is the best option).

**Comment by boomcreeper11** [comment]
Oh ok
