### ISSUE TITLE
COM frequency issue v0.12.7

### ISSUE THREAD

**Issue by r-flo-r** [Working-Title-MSFS-Mods/fspackages#1355]
hi. when i am setting a com frequency, it dials it in for about 2secs, but then jumps back to the initial value. to be more precise: i can dial in another freq on the COM1-Recall button and it stays there. if i hit recall it changes to a frequency which was there before i dialed the new on in on Recall.
if i directly try to dial in it in the COM1 directly, its there for about 2seconds and then switches back to the old one.

thanks

**Comment by dga711** [comment]
Make sure that AI is not controlling the radio comms in Assistance Options
