### ISSUE TITLE
The NAV caravan C208 does not work

### ISSUE THREAD

**Issue by chote85** [Working-Title-MSFS-Mods/fspackages#1358]
**Hello, today I installed the update within MFSM and I went to fly the caravan and the NAV does not work, the CDI is in GPS and it does not go to the route that has been marked, it is still straight or with the FD on, the GPS marks display but not goes to the road**

**Comment by StarkGER** [comment]
yep, same problem on other planes here aswell. NAV Mode seems to be INOP atm. 
Tried C172 G1000, DA62 and Cirrus SR22. All the same on those regarding NAV mode

**Comment by mattnischan** [comment]
@chote85 @StarkGER - We are not taking reports for the G1000 NXi here, as it is not one of our open source mods. Please find us on our Discord or on the Flight Simulator forums.

If you are experiencing issues with NAV mode following the course, please note the following in the release notes (this is accurate to the real unit):

> **GPS, LOC, and VOR modes now ARM!** Be aware that you will need to be on an intercept course and within capture distance of the desired flight path before those modes will become active.

**Comment by StarkGER** [comment]
Oh my bad. Sorry for that. And thank you really much for enlightening me on my stupidity... should've looked further. I even saw the GPS Arm notification... Have a nice day
