### ISSUE TITLE
OBS Button Grayed Out in G1000 Nxi v0.5.1

### ISSUE THREAD

**Issue by mathurpc** [Working-Title-MSFS-Mods/fspackages#1361]
The default G1000 has a functioning OBS button but the latest update from WorkingTitle has a non-functioning OBS button

Pramod

**Comment by mattnischan** [comment]
Hello,

We do not accept reports for the NXi here, as it is not one of our open source mods, but a new ground-up product. However, OBS is not yet implemented on the NXi, but will be coming in the next major release.
