### ISSUE TITLE
[cj4 0.12.7] Alt sync does nothing 

### ISSUE THREAD

**Issue by psyonicus** [Working-Title-MSFS-Mods/fspackages#1367]
Hello everyone. 

Issue: "Pressing" the alt knob to sync altitude does nothing.

Expected behavior: Should immediately set autopilot set altitude to current aircraft altitude.

Reproducibility: 100% happens (or rather, nothing happens) all the time for me. Can anyone confirm?

Let me know if further info or testing is required.

Best regards.

**Comment by dga711** [comment]
That is correct as per the real thing. It isn't there to sync the altitude but to cancel the alert (flashing on PFD) when coming close to the preselect altitude.
