### ISSUE TITLE
The target name length 261>277 is more then 259 characters  G3000-v0.74 fresh install

### ISSUE THREAD

**Issue by DjSteveOhh** [Working-Title-MSFS-Mods/fspackages#1372]
..\Community\fspackages-g3000-v0.7.4\src\workingtitle-vcockpits-instruments-airliners\html_ui\Pages\Vcockpit\Instruments\Airliners\Shared\WT\VerticalSpeedIndicator,js

is the first one and then about 80 more in different locations all being to long with the filenames...

**Comment by dga711** [comment]
Please see here https://www.workingtitle.aero/packages/g3000/issues
