### ISSUE TITLE
CJ4  - Cannot select chart to display on MFD

### ISSUE THREAD

**Issue by 1r2s3s** [Working-Title-MSFS-Mods/fspackages#1377]
Per the Users Guide:
Before any charts will appear, an ORIGIN and/or DEST (destination) must be filled on the FPLN page. Then, press the LWR MENU button and use the MENU ADV (outer knob) on the CCP to highlight a chart. To view, press the inner PUSH SELECT button.

To view, press the inner PUSH SELECT button. 
This does not work. 
It just shows a picture of a hand.

**Comment by dga711** [comment]
With the new interaction system since SU5 you have to hold the inner knob with the left mouse button and press the right mouse button to actually press it.

**Comment by 1r2s3s** [comment]
Thanks, I tried it.

Mouse over knob. Hand displays.
Left click and hold. Inner knob turns yellow.
Right click. Nothing happens.
