### ISSUE TITLE
Make available on xbox

### ISSUE THREAD

**Issue by robzig** [Working-Title-MSFS-Mods/fspackages#1383]
i'd like to put in a plug for you to port your Cj4 into xbox.  i'm using your G1000 NXI in xbox and it is excellent.  It would be great to be able to access your Cj4 in xbox with all its enhancements, including VNAV functionality.

**Comment by extdesign** [comment]
Wait this magic too

**Comment by snipem** [comment]
@dga711 Why closed? Any new info on this? Regards

**Comment by dga711** [comment]
@snipem  Because its not related to the open source mods here on GitHub. The open source mods themselves will never be on Xbox. Any work we now do directly on the sim will be (like the NXI).
