### ISSUE TITLE
G3000 on Longitude: LOC is not working, GS works fine.

### ISSUE THREAD

**Issue by xrb936** [Working-Title-MSFS-Mods/fspackages#1390]
When final approach, LOC can be caught without any issue, but the aircraft won’t fly with it. GS works fine. Tried with multiple airports.
I am currently using this mod: https://de.flightsim.to/file/3655/asobo-cessna-citation-longitude-flight-dynamics-modifications-project-version-1-0
Thanks!

**Comment by antonvons** [comment]
I have noticed a recent change (at least in the G1000) in the way LOC works not. When you select APP you have to also select NAV/GPS if on HDG mode before the Localizor will engage.
This may or may not be what you are experiencing.

**Comment by XCSWxcsw** [comment]
same for me here, always a little bit left or right of LOC. Also it will not automatically catch LOC. you need still active by yourself.

**Comment by mattnischan** [comment]
Hi all,

The autopilot and navigation systems in the G3000 mod are the stock simulator systems. The is no custom navigation or autopilot in the G3000. Therefore this is unfortunately an issue within the sim.
