### ISSUE TITLE
G1000: Endurance = 0

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#140]
Hi,

After the problem with endurance and range while fuel flow is 0 was fixed yesterday, I now get an endurance reading of 0:

On commit 5907caa6784e5ae2f619978a5fa319771f6b1488

![image](https://user-images.githubusercontent.com/11409383/94609256-c6e64480-029e-11eb-8c7a-cdc9ba2ec8f5.png)

**Comment by kaosfere** [comment]
Thanks, we fixed this one prior to release.
