### ISSUE TITLE
CJ4 - LNAV not working while pending changes to Route?!

### ISSUE THREAD

**Issue by ChrisMuellersCode** [Working-Title-MSFS-Mods/fspackages#1415]
I was just planning my approach while in cruise. I had pending changes in the FMS on the LEGS page (the EXEC light was illuminated). While I was double checking everything with my charts (several minutes, I took my time), I overflew a waypoint and my new course required a correction of several degrees to the right (about 20 I guess). The autopiloted did not change course. The FD did not indicate a correction necessary. 
The FD & autopilot only corrected after I executed the changes. 

Version 0.12.8

Regards, 
Chris

**Comment by dga711** [comment]
That should usually not be the case. Will try to reproduce.

**Comment by ChrisMuellersCode** [comment]
I am experiencing the issue with Version 0.12.9 also. Happens every time there are pending changes.
