### ISSUE TITLE
Increase the density of displayed intersection waypoints at highest map detail

### ISSUE THREAD

**Issue by rjp7** [Working-Title-MSFS-Mods/fspackages#1419]
I've noticed this mod displays fewer intersections on the map than the default G3000. What controls which intersections are displayed? A hidden intersection will display on the map if added to a flight plan. Would prefer the option to see them all displayed on the map to allow for more precise flight planning.

**Comment by mattnischan** [comment]
The default G3000 behavior is not accurate to the real unit, while the mod's is. The real G3000 (and the mod) will cull intersection labels that are too close together, and will display only the icon of an intersection when the density becomes high, choosing instead to just display a single label for one intersection and not display any of the other labels that would be overlapping. There is no configuration option to force labels to be overdrawn.

The moving maps of the Garmin units are not really intended for use as a flight planner, but for situational and spatial awareness.

**Comment by rjp7** [comment]
Ok. But when zoomed in, there is plenty of open space on the map for more intersections to be drawn if they exist. No overlapping necessary. I often look for ones close to airports. But if that's how the real G3000 behaves then so be it.
