### ISSUE TITLE
overfly function

### ISSUE THREAD

**Issue by XCSWxcsw** [Working-Title-MSFS-Mods/fspackages#1422]
Some airports have not published the SID/STAR. I made waypoint myself, but I found that the G3000 does not have the overfly function. Can you add that aslo? Thansk a lot!

**Comment by mattnischan** [comment]
@XCSWxcsw The G3000 mod uses all stock navigation, flight plan, and autopilot systems. As such we will not be able to add the ability to set a waypoint to overfly. We do not plan to add custom nav to the G3000 mod.

Stay tuned for our G3000 Marketplace early access version which will be receiving custom nav: like the NXi, this will be free on the Marketplace in early access and then will eventually replace the stock G3000 in the sim.
