### ISSUE TITLE
MSFS 2020  1.21.13.0    CJ4  Working Title  v0.12.9

### ISSUE THREAD

**Issue by ftd1949** [Working-Title-MSFS-Mods/fspackages#1425]
Unable to activate options available in the LWR MENU  ie: PPOS Working Title  v0.12.8  Unable to change the format from ROSE to other available format
![Capture](https://user-images.githubusercontent.com/30202162/142656797-b708e963-ff0b-4c4e-a279-dc449ce5db15.PNG)
s.

**Comment by slip664** [comment]
Version 12.9 is the current version which includes fixes for the latest MS Service Update. 

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.12.9

**Comment by ftd1949** [comment]
Thanks for the response.  While that may include fixes I still am unable to
enable PPOS.  I've been using the 12.9 Mod since it was available and have
had no problems with it until now.
Any suggestions?  I moved it out of the Community folder and re-downloaded
and installed it back into Community.


*Craig S. Evans*

*40112 Crooked Stick Dr.*
*Lancaster, SC 29720*

*540.580.4170*

**Comment by ftd1949** [comment]
Sorry. I am using 12.9 and am still having issues enabling PPOS
*Craig S. Evans*

*40112 Crooked Stick Dr.*
*Lancaster, SC 29720*

*540.580.4170*

**Comment by mattnischan** [comment]
@ftd1949 Just a heads up, all emails in response to these messages get posted to GitHub (that's just the way GitHub works), and they are presently including your address and phone number.

I'm deleting those details from the GitHub but would advise caution.

**Comment by ftd1949** [comment]
Ok, thanks.
*Craig S. Evans*

*40112 Crooked Stick Dr.*
*Lancaster, SC 29720*

*540.580.4170*

**Comment by MilanPutnik** [comment]
> Thanks for the response. While that may include fixes I still am unable to enable PPOS. I've been using the 12.9 Mod since it was available and have had no problems with it until now [...]

@ftd1949
No, you have been using version 12.8 up until now. And after updating the simulator to 1.21.13.0 you started having that issue.
Now you downloaded the latest updated CJ4 version 12.9, and you no longer experience the issue. You are flying happily. Ain't that right? 😁

**Comment by mattnischan** [comment]
@ftd1949 If you are in the simulator's lock interaction mode (which you might be, since some settings got reset in SU7), then you need to hold left mouse button with the knob highlighted and click the right mouse button to press in a knob.

**Comment by ftd1949** [comment]
I'm still having the problem using version 12.9

**Comment by ftd1949** [comment]
thx mattnischan.  All is well.  Found Legacy mode
