### ISSUE TITLE
Sim Update 7, CJ4 Beacon and Strobe no longer working?

### ISSUE THREAD

**Issue by mms1648** [Working-Title-MSFS-Mods/fspackages#1426]
Since updating to SU7 and using the new WT CJ4 version (v0.12.9) the Beacon and Strobe lights are inop, tried the previous version CJ4 (v0.12.8) and same issue.  Not using any other add-ons in Community

**Comment by dga711** [comment]
Thought I tested that. Will check again

**Comment by dga711** [comment]
@mms1648 They seem to be working fine for me
![image](https://user-images.githubusercontent.com/2995606/142843464-d548f38c-ebe1-4ee9-b56e-c979425ed2a3.png)

Do you have any lighting/fx mods installed?

**Comment by mms1648** [comment]
Thanks for double checking, I don't have any mods other than Air Manager.

**Comment by mms1648** [comment]
Just to let you know, I wiped my entire PC, reinstalled Windows 11 from scratch (trying to solve CTD issues) and then only installed Flight Simulator, the lights didn't work on the default CJ4 or WT, so something else at play here, didn't fix my CTD's either, I have tickets in to Zendesk

**Comment by evpoppel** [comment]
lights working fine for me. SU7 beta

**Comment by mms1648** [comment]
I figured it out finally, the update must have reverted some mappings on my Bravo throttle, all good now!
