### ISSUE TITLE
CJ4 ILS Issues

### ISSUE THREAD

**Issue by Gazzareth** [Working-Title-MSFS-Mods/fspackages#1429]
In this case short test flight:

EGPH RW24 CUMBO ILS RW23 EGPF

1/ When switch from LNAV to LOC occurs PFD does not switch to NAV mode.

2/ Glideslope Arms, but does not capture.

3/ Switch to NAV mode manually and CRS is set to to 000.

Using Navigraph data, if that makes any odds..

G

**Comment by mattnischan** [comment]
Duplicate of #1428
