### ISSUE TITLE
CJ4 CCP and DCP not working completely.

### ISSUE THREAD

**Issue by hydbyr** [Working-Title-MSFS-Mods/fspackages#1431]
Completely is the correct word because some of the functions appear to work. Running WIN11, SU7. CJ4 Version12.9.  Same problem in Ver 12.8 with SU6 of MSFS2020.

I cannot set the display range.  I can only get the NAV switch to work on the Display control panel. None of the buttons on the Cursor Control Panel function.

I have changed the livery several times (and re-started the sim) without luck.  I have used the Air Canada livery, the CAF livery, and the Freightway livery. All these functions worked in ver 10.

After making the above changes without success, I am beginning to think that I am either doing something wrong or missing a fundamental step. Any good ideas???

**Comment by mattnischan** [comment]
@hydbyr Do these functions return if the CJ4 is the only thing in your Community folder?

**Comment by hydbyr** [comment]
Will check.

**Comment by hydbyr** [comment]
YES.  With the Global Freightways and the default livery.  I will try the non-standard liveries now.  I found all the assists set to easy and had to re-set them.  The bird shouts "autopilot" right at the beginning, but I don't think that's a WT issue.  I noticed that someone had issues with their strobe lights - not a problem on my installation.  I don't overclock as my 1080Ti doesn't like it in MSFS2020.
Do you think the issue is with one of the liveries, or with another add-on? Just a guess from you based upon what else you may have seen.

**Comment by hydbyr** [comment]
Lat time I got the menus and figured all was good.  I checked further and found that the "push to select" (on both panels) was inoperable. I couldn't select anything in the menus.  The range increase/decrease works.  The menu advance works.

**Comment by mattnischan** [comment]
@hydbyr In lock interaction mode you need to hold the left mouse button while on a knob and then click the right mouse button to press the knob.

**Comment by hydbyr** [comment]
Matt:

That works.  I have the 12.8 manual - where do I find that?  I have obviously missed something important.

 

Regards,
KC

 
 

Sent: Sunday, November 21, 2021 at 8:08 AM

**Comment by mattnischan** [comment]
@hydbyr This is not a CJ4 specific thing, this is just how the MSFS lock interaction mode works throughout the sim in all aircraft.

**Comment by hydbyr** [comment]
Sorry about that Matt - where is that info found?  If it's in the training missions, then there is almost zero chance that I would see it (PPL, IFR SEL).  What other modes might there be and where should I look for that info?

 

I'm really trying to get better at the sim.

 

Regards,

KC

 
 

Sent: Sunday, November 21, 2021 at 9:19 PM

**Comment by mattnischan** [comment]
@hydbyr That's actually a good question, I don't know where they explain the Lock Interaction Mode. There are two modes: Lock and Legacy (which is more like the old mode), which can be found in Options -> General Options -> Accessibility -> User Interface -> Cockpit Interaction System

**Comment by hydbyr** [comment]
Thanks a lot, Matt.  I truly appreciate your responses - this whole lock interaction mode was driving me crazy.  I figured out the grab and move interaction for switches by sheer good luck.  I doubt I ever would have figured out how to get the select option switch to work.

Regards,

KC

 
 

Sent: Monday, November 22, 2021 at 8:42 AM
