### ISSUE TITLE
Wrong/missing information G1000 NXI

### ISSUE THREAD

**Issue by WoSt53** [Working-Title-MSFS-Mods/fspackages#1441]
G1000 NXI, version: 0.9.0
Take a short VFR flightplan with some waypoints.
Example: EDLW - KOLOT - DL410 - VP216 - OSDIK - OSN - DG016 - EDDG. ILS EDDG 25: 110.10
![annt](https://user-images.githubusercontent.com/94929844/143090242-4ac8d61c-13c2-4693-9420-a82a5b5a81a7.JPG)

First line G1000 NXI shows 'DIS' = 6.5 NM, reamining from OSDIK.
Bottom line of picture shows 'GPS' = 0. Here should be 6.5, because I used 
A:GPS WP DISTANCE. This is standard from simulator.
Means, it is broken.

Picture shows another problem. DME says, NAV1, (IMOW)  is within 19.5 NM. Correct.
Bearing for NAV1 shows the white circle in HSI, but no arrow.

Both problems are gone, when using stock G1000.

When you need further explanation, please ask.
Please continue your good work and fix those problems.

**Comment by antonvons** [comment]
Just a thought, WT may not action your report as they have asked that all NXi issues should be reported via their discord. (see note at the top of the issues channel)
