### ISSUE TITLE
CJ4 - FMS in InMg or hPa

### ISSUE THREAD

**Issue by AzzameenF18** [Working-Title-MSFS-Mods/fspackages#1442]
Hi, is there a possibility in the FMS to switch between hectopascals and inches of mercury? I can see that it is possible in the PFD, but I can't find it in the FMS. Thank you very much

**Comment by dga711** [comment]
I believe that in the perf pages you can just enter both

**Comment by AzzameenF18** [comment]
That's right, if you enter the value without a dot, it just does the conversion by entering it. But as an improvement, it would be nice to be able to select one or the other measure. (Note, only as a future option). Thanks you!!!!
