### ISSUE TITLE
CJ4 Issue in both versions 0.12.9 & 0.12.10

### ISSUE THREAD

**Issue by Topgun13807** [Working-Title-MSFS-Mods/fspackages#1443]
1. PFD, MFD and FMS for both Pilot and Co-pilot have blank white screens &
2. Can't load a simBrief Flight Plan.  The FMS hangs prior to EXEC.  Flight Plan can be loaded by clicking the Left LSK 4 from game but flaps and gear aren't activated on final approach when AI Control is activated .
3. Reloading Workingtitle v0.12.8 brings all the aforementioned screens up again but same issue continues when trying to import a simBrief Flight Plan into the FMS.
![Blank White PFD MFD   FMS Screens](https://user-images.githubusercontent.com/94807881/143516319-558c0ddc-4d6e-420c-9865-f806fe9498f6.jpg)
![SimBrief Flt Plan](https://user-images.githubusercontent.com/94807881/143516413-faaa6053-de79-4223-bb0e-7c31ca317905.jpg)

**Comment by dga711** [comment]
@Topgun13807 Are you sure your sim and content is actually updated to SimUpdate 7? It should have the version 1.21.13.0 in the window title.
The CJ4 12.8 should not work in SU7 and in fact give you white screens whereas 12.9+ should not. So something is turned on its head in your case.

1. Read the "Note about Liveries" in the latest readme https://www.workingtitle.aero/packages/cj4/2021/11/23/cj4-release-v0.12.10.html and also update the cockpit texture mod if you are using that.
2. and 3. Should be fixed if 1. is resolved.

**Comment by Topgun13807** [comment]
First of all, thank you for responding to my Email so promptly.  I’m sure you guys are very busy.  You need to be congratulated on all the good work you’re doing so that we, the end users, can enjoy flying.

 

I’ve responded to your questions below (highlighted in YELLOW) and have also outlined what I’ve done this morning since receiving your Email.

**Comment by mattnischan** [comment]
@Topgun13807 The cockpit texture mod is not official or from Working Title; the suggestion here was merely that _if_ you have that mod installed, then you will need to upgrade it. It is not a required addon.

Glad you were able to get your issues sorted.
