### ISSUE TITLE
CJ4 Throttle position doesn't update whilst in freelook mode

### ISSUE THREAD

**Issue by RSpeekenbrink** [Working-Title-MSFS-Mods/fspackages#1446]
When in freelook in the cockpit camera (right mouse button by default) control inputs on the throttle are not working and won't be updated until you release the freelook.

version 0.12.10 in SU7

**Comment by mattnischan** [comment]
@RSpeekenbrink This is an issue within the sim and not within the mod, and cannot be addressed by mod code. This happens with all aircraft presently in MSFS.
