### ISSUE TITLE
CJ4 Sudden loss of thrust and ITT Master Warning

### ISSUE THREAD

**Issue by ChrisMuellersCode** [Working-Title-MSFS-Mods/fspackages#1451]
CJ4 Version 0.12.10

Today I experienced a weird behavior that leads me to suspect a bug somewhere in the FADEC code. Unfortunately I do not have a precise reproduction of the issue. I hope the below stories help to pinpoint it anyway. 

I was climbing out of LOWW through FL224, in the clouds with wing anti ice, engine anti ice and pitot heat on, when a sudden and very drastic wind change / turbulence hit me. I noticed a sudden increase, followed by a decrease in indicated airspeed and the wild camera movement that comes with it. It looked to me, as if MSFS recalculated upper winds at that moment, since the direction was changing from more or less a headwind to a tailwind and then, after a few seconds, back to a headwind again.
Right at that moment, I received a master warning (ITT) and the ITT scale indication on both engines was at its maximum value. At the same time, thrust values for both engines where at around idle, even though I was on a climb thrust setting. 
I tried setting TOGA thrust and after that idle thrust followed by TOGA thrust again. Both actions did not change anything. I tried to shut down (via engine run/stop button) and restart both engines (via starter switch an run/stop buttons) while I descended to remain above stall speed. Both engines restartet. And seemed to stabilized. After another drastic change in wind speed and direction I received the same behavior. This time I was stalling and the following recovery maneuver I overstressed the airframe and that ended the flight.

I can not yet provide an exact reproduction of the issue. However, I experienced something similar where I was leveling of for a cruise at FL450. This time without engine and wing Anti ice. I received a very brief Master Caution that was so brief, I could not even read it. Simultaneously both engines delivered a little bit more than idle thrust. They where responding to the thrust inputs, but TOGA lever position never led to TOGA thrust. I immediately descended to FL430 and switched on Engine Anti Ice and wing anti ice, since I was suspecting an icing issue that led to a flame out. After a while the engines stabilized and I finished my flight uneventfully.

**Comment by SLOJO1** [comment]
Getting the same during climb out of Aspen in FLC. Losing 80 knots and power. Kicking off AP and descending restores after a couple of minutes, but then any attempt to climb and the issue repeats. Have used the mod normally since reinstalling after Update 7. This isue just began today. No other mod updates applied recently. Going to delete and reinstall this mod and recreate.

**Comment by mattnischan** [comment]
This is currently an issue with the live weather system, and not the mod. See the SU7 known issues list for the temp issue above 44.5K and see the following link for the current lower altitude spikes:

https://forums.flightsimulator.com/t/oat-of-248-c-at-fl285/478029/53

**Comment by ChrisMuellersCode** [comment]
Didn't know that. What a pity. Thanks for the clarification @mattnischan
