### ISSUE TITLE
N1/throttle failure around FL250

### ISSUE THREAD

**Issue by jpfowler** [Working-Title-MSFS-Mods/fspackages#1452]
The past couple of days I've noticed that upon reaching approx. FL250, N1 will drop to around 20-30% and not be able to be increased until altitude is reduced (effectively an engine failure at that altitude; speed drops to around 150 kts). When this happens, there is also uncontrollable and unrealistic turbulent motion of the aircraft. I believe this to be a bug and not just a coincidence of the past couple days, as I have not flown the Working Title CJ4 in a really long time until the past couple of days. Just in case you're wondering, this is with v0.12.10.

After two experiments this is what I've gathered:

I first noticed this yesterday but did not log it. But I know it was very similar, and probably exactly the same.

1st) Climb rate was ~2400fpm (set with V/S). Upon reaching roughly FL250, N1 dropped instantly to around 25% and I could not increase or adjust it (complete throttle failure). KIAS dropped to around 150kts almost instantly as well. I reduced vertical speed to a steady descent rate of ~2000fpm and upon reaching FL245, N1 came back to live and was controllable/adjustable.

2nd) I then tried to reproduce this bug. Similar to the first attempt, I set V/S to ~2400fpm and upon reaching FL256 N1 did the same thing, total throttle failure, KIAS dropped to around the same ~150kt value. I then descended, and at FL253 N1 came back and throttles were controllable.

I managed to fly a successful flight by staying right around/below FL250 because going a little higher will produce the bug.

Hope you get something out of this,
John

**Comment by mattnischan** [comment]
Please see: https://forums.flightsimulator.com/t/oat-of-248-c-at-fl285-impacts-negatively-on-aircraft-performance-and-autopilot-function/478029/288

**Comment by jpfowler** [comment]
Yes, thanks. I just got this cleared up in Discord (I think by you).
