### ISSUE TITLE
CJ4 PFD and MFD are blank white

### ISSUE THREAD

**Issue by Cspielman63** [Working-Title-MSFS-Mods/fspackages#1461]
When I load into the CJ4 the PFD and MFD are pure white. Even with the battery off.

This is with Version 12.11

**Comment by DennisHallIBM** [comment]
This is an incompatibility with one of the liveries....either uninstall CJ4 liveries 
one by one or remove all and add back one at a time to see which ones break the CJ4.  This is a known issue.

**Comment by dga711** [comment]
also make sure to update the cockpit texture mod if you are using that
