### ISSUE TITLE
Missing STARs

### ISSUE THREAD

**Issue by mmCpp11** [Working-Title-MSFS-Mods/fspackages#1463]
So I'm missing some STARS in the FMC on the CJ4. I noticed this problem at KBOS because my flight plan from SimBrief included ROBUC3. With default MSFS, only non-RNAV STARs are available. If I sync with Navigraph, all the STARs vanish and only the runway arrivals remain. Not sure if this is a bug or if I'm just doing something wrong. This is with version 0.12.11.

**Comment by mattnischan** [comment]
The mod merely reads what navdata is installed in the sim. If you are finding navdata to be missing, either it is missing in stock or Navigraph is not properly installed, which manifests as the problem you describe.

In either case, we would not be able to address it on our end.
