### ISSUE TITLE
G3000 v0.7.6 Synthetic Vision Exaggerates Height of Mountains

### ISSUE THREAD

**Issue by Geschosskopf** [Working-Title-MSFS-Mods/fspackages#1465]
Problem:  The synthetic vision of the G3000 mod (at least in the TBM 930) greatly exaggerates the height of mountains, making them appear much taller than either real life, the MSFS visual world, or the stock G3000's synthetic vision.  This appears to be a scaling issue with drawing the terrain.

NOTE:  I do use Navigraph Charts but I don't think this has anything to do with terrain.

Example:  I was flying east cross northern Columbia in the TBM 930.   My route took me over Pico Cristobol Colon which in real life tops out about FL188.  Skyvector's sectional shows FL197 for that quadrant.
![SynthViz 01](https://user-images.githubusercontent.com/5100775/146629646-897e979a-9732-46fe-8f67-52b060bae36a.jpg)

I was initially flying at FL250 at night in IMC so couldn't actually see the mountains to begin with.  However, synthetic vision showed them sticking up above my altitude, which would make them taller than Everest.  I of course trust nothing in MSFS so figured there might be a terrain bug here.  So I trusted the synthetic vision and climbed to my ceiling of FL310.  And it still looked like a near-run thing.
![46-03 Pico Cristóbal Colón Looks Higher than it is](https://user-images.githubusercontent.com/5100775/146629854-444b70f3-bb7c-4184-bb41-546924dbdb9b.jpg)

However, when I actually got over the mountains, by which time I was in VMC under bright moonlight, their elevation was as advertised on the sectional and I would easily have cleared them at my original altitude of FL250.
![46-04 No Problem Clearing Cristóbal Colón](https://user-images.githubusercontent.com/5100775/146629933-8b2fc59e-9325-4d70-b426-2440ccc3729d.jpg)

So, as I said, it appears there's a scaling issue with the synthetic vision.

**Comment by mattnischan** [comment]
Synthetic vision is drawn the by the sim, and not by the mod, therefore we are unable to address this. If you believe the display is in error, you will need to open a Zendesk with MSFS.

**Comment by Geschosskopf** [comment]
OK.  Because the mountains look the correct height in the stock G3000, I figured you all might have something to do with it.  But I will talk to Zendesk.
