### ISSUE TITLE
G1000nxi probably can't handle to many waypoints

### ISSUE THREAD

**Issue by Breenild** [Working-Title-MSFS-Mods/fspackages#1466]
Today we did a groupflight, which planned a vfr flight for. This contained MANY user-created waypoints to model the desired route.
But loaded into the G1000 (through the MSFS Worldmap - More - load) the route showed only a direct from origin to destination.
All the waypoints were not shown.

Could you please have a look into that and increase the number of allowed waypoints?

you can find an exampe of the flightplan here:
https://www.dropbox.com/s/xe92k8uzqptbjfc/VFR%20Locarno%20nach%20Locher.pln?dl=0

**Comment by mattnischan** [comment]
@Breenild This GitHub is for our legacy open source mods only. We do not track NXi issues here. Please direct your feedback to our NXi channel on our Discord.
