### ISSUE TITLE
Citation Longitude G3000 - WX Radar only updating on mode change

### ISSUE THREAD

**Issue by sixfoxes** [Working-Title-MSFS-Mods/fspackages#1467]
WX Radar precipitation image will only update on Scan Mode mode change. Image does not refresh or appear to change in sweeping manor when changing zoom level or turning radar off / on or through normal usage. Also fails to update when selecting display from off to Weather in WX RAD menu.

**Comment by mattnischan** [comment]
This is presently an issue with all weather radars generated by the sim, a bug introduced in SU7 that cannot be addressed with the mod.

We recommend opening a Zendesk for the issue.

**Comment by dga711** [comment]
for reference: https://devsupport.flightsimulator.com/questions/4155/su7-bug-weather-radar-doesnt-scan-any-more.html?childToView=4691#answer-4691
