### ISSUE TITLE
Unable to switch between NAV1 and NAV2 radios

### ISSUE THREAD

**Issue by jmiletti** [Working-Title-MSFS-Mods/fspackages#1468]
On the Cessna 172 Skyhawk using an Xbox Series console, the button that switches between NAV1 and NAV2 does not work.

This creates a lack of realism issue with the Garmin 1000 Nxi when planning to fly VOR to VOR and using more than two VOR waypoints.

**Comment by mattnischan** [comment]
@jmiletti This GitHub is for our open source mods only, and we do not track NXi issues here. Please direct your feedback to the NXi channel on our Discord.
