### ISSUE TITLE
Pan button does not work on the G1000 Nxi when using MSFS on XBox Series X

### ISSUE THREAD

**Issue by jmiletti** [Working-Title-MSFS-Mods/fspackages#1469]
Subject issue creates a lack of realism on G1000 Nxi as the only way to keep the plane position in view is to adjust the range.

**Comment by mattnischan** [comment]
@jmiletti This GitHub is for our open source mods only, and we do not track NXi issues here. Please direct your feedback to the NXi channel on our Discord.
