### ISSUE TITLE
G1000 NXi - Direct To Navigation

### ISSUE THREAD

**Issue by Nosruh** [Working-Title-MSFS-Mods/fspackages#1473]
DA62 unable to cancel direct-to navigation. 

From G1000 Cockpit Reference Guide (page 41):

"CANCELLING A DIRECT-TO

1) Press the Direct-to Key to display the Direct-to Window.
2) Press the MENU Key.
3) With ‘Cancel Direct-To NAV’ highlighted, press the ENT Key. If a flight
plan is still active, the system resumes navigating the flight plan along the
closest leg."

When in Direct-to Window, Menu Key not active.

**Comment by mattnischan** [comment]
@Nosruh This GitHub is for our open source mods only, and we do not track NXi issues here. Please direct your feedback to our NXi channel on our Discord.
