### ISSUE TITLE
Honeycomb beta throttle VS and IAS buttons not working with CJ4 working title mod

### ISSUE THREAD

**Issue by Shivato10** [Working-Title-MSFS-Mods/fspackages#1477]
I love this mod, it makes the CJ4 a lot more enjoyable to fly. So thank you for all the effort all you put in this.
When trying to fly with my Honeycomb Beta I noticed the VS and IAS buttons do not actually activate the VS or FLC mode in the CJ4 when using the mod. These buttons to function correctly in the vanilla/original version of the CJ4 shipped with smfs (i checked this). The VS and FLC can be activated in the mod using the mouseclick of the buttons in the cockpit and subsequently the value of VS/FLC can be controlled by the honeycomb beta throttle unit works.So only the VS/FLC selection buttons on the honeycomb throttle unit don't seem to activate these two modes. HDG, NAV. ALT work fine. It's a minor issue, but I hope it will be fixed.

**Comment by mattnischan** [comment]
@Shivato10 Per the release notes, in the known issues area, we do not support the binding of commands to the CJ4 autopilot via the sim. You will need to use external hardware binding programs, like spad.Next, Mobiflight, or similar.

**Comment by Shivato10** [comment]
@mattnischan I see, i was not aware binding is not supported. But i understand. I'm aware of this third party solutions. Thank you for the quick reply.
