### ISSUE TITLE
CJ4 v0.12.11 PFD Altitude stuck

### ISSUE THREAD

**Issue by capsos88** [Working-Title-MSFS-Mods/fspackages#1489]
on climb up to FL450,  the Altitude Band is stuck at 44600. but the A/C seems to climb further.
first Picture attached is my current PFD/MFD , 2nd Picture is the corresponding altitude on IVAO.
![2022-02-27 16_46_41-Window](https://user-images.githubusercontent.com/78560877/155889562-85afde17-9821-42e8-a32a-8ee5cbe1ed21.jpg)
![2022-02-27 16_47_03-IVAO Webeye](https://user-images.githubusercontent.com/78560877/155889568-cb8f9ef5-c229-423e-a2db-7932f01c9599.jpg)

**Comment by mattnischan** [comment]
@capsos88 Hi there, this is presently a bug in the simulator with any plane at that altitude, and will be fixed within the sim in SU8.
