### ISSUE TITLE
WT CJ4 FD flight control system display and flight commander command bars flickering

### ISSUE THREAD

**Issue by Axlsys** [Working-Title-MSFS-Mods/fspackages#1495]
hi, the FD flight control system display and flight commander command bars are flickering and flight director not engaging. 
any help in sorting this would be good. ta

**Comment by dga711** [comment]
Do you have any hardware connected and bindings to things that might influence it? 
For example switches on the Honeycombs send constant trigger signals.

**Comment by Axlsys** [comment]
Thanks for the quick reply. 
I yes, I  have saitek multi, switch and radio panels all using les O'Reillys ct4 spad.next snippets.
I also have thrustmaster rudder pedals, saitek cessna yoke, 2 Leo bodnar boards and a butchered cyborg joystick.

**Comment by Axlsys** [comment]
So, the wt cj4 seems to not like ether of the Leo bodbar boards, the other aircraft (default and fbw a32nx) are fine with it...... fussy old cessna lol
