### ISSUE TITLE
Regular CTD on G1000 NXI when using FMS knob since SU8

### ISSUE THREAD

**Issue by jcmk06270** [Working-Title-MSFS-Mods/fspackages#1496]
Using the default C208 with the G1000 NXI. Sometimes after 2 minutes of flight, sometimes after 20-30 minutes, when I turn the large FMS knob going between Map WPT Aux FPL NRST I get a CTD. It's always when I'm moving between these menus using the large FMS knob.  Have tried uninstalling the G1000 NXI from the content manager and reinstalled. When the G1000 NXI is not installed, using same plane/airport I'm not getting the CTD. I've also got the G3000 installed for the Longitude, that's working fine.

**Comment by mattnischan** [comment]
Hello,

We do not accept bug reports here for the NXi, as it is not one of our open source mods under this repository.

However, the issue you are describing is a bug from within the sim's terrain map rendering system (as JavaScript instruments like the NXi cannot CTD the sim on their own). We expect a fix for this issue in the sim to be delivered in SU9.
