### ISSUE TITLE
CJ4: No distance information on ILS approach (CJ4 0.12.12 with Sim Update 8)

### ISSUE THREAD

**Issue by avonheimburg** [Working-Title-MSFS-Mods/fspackages#1506]
When flying an ILS approach, there is no distance information shown (DME: ---).

**Comment by mattnischan** [comment]
Not all ILS beacons have DME. Have you checked a number of beacons?

**Comment by avonheimburg** [comment]
They should have DME  according to the charts (EDDW RWY 09 and EDDH RWY 23), I will have to check with another aircraft whether that is actually present in-game.

**Comment by avonheimburg** [comment]
That seems to have been a problem with the pilot. Closing.

**Comment by avonheimburg** [comment]
I have checked at EDDW RWY 09 and EDDH RWY 23. Both should have DME at
least according to the charts.

Am Sa., 19. März 2022 um 14:40 Uhr schrieb Matt Nischan <
***@***.***>:
