### ISSUE TITLE
RedBlink and YellowBlink not working for Vertical Gauges. YellowBlink not working for Circular Gauges

### ISSUE THREAD

**Issue by jb232** [Working-Title-MSFS-Mods/fspackages#1510]
When writing a custom panel.xml <RedBlink> and <YellowBlink> don't function for both Vertical and DoubleVertical gauges. They work only for Horizontal gauges 

Only <RedBlink> works fine for a Circular engine gauge, <YellowBlink> does not work for a Circular engine gauge

YellowBlink is critical to model the overspeed function of the Diamond aircraft for example which shouldn't be run at 100% until after takeoff/go around

**Comment by dga711** [comment]
Is this about the NXI?

The NXI is not part of our former open source mods on this repository, so we don't accept reports here.
Please report in our Discord or MSFS forums.
Thank you.
