### ISSUE TITLE
cannot link navigraph

### ISSUE THREAD

**Issue by beebase** [Working-Title-MSFS-Mods/fspackages#1519]
Browser doesn't open after message "linking navigraph" appears in the MCDU

**Comment by tigert** [comment]
I am having the same issue. It used to work earlier, but I had a pause in my navigraph subscription and it was initially "linked" but wouldnt give me charts, so I wanted to see if linking it again would help but it does not open the web page anymore.

**Comment by dga711** [comment]
Its usually an "issue" with the browser.
Make sure to have all browser windows closed before trying to link. For some it also helps to temporarily disable their blockers etc.

**Comment by beebase** [comment]
I fixed it by changing default browser from Chrome to Edge.
On second thought this might be related to add blockers as @dga711 mentioned above.
(I don't have any ad blockers in Edge)
