### ISSUE TITLE
[G1000] display backup has no effect on pop up MFD

### ISSUE THREAD

**Issue by cpuwolf** [Working-Title-MSFS-Mods/fspackages#1526]
"display backup" button does has effect in-game MFD, but no effect on pop-up MFD

**Comment by mattnischan** [comment]
@cpuwolf 

If this is regards to the G1000 NXi, we do not accept issues here, as it is not part of these mods and instead part of our work with the MSFS team.

However, this is a limitation of the sim display backup implementation, and also affects the stock G1000. We will be unable to work around this issue. I would instead put in a Zendesk ticket.
