### ISSUE TITLE
[G1000] display back up button is not hardware friendly

### ISSUE THREAD

**Issue by cpuwolf** [Working-Title-MSFS-Mods/fspackages#1527]
(>H:AS1000_MID_Display_Backup_Push)

**Comment by mattnischan** [comment]
@cpuwolf 

If this is regards to the G1000 NXi, we do not accept issues here, as it is not part of these mods and instead part of our work with the MSFS team.

The buttons and panel behaviors are part of the aircraft package, and not part of the NXi code. Please open a Zendesk ticket for any panel event concerns.
