### ISSUE TITLE
G1000: active leg color bug?

### ISSUE THREAD

**Issue by kaosfere** [Working-Title-MSFS-Mods/fspackages#153]
From https://forums.flightsimulator.com/t/release-working-title-g1000-v0-3-1-9-3-0-compatible/288944/16:

The first leg in the map is sometimes getting white and then back to magenta. Not sure if this is a MSFS issue or caused by the mod. Once on track, the leg remains magenta.

Inflight it seems like the magenta color is not always displayed despite the leg being active and AP GPS is following it nicely. So it seems like a display issue (maybe z-layer priority?). It stays white for this leg, the previous legs were all correctly magenta when active.

![](https://forums.flightsimulator.com/uploads/default/original/3X/c/9/c9079aafe40a9ae5f33861cdd083ac99c9e02f72.png)

**Comment by helge000** [comment]
Same issue the G3000:
![2020-10-18 21_18_12-Microsoft Flight Simulator - 1 9 5 0](https://user-images.githubusercontent.com/13696924/96378181-93565600-118a-11eb-810e-37c860cca302.png)
