### ISSUE TITLE
Does not capture LOC or GS when APR mode is selected

### ISSUE THREAD

**Issue by seglh** [Working-Title-MSFS-Mods/fspackages#1532]
Hi,

I fly  the TBM930 with the latest Workingtitle G3000 Ver 7.7.0
I select an ILS approach in the panel. The ILS frequency is automatically set in NAV1
I am in NAV mode (not FMS) and NAV1 is selected on the panel.
LOC and GS are active in the nav display. I am on hdg mode (30 deg offset final course)
I press APR and expect the aircraft to follow the LOC and to capture the GS but none of that happens.
The LOC and the GS symbol on the G3000 stays on the white color and the LOC or GS are never captured.

I happens all the time and just today 2 times.

Best regards / Jan

**Comment by Michail71** [comment]
I can confirm I experience similar.  Although I have had it work on a couple of occasions. I may have manually tuned the LOC frequency the times it has worked for me.

**Comment by mattnischan** [comment]
The WT G3000 mod uses entirely sim default flight planning, navigation, and autopilot. As such we will not be able to resolve any issues of this type. However, the upcoming G3000 refresh, due this year, will use the same technology currently being used in the NXi.
