### ISSUE TITLE
G3000 Autopilot Unable to Capture Initial Leg

### ISSUE THREAD

**Issue by Michail71** [Working-Title-MSFS-Mods/fspackages#1534]
TBM930
SU9
G3000 v0.7.8 

I'm not able to get the AP to lock on to the initial leg of a flight plan connecting to the departing airport. The heading indicator is usually pointed in a random direction not in alignment with the leg.  I either need to circle the airport until the heading indicator lines up or active Direct To on the next waypoint.

**Comment by mattnischan** [comment]
The WT G3000 mod uses entirely sim default flight planning, navigation, and autopilot. As such we will not be able to resolve any issues of this type. However, the upcoming G3000 refresh, due this year, will use the same technology currently being used in the NXi.
