### ISSUE TITLE
G3000 - Lateral alignment issue with heading indicator and map leg

### ISSUE THREAD

**Issue by Michail71** [Working-Title-MSFS-Mods/fspackages#1535]
TBM930
SU9
G3000 v0.7.8 

The heading indicator is laterally misaligned with the map leg by approximately 1.5 to 2 NM.  The AP seems to be following the heading indicator.

**Comment by mattnischan** [comment]
The WT G3000 mod uses entirely sim default flight planning, navigation, and autopilot. As such we will not be able to resolve any issues of this type. However, the upcoming G3000 refresh, due this year, will use the same technology currently being used in the NXi.
