### ISSUE TITLE
White Screens

### ISSUE THREAD

**Issue by normanh2** [Working-Title-MSFS-Mods/fspackages#1542]
I am getting white screens since SU 10 I am using the default livery and have removed everything I think may be causing the conflict but no luck. I removed Version 12.13 and installed version 12.14 I have been flying the CJ4 for quite a while and consider it to be the best there is -- I admit I am not "the sharpest knife in the drawer" when it comes to technicalities but I hope you can help me to get back flying this fantastic aircraft. Thank you for your anticipated understanding - Cheers - Philip Holden

**Comment by dga711** [comment]
There are a few possible causes for white screens, which happens if an old panel.cfg or cockpit model is around
- Make sure CJ4 is at least on version 0.12.14 and you updated it by removing the old one first
- Make sure you don't use an old livery that fully overrides panel.cfg (which only old obscure ones would still do)
- If you are using the CJ4 Cockpit Texture mod then update it to the latest version

**Comment by normanh2** [comment]
Thanks for the response - appreciated.
I am on version 0.12.14 and it was updated by removing the old version first
I am using the default livery
I am not using the CJ4 Cockpit Texture
I guess I will just have to keep trying as I really do enjoy flying the CJ4

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by normanh2** [comment]
I am so sorry -- I have now found I do have the Texture Mod installed in my Community Folder - how do I delete it - I can't see it - would really appreciate your help - once again apologies for my error

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by dga711** [comment]
Just delete the folder of the texture mod from your Community folder.
Otherwise you can also update it, there is a new version out that should be compatible.

**Comment by normanh2** [comment]
I found it and it fixed the white screen problem - thanks for your assistance

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
