### ISSUE TITLE
G3000

### ISSUE THREAD

**Issue by Exceljet7** [Working-Title-MSFS-Mods/fspackages#1545]
I recently installed the G3000 nice unit but I have several issues, The Activate vectors to final function is not there. also when flying an ILS Approach with everithing set as it should it wonders off the Localizer and does not properly capture the glideslope ( Real life Citation Latitude Pilot here,  same avionics as the Longitude )

**Comment by mattnischan** [comment]
The G3000 mod uses the stock sim autopilot, flight plan system, and navigation, and does not change those components in any way. So any issues you are seeing there are due to those items.

The upcoming G3000 refresh will use customized systems, and is due sometime this year.
