### ISSUE TITLE
Honeycomb autopilot CJ4

### ISSUE THREAD

**Issue by MaciejP92** [Working-Title-MSFS-Mods/fspackages#1547]
First and foremost I just want to say that your job on CJ4 is amazing and I really appreciate it as I had to experience the default one! 

However! :D I am using honeycomb throttle with AP switches and it's all binded properly but it doesn't react when I switch modes. For example I hit NAV mode and nothing happens but when I hit it in virtual cockpit in game it lights up the switch on hardware plus it lights up the wrong one. I press NAV mode in game -> HDG mode illuminate on hardware and vice versa HDG mode lights up NAV switch on hardware. ALT mode lights up VS button and VS mode does not affect hardware at all. IAS also does not illuminate in FLC mode even though it is binded as such as I understand. Knobs are working perfectly fine in all modes it is ALT/VS/HDG/CRS/IAS(it changes speeds while in FLC mode so I guess it is bined correctly and it's binded to the same mode as IAS mode button)

So there is some issue only with mode switches - none are put input to the game and feedback from the game to the hardware is reversed in case of HDG/NAV  ,  VS/ALT.    APR and IAS does not affect sim nor receiving feedback from the game.

I have checked binding and it works correctly in case of other A/C's

**Comment by dga711** [comment]
Please read the note in the release notes

> Autopilot modes cannot be triggered via key bindings or controllers and must currently be triggered in the cockpit with the mouse. External binding applications are adding support for LVars and HEvents. Used SimVars are documented in our [Guide on SimVars](https://www.workingtitle.aero/packages/cj4/guides/simvars)

It won't be an issue with the upcoming refresh though.

**Comment by MaciejP92** [comment]
That is great to hear! Thanks for reply!
