### ISSUE TITLE
waypoints do not load G1000nxi

### ISSUE THREAD

**Issue by TroyMon** [Working-Title-MSFS-Mods/fspackages#1550]
Just recently, not sure if its WU11 or the GNS 430/530 install, any aircraft using the garmin 1000 nxi will not load way points. Example: I choose the C172, select departure airport then the arrival airport. I would add several waypoints in between then select FLY. After all has loaded, the Garmin only shows a direct flight. No waypoints I selected were plugged in. Other aircrafts NOT using the G1000 function perfectly. 

I uninstalled the GNS 430/530. 
I uninstalled the G1000 nxi 
Still will not load waypoints I selected in my flight plan.

Any suggestions or tricks I can try?

**Comment by dga711** [comment]
#1310
