### ISSUE TITLE
GNS-Early-Access MSFS - Delete Approach Issue

### ISSUE THREAD

**Issue by fkolbe** [Working-Title-MSFS-Mods/fspackages#1551]
Issue: When deleting an approach in an active flight plan using the WTGNS530 the destination airport is replaced with the destination airport runway. The expected behaviour is when deleting the approach the flight plan would only include the departure and arrival airport. For example of issue, flight plan CZBA CYKF with arrival RNAV 26 y.  When deleting the approach from the flight plan the new displayed flight plan is CZBA RW26

How to create issue:
1. In MSFS, using WTGNS530 in stock Cessna 172 create a flight plan CZBA CYKF and include the approach RNAV 26 y;
2. Press Menu
3. Select Delete Approach
4. On the GNS530 flight plan page user will see the departure airport CZBA followed on the next line by the runway of the arrival airport RW26.

Using latest build in MSFS and latest build of WT GNS530 (Nov 18/22). Only item in Community folder is RealSimGear. Hardware includes RealSimGear GNS530. Windows 10 machine.  

Screenshot 1 - WT GNS530

![Microsoft Flight Simulator 2022-11-18 5_00_58 PM](https://user-images.githubusercontent.com/60490392/202810805-6cf175cb-6ec2-48f9-8ecb-3b31dcf74e97.png)

Screenshot 2 - GNS530 mod by PMS50
![Microsoft Flight Simulator 2022-11-18 5_05_40 PM](https://user-images.githubusercontent.com/60490392/202810806-37461c87-62c0-4168-a46f-3de5284f7acf.png)

**Comment by dga711** [comment]
#1310

**Comment by fkolbe** [comment]
Hello

I’m a bit confused as Working Title’s Discord rules clearly state to report bugs on GitHub (see below):


2) Bug reports [??] should be made here: https://github.com/Working-Title-MSFS-Mods/fspackages/issues | bugs reported on discussion will likely be lost in the discussion and not addressed.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mattnischan** [comment]
Apologies for the confusion.

That rule was specifically for our old open source mods that exist on this GitHub repository. For the new work (G1000 NXi, GNS 430W/530W), please use the Discord channels or dedicated MSFS forum threads for reports.
