### ISSUE TITLE
COM audible when not the active

### ISSUE THREAD

**Issue by Tetley22** [Working-Title-MSFS-Mods/fspackages#1552]
I _think_ this is a bug (not sure), but when I tune ATIS on com  2, and tower on com 1, and make com 1 the active (green light on com1 on panel), I still hear the ATIS from com 2. Only way to fix this is to turn the volume down for com 2. I may be wrong about this being a bug, but I don't think this is the intended behavior.

**Comment by mattnischan** [comment]
This is indeed intentional, and how it works on the real aircraft as well. 🙂 

Green is for the selected transmit channel; all channels always receive unless explicitly turned off.

**Comment by Tetley22** [comment]
Ok, thanks for the reply. Now to figure out how to turn off a channel...

**Comment by mattnischan** [comment]
You were doing it right. Just turning it all the way down to zero volume is how it is done (in the real aircraft there's a little click stop you would feel).
