### ISSUE TITLE
No screens for CJ4 navigraph

### ISSUE THREAD

**Issue by glitchyhitchy1** [Working-Title-MSFS-Mods/fspackages#1559]
decided to incorporate the navi charts into the cj4, put into the community folder and removed the old one and all i get are white screens before even turning the battery on :/ ANY HELP i cant find anyone else having this issue
![Microsoft Flight Simulator Screenshot 2023 05 31 - 19 39 20 24](https://github.com/Working-Title-MSFS-Mods/fspackages/assets/135164111/09ea81ab-df30-48ec-8bdd-3e59df8555ec)

**Comment by dga711** [comment]
The old CJ4 mod on this GitHub is not compatible with the sim anymore.
See the Readme of this Repository. https://github.com/Working-Title-MSFS-Mods/fspackages/blob/main/README.md

The source of our work that is included with the simulator can be found here https://github.com/microsoft/msfs-avionics-mirror
