### ISSUE TITLE
G1000: ETE format on MFD displaying only Minutes and Seconds

### ISSUE THREAD

**Issue by krosswynd** [Working-Title-MSFS-Mods/fspackages#156]
Currently ETE on top of MFD in magenta color as a format not displaying correctly if the flight is more than an hour. It is showing in minutes:seconds

This below statement is from the g1000 manual on page 241. https://static.garmincdn.com/pumac/190-00498-07_0A_Web.pdf	

"Estimated time enroute (ETE) - ETE is shown as hours:minutes until less than an hour, then it is shown
as minutes:seconds. "

I am not sure how easy it is to implement the change but thought to let you guys know.

Thank you for the awesome mod.

krosswynd

**Comment by kaosfere** [comment]
We'll add that to the list, it should be fairly doable.   Thanks!
