### ISSUE TITLE
installing working title Cessna Citation CJ$ for MSFS2020.

### ISSUE THREAD

**Issue by Myjaguar27** [Working-Title-MSFS-Mods/fspackages#1561]
I have found the latest version of this on Working Titles (v0.12.14) but don't know how to download it. (limited computer skills) If I click on the version I get options but don't know which to select. Any help would be appreciated.

**Comment by dga711** [comment]
https://www.badcasserole.com/whats-the-deal-with-the-working-title-cj4-mod-now/
