### ISSUE TITLE
G1000: Freezing entire game

### ISSUE THREAD

**Issue by h0useRus** [Working-Title-MSFS-Mods/fspackages#157]
Installing this mod completely freezing my sim for 10-15 sec on any G1000 screen power on (by battery on, or avionics switch).

Also, randomly MFD may completely stop redraw (usually in APR mode) for couple of minutes.

After deleting mod all back to operational. I’m using latest 0.3.0, and it never was with 0.2.0

**Comment by knighty** [comment]
What plane are you using and do you have any other community mods installed?

**Comment by h0useRus** [comment]
I tested on Bonanza G36 with and without this mod https://github.com/TheFrett/msfs_g36_project/releases/tag/0.5
I have installed G3000 mod https://github.com/StuTozer/G3000-Touchscreens-Restyled/ for https://github.com/guifarias31/msfs_tbm930_project/releases ,  but those mods should not effect.

Nothing else, I tested plane on and around YSSY airport.

**Comment by h0useRus** [comment]
Seems it was something else, when I cleaned the Community folder and left only your mod and G36, so far so good. 
Doing test flight now, will update if find something

**Comment by kutak11** [comment]
same happens to me.. freezing about 10 seconds during searching the waypoint with knobs. But it could be also Navigraph beta database I have installed. Unfortunately if I delete navigraph, the sim wont start.

**Comment by mattnischan** [comment]
Hi @kutak11,

We have noticed a large regression in the performance of the sim waypoint loader system. Sometimes, when the instrument code asks the sim for a fix, we have noted 10-15 second delays in receiving the data back from the sim. This appears to be an issue introduced in 1.9.3 in the game code. Unfortunately, we don't have any control over the waypoint loader system.

We'll continue to monitor this and see if the next game patch improves the loader performance.

**Comment by h0useRus** [comment]
I found the problem, it is Navigraph - AIRAC Cycle 2010 + MFS Beta Rev 13.0 
After I installed it to my Community folder the freezing problem back.

**Comment by kutak11** [comment]
Did you try it also without this G1000 mod?

**Comment by h0useRus** [comment]
> Did you try it also without this G1000 mod?

Yes, sim freezing even with default instruments and only Navigraph in community folder.
