### ISSUE TITLE
G1000: Vertical speed issue

### ISSUE THREAD

**Issue by kutak11** [Working-Title-MSFS-Mods/fspackages#160]
Hi,
After last mod rev. I am having crazy vertical speed when on AP and VS mode on DA62.
There is stable vertical speed as set until I put some direct for shortcut in FPL. Nose pitch is going crazy up and down.
(AP, NAV(GPS), VS activated).
After removing this mod it works normaly.

Thanks

**Comment by knighty** [comment]
We don't have any influence over AP, and porpoising (the action you're referring to) has been an acknowledge issue before and exacerbated in some cases it seems by the patch. I'm going to close this as I'm confident this is outside of our control.
