### ISSUE TITLE
CJ4: Enhanced checklist

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#161]
Now that you've made so much more things working in the cockpit and FMS it would be nice if you could enhance the checklist like in the FlyByWire A32NX mod. I think this is the one: https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.skyservices-flightacademy.com/wp-content/uploads/2018/08/normal_and_emergency_check_list.pdf&ved=2ahUKEwjGxNjIpZPsAhUEiYsKHZnhClwQFjADegQIBBAB&usg=AOvVaw2e8g8xdwyPdHY_ChNIQlxc

**Comment by J-Hoskin** [comment]
@AndersHogqvist Hey, thanks for the suggestion. We are currently working on this item including an inbuilt MFD checklist. PR #122 is currently extending the UI checklist.

**Comment by AndersHogqvist** [comment]
Already taken care of
