### ISSUE TITLE
G1000 v0.3.0 breaks synthetic vision in g3000 in TB930

### ISSUE THREAD

**Issue by Kaerbr** [Working-Title-MSFS-Mods/fspackages#168]
MSFS 1.9.3.0
working title mod G1000 v0.3.0

If I have the G1000 mod installed there is no synthetic vision on the G3000 in the TBM930.
If I remove the G1000 mod the synthetic visio returns.

Unfortunately there is no switch for the synthetic vision in the tbm930 garmin suite. :(

Theese are my other mods:
![grafik](https://user-images.githubusercontent.com/70379879/94928551-270a0000-04c4-11eb-8c4c-c72d0f7e348d.png)

**Comment by kutak11** [comment]
I think it is known issue at the moment. I have the same.

**Comment by mattnischan** [comment]
Hi all,

We are aware of this issue and it is being handled in #159 which should appear in the next release.

**Comment by lars-reimann** [comment]
Nice. Just for the sake of completeness: The Beechcraft King Air 350i is also affected by this issue but I take it the pull request does not solely target the TBM anyway.

**Comment by B1ackJ** [comment]
Cessna citation longitude(G5000) is also affected by this issue.

**Comment by kaosfere** [comment]
If you want to try the latest pre-release it should take care of this:

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/g1000-v0.3.1-pre2/workingtitle-g1000-v0.3.1-pre2.zip

**Comment by lars-reimann** [comment]
I tested version v0.3.1-pre2 and synthetic vision is indeed [restored on the TBM, the King Air and the Longitude](https://imgur.com/a/PMyV1DY).

**Comment by kaosfere** [comment]
Great, thanks for the confirmation!
