### ISSUE TITLE
CJ4: Struggling to maintain speed during climb/cruise

### ISSUE THREAD

**Issue by rasmulisone** [Working-Title-MSFS-Mods/fspackages#170]
During climb at 2000 fpm I had to keep the throttles at max to maintain a speed of 200-210 kts IAS and during cruise at FL320 I have to keep them at 89 to maintain a cruise speed of 440 kts TAS (~275 IAS). Gear and flaps up of course. This wasn't happening before I downloaded this mod... I could keep the throttles at ~65-68 and still maintain 440 kts TAS. Nice work though, the fuel burn is still lower with this mod :D

**Comment by mattnischan** [comment]
Climb performance in the real aircraft is going to be down close to 1500fpm by 30K feet, so you may need to decrease your climb speed. 89-91% N1 is about the right power setting for maximum speed cruise. We've made those adjustments to reflect real world performance, so your numbers sound about right.

We have some additional custom fuel flow modeling coming in the next release which will align fuel flow to much more closely match the real aircraft as well. Range at cruise will be significantly improved.

Happy flying!

**Comment by rasmulisone** [comment]
Oh, okay, I didn't even consider it could be realistic. Thank you for the quick reply!

**Comment by mattnischan** [comment]
Of course!
