### ISSUE TITLE
CJ4: Taxi/Landing light illuminating inside of the cockpit (foot area)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#171]
I recognized some strange lighting in the area where the control collumn is, when turning on taxi, or landing light, or both.

This with no taxi/landing light on
![No light](https://user-images.githubusercontent.com/71773282/94960254-deb60680-04f2-11eb-8e21-bd8552b5a749.jpg)

Now only taxi light
![Taxi light on](https://user-images.githubusercontent.com/71773282/94960301-f1c8d680-04f2-11eb-8fc0-60b2a21f4ef9.jpg)

And here landing light
![Landing light on](https://user-images.githubusercontent.com/71773282/94960437-2e94cd80-04f3-11eb-8176-694ab9a1466e.jpg)

**Comment by cwburnett** [comment]
@Uwajimaya is this something you have or could possible address? Or maybe it's not a problem anymore with your latest update?

**Comment by cwburnett** [comment]
Hey no worries at all @Uwajimaya I appreciate your work! I'll go ahead and edit the file now in our 0.5.0 prerelease ;-) Thanks!

**Comment by cwburnett** [comment]
Fixed
