### ISSUE TITLE
CJ4: Perfomance issue

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#173]
On my last flight I did some documentation during flight, about some notes about the performance:

Fuel Flow (during climb at max. thrust)

**Flight Level    //                 Fuel Flow (PPH)**           
FL330              //             1230-1250
FL340              //              1230-1250
FL350              //              1230-1250
FL370              //              1230-1250

This does not seems to be correct in my eyes, but what do you think? 
Normally with gaining hight and due to lower temps. the fuel flow should decrease and not stay the same.

Cruise notes 

**FL360**

84,6% N1   =  _1004 PPH_ 
TAS=422 / SAT -47 / (ISA+8) <- ISA deviation is out of the system

**FL380**

84,6 N1     =   _1018 PPH_
TAS=422  / SAT -52  / (ISA +7) <- ISA deviation is out of the system

A difference in 2.000ft may result in a consumtion reduction about 200-300 PPH, but it uses more or less the same.

**Comment by mattnischan** [comment]
Hi @Jack737800,

Previously, with ESP based flight sims (FSX, P3D, etc), fuel flow was `tsfc * thrust`. However, this relationship no longer applies: MSFS specifies a min fuel flow and max fuel flow by throttle position in the engine configuration now. Therefore, fuel flow is only tied to throttle position and not to thrust at all. This ends up with extremely incorrect fuel consumption levels, especially as thrust lowers with altitude.

We are implementing some custom fuel flow modeling that will be overriding the default fuel flow and replacing it with a thrust and mach derived curve for much, much more accurate burn numbers. This work is being tracked in #164 and should be available next release.

**Comment by Jack737800** [comment]
Why are they doing this ? Sorry, retoric question...Sometimes I´m wondering a bit how the "real pilots" in the MSFS Team advised them, how to create such "basic" errors, nevertheless I´m also happy to read that you guys are working on this one too! 
Outstanding job so far! I´m honestly hoping that you don´t have to release a new version, after one of the major updates of the sim, which is only an additional workload as well
