### ISSUE TITLE
G36 manifold pressure and fuel flow just show "NaN" instead of their respective values

### ISSUE THREAD

**Issue by promethues5500** [Working-Title-MSFS-Mods/fspackages#174]
Just trying out these mods, looking great so far other than this issue. Difficult to set my power with no manifold pressure, and hard to fuel plan without knowing a more precise fuel flow.

**Comment by kaosfere** [comment]
This should be fixed in the latest pre-release:  https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/g1000-v0.3.1-pre2/workingtitle-g1000-v0.3.1-pre2.zip

Try that and see if it helps.   You can install it directly on top of -pre1.

**Comment by promethues5500** [comment]
Solved! Working and looking great. Thank you so much!
