### ISSUE TITLE
CJ4 0.3.1 After about 30 minutes of flight, entire plane went weird

### ISSUE THREAD

**Issue by hapes** [Working-Title-MSFS-Mods/fspackages#175]
Flight plan:
SUDDZ1 SUDDZ DATME SNDIA3 (from SimBrief), using the most recent AIRAC from Navigraph.

It looked like it was programmed correctly in the FMS.
After approximately 30 minutes of flight time, the Airspeed indicator in the PFD indicated '-- KT' as in 0 air speed.  Ground speed was 343 or so.  At the same time, the plane started doing S-Turns around the nav line in the secondary display.  I MAY have clicked something in the AP panel to make it do that, but I double, triple, quadruple checked the AP panel, and it was still doing it.  Also, the plane seemed to be dry-humping the air.  The pitch was bouncing up and down.  The throttle had no effect, full or idle, no effect on speed or altitude.  The plane was dropping at a regular about 150 fpm.  The autopilot was doing something because I would adjust the trim to get back up to my assigned altitude of 14,000' and it would fight back, and we'd end up descending at the same rate.

Again, I'm not sure if I accidentally clicked something in the cockpit that made it do that, I'm willing to accept it was my fault.  It also may be a simulator issue, as opposed to an issue with the mod.  But I thought I should report it, if it's something you folks need to address.

**Comment by Jack737800** [comment]
Well, if your IAS is showing "--kt", so means 00kt, it´s for sure the sensing units are blocked. So in that case swtich on your Pitot-heat (both L+R) and you should get reliable data within a short period of time.  -> Pitot heats should be on the checklist set to ON, before taking off ;)
Blocked pitot static system may also result in this unstable A/P behaviour !?

**Comment by hapes** [comment]
Ah.  Is there a checklist that isn't the in-sim version which is "turn the engines on, fly"?

**Comment by dga711** [comment]
@hapes pull request #122 will introduce a proper checklist.
And @J-Hoskin is working on bringing it to the MFD too

**Comment by hapes** [comment]
I'm going to close this as user error, and if it happens again, I'll reopen.
