### ISSUE TITLE
G1000: Heading sync not working in 0.3.1pre1

### ISSUE THREAD

**Issue by yusufsan38** [Working-Title-MSFS-Mods/fspackages#177]
Heading bug does not synchronize to the present heading when HDG knob is pressed was using C172 G1000.

**Comment by kaosfere** [comment]
Thanks for the report.   Was this also broken for you in 0.3.0, or is it new in -pre1?

**Comment by yusufsan38** [comment]
> Thanks for the report. Was this also broken for you in 0.3.0, or is it new in -pre1?

This was only for prep 0.3.0 does not have the problem

**Comment by DanP77** [comment]
I confirm (I'm using DA62) pressing HDG sync, it does not sync on the HDG but on the track
