### ISSUE TITLE
CJ4: blue lights on all four anti-ice buttons, always on

### ISSUE THREAD

**Issue by Nedo93** [Working-Title-MSFS-Mods/fspackages#178]
First of all I would like to thank you for your incredible work on this mod.
This issue is really small and I don't know if it's a problem of mine or not, actually not even a problem, just wanted to let you know.
All 4 anti-ice buttons (engine 1, engine 2, engine and wing 1, engine and wing 2) have the blue light always on, even when they are not active.
I thank you in advance and wish you a nice weekend.

**Comment by K20017** [comment]
Do you have the A32X mod installed?  If so, one of their files is incorrectly configured such that it is overwriting a shared file that the CJ4 uses.  This is something that can only be fixed by their team or by removing their mod from the community folder.

**Comment by Nedo93** [comment]
Yes, I do have that mod.
Got it, thank you for your quick answer, I can live with that for now, while I cannot live without these two mods :P
