### ISSUE TITLE
Can't Install: File name too long for the destination folder

### ISSUE THREAD

**Issue by Piotre64** [Working-Title-MSFS-Mods/fspackages#180]
I'm unable to install the "workingtitle-g1000" in the community folder as I get the message "File name too long for the destination folder".

Unfortunately I bought the MS store version and installed on a different drive than the default, so my community folder location looks like this: F:\WpSystem\S-1-5-21-2372559687-1840544934-2577146336-1000\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community.

I can copy most of the files, the only two offending files that don't get copied to my community folder are these two:
workingtitle-g1000\html_ui\Pages\VCockpit\Instruments\NavSystems\Shared\Templates\AttitudeIndicator\AttitudeIndicator.js
workingtitle-g1000\html_ui\Pages\VCockpit\Instruments\NavSystems\Shared\Templates\XMLEngineDisplay\XMLEngineDisplay.js

Is there any way to solve this issue?

**Comment by J-Hoskin** [comment]
Yeh this is an odd issue. Maybe this #176 can provide some guidance.

**Comment by kaosfere** [comment]
Yep, this is an unfortunate issue with the lengths of the paths that MSFT use, and it seems to be particularly troublesome for folks who don't install onto their system drive for some reason.

I have this same problem myself, with a number of mods with lengthy paths.   #154 describes how I set up my system to avoid it and it works pretty well for me.  That would be my suggestion for the way to go.   #176 could also be useful as @J-Hoskin noted.
