### ISSUE TITLE
G1000. Logic of avionics switch

### ISSUE THREAD

**Issue by triplesevenbob** [Working-Title-MSFS-Mods/fspackages#181]
In the default Caravan mod with the G1000 mod the avionics switch for 1 and 2, 1 turns on PFD with no engine instruments. Avionics switch 2 will only turn on center screen with engine instruments after avionics switch 1 turned on.

**Comment by kaosfere** [comment]
I'll check this one out.   To clarify, you say it's "with the default Caravan mod".   Is that "mod" extra in there, or are you using a modded Caravan?

**Comment by triplesevenbob** [comment]
> 
> 
> I'll check this one out. To clarify, you say it's "with the default Caravan mod". Is that "mod" extra in there, or are you using a modded Caravan?

Hello I am combining the G1000 mod and the C208 mod here https://github.com/Exp232/C208-MSFS2020-Fix/tree/Dev-Version

**Comment by kaosfere** [comment]
Got it, thanks for the update.   I'll grab that one and do some testing as soon as I can to see if I can figure out what's going on.
