### ISSUE TITLE
CJ4 v0.3.1: Use Oxygen mask at above FL440

### ISSUE THREAD

**Issue by edmond1992** [Working-Title-MSFS-Mods/fspackages#183]
Use Oxygen mask cation at above FL440
All button except the flight control related are untouched (cabin pressure dump)
![Oxygen mask](https://user-images.githubusercontent.com/47852799/95021788-c5a18700-06a5-11eb-9ac9-2cdbbb0a0e87.png)

**Comment by mattnischan** [comment]
I just saw this during my fuel flow testing as well. Not sure what's causing it yet since we disabled the pressure system (due to it being unusably broken at the moment).

This one will probably be a little bit lower on the list due to needing to rebuild the cabin pressure system.

**Comment by J-Hoskin** [comment]
Though, is this a problem? Flying at that flight level, oxygen masks are used in case of a sudden decompression, where you only have seconds before passing out. Especially if flying single pilot. May also be regulation.

**Comment by edmond1992** [comment]
> 
> 
> Though, is this a problem? Flying at that flight level, oxygen masks are used in case of a sudden decompression, where you only have seconds before passing out. Especially if flying single pilot. May also be regulation.

I'm not sure. Hope some real pilot or know the plane can provide the information

**Comment by K20017** [comment]
That message does not exist in the airplane, we will remove it at some point.  The only thing regarding cabin pressure is a red "CABIN ALTITUDE" CAS message that goes off if the cabin altitude is above 9800ft.  Also, 1 pilot just wear a mask above FL410 but the airplane doesn't care if you do or don't.
