### ISSUE TITLE
G1000 Engine Pages don't work with DA40-NGX

### ISSUE THREAD

**Issue by eaglechlapf** [Working-Title-MSFS-Mods/fspackages#185]
With 0.3.1 the engine pages on the DA40 on the MFD don't work with the DA40-NGX mod (v0.5.6, without FADEC) installed. When reverting to 0.3.0 there is no problem.

**Comment by knighty** [comment]
Hi,

As per https://github.com/Working-Title-MSFS-Mods/fspackages/issues/179 this should be fixed.

Download: https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/g1000-v0.3.1-pre2/workingtitle-g1000-v0.3.1-pre2.zip
