### ISSUE TITLE
G1000: Instrument lighting

### ISSUE THREAD

**Issue by strongbow1** [Working-Title-MSFS-Mods/fspackages#188]
First of. Thank you for the great work. I really enjoy it. I have noticed on the G36 Bonnie actually the only plane I flew with the mod that my instruments are very dim and I can not adjust it with the lighting switches. For now I removed the mod as its sometimes to dark in day light.

**Comment by tigert** [comment]
Have you tried the dimmers located under the co-pilot's yoke? Because one of those should adjust the G1000 screen brightness.

**Comment by strongbow1** [comment]
Yes I have. When I remove the mod it works again on the Bonanza. Its nothing to serious just want to mention I have that issue on the Bonanza

**Comment by kaosfere** [comment]
Thanks for the report, sorry I missed this until now.   Are you able to control the brightness via the PFD setup menu (by pressing MENU on the PFD without any other popups open).

If you are..  can you tell em if you have any other avionics mod installed?   And are you using the stock Bonanza or TheFrett's mod?

**Comment by strongbow1** [comment]
Hello. No problem and thank you for the reply. I have only tried to brighten up the displays via the dim/bright rotary knob below the co pilot yoke. Without any success. If I remove the mod it works. I have to load a different airplane then load back into the bonanza then it seems to work. Bit annoying but that seems to work for now.

**Comment by kaosfere** [comment]
OK, I'll check it out.    Is this using the stock Bonanza?

**Comment by strongbow1** [comment]
I have the G36 improvement mod also installed. Have not tried to remove that mod and only run this one. Will try it once I get a chance

**Comment by kaosfere** [comment]
I have been unable to replicate this at all and we've released a couple versions since.   Are you still having an issue with this?

**Comment by strongbow1** [comment]
I just updated to the newest version. I do not have the problem anymore

With Best Regards
Mit Freundlichen Grüsse
Sandro Strimer
________________________________
