### ISSUE TITLE
CJ4: Transition altitude cannot be changed

### ISSUE THREAD

**Issue by yusufsan38** [Working-Title-MSFS-Mods/fspackages#191]
Transition altitude can not be set it's stuck @ 18000ft

**Comment by mattnischan** [comment]
@yusufsan38 - At this time, the VNAV perf pages are just a skeleton and do not affect the behavior of the aircraft. We expect to flesh out those functions later on down the road after we have overhauled flight plan management and the autopilot.

We appreciate the report!

**Comment by cwburnett** [comment]
Will be included in VNAV
