### ISSUE TITLE
TBM900 LOST of SYntetic vision

### ISSUE THREAD

**Issue by cangianos** [Working-Title-MSFS-Mods/fspackages#192]
With this mod the TBM900 lost the syntetic vision

**Comment by mattnischan** [comment]
Hi @cangianos,

I'm not sure which version you're running, and I assume you're referring to the G1000 mod. The synthetic vision conflicts with the couple of stock aircraft have been fixed as part of #159 and are currently included in the G1000 0.3.1 pre-release. Please feel free to try out the pre-release on the Releases page, or you can wait until the official release.

We appreciate the report!
