### ISSUE TITLE
Blank Screens

### ISSUE THREAD

**Issue by 757John** [Working-Title-MSFS-Mods/fspackages#199]
I have dropped the folder into the community folder, but when I load the CJ4, all the PFD/ND/FMC are blank. The mods seems to be loaded as the seatbelt sign is clickable and the sound is played.
My FS2020 install is located on this path: D:\MSFS2020
Thank you.
John

**Comment by 757John** [comment]
isnt 0.3.1 for the G1000? I am talking about the mod for the CJ4 (https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.2.0)
Did I post in the wrong section?

**Comment by mattnischan** [comment]
@757John - The CJ4 is also at 0.3.1 at the moment. The earlier versions of the CJ4 are not compatible with MSFS 1.9.3.

You can grab CJ4 0.3.1 at https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.3.1

**Comment by 757John** [comment]
oh I feel so stupid, I was working from an old link from an AVSIM thread, had I scrolled to the bottom of the page I would have seen the latest build. I am all set,thank you both for getting back to me, all set now. THANK YOU for this amazing mod!
John

**Comment by mattnischan** [comment]
No worries @757John! Happy flying!
