### ISSUE TITLE
G1000: DCT mode issue

### ISSUE THREAD

**Issue by kutak11** [Working-Title-MSFS-Mods/fspackages#201]
Hi,
I am not sure if I am doing something wrong, but if I am flying DCT shortcut somewhere and during that set arrival route or approach load or just put another waypoint beyond the point I am currently on direct, it suddenly cancel direct nav and activate LEG from original FPL route. So I have to set HDG for some time, again find the point with knobs to fly direct (would be perfect if this point is automatically found on DCT page after just selecting in FPL and pressing DCT). This bug is really frustrating and I would much much appreciate if you could fix it.
Many thanks
Tomas K.

**Comment by knighty** [comment]
This may well be irrelevant once we've finished the dual job of rebuilding the flight plan system and UI, but thanks for the heads up and suggestion

**Comment by kaosfere** [comment]
I wouldn't say irrelevant, as it's definitely a bug and a point of frustration.    We are definitely trying to do some heavy work on improving the flight plans and any comprehensive fix may have to wait for then, but we can put this in the queue for v.Next to see if it's something we can address in the near-mid term.   Thanks for the report, @kutak11 .
