### ISSUE TITLE
CJ4: Bug in FPLN when DEP is only single fix

### ISSUE THREAD

**Issue by dga711** [Working-Title-MSFS-Mods/fspackages#203]
When i select departure ORD5 of KORD, which in msfs does seem to only have a single fix, it doesn't show up in FPLN as first TO waypoint.

![image](https://user-images.githubusercontent.com/2995606/95320080-3c52a600-0899-11eb-801c-4e6e0d9b51b9.png)

![image](https://user-images.githubusercontent.com/2995606/95320096-41aff080-0899-11eb-8195-cc3597a3cb0a.png)

When a runway is selected it shows a waypoint, which is a different one while LEGS still shows ACITO
![image](https://user-images.githubusercontent.com/2995606/95320592-f9dd9900-0899-11eb-9a90-d5939fd0060e.png)

EDIT: **Following other experiments, i think the departures in KORD are totally bugged in general data-wise**

**Comment by cwburnett** [comment]
@dga711 this is really a function of the 'default' departure from airports. Most airports have a 'catch all' departure procedure that really means vectors. There is no route.  At ORD they got rid of all their departure procedures a couple years ago, there's only the ORD5, and it just has a list of acceptable transition points, but no route and it's entirely a vectored departure. So it should just show ORD5           VECT

**Comment by dga711** [comment]
Ok. I think we can closes this then as we show as much as the data is giving us.

 Thanks for the explanation

**Comment by cwburnett** [comment]
@dga711 maybe we could show VECT when there is no waypoint on the departure?
