### ISSUE TITLE
G1000: ETE shows time for entire FPL, not current leg

### ISSUE THREAD

**Issue by SCdF** [Working-Title-MSFS-Mods/fspackages#204]
Apologies if this is actually intentional! I am not a pilot. Reading the Garmin G1000 manual, I think in that depending on the mode / configuration the ETE can potentially show either the entire flight plan, or the leg (as in vanilla MSFS). However, in this mod I don't think it's configurable?

Raising as I'm unclear how this should work, anyway. For me (again: not a pilot!) the leg ETE is more useful, because it lets me calculate TOD more accurately / easily than relying on (decent * 3 / 1000)nm etc.

Info: this is using your mod via https://github.com/thefrett/msfs_g36_project/

**Comment by knighty** [comment]
I've been working on the flight plan page and it seems like the data that the game gives out doesn't update the ETE at all and neither the current distance remaining (which would make it easy to calculate ourselves). Not sure how best to fix this but thanks for the heads up!

**Comment by kaosfere** [comment]
@jonasbeaver, if you're reading, do you have any input on this one?

**Comment by magraina** [comment]
@knighty maybe this helps
It can be configured to Fuel Remaining (FUEL REM), Estimated Time Enroute (ETE), Estimated Time of Arrival (ETA), and
Bearing to the waypoint (BRG)

[http://static.garmin.com/pumac/190-02177-00_A.pdf](http://static.garmin.com/pumac/190-02177-00_A.pdf)
Page 121 (135 in PDF) for MFD Navigation Data Bar at Top
Or Page 204 (218 in PDF) for Flight Plan Views

**Comment by kaosfere** [comment]
Adding configurable navdata options would be very desirable.   I'll log this as a future feature.
