### ISSUE TITLE
CJ4 STAR's and Approaches

### ISSUE THREAD

**Issue by cisco92** [Working-Title-MSFS-Mods/fspackages#205]
Hi,

So I'm having the issue, both with default and with Working Title mod, that when in the FMS, when I go to the Arrivals page, if I choose a STAR, all Approaches disapear, and vice versa as well.. Is this a known issue?? Tried multiple airports (Only in Sweden) but same thing.. 

Best Regards
Cisco

**Comment by K20017** [comment]
Can you tell us which airport and arrivals you were trying to load?  For some reason, the baby data in Europe is very funky in certain places and it wouldn't surprise me if the ones you were trying are bugged out.  I haven't seen this happen on the US airports I've tried. Unfortunately, if it's a database issue, that might be something Asobo has to sort out.

**Comment by cisco92** [comment]
You can test ESGG, as soon as you choose any Arrival, all Approaches disappear from the list, and vice versa.

**Comment by tscharlii** [comment]
This will be fixed in v0.4.0. I encountered the same issue with german airports and proposed a bugfix, which just got included into the upcoming release.
ESGG Star KELI2K allows approaches to runway 03: https://imgur.com/a/jhJqsgC

**Comment by cisco92** [comment]
Cool! And the fix will also work for Swedish airports? Okey, so one out of too many STARs gave the approaches, which is still very incorrect :)

**Comment by cisco92** [comment]
FYI. I also raised a ticket on zendesk for Asobo to check on that. Don't know if they will anytime in the near future though..

**Comment by dga711** [comment]
Fixed via #202 and will be included with the next release 0.4.0
Thank you @tscharlii

**Comment by cisco92** [comment]
Downloaded the source from #202 and can confirm it's working! Thanks! :)
