### ISSUE TITLE
CJ4: MFD not centered on aircraft

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#219]
The MFD does not center on the aircraft if going from upper menu OFF to FMS TEXT, CHECKLIST or PASSENGER BRIEF. Going to the SYSTEM page does correctly center the MFD and subsequently going from the SYSTEM page to one of the other three keeps the MFD centered correctly. See the video below:

https://youtu.be/6NwEZrIMFj8

On an unrelated note: any idea what happened to the engines near the end of my video? They seemed to overspeed twice while no input was given?

**Comment by dga711** [comment]
Thank you for your feedback.
That certainly doesn't look right and we will have a look at it.

**Comment by J-Hoskin** [comment]
Nice pickup @TheFrett, this will be fixed in our next release.


Thanks 💯 🥇

**Comment by J-Hoskin** [comment]
#231
