### ISSUE TITLE
CJ4: FMS shows fuel flow for switched off engine 

### ISSUE THREAD

**Issue by tscharlii** [Working-Title-MSFS-Mods/fspackages#224]
FMS shows left engine fuel flow, although the engine is still off. Just started the right engine.
![fms_fuel_flow_left_engine](https://user-images.githubusercontent.com/6066377/95659106-1a6a5500-0b1f-11eb-99c1-9235b65ae5fa.png)

The fuel is not actually burned though: left tank is still full.
![fuel_unused_left_engine](https://user-images.githubusercontent.com/6066377/95659109-1f2f0900-0b1f-11eb-8a5f-871a232881a9.png)

**Comment by K20017** [comment]
Weird, will take a look.
