### ISSUE TITLE
CJ4: Delete airway route from flightplan

### ISSUE THREAD

**Issue by tscharlii** [Working-Title-MSFS-Mods/fspackages#225]
After adding a fix via an airway to the flightplan: if i want to delete that, i have to do it leg by leg. Is that the correct behaviour?
https://youtu.be/qgQHBs7nKMk

Not a big deal though, maybe something for the flight plan manager complete rewrite.

**Comment by K20017** [comment]
Not the desired state right now but we just didn't have time to sort it all out with this update.

**Comment by tscharlii** [comment]
Yes, figured that. Right call to release 0.4.0! So much cool new stuff!
