### ISSUE TITLE
CJ4: FPLN does not add the complete airway

### ISSUE THREAD

**Issue by tscharlii** [Working-Title-MSFS-Mods/fspackages#226]
Starting from Fix NIK in Belgium: added Fix LAM in Great Britain via airway L610
Did not get the whole route but just a few fixes up until BULAM, which is on the airway L610 to LAM

Maybe because LAM is a sub string of BULAM?

**Comment by K20017** [comment]
I would not be surprised if this is a nav database issue because one of our other members working on the G1000 was having a hard time with approach fixes that were related to LAM.  The database doesn't list them correctly.  For some reason, the in-game database for Europe seems funky and erroneous at times.

**Comment by tscharlii** [comment]
So the L610 route from NIK to LAM is:
NIK DENUT LUMEN BULAM DIBLI RAPIX SUNUP TEBRA KOPUL UNSAD NILON GILDA LAM

I think in this case the problem is the js code, not the airway database.
I suspect this line of code:
https://github.com/Working-Title-MSFS-Mods/fspackages/blob/59bce7b42d4ae303e21579676c7302df04f66b8a/src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js#L448

_lastWaypointIdent_ is the exit fix, LAM in my case
_airway.icaos_ are all the fixes on the airway

It checks, whether the the text "LAM" occurs in any of the airway fix names, and returns the first one found.
So if BULAM occurs before LAM in the airway icao list, it returns the index of BULAM.

**Comment by dga711** [comment]
ooof. good find! :D 
Actually i suspected you hit another bug, where when you already have an approach selected the temporary flight plan will ommit the last waypoint of an airway. But then show it after EXEC (asobo!)

But this also makes sense.
Much of the code you'll find is modified Asobo code, as i mostly tend to stay as close as possible to their implementation (even though they suck at time ^^) I didn't catch das checking for indexOf could of course cause problems.

Will get fixed! Again, very good find! ;)
