### ISSUE TITLE
CJ4 0.4.0: antice.

### ISSUE THREAD

**Issue by DanP77** [Working-Title-MSFS-Mods/fspackages#230]
With the mod version 0.4.0 some antice switch light are ever switched on. (Only the light)

**Comment by dga711** [comment]
It' caused by the A320NX mod.
Sadly they changed some XMLs which will leak into other planes. And in this case break Anti-Ice.

Hope they will come to their senses and fix that.

**Comment by dga711** [comment]
https://github.com/flybywiresim/a32nx/issues/882
