### ISSUE TITLE
CJ4: Progress page showing wrong distance to destination

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#232]
This issue is closely related to #220 and the discussion we had there. 

The indicated distance to the final waypoint on the progress page is wrong. The flight is as follows:

EKYT/26R VEPIP ADAXA LASMA EVLA/24 (ILS24 trans LAROKSO app)

Before reaching the first enroute waypoint (FMS TEXT is correct here)
![Screenshot (313)](https://user-images.githubusercontent.com/11409383/95675013-63201d80-0bb4-11eb-8f06-1e46a4fe16f0.png)

When I got close to VEPIP, the indication was almost correct
![Screenshot (314)](https://user-images.githubusercontent.com/11409383/95675020-73d09380-0bb4-11eb-96be-fe65426d3bae.png)

However just after passing VEPIP, the PROGRESS page displayed a completely wrong distance once again:
![Screenshot (315)](https://user-images.githubusercontent.com/11409383/95675053-a67a8c00-0bb4-11eb-9faa-2e74b07dde73.png)

**Comment by cwburnett** [comment]
So, I did a little checking and I think there's a math problem on PROG, but actually the FMS TEXT appears wrong as well. The approach you have selected should be adding about 42NM to the route, making the flight plan distance to the destination from LASMA to the runway 70NM. But, indeed, the PROG page uses the flightplanmanager cumulative distance in flight plan, while the FMS TEXT is manually calculating distances. I'll do some more double checking, but the output will definitely depend on whether an approach is loaded.

@K20017 can you recall what destination distance calculation is correct? I assume it reports the actual flight planned distance, ignoring discontinuities and vectors, to the landing runway?

**Comment by K20017** [comment]
I'm not 100% but based on what I fly now, it should only report distances between waypoints so it won't care about a vector or discontinuity.  If the arrival has you flying from ROAMES intersection then vectors and you have the whole approach loaded in from the initial approach fix of GOATY, it will calculate the straight line distance from ROAMES to GOATY and then the rest of the approach.

**Comment by cwburnett** [comment]
Okay, there was an error in the PROG page math, which has been resolved in the 0.4.1 pre-release branch.

**Comment by J-Hoskin** [comment]
@cwburnett Yeh I didn't properly account for approach waypoints. But I think once included, it will be more accurate than the PROG page calculation.

We can standardise this in the next update.
