### ISSUE TITLE
VFR Squawk Code

### ISSUE THREAD

**Issue by BradleyDeLar** [Working-Title-MSFS-Mods/fspackages#233]
The default VFR squawk code in FS2020 is hardcoded to `1200` (located in `CommonPFD_MFD.js`) which is only applicable in North America. According to Garmin:

> The pre-programmed VFR code is set at the factory to 1200.

And as far as I'm aware no functionality already exists to change this so it would be nice to have some sort of config option to set the VFR code to something else like `7000` which is the VFR squawk in Europe.

**Comment by knighty** [comment]
Thanks for the issue. Had thought about this before but forgot about it, will probably add it to the settings page, even if it's not there in the real thing.

**Comment by BradleyDeLar** [comment]
Good work! Thanks!
