### ISSUE TITLE
CJ4 Weight seem to be incorrectly calculated

### ISSUE THREAD

**Issue by cisco92** [Working-Title-MSFS-Mods/fspackages#241]
Hi, 

It seems like weight is incorrectly calculated in the CJ4 FMS.. 
I compare it to the calculation inside FS2020 and also in the flight planner I use (ForeFlight)..
It should be as it states in the payload manager which you can see in the attached picture but for some reason it gets waay to high everytime even though I add the correct cargo lbs etc in the FMS.

![weight](https://user-images.githubusercontent.com/22174011/95788831-94940880-0cdc-11eb-888c-90cbc58d4947.png)

**Comment by cwburnett** [comment]
@cisco92 I just did a quick test and came up right. Right now, the PAX weight is set at 170 in the FMC, though we'll be adding the ability to adjust that in Defaults later.

If you run into more trouble, can you share what your PERF INIT page looks like?

![image](https://user-images.githubusercontent.com/70416619/95792751-4b729300-0ca1-11eb-913d-698b931779e2.png)

**Comment by cisco92** [comment]
Alright. Well I had pax set to 0.. and Cargo set to the same as the payload manager, but still it was giving me a way to high weight in the FMS. I can take a print screen tomorrow and show.

**Comment by K20017** [comment]
This has been fixed in the upcoming patch.
