### ISSUE TITLE
CJ4: Constant warning with PITOT / STATIC Heat on

### ISSUE THREAD

**Issue by cisco92** [Working-Title-MSFS-Mods/fspackages#242]
Hi,

This issue I didn't have before the 0.4 update but everytime I turn on the PITOT / STATIC Heat I get the yellow PT Heat warning L/R..

Best Regards
Cisco

**Comment by cisco92** [comment]
@dga711 this issue still exist for me in 0.4.1..
![Screenshot 2020-10-14 174112](https://user-images.githubusercontent.com/22174011/96012521-7a753a00-0e44-11eb-9b72-52dba0dfabc1.png)

**Comment by mattnischan** [comment]
@cisco92 Are you totally sure you have 0.4.1 properly installed? We completely removed the warning in 0.4.1, and instead you should only get a warning if pitot heat is off and throttle is above 70%.

**Comment by cisco92** [comment]
Yes , I completely removed the old one and replaced it with the new release.. But it's still there.. New things like announcement and stuff are working so it is 0.4.1

**Comment by mattnischan** [comment]
Any other mods installed?

**Comment by cisco92** [comment]
@mattnischan only scenery

**Comment by cisco92** [comment]
This is still the case for me even though I just updated to 0.5.. Always PITOT HT warning when I turn it on.. Any thoughts? @mattnischan @dga711

**Comment by dga711** [comment]
@cisco92 It doesn't exist in the XMLs anymore. So right now we can't really think of a way how this would show up for you.

**Comment by J-Hoskin** [comment]
I have experienced this too. It seems it has not been fixed.

**Comment by cwburnett** [comment]
@J-Hoskin for you when you get to CAS messages.

**Comment by dga711** [comment]
No further information or progress.
