### ISSUE TITLE
CJ4: Close waypoint cut/skipped

### ISSUE THREAD

**Issue by slip664** [Working-Title-MSFS-Mods/fspackages#247]
Departing KCRQ. Input flight plan using DEP/ARR KCRQ PADRZ2 runway 24, (suppose to be .CHKNN but because transitions are still WIP it defaulted to that anyway)..SEBBY..YELAH..MISEN.KEPEC6 into KLAS. Right at the HFMNN intersection, CHKNN is suppose to be next but the FMS sort of "shortcut" itself and went right towards SEBBY. I know it's a pretty hard right turn so I'm not sure how to deal with the turning logic, or how it works in the real aircraft but it seems like it could be _slightly_ more adherent before it cut the route.

Not a major issue but I thought I would bring it up.

<img width="768" alt="PNG image 2" src="https://user-images.githubusercontent.com/72432870/95805671-d0b67180-0cba-11eb-99ed-f3b80a810c69.png">

**Comment by mattnischan** [comment]
@slip664 The waypoint sequencing logic and all autopilot functions are in internal Asobo sim code that we do not have access to. We have noticed the same issue at times with close waypoints.

Eventually we will be replacing the entire flight plan system and AP sequencing system with our own, but for now this is something on Asobo's end.

**Comment by dga711** [comment]
If there is no objection to it, I will therefore close the issue. Thank you for your feedback.
