### ISSUE TITLE
CJ4 MFD NAVBAR - GS Should be Magenta

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#249]
In the MFD, the GS value should be colored Magenta, like this:
![IMG_20170906_122032](https://user-images.githubusercontent.com/70416619/95898173-dc9e4400-0d4b-11eb-8e1c-15287e9b9ca7.jpg)

In \workingtitle-vcockpits-instruments-cj4\html_ui\Pages\VCockpit\Instruments\Airliners\CJ4\MFD\CJ4_MFD.css
about at line 490
just the GS text value needs to be magenta

**Comment by J-Hoskin** [comment]
Fixed #eac706b
