### ISSUE TITLE
CJ4: MFD map functionality

### ISSUE THREAD

**Issue by JBFUK** [Working-Title-MSFS-Mods/fspackages#252]
I don't know whether it's possible on the real systems but it would be great to if we could change the zoom on the MFD map independently of the PFD map zoom (I use the MFD map in Plan mode most of the time).  It would also be great to be able to use the joystick to pan around the map.

**Comment by K20017** [comment]
Unfortunately, the zoom feature affects both MFD/PFD and can't be separated.  The joystick is only used to pan on charts and the graphic weather map.  Those are currently on the to-do list, though.

**Comment by dga711** [comment]
@K20017 So it is like that on the real plane too? Therefore, closing it.
