### ISSUE TITLE
CJ4: FMS black screen in PERF approach

### ISSUE THREAD

**Issue by iddqdosc** [Working-Title-MSFS-Mods/fspackages#253]
Hello, the FMS screen went black after I hit the "next" page in PERF Approach. I had the following: 

Wind: 250/6
Temp: 7º
QNH: 30.24

ENBO/25 IBVI2B BO710 DCT OSRUL RNAV Y ENSH/01

This happened a few miles before OSRUL when I was finishing the approach setup.

CJ4 0.4.1 and MSFS 1.9.5

Thank you!

**Comment by IgorTsapyak** [comment]
Hello, I haver the same issue. But want to admitt, that this bug appears in case if you trying to set the wind settings. 
If you use only QNH and Temp it works fine.
