### ISSUE TITLE
G1000 freezing after around 40 minutes in flight

### ISSUE THREAD

**Issue by Grizzlybird311** [Working-Title-MSFS-Mods/fspackages#255]
I have an issue where the G1000's PFDs in C208 freeze after around 40 mins of flying. The HSI works, and the TMR/REF and NRST functions still work, but everything else is frozen.  I've tried recycling the avionics but it'll still end up frozen.  I've had it happen twice, once before the 1.9.5.0 update, and once again after.  I am also using this mod along with Uwajimaya's C208-MSFS2020-Fix mod.  

ETA: The MFD still works fine after the PFDs freeze.

**Comment by Jessidhia** [comment]
Sometimes this also happens when loading an arrival or approach using the PROC menu

**Comment by umurkontaci** [comment]
FWIW, C208's G1000 freezes on me without this addon as well, so this might not be due to the addon.

**Comment by Grizzlybird311** [comment]
Okay I've spent a better part of fiddling around with the G1000 in the caravan trying to replicate the issue, with and without the mod. It seems to be a problem with the base G1000 itself, since I can replicate it even without the mod. 

From what I've seen it always happens sometime around the approach and when you're fiddling around with the PROC menu or when you miss a waypoint, or when it transitions to a point that is in the database to a USER waypoint. 

Maybe the whole base G1000 guts in the sim needs to be ripped out and replaced by what you WT are doing haha.

**Comment by magraina** [comment]
It seems to be only the G1000 is affected by this. The standby instruments are still working at this point.
But sometimes it is unfreezing after a while

**Comment by fppilot** [comment]
I am replicating here some message history from an Avsim topic titled "Garmin freezing up after patch 1.9.5"
By Dillon, Friday at 07:18 PM in Microsoft Flight Simulator (2020)

I am fppilot on Avsim and elsewhere.  Here are my exchanges with Avsim user rjquick:.  To me the last message below may be the most significant reporting of my experiences.  The only other mods I had installed were the WT G3000 mod and the Robert Young Turbo Bonanza mod.  I was flying the G58 Baron when the MFD locked me into the PROC pages.  When that occurred the engine monitoring and navigation monitoring (top of MFD) both went static.  Per my last message below it appears only the MFD is affected.  The PFD continued to operate normally and I was able to make enroute flight plan changes with the PFD.

Was doing some studying in the Bonanza and in the  C172 G1000 when I noticed the very slow responses to waypoint lookup and entry.  I had experienced those delays in the G58 before it locked me in.  
---------------
As I mentioned above, I froze up the MFD in the PROC pages and the rest of the MFD stopped as well.  I could page within the PROC function, but could not exit it.  The AP either continued working or at least reset when I cycled the master avionics switch, but the MFD stayed in the locked up state.  Was flying the G58 Baron.  I did have to turn the AP back on and reestablish AP functions after cycling the avionics switch.  I was able to manage the rest of my flight plan and approach with those functions of the PFD.

I was using G1000 v0.3.1 and I had the G3000 mod in place as well.  I have no G58 mods or liveries.  I have now removed the G3000 mod but have not flown again.  Likely not a factor, but I also have a pms50-gns530 mod in place.
--------------------
22 hours ago, rjquick said:
There seems to be some consensus (reading forum entries) that the freeze occurs on the first approach leg.

Not from me.  I was nearing the end of the first hour of a three hour flight.  Had a long way to go.  However I was in the PROC pages of the MFD when it happened as I was checking to see if the database contained the RNAV approaches for the airport I was heading to.  I had then loaded an approach, but had not activated it.   At least three airports I have flown to so far in MFS have lacked some of the published approaches.
----------------------
22 hours ago, rjquick said:
Some have said that you can unfreeze it by deleting the previous waypoint from the flight plan.

I just noticed this as well.  I got stuck in the two or three pages in the MFD PROC functions.  Though I could page there, I could not complete any functions. No way to do anything in the flight plan pages as I could not even get to those pages.
-----------------------
I neglected to point out another characteristic that seems to precede the freezing.  When with the MFD I go to enter a new interim waypoint into a loaded flight plan, once I have dialed in the identifier for the waypoint and click the ENT button, there is a considerable delay until the code is accepted and entered, or until I am prompted to choose from among duplicates.  Once I choose from among the duplicates and press ENT, there is another considerable delay before it appears in the flight plan.  I do not recall these delays prior to this latest version of the mod.  Subsequent G1000 MFD operations seem sluggish after I notice this issue, and the effect may be cumulative, leading to the freeze.

The PFD does not appear to be affected.  When editing in a new waypoint in the PFD there is a short delay as it looks up and identifies duplicates, but inserts the selection immediately once selected.  No sluggishness. 

I recommend for time being that all flight plan and PROC edits be made with the PFD.  (for PIC's that is the display on the left, LOL)

Edited 15 hours ago by fppilot

**Comment by kaosfere** [comment]
Freezing issues are very hard to troubleshoot.   However, I'm fairly convinced that these are due to issues in the base sim, as Asobo have acknowledged multiple avionics freezing problems.   They also seem to have decreased with recent patches.  IF anyone is still seeing freezing issues that can be reliable reproduced with our G1000 installed but have never happened with the stock one let's try to get a new issue opened for those on a case by case basis.
