### ISSUE TITLE
G1000 Map overlay

### ISSUE THREAD

**Issue by Andywmm9** [Working-Title-MSFS-Mods/fspackages#264]
See screenshot.  Going to any of the map pages causes the map to be cut off.   If I go to the weather radar and back to the map it corrects itself.  ![image](https://user-images.githubusercontent.com/45742070/96071065-0304d200-0e67-11eb-8a5f-30631071fea1.jpeg)

**Comment by kaosfere** [comment]
This was fixed in a v0.3.1.
