### ISSUE TITLE
G1000/G3000:  G1000 PFD freezes on start of flight with G3000 mod installed

### ISSUE THREAD

**Issue by dodougla** [Working-Title-MSFS-Mods/fspackages#269]
With G3000 package installed, G1000 PFD is frozen at startup (either cold/dark or engines running)   Have seen in Bonanza and Baron so far.  Removed/Reinstalled g1000 package with no change.  Removed g3000 package and all is working fine.

**Comment by cywang90** [comment]
this should be fixed with g3000-v0.2.0-pre2
