### ISSUE TITLE
CJ4: Direct To When IN Approach

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#27]
When an approach is active, need to not delete waypoints - add criteria for IF statement asking is approach waypoint AND is approach active and change behavior accordingly.

**Comment by cwburnett** [comment]
Added  && fmc.flightPlanManager.isActiveApproach() != true condition to the alternate handling that activates the approach to prevent the subprocess from running if the approach is already active.

**Comment by cwburnett** [comment]
This is on hold until an Asobo update that allows for editing of the approach flight plan. Existing functionality is DTO enroute from enroute or DTO to IAF from enroute.

**Comment by dga711** [comment]
While it will have some bugs here and there. Will close this issue and we will handle further problems seperately.
