### ISSUE TITLE
Adding an Approach removes the IAF

### ISSUE THREAD

**Issue by BPieke** [Working-Title-MSFS-Mods/fspackages#273]
I did not see this raised before.
When adding an Approach (Example KTPA RNAV 01L via FITPA-SNORK-WELIT, the IAF FITPA is replaced by "USER" and does not appear in the flightplan or the map.

![RNAV KTPA 01L](https://user-images.githubusercontent.com/71661698/96163033-30389b00-0ece-11eb-92ce-c7498048e400.jpg)

**Comment by dga711** [comment]
From my experience, this is something the game does to have a "from" fix. Not sure if we can do anything about besides maybe not showing it at all.

**Comment by kaosfere** [comment]
I'm going to close this, at it's something that will be taken care of by the new FPM when it gets ported over.
