### ISSUE TITLE
[g3000-v0.2.0-pre1] Changelog

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#274]
I received an automated email subject "[Working-Title-MSFS-Mods/fspackages] Pre-release g3000-v0.2.0-pre1 - g3000-v0.2.0-pre1" which contains a detailed changelog.

However, on the Github website I only see summarized highlights.

Can you point me to the place where I can see the detailed changelog at Github website? If unavailable, can you ensure this is added to the release?

**Comment by cywang90** [comment]
The changelog can be found in the .zip as CHANGES.md. You can also view it on github here: https://github.com/Working-Title-MSFS-Mods/fspackages/blob/g3000-v0.2.0-pre2/docs/workingtitle-g3000/CHANGES.md
