### ISSUE TITLE
TAKEOFF REF pages 2+ does not work.

### ISSUE THREAD

**Issue by malloycv** [Working-Title-MSFS-Mods/fspackages#275]
For version 0.4.1.
Take of ref pages does not switch after "next" button pressed, message "INVALID" appears in bottom left corner. 
WIND : 010/6
OAT : 15C
QNH : 29.92
RWY ID : NO TAKEOFF RW
RWY WIND : H5 R1
RWY LENGTH : 0  FT
RWY SLOPE : --.-%
RWY COND : DRY/WET

**Comment by K20017** [comment]
It appears you did not load a departure runway.

**Comment by malloycv** [comment]
Oh, sorry. Now I see. Thanks.
