### ISSUE TITLE
g3000-v0.2.0-pre1:  Direct to from FPL does not work

### ISSUE THREAD

**Issue by kutak11** [Working-Title-MSFS-Mods/fspackages#283]
hi,
in G3000 is not working "Direct to" properly. After pressing to waypoint then Direct to in option this point is not selected and must be written manually everytime.
thanks

**Comment by cywang90** [comment]
I'm unable to reproduce this. Can you please provide more details?

**Comment by kutak11** [comment]
close this, I just found pre2 version where it is working properly or maybe some intermittent bug, sorry
