### ISSUE TITLE
g3000 syntetic vision not work with pre 2.0

### ISSUE THREAD

**Issue by cangianos** [Working-Title-MSFS-Mods/fspackages#284]

**Comment by cywang90** [comment]
Can you provide more detail please? Steps to reproduce would be really helpful.

**Comment by cangianos** [comment]
Hi If I install the pre-release 2.0 of G3000 working title I cannot see the synthetic vision mode in my TBM.  I have installed only working tytle g1000. Bonanza turbo mod and TBM improvement mod.

**Comment by cywang90** [comment]
g3000 v0.2.0 will switch SVT off by default. You can turn it on by using the softkeys: PFD Settings -> Attitude Overlays -> Synthetic Terrain. Please let me know if that works for you.

**Comment by helge000** [comment]
I confirm synthetic vision works as expected.

**Comment by cangianos** [comment]
Thanks, It was another mod in conflict. Is working now.
