### ISSUE TITLE
CJ4: Cannot set VOR2 Course

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#285]
It's not possible to set the VOR2 course on PFD.

I'm also missing the BRG needles for GPS, VOR1, VOR2 and ADF. They are a must have for some instrument approaches.

**Comment by ntlgr** [comment]
Indeed the CRS2 control does not change the VOR2 course. Can this be fixed please? This is key for instrument approach.

**Comment by cwburnett** [comment]
Fixed for next release

**Comment by cwburnett** [comment]
Closed with #424

**Comment by ntlgr** [comment]
You guys rock.
