### ISSUE TITLE
G3000: Weather/Map zoom setting differ/out of sync

### ISSUE THREAD

**Issue by helge000** [Working-Title-MSFS-Mods/fspackages#287]
The weather map's zoom setting will always be a few steps lower than the nav map's.

Seen in TBM.

**Comment by cywang90** [comment]
Thank you for reporting this. This is a known issue and a fix is planned for a future release.

**Comment by helge000** [comment]
@cywang90 - nice, your commit just now. Was a very minor thing anyway for me!

Off topic:
I am so happy you guys make the G3000 actually usable (`Range to altitude` is among my favourites because of the missing VNAV).
