### ISSUE TITLE
G3000 0.2.0 pre2

### ISSUE THREAD

**Issue by yusufsan38** [Working-Title-MSFS-Mods/fspackages#290]
Synthetic vision is broken in the TBM 930, I tried with all workingtitle mods and nothing else in the community folder as well as just only G3000 0.2.0 pre2 in the community folder and each time the synthetic vision is not displayed. Only change I've made to TBM is the engines.cfg and flightmodel.cfg to fix the torque and gear drag.

**Comment by cywang90** [comment]
Did you turn SVT on using the PFD softkey menu?

**Comment by yusufsan38** [comment]
> Did you turn SVT on using the PFD softkey menu?

Let me try it one more time, I thought I did but I want to double check

**Comment by cywang90** [comment]
Go to PFD Settings, Attitude Overlays, Synthetic Terrain

**Comment by yusufsan38** [comment]
> Go to PFD Settings, Attitude Overlays, Synthetic Terrain

Ah I thought it should be on by default. Works now thank you!
