### ISSUE TITLE
CJ4 0.5.0: Remove or Fix DECEL waypoint

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#297]
Remove of fix the DECEL waypoint.

**Comment by dga711** [comment]
I think we can set a simple simvar to disable it. Or change the logic that sets it up. Quite accessible

**Comment by cwburnett** [comment]
Yes just putting it here so I don't forget.

**Comment by cwburnett** [comment]
This has been updated in flightplanmanager, but still needs to have the 'name' updated to TOD in the mapinstrument. Also need to make sure that the location is actually updating when the cruise altitude is set or changed.

**Comment by cwburnett** [comment]
Include in FPM
