### ISSUE TITLE
CJ4 0.5.0: Some Waypoint Labels on Map have text overlap

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#298]
![image](https://user-images.githubusercontent.com/70416619/96350225-fef8d000-1071-11eb-917b-39b94fddb995.png)
Seems to be current and past waypoints only...

**Comment by dga711** [comment]
Weeks ago when i dived a bit into map things, I think that waypoint with waypoints it couldn't assign to a coordinate. So they got overlayed onto another.

**Comment by dga711** [comment]
Should be a non issue now
