### ISSUE TITLE
Throttle resets to 0 using joystick mapping

### ISSUE THREAD

**Issue by peyton18scott18** [Working-Title-MSFS-Mods/fspackages#302]
Throttle is only adjsutable on keyboard controls, using joystick lever always leads to it being reset to the value used by keyboard.

**Comment by Jessidhia** [comment]
Make sure you're not using one of the airplane mods that implement a FADEC, like the DA40-NGX mod; they warn you in the README that only F2-F3 works for them due to a bug in SimConnect.

**Comment by dga711** [comment]
I don't think this is something related to our mods. Therefore I will close this one
