### ISSUE TITLE
G3000 V0.2 - 500 foot altitude warning is not triggering aural alert

### ISSUE THREAD

**Issue by CasualClick** [Working-Title-MSFS-Mods/fspackages#305]
Tested with MSFS 1.9.5.0.

Mods installed in community:

WorkingTitle G1000 V0.3.1
WorkingTitle G3000 V0.2.0

Aircraft used: Daher TBM 930 - no mods other than G3000.

Airfield KBID - daylight hours, custom clear weather, deleted any wind layers including the 3 @ 275 default. 80 percent total weight - two pilots @ 170 lbs each.

Conducted two left-hand circuits at 1000' pattern, lowering landing gear and flaps 1 at downwind abeam runway threshold. Stabilized on final at 800-900'  with full flaps and gear down. Passed 500' in 300-400' fpm descent, no aural warning.

Synthetic vision is enabled.

**Comment by cywang90** [comment]
Apparently this is broken in vanilla as well. Luckily there is a mod that fixes it: https://forums.flightsimulator.com/t/tbm-930-audible-alert-fixes-updated/278815
