### ISSUE TITLE
G1000:  ETE changes from default

### ISSUE THREAD

**Issue by LJD46506** [Working-Title-MSFS-Mods/fspackages#308]
I didn't see this in the documentation as a deliberate change so if it is, pardon me.

The Default G1000 shows the time to NEXT FIX in the ETE field above the MFD.  The Mod has changed that behavior and now shows the Total Flight Plan time in the ETE field.  Don't know if that was on purpose or not.

Thanks,
Larry

**Comment by LJD46506** [comment]
In the following file:
html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js

I made the following change:
from: var ete = SimVar.GetSimVarValue("GPS ETE", "seconds");
to:  var ete = SimVar.GetSimVarValue("GPS WP ETE", "seconds");

That returned ETE back to the waypoint instead of the entire flight plan.
Don't know if that change was deliberate on your part or not, but it does allow us who like waypoint ETE to have it back.

**Comment by knighty** [comment]
I'm honestly not sure when that would have been changed, but I'll make sure it's the correct value going forwards with my rearchitecture work.
