### ISSUE TITLE
G1000: A bunch of feature request...

### ISSUE THREAD

**Issue by CkovMk** [Working-Title-MSFS-Mods/fspackages#31]
Thanks for your work, and I wanna request a few features on the improved G1000...
1. Save Settings. Every time a plane is loaded, the PFD settings (Wind Direction, Bearing Pointers, Reference Speed, etc.) are gone. I don't know if the real world Garmin would reset these settings. I wonder if you could save the settings and load it at start.
2. OBS (Other Bearing & Suspend). It let you select another CRS inbound to a GPS Waypoint. Can be useful when flying some procedures.
3. insert Vectors-To-Final and Activate-Vector-To-Final. I even don't know if they are in database... If not, this is probably impossible though...
4. VNAV
5. Save and Load Flight Plans
6. Map Declutter

I just know a bit about MFS SDK, and still learning. Some feature may be hard to realize, so its just a suggestion on what you could probably make later.

**Comment by jonasbeaver** [comment]
7. Same treatment for the C208 as the C172/G36
8. Direct-to fuction remembering last waypoint so you can just hit "-D> enter enter" and re-centre the needle
9. Menu screen function expanded to return flightplan functions on the PFD
10. On activating an approach, create a direct-to function on the GPS instead of a USER waypoint created that you have to fly back to, to start the approach. It is especially useless if you try to do the approach without going to the IAF, which in reality from the flightplan page highlight any waypoint (including ones on the approach) with the cursor and then hit direct-to and it will auto-fill to fly to the highlighted waypoint. This is one of the real life functions I miss the most.

**Comment by guifarias31** [comment]
11. Be able to ajust the course when a LOC frequency is active.

12. Do all the things for G1000, G3000, G3X and GNS450/530.

**Comment by jonasbeaver** [comment]
12... lol

**Comment by CkovMk** [comment]
14. update the softkey menu. Here's a [video](https://www.youtube.com/watch?time_continue=707&v=UR0DKGk3-fE&feature=emb_logo) that provides lots of useful infomation.

**Comment by guifarias31** [comment]
> 1. update the softkey menu. Here's a [video](https://www.youtube.com/watch?time_continue=707&v=UR0DKGk3-fE&feature=emb_logo) that provides lots of useful infomation.

That's the G1000 NXi, which is a different/newer version than the G1000 from MSFS.

**Comment by CkovMk** [comment]
> > 1. update the softkey menu. Here's a [video](https://www.youtube.com/watch?time_continue=707&v=UR0DKGk3-fE&feature=emb_logo) that provides lots of useful infomation.
> 
> That's the G1000 NXi, which is a different/newer version than the G1000 from MSFS.

I know the difference about G1000 /G1000 NXi. G1000 model is quite old, and I see no point of sticking in that old version. What's more, graphics in G1000 NXi share the same design with G3000 / G5000, which is already in game. This make it easy to reuse the resources.
That's just my personal view though. If this project is meant to simulate the old G1000, it's still a good idea.

**Comment by CkovMk** [comment]
15. AP should disengage automatically when using manual trim
> The GFC 700 may be manually disconnected by any of the following means:
> - Depressing the red AP DISC button on the pilot's or co-pilot's control stick
> - **Moving the left (outboard) side of the manual electric trim switch on the pilot's controlstick**
> - Pushing the AP button on the autopilot mode controller when the autopilot is engaged
> - Depressing the GA button on the left side of the power lever (if ESP is not installed)
> - Pulling the AFCS/ESP/USP circuit breaker
> - Turning off the AVIONICS MASTER switch
> - Turning off the ELECT. MASTER switch

(Diamond DA 62 Flight Manual)[https://www.manualslib.com/manual/1626359/Diamond-Da-62.html?term=yaw+damper&selected=6&page=478#manual], page 478.

**Comment by guifarias31** [comment]
17. Changing the font to [something closer](https://fontstruct.com/fontstructions/show/86362/g1000) to the real G1000.

**Comment by kaosfere** [comment]
This is an awesome list, y'all.   I just wanted to acknowledge it even though we haven't done anything with it yes because we've been focused on getting the next version with the most asked for functionality (except for OBS, because I think that's gonna be _really_ had) out the door.   Definitely going to turn to tackling some of these after that, though.

**Comment by bachian** [comment]
> 12... lol < now you made me laughing at your 12. seem silly!

Actually this makes sense. The font used by Asobo does not match the original G1000 font.

The font recomended by @guifarias31 is closer (yes, it's a pixel font, like the real unit), but is unfinished.

I was looking at the G1000 manual, and it's hard to figure out if there is just one or more pixel fonts. Also, there some special characters, like ºF or ∆P.

I believe this topic deserves a topic itself.

I'm attaching some references from the original UI.

<img width="765" alt="1" src="https://user-images.githubusercontent.com/29262832/95697973-e8d4b500-0c16-11eb-95b2-39f8a4cb8507.png">
<img width="264" alt="3" src="https://user-images.githubusercontent.com/29262832/95697983-ed996900-0c16-11eb-9d30-67c4d34ebbc2.png">
<img width="387" alt="2" src="https://user-images.githubusercontent.com/29262832/95697989-eeca9600-0c16-11eb-9e43-993154428628.png">

**Comment by guifarias31** [comment]
> Actually this makes sense. The font used by Asobo does not match the original G1000 font.
> 
> The font recomended by @guifarias31 is closer (yes, it's a pixel font, like the real unit), but is unfinished.
> 

And actually, there's an A1000 font already inside the game, but seems like Asobo decided not to use it:
...\Steam\steamapps\common\MicrosoftFlightSimulator\Packages\fs-base-ui\html_ui\Fonts\A1000

I even managed to change the font, here's the result:
![image](https://user-images.githubusercontent.com/70555403/95704258-a0bd8e80-0c26-11eb-937a-2fc7f543f9c9.png)

**Comment by bachian** [comment]
> And actually, there's an A1000 font already inside the game, but seems like Asobo decided not to use it:
> ...\Steam\steamapps\common\MicrosoftFlightSimulator\Packages\fs-base-ui\html_ui\Fonts\A1000\a1000.ttf
> 
> I know an user called L3m0n was working on that for the Working-Title project, but I managed to change the font myself, here's the result:

Good to know someone is already working on that.

I'm surprised Asobo didn't used the right font. Your version looks nice, I hope we can have that soon.

Obrigado Guilherme!

**Comment by knighty** [comment]
Personally I despise looking that the proper font :P. Thought I'd stick it on my current work so you could see what it's like though.

![image](https://user-images.githubusercontent.com/1693684/95762553-c6d64380-0ca5-11eb-8680-7ca76378b77c.png)

With my redesign I've made it pretty easy to sub in/out fonts and sizes so what I think would be a good idea is an option in the settings screen to choose between the more accurate font and a more legible font so we get the best of both worlds for whatever users want

**Comment by guifarias31** [comment]
> With my redesign I've made it pretty easy to sub in/out fonts and sizes so what I think would be a good idea is an option in the settings screen to choose between the more accurate font and a more legible font so we get the best of both worlds for whatever users want. The font in that folder only is also not exactly accurate, note how bad the kerning is on the numbers there for example, the 1 should be centred.

Oh my god, this is perfect! Can't wait to try this! Thanks for all your work!

**Comment by bachian** [comment]
> Personally I despise looking that the proper font :P. Thought I'd stick it on my current work so you could see what it's like though.
> 
> ![image](https://user-images.githubusercontent.com/1693684/95762553-c6d64380-0ca5-11eb-8680-7ca76378b77c.png)
> 
> With my redesign I've made it pretty easy to sub in/out fonts and sizes so what I think would be a good idea is an option in the settings screen to choose between the more accurate font and a more legible font so we get the best of both worlds for whatever users want. The font in that folder only is also not exactly accurate, note how bad the kerning is on the numbers there for example, the 1 should be centred.

Absolutely amazing! I can't wait to have it.

**Comment by Alpny** [comment]
Bonjour and thank you for the great work. You deserve a barrel of beer. How to donate?

17 ? Give the possibility to change the desired course when activating a direct-to. 

Xplane simulates this feature very well and I use it most of the time. Knowing the orientation of a runway (eg. 218 degrees), you get a course perfectly aligned for the landing approach. It’s a special use of the direct-to, as after ACTIVATE, your plane is off-course (of course...😃). But this feature is implemented in the G1000. 


![DE1C796F-A667-49D1-B834-1468617EBE2E](https://user-images.githubusercontent.com/68559667/97774709-5c088180-1b5a-11eb-961c-83cf043e3467.jpeg)

**Comment by tigert** [comment]
> Bonjour and thank you for the great work. You deserve a barrel of beer. How to donate?
> 
> 17 ? Give the possibility to change the desired course when activating a direct-to.

I think this is the same what you can do on the fly with the OBS key. It is a super neat and useful feature (basically what it does, is it makes any waypoint a "VOR". So you can rotate the course and it draws a line on the map that crosses the waypoint at that direction. It's also mentioned above as one particularly difficult feature to implement, which I can imagine.

I also OBS mode on the GNS430 when going to a new airport which was not familiar, you have a quick reference to the runway direction.

You can get somewhat similar orientation help if you set CDI to display VOR1 or VOR2 and set that course to the runway heading, the arrow in the HSI then is parallel to the runway.

**Comment by Alpny** [comment]
> I think this is the same what you can do on the fly with the OBS key that is not implemented either.

Yes, my friend, you’re right. OBS mode gives the same possibility with any waypoint within a flight plan. And OBS mode suspends the sequencing to the next waypoint. You can test it in xplane’s G1000, where it works quite well. 

Take care

**Comment by Shaha787** [comment]
You are doing a very good job and I am very grateful to you. Your work on the harmine made it very realistic. But still I would like to add a couple of functions such as OBS and metric calculation. I would be very grateful to you. Have a nice day and if I made a mistake in the text, I apologize to you! Thanks in advance)))
