### ISSUE TITLE
G1000: Weird big icon on MFD

### ISSUE THREAD

**Issue by danecreekphotography** [Working-Title-MSFS-Mods/fspackages#311]
I've got a giant big icon in the middle of the MFD for some reason in the Cessna 172's G1000:

![image](https://user-images.githubusercontent.com/9524118/96357915-751f2600-10b6-11eb-9502-7d7f3b7fba25.png)

Version: not sure. The readme says v0.3.0 but the manifest.json file says 0.2.0.

**Comment by cywang90** [comment]
Do you by any chance have the g3000 mod installed as well?

**Comment by danecreekphotography** [comment]
Yes, I do.

**Comment by cywang90** [comment]
I suspected you might. This is a compatibility issue with the g3000 mod. It will be addressed in an upcoming hotfix.
