### ISSUE TITLE
G3000 freq transfer in NAV 1 or 2  changes ADF as well

### ISSUE THREAD

**Issue by ccapilot** [Working-Title-MSFS-Mods/fspackages#312]
as the title says, everytime you hit XFER to transfer stby/active frequencies on NAV1 or NAV2, the stby/active frequency for ADF gets changed as well, when they should be of course totally independent.

**Comment by cywang90** [comment]
I'm not able to reproduce this issue. Can you please provide more details, including the exact steps you took when this issue occurred?

**Comment by ccapilot** [comment]
go to NAV/COM page, note the active/standby frequencies for NAV1 / NAV 2 radios, now scroll down to ADF and note active/standby freq. Select ADF frequencies box and hit XFER, now go back and look at the NAV1 / NAV 2 frequencies, probably at least one of them swapped as well, now select a NAV 1 or NAV 2 frequency and hit XFER and go back to ADF and those frequencies have swapped as well. Please let me know if still unable to reproduce and I will make a quick short video showing this annoying bug. thanks

**Comment by ccapilot** [comment]
and even worse, now that I am playing with this, I see I enter a random frequency on stby NAV 1 or NAV 2 and hit XFER and the either active or stby frequencies on ADF get completely changed to different numbers... very strange bug

**Comment by cywang90** [comment]
Ok, got it to repro; the key was actually changing the ADR freqs (not just swapping them). Looks like a vanilla bug though since it's still present even without any WT mods. I'll flag it as bug and see if we can fix it for a later release.
