### ISSUE TITLE
CJ4: Simbrief importing suggestion

### ISSUE THREAD

**Issue by oliverpope03** [Working-Title-MSFS-Mods/fspackages#315]
Hello, i was just looking at the api for simbrief as i was confused where to find my id, i was wondering if you could maybe add a second box where you can enter a username and use this url https://www.simbrief.com/api/xml.fetcher.php?username=<username> to allow people to enter there username which is easier to locate, then the code can find there ID from the xml it provides, Username are not case sensitive and therefore will work in the fmc

**Comment by dga711** [comment]
@oliverpope03 We thought about using the username. But I was afraid of there being symbols you cannot enter via the fms push buttons. Also don't know if their usernames are case sensitive.
So this looked like the more safe approach.

![image](https://user-images.githubusercontent.com/2995606/96368748-faa5e300-1155-11eb-9575-033aae1bd2b7.png)

**Comment by oliverpope03** [comment]
Thank you for the reply, didnt realise thats where the user id was, i tested the username function for getting my user id and it is not case sensitive i tried multiple ways but i understand the symbol limitation thank you 👍

**Comment by dga711** [comment]
I think we will discuss that in the team. Thank you for the feedback.

**Comment by cwburnett** [comment]
For now we will stick with PILOT ID as it is easily accessible on the flight planning page in simbrief.
