### ISSUE TITLE
WXRadar vertical mode scale stuck at 60k feet (G3000)

### ISSUE THREAD

**Issue by helge000** [Working-Title-MSFS-Mods/fspackages#316]
First of all, sorry for opening this issue here since clearly a bug in vanilla:

### The vertical WX Radar scale is stuck at 60k feet at all zoom levels (observed on G3000)
![WX Radar scale](https://user-images.githubusercontent.com/13696924/96367737-f37bd680-114f-11eb-8c46-5482e4bb2512.png)

**Comment by cywang90** [comment]
Fixed with 0.4.0
