### ISSUE TITLE
TOC/TOD  spped and Criuse FL

### ISSUE THREAD

**Issue by telemakox** [Working-Title-MSFS-Mods/fspackages#319]
In the FMC the cruising speeds and the cruising flight level are no longer seen on the right side. Also the TOC and the TOD are missing

**Comment by K20017** [comment]
Those do not exist on the real FMC.  It will only show you speed and altitude constraints if it applies to a fix.

**Comment by telemakox** [comment]
THX for  your kind reply….

Bruno

Inviato da Posta per Windows 10

Da: K20017
Inviato: domenica 18 ottobre 2020 17:41
A: Working-Title-MSFS-Mods/fspackages
Cc: telemakox; Author
Oggetto: Re: [Working-Title-MSFS-Mods/fspackages] TOC/TOD spped and Criuse FL(#319)

Those do not exist on the real FMC. It will only show you speed and altitude constraints if it applies to a fix.
