### ISSUE TITLE
CJ4: Import Simbrief route with coordinates fix

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#321]
Please, consider add support for coordinates in the navigation plan.

I had this route:
**SBJD/36 DCT 2313S04716W DCT ILSAN Z41 MOLMI DCT SBRP/36**

The first fix, **2313S04716W** was skiped when importing from Simbrief.

Superb job with v0.5 release by the way!

**Comment by dga711** [comment]
Currently there is no way to set custom waypoints in the game's flight plan. 

But we are working on our own flight plan implementation where this would be a possibility. Thanks for the feedback.

**Comment by bachian** [comment]
Good to know you are working on a solution.

This project is awesome!

**Comment by cwburnett** [comment]
Without the current possibility to add custom waypoints, this is not a bug. Adding custom waypoints is on our enhancement wish list already. Closing issue.
