### ISSUE TITLE
G3000 no longer shows terrain in PFD?

### ISSUE THREAD

**Issue by danecreekphotography** [Working-Title-MSFS-Mods/fspackages#324]
I just tried a flight with the G3000 add-on, readme says the version is v0.2.1, and I don't seem to have any terrain in the PFD display anymore. I went back and looked at my old screenshots pre-addon installation just to make sure I wasn't going crazy and sure enough the stock version shows terrain in the PFD.

I've gone through every setting/option I can find in the UI and can't find a way to bring it back. I'm 99% sure this is user error on my part: where is the option to turn it back on?

What I had during my flight:

![image](https://user-images.githubusercontent.com/9524118/96390435-7e1cff80-1169-11eb-889c-a12c861356de.png)

What it used to show:

![image](https://user-images.githubusercontent.com/9524118/96390456-955bed00-1169-11eb-99c0-dba21cd52a91.png)

**Comment by cywang90** [comment]
Use the PFD softkey menu. PFD Settings > Attitude Overlays > Synthetic Terrain. Let us know if this doesn't work.

**Comment by danecreekphotography** [comment]
Yuuuuup sure was user error 🤦‍♂️ Thank you for the quick response.
