### ISSUE TITLE
CJ4: IAS, Speedtape, Mach, Vmo, Mmo and FLC Mach issues

### ISSUE THREAD

**Issue by boufogre** [Working-Title-MSFS-Mods/fspackages#326]
According to [this EASA document](https://www.easa.europa.eu/sites/default/files/dfu/525C-CJ4.pdf), the VMO/MMO of the CJ4 are the following:

VMO (altitude<8000ft): 260kt
VMO (8000ft<altitude<27884ft): 305kt
MMO (27884ft<altitude): 0.77

- [x] Currently, the MMO is improperly calculated and displayed.
- [x] Need to align overspeed warning with  tape and IAS
- [x] At the same time fix FLC Mach recalculation so that the bug and FLC target is adjusted once a second when in Mach mode
- [x] Need to fix  Airspeed and altitude window issue
- [x] Airspeed not vertically centered in the window

![image](https://user-images.githubusercontent.com/70416619/97503996-b081e600-193b-11eb-8d26-734f69c0aa42.png)
![image](https://user-images.githubusercontent.com/70416619/97504006-b4ae0380-193b-11eb-9726-897ef8a8eccb.png)
![image](https://user-images.githubusercontent.com/70416619/97504012-b8418a80-193b-11eb-90d3-1476c8c0df96.png)

**Comment by cwburnett** [comment]
This is a default PFD bug and is on our enhancement list already.

**Comment by cwburnett** [comment]
Combining in "Premature" Overspeed Warning - need to adjust overspeed and tape to respond to correct altitude conditions

**Comment by cwburnett** [comment]
Combining in PFD Airspeed and altitude window issue

**Comment by cwburnett** [comment]
Combined in https://github.com/Working-Title-MSFS-Mods/fspackages/issues/410

**Comment by mattnischan** [comment]
Overspeed warning tape was finally fixed in 0.9.1, so that should be the last of the bugs from this report.
