### ISSUE TITLE
ISA temperature indication wrong CJ4

### ISSUE THREAD

**Issue by boufogre** [Working-Title-MSFS-Mods/fspackages#328]
On the MFD, ISA temperature calculation is wrong.

In ISA, temperature at sea level is 15°C and decreasing 1.98°C/1000ft of increasing altitude up to 36000ft where temperature reaches a minimum of -56.5°C. This minimum is maintained throughout the stratosphere, up to 65000ft, where the temperature starts increasing again by 0.3°C/1000ft.

In the current calculation, the lapse rate of -1.98°C/1000ft is applied above 36000ft, which is incorrect.

![Wrong ISA](https://user-images.githubusercontent.com/73106379/96432300-f97fbf00-1204-11eb-9dd4-4d507e8cd156.jpg)

In the picture, the ISA deviation should be indicating +2°C instead of 20°C.

**Comment by dga711** [comment]
per pr #357 should no show isa deviation
