### ISSUE TITLE
Mirrored elevator trim indication MFD CJ4

### ISSUE THREAD

**Issue by boufogre** [Working-Title-MSFS-Mods/fspackages#329]
The elevator trim position indicator on the MFD is currently reversed, showing nose down indication, when the trim is set to nose up.

The green take-off band is similarly misplaced.

Below, screenshots from the MFD and the UI indicator in outside view to illustrate the problem. The UI indicator is correct.

![Reversed elev trim](https://user-images.githubusercontent.com/73106379/96439945-89266d00-1207-11eb-9659-5ccb1b85061c.jpg)          ![Elev trim outside view](https://user-images.githubusercontent.com/73106379/96439971-93486b80-1207-11eb-9d38-b432a2de77cf.jpg)

**Comment by cwburnett** [comment]
This is a default aircraft bug and on our MFD enhancement list already.

**Comment by J-Hoskin** [comment]
Ahhh I never understood the green marker on the elevator trim being offset. I'll fix these issues. Thanks for the report.

**Comment by cwburnett** [comment]
@J-Hoskin the entire gauge needs to be flipped (NU <--> ND), which will then put the green TO band in the right spot. We discussed this a few weeks ago but were waiting until we did an overhaul of that part of the MFD with updated readability, etc.

**Comment by J-Hoskin** [comment]
@cwburnett Yeh I remember vague discussions. I'll flip it anyway cause its an easy fix and has always annoyed me.

**Comment by cwburnett** [comment]
Sweet, it annoys me ;-)

**Comment by dga711** [comment]
@J-Hoskin 
Please check PRs #340 #341 and act accordingly ;)

**Comment by dga711** [comment]
Closed via #340 #341 
Thank you @Danice737
