### ISSUE TITLE
CJ4: Missing Bearing Pointers

### ISSUE THREAD

**Issue by e4rthdog** [Working-Title-MSFS-Mods/fspackages#33]
DMEs are nowhere to be found for both VORs.

**Comment by kaosfere** [comment]
Not sure what you mean with this one...  are you seeing missing distance information for VORs somewhere?   Is this for the G1000?

Thanks!

**Comment by e4rthdog** [comment]
Sorry that i did not make it clear.

I tune a VOR that is reachable but i dont see the DME distance number nowhere. Also i don't see needles for the VOR (i dont know if this is normal in this aircraft). I only see the needle that moves when i change the VOR course.

**Comment by jonasbeaver** [comment]
Page 60 on the G1000 manual
https://static.garmincdn.com/pumac/190-00498-07_0A_Web.pdf

Press the pfd softkey at the bottome of the pfd then press brg1 or brg1 to set up the bearing mode on either side. In the real G1000 the default mode is vor1 on brg1 and vor2 on brg2. The default mode in the msfs g1000 is off for both.

This is a user error that is magnified by non-standard defaults in the msfs g1000.

**Comment by e4rthdog** [comment]
I am talking about the CJ4 not the G1000. In CJ4 i cant see the number of NM for the DME for VARs and i dont see needles.

**Comment by mattnischan** [comment]
There definitely should be needles (we noticed this also), and I assume distance. That's something we'll definitely take a look at.

**Comment by e4rthdog** [comment]
> There definitely should be needles (we noticed this also), and I assume distance. That's something we'll definitely take a look at.

Thank you very much. Waiting for that. Keep up the good work.

**Comment by cwburnett** [comment]
From @Mekein
Basically, when shooting an ILS app, there is no information about distance to runway (DME) in the PDF. Not entirely sure if in default CJ4 its also missing, will try later.

Also, first time posting here trying to figure out tags, labels etc..

**Comment by cwburnett** [comment]
From ryanbatcund on Avsim:

Is there a way to get the HSI now?  I think before one would press FRMT.  There seems to be a difference between the TUN page and what is shown when I turn on BRG pointers.  Essentially, I cannot tune a VOR and use the HSI anymore.

Looks like the FMS TUN page is disconnected from the NAV1/NAV2 readout on the PFD/MFD.

**Comment by e4rthdog** [comment]
Any chance to give this task some love , in order to be able to fly VOR/DMEs?

**Comment by mattnischan** [comment]
We've started to take a look at it, yes. Some of these tasks will be a bit slow going. Almost all of the PFD and MFD display code is shared by every jet in the game, so it's been challenging to make the changes we need to safely while maintaining compatibility with other mods and not breaking the default aircraft.

But it is definitely on the list!

**Comment by e4rthdog** [comment]
I was glad to see today that you added DME for the VORs... Just to make sure, you will also add the VOR needles?

**Comment by cwburnett** [comment]
@e4rthdog can you confirm what you mean by needles? Something other than this?

https://i.imgur.com/EZKA836.jpeg

What's there right now is the HSI 'needle' in cyan. This is the wrong size and color right now, and that's on our list, but want to confirm you should be seeing the HSI when turned to a VOR.

**Comment by e4rthdog** [comment]
> @e4rthdog can you confirm what you mean by needles? Something other than this?
> 
> https://i.imgur.com/EZKA836.jpeg
> 
> What's there right now is the HSI 'needle' in cyan. This is the wrong size and color right now, and that's on our list, but want to confirm you should be seeing the HSI when tuned to a VOR.

The HSI is there indeed.

I am talking about the straight arrows that show to the VOR/ADF....I just dont know if the avionics of CJ4 has them..

See the green and blue on the following pic 

![image](https://user-images.githubusercontent.com/1651764/94723406-5e13d080-0361-11eb-8e70-409c7720bab3.png)

**Comment by K20017** [comment]
Oh, those are called Bearing Pointers and it is on our list to implement.  It is normally adjusted in the PFD MENU -> BRG SRC and it looks like this: https://imgur.com/a/JEqzIUz

**Comment by e4rthdog** [comment]
> Oh, those are called Bearing Pointers and it is on our list to implement. It is normally adjusted in the PFD MENU -> BRG SRC and it looks like this: https://imgur.com/a/JEqzIUz

Perfect! Thank you guys for your efforts!

**Comment by mattnischan** [comment]
Hi all,

Since DME information was addressed in #133, I am going to slightly edit the title of this to reflect. Thanks all!

**Comment by bachian** [comment]
I glad to know you are already working on BRG needles. Whithout them, it's impossible to do some kind of IFR approaches.

**Comment by e4rthdog** [comment]
Any more concrete news as to when we can expect to have the ability for VOR approaches?

**Comment by mattnischan** [comment]
Bearing pointers will not be in 0.5.0. Unfortunately, we will have to create them entirely from scratch, as no support at all exists for them in the aircraft as is. Asobo left a placeholder but clearly never finished it.

**Comment by Frolic31** [comment]
Hello,
Glad to see that you're working on it. It's so sad to be unable to perform an NDB final or to set route on a VOR...
Thanks for all you do, you C14 mod is just awesome.

**Comment by mattnischan** [comment]
Implemented in #352
