### ISSUE TITLE
CJ4: Standby altimeter settings display CJ4

### ISSUE THREAD

**Issue by boufogre** [Working-Title-MSFS-Mods/fspackages#330]
On the standby altimeter, the baro setting is incorrectly displayed using 2 or 3 digits instead of 4 when using a round setting.

For example 29.90 inHg will be displayed as 29.9, or 30.00 will displayed as 30.

See screenshot below.

![stby ADI](https://user-images.githubusercontent.com/73106379/96441277-90e71100-1209-11eb-840f-34e74a0a0087.jpg)

Another bug is that the setting 29.99 is repeated twice.

**Comment by bachian** [comment]
It would be good to have the capacity the also change the standy altimeter unit to hpa.

**Comment by cwburnett** [comment]
These are bugs in the default and are in our enhancement list already.

**Comment by J-Hoskin** [comment]
This item has been fixed in will be in the next update

**Comment by cwburnett** [comment]
@J-Hoskin will this make it in by tomorrow or is this a next week fix?

**Comment by J-Hoskin** [comment]
I can release it tomorrow.

**Comment by neoeinstein** [comment]
Nominate this for closing, as fixed. I verified that the setting here is showing in the right precision even on round numbers.

**Comment by dga711** [comment]
Thanks for verifying 👍
