### ISSUE TITLE
CJ4: STD Altimeter for hpa

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#332]
Pressing STD using hpa, does not set altimeters to 1013 hpa.

**Comment by cwburnett** [comment]
This is a default sim issue we're researching - right now commanding STD from the BARO know results in the equivalent of pressing 'B' to set BARO to the current setting, if > 18000' then it will set 29.92inHG, otherwise it sets the local altimeter setting.

**Comment by cwburnett** [comment]
Fixed with next update
