### ISSUE TITLE
[CJ4] - Request PFPX performance file - DONE

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#338]
Hey guys,

thanks for providing the CJ4 data for SimBrief.
Would be nice to get the perfomance file for PFPX, if possible :)

Cheers

**Comment by dga711** [comment]
I think someone in the team was already looking into it.
We will also do one for LNM which is more simple.

**Comment by Jack737800** [comment]
I highly appreciate it ! 

Thanks

**Comment by cwburnett** [comment]
@kaosfere 👍

**Comment by Jack737800** [comment]
In the meantime someone had the time and patient and of course the documents, to create a PFPX file.
It can be found in the following link:
https://flightsim.to/file/5645/cessna-citation-cj4-pfpx-aircraft-performance-file

Maybe worth it to link it somewhere here within the project !?
