### ISSUE TITLE
CJ4: AP don't keep HDG to intercept the route

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#339]
When flying on HDG Mode and press NAV to intercept the route, instead of keep the current heading and arm the NAV Mode until intercept it, the airplane instantly goes to NAV and assumes a weird heading to force intercept the route early.

**Comment by cwburnett** [comment]
Yes, this is an issue with the MSFS autopilot out of our reach. Can potentially be fixed by a custom autopilot in the future.
