### ISSUE TITLE
CJ4: After a DIR TO waypoint, it's reverting to ROLL Mode

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#346]
When you set DIR TO a waypoint on flightplan, after the waypoint, the aircraft reverts to ROLL Mode instead go to the next waypoint in LNV Mode.

**Comment by K20017** [comment]
This is a known issue and something outside of our control as we can't access the AP code.  If you re-engage NAV, everything after will re-sequence just fine until you do another DIR TO.
