### ISSUE TITLE
G1000 screens not loading

### ISSUE THREAD

**Issue by kevfol07** [Working-Title-MSFS-Mods/fspackages#356]
After putting the mod in the community folder and the opening MSFS and starting either a Cessna 172 or a Caravan the screens do not come alive, they are just blank even when starting with the engine running. What am I missing?

**Comment by antonvons** [comment]
Hi @kevfol07, I think we have the same issue. Here is my post
https://github.com/Working-Title-MSFS-Mods/fspackages/issues/366

**Comment by kevfol07** [comment]
Thanks, I did have the G3000 installed, that wasn't working either, removed it but it did not bring back the G1000 screens. When copying to the community folder I get error messages advising some file names are too long. Maybe I will wait until Asobo do more work on the systems.

**Comment by antonvons** [comment]
@kevfol07 I thought I would let you know that the issue was caused by also having the workingtitle-gx-v0.1.0-dev2 mod installed. After downloading and installing gx-v0.1.0-dev1 the issue was solved.

**Comment by kaosfere** [comment]
This should no longer be an issue as long as all three WT avionics mods, if installed, are current.
