### ISSUE TITLE
G1000 airspace and highways missing- only on DA40NGX, only in certain area

### ISSUE THREAD

**Issue by Crocodoc84** [Working-Title-MSFS-Mods/fspackages#360]
![Microsoft Flight Simulator 22 10 2020 19_32_31](https://user-images.githubusercontent.com/68860491/96911809-a5453b00-14a1-11eb-9838-7fc5b12416b1.png)
![Microsoft Flight Simulator 22 10 2020 19_28_05](https://user-images.githubusercontent.com/68860491/96911814-a70efe80-14a1-11eb-86a1-c2074500e61f.png)

Situation: I'm starting a flight in the DA40NGX mod (5.9), at EDLA airport. The G1000 in the DA40 will blank out airspace and highway data in a bigger area around the position. Also the declutter button only seems to work from time to time or at certain zoom levels. 
One time switching through zoom levels, the airspace briefly flickered up, then vanished again- as if another layer is above and blocking it.
The standard C172 or the G36 mod do not show this behavior, there it shows perfectly fine.

I am currently in the process of building a better scenery at EDLA, if that would matter.

Maybe you have an idea here..

**Comment by kaosfere** [comment]
I can't think of any possible thing which would cause this to happen on the DA40 but not any other.   Regardless, this should hopefully be made redundant by the various map and FMC overhauls we are working on, so I'm going to close this as a standalone issue.
