### ISSUE TITLE
Blank screens when WT G3000 installed

### ISSUE THREAD

**Issue by antonvons** [Working-Title-MSFS-Mods/fspackages#366]
Hi, Whenever I install the WT G3000 mod into my community folder (v0.2.0 or 0.2.1) all planes with either a G1000 or G3000 load with blank screens. As soon as I delete the G3000 mod all planes load with their displays (PFD/MFD) working.

When I saw the change list for ver 0.2.1 I thought this would be fixed but alas no.

Attached are screen shots of with and without the G3000 mod. Screenshot with the displays working is without the G3000 mod

![2020-10-23 11-31-21 cc1](https://user-images.githubusercontent.com/67151436/96945720-36f88b00-152a-11eb-9295-63a365741faf.JPG)
![2020-10-23 11-19-52 cc1](https://user-images.githubusercontent.com/67151436/96945729-3bbd3f00-152a-11eb-91db-e189a53a9596.JPG)

#G1000 
#G3000

**Comment by cywang90** [comment]
What other mods are you using?

**Comment by antonvons** [comment]
Hi. I will add the contents of my community folder below. Aside from that I
have pushback helper, LittleNavMap and remote Virtual Cockpit.

...............

2020-10-23 Full Community folder list

0-workingtitle-g1000
01 JD MOD Cessna 208B EX v4.5
5NM
40I
787-livery-Lufthansa
aircraft-tbm930-improvement
ARNZ-NZDN-Dunedin
asobo-aircraft-a320-neo-liveries
au-esdailesoft-three_sisters
au-mel-aamipark
au-mel-Albert Park Pit Lane
au-mel-apcarouselcafe
au-mel-apmsac
au-mel-apsoccer
au-mel-apthepark
au-melbournecricketground
au-mel-marvelstadium
au-mel-southernstar
au-sa-adelaideoval
au-sydneyharbourbridge
au-sydneytower
AYYZ
Beechcraft Bonanza G36 Basic Blue Red
Beechcraft Bonanza G36 Flipper
bergenfix
BGBW
BGCO
bonanza-livery-BLKX
bonanza-livery-BLUX
bonanza-livery-BRGX
bonanza-livery-CRMX
bonanza-livery-GRNX
bonanza-livery-PURX
bonanza-livery-REDX
bonanza-livery-YELX
br-rioantirio2-nikprist
CAR2
CBY2
CQRA
croixdunivolet
CYAS
CYAY
CYBA-Banff-Airport-rory-mc-alduff
DA40-NGX
DA62X
Diamond DA62-livery-pack
EDAY
EDEN
EDLP-aerosoft-paderborn
EDXQ
EG13
EG48
EGCA
EGDF
EGIC
EHEH
ENSD-Sandane-Norway-anda-aw
EPBA
EPKP
EPNS-EPKU-EPKQ
fr-stadedefrance
FSIA
fsimstudios-cylw-kelownainternational
fsimstudioskelowna-aerial
godzilla
icelandwaterheightfix
jordanjames94-yapo
jordanjames94-yara
jordanjames94-ybdg
jordanjames94-ybgr
jordanjames94-yblt
jordanjames94-ybrs
jordanjames94-ybss
jordanjames94-ycde
jordanjames94-ycem
jordanjames94-ydrn
jordanjames94-yech
jordanjames94-ykyb
jordanjames94-yled
jordanjames94-yleg
jordanjames94-ylil
jordanjames94-yltv
jordanjames94-ymmb
jordanjames94-ymng
jordanjames94-yola
jordanjames94-ypbh
jordanjames94-ysht
jordanjames94-ytya
jordanjames94-ywbl
KASH Nashua-nh-flyingscool
KCFD-bsdesigns
KEMT-vtolaviation
KHF
KHHR-assets-vtolaviation
KHHR-vtolaviation
KJAC-justokayscenery
kmry-captainvtol
KNZY
liveries-a5
liveries-c172-as1000
liveries-cessna208b
liveries-da40ng
liveries-da62
liveries-kingair
liveries-tbm930
liveries-xcub
LJAJ
LSPU
missouririverfix
MKO
navigraph-navdata
nimes
nl-tbm930-liveries
Notification_Tips
NoToolbarHandle
NZ_AUS_MFS2020_Discord - NZNR & Napier Scenery 1.8
NZA-Discord_Auckland-AucklandHarbourBridge
NZA-Discord_Auckland-AucklandMuseum
NZA-Discord_Auckland-CBD01
NZA-Discord_Auckland-CBD02
NZA-Discord_Auckland-CBD03
NZA-Discord_Auckland-CBD04
NZA-Discord_Auckland-CBD05
NZA-Discord_Auckland-CBD06
NZA-Discord_Auckland-CBD07
NZA-Discord_Auckland-CBD08
NZA-Discord_Auckland-CBD09
NZA-Discord_Auckland-CBD10
NZA-Discord_Auckland-CBD11
NZA-Discord_Auckland-CBD12
NZA-Discord_Auckland-CBD13
NZA-Discord_Auckland-CBD14
NZA-Discord_Auckland-CBD15
NZA-Discord_Auckland-CBD16
NZA-Discord_Auckland-CBD17
NZA-Discord_Auckland-CBD18
NZA-Discord_Auckland-CBD19
NZA-Discord_Auckland-CBD20
NZA-Discord_Auckland-CBD21
NZA-Discord_Auckland-CBD22
NZA-Discord_Auckland-CBD23
NZA-Discord_Auckland-CBD24
NZA-Discord_Auckland-CBD25
NZA-Discord_Auckland-CBD26
NZA-Discord_Auckland-CBD27
NZA-Discord_Auckland-CBD28
NZA-Discord_Auckland-CBD29
NZA-Discord_Auckland-CBDSkyTower
NZA-Discord_Auckland-EdenPark
NZA-Discord_Auckland-Port01
NZA-Discord_Auckland-Port02
NZA-Discord_Auckland-SparkArena
NZA-Discord_NZOU_Oamaru-Scenery-Pack-1.0
nz-aucklandharbourbridge
nz-aucklandskytower
NZME
NZTL tekapo
OG20
orbx-airport-kbce-bryce-canyon
orbx-airport-ksba-santa-barbara
orbx-airport-lowg-graz
orbx-airport-lowi-innsbruck
orbx-airport-og20-fairways
orbx-cityscape-sydney
PAUN
PAVD
pertharena
PHP-NoTooltips-Fix
pl-drzewieckidesign-warsawcity
SDUN
SDYL
SIXE
SSCF
SSGV
treeheightfix
tromac-ftden-au
u60-u60
UHML
uk-blackpooltower
UK-eget-tingwall1.1-superspud
UK-egpw-unst1.1-superspud
UK-fea-fetlar1.1-superspud
UK-scenery-shetland1.2-superspud
UK-scenery-stonehenge
ulmmuenster
us-alaskawaterheightfix
us-mo-river-terrain-slibit-scenery
US-mountrushmore
US-talkeetna-area-pack-julysfire-airports
verticalsim-kittyhawk-first-flight
VL-3-rotax915
whales
WOL
woodwardhall
workingtitle-aircraft-cj4
WV08
XCUB PERFORMANCE+ v1.6.6
ymmb-moor
z-bonanza-g36-improvement-project
credits.txt
Notification_Tips.css
...

**Comment by cywang90** [comment]
That's quite the list. I suggest moving all other mods out of the Community folder and testing with just the g3000 mod to see if you still have the issue. If it is a compatibility issue, I would then start adding mods back in a few at a time to see which one is causing the issue (it's probably not a scenery mod, so I would not start with those).

**Comment by raxx-rexxor** [comment]
Hi, I have the same problem, but I also get an error message when I copy the folder into the community folder: The path and file name is to long for the target folder. When I click cancel, I have a 11.7MB folder and the original unzipped folder is 12.2MB. For me this led to black G3000 screens in my TBM. Not sure if this is of any help.

**Comment by antonvons** [comment]
Good news. I have tracked down my issue. It was either a corrupt file or the extraction process. 

Here is my test procedure

1. I cleared out my Community folder totally and ran MFS and loaded the TBM. Spawning to a test runway with everything running, the G3000 was on.

2. I placed my folder copy of G3000 into the Community and repeated step 1. The G3000 was blank. I deleted my copy and downloaded a new copy.

3. Upzipped this time in a spare drive (where I had the .zip file and copied the Workingtitle-3000 folder to my community folder and re-ran step 1.  This time the G3000 was running. Solved.

4. To further reassure myself, I re-downloaded the G1000 and installed this the same way along with a few other Mods and all is well.

Worth noting that there was a different file size with the downloaded G3000 folders when either unzipped directly into my Community folder or on a spare drive. This seems to be important and I think I have seen this mentioned elsewhere.

![2020-10-24 16-38-36 cc1](https://user-images.githubusercontent.com/67151436/97069643-4efd0700-161d-11eb-8a04-9b99df52c453.JPG)
 
And here is the result after step 4.

![2020-10-24 17-02-33 cc1](https://user-images.githubusercontent.com/67151436/97069662-6dfb9900-161d-11eb-8961-79fac3818143.JPG)

Thank you again for your great work..

Cheers Anton.

**Comment by antonvons** [comment]
Footnote. After putting all my Community files back, I again found that I had blank G1000 or G3000 displays. Some six hours later I tracked the issue down to the working title gx-v0.1.0-dev2.

I solved this by downloading and installing gx-v0.1.0-dev1.

I hope this may help someone else.
