### ISSUE TITLE
CJ4-Yaw damper/landing gear warning

### ISSUE THREAD

**Issue by musurca** [Working-Title-MSFS-Mods/fspackages#38]
The yaw damper doesn't work, and the landing gear warning goes off prematurely. This thread details both problems and also provides fixes:

https://forums.flightsimulator.com/t/citation-cj4-yaw-damper-gear-warning-fixes/272098

(copied from previous repo)

**Comment by musurca** [comment]
(if it's helpful, I can submit a PR containing both these and Uwa's CJ4 light mod.)

**Comment by dga711** [comment]
@musurca Would be very appreciated if you could PR it, thanks.

**Comment by cwburnett** [comment]
Yup, @musurca please PR that change - let us know if you need guidance on where to do it. You can branch off main for this.
