### ISSUE TITLE
[G3000 v0.2.1] MSFS Freeze Upon Scrolling Flightplan

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#382]
In certain situations MSFS completely freezes without error message upon scrolling down the flight plan waypoints to destination airport.

A fix has been created by a MSFS Forum user at https://forums.flightsimulator.com/t/tbm930-mfd-game-freezes/283948/59.

It would be very useful if this fix could be integrated to your G3000 mod subject to his approval.

**Comment by mrmoorey** [comment]
I've provided a newer version of my TBM-930 fixes. You can also find them here [here]
(https://flightsim.to/file/2195/fix-tbm-930-mfd-freeze-when-scrolling-down-in-the-flight-plan). I've commented the code to explain where I've changed it relative to the original Asobo file. I also think there's significant inefficiency in the original code, where the onUpdate() method is causing excessive redraws for no good reason.

[NavSystemTouch.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5455116/NavSystemTouch.zip)
