### ISSUE TITLE
G1000 freezing after pressing FPL or DRT on either PFD

### ISSUE THREAD

**Issue by Lobster148** [Working-Title-MSFS-Mods/fspackages#387]
The G1000 freezes after pressing FPL, resulting in no engine details or frozen PFD

**Comment by cjflyswmu** [comment]
I can second this. Was flying the G36 last night and witnessed this behavior. In my case, the PDF froze after pressing the direct key on the PFD. I like to have my initial approach fix up in the PFD lower right direct window for top of descent calculation purposes. I started playing around with the buttons and found that I could unfreeze the PFD by pressing the menu key with the direct window open, selecting the "Cancel Direct-to" option and pressing enter. I found that if I cycled through this process a few times the PFD would unfreeze eventually.

**Comment by geka79** [comment]
I had the same trouble. The same workaround 👍

**Comment by kaosfere** [comment]
@geka79  Does that mean that this is sill an active issue with the current sim version and G1000 v0.3.2?

**Comment by geka79** [comment]
G1000 0.3.2
Fs: the actual latest patch

**Comment by Paikanx** [comment]
I juste experienced this bug few minutes ago after going to "direct to" menu. Workaround doesn't work for me.
(last version of FS and G1000 v0.3.2)

**Comment by RichardHancock** [comment]
Same issue in a C172, will try that workaround next time.
