### ISSUE TITLE
CJ4 Unable to set arrival to KSFO

### ISSUE THREAD

**Issue by theRealPDXMike** [Working-Title-MSFS-Mods/fspackages#388]
Occurs with v0.6.0 also with 0.5.1. 

Tried to import a flight plan from SimBrief KPDX/KSFO. on loading the plan legs looked good until last fix before KSFO, then it went direct back to KPDX.  Just tried with KPDX/KSEA and KPDX/KSJC they work as expected. 

Also went to FPLN page, and tried to CLR the arrival (KPDX in first example) no go. Then tried to enter KSFO from scratch pag and enter as DEST also no go.  I am able to enter other (KSEA, KSJC,KOAK) as DEST from scratch pad.

**Comment by dga711** [comment]
KSFO is bugged in Asobo data since 1.9.3 as far a i know

**Comment by mattnischan** [comment]
@theRealPDXMike

This is a known issue in MSFS 1.9.5 with a few airports. Unfortunately, they broke the nav data with Premium for a couple airports, of which SFO is a victim. You will find you will be unable to add it in any aircraft at the moment.

There's a big MSFS forum thread on it, so hopefully Asobo is aware of their issue.
