### ISSUE TITLE
Passengers Cabin lights always "on"

### ISSUE THREAD

**Issue by telemakox** [Working-Title-MSFS-Mods/fspackages#389]
I noticed that from version 5.0 to version 6.0 it is no longer possible to manage the passenger cabin lights from the FMC, which always remain "on" each time the program is restarted. The problem seems to be an interference with the avionics switch  device. I changed the following lines   of the system.cfg,  by putting the parameter 10 instead 28, this seems to fix in part the issue:
 
 #cabin
lightdef.31 = Type: 13 # Index: 0 # LocalPosition: 6.5,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.32 = Type: 13 # Index: 0 # LocalPosition: 3.6,0,2.72 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.33 = Type: 13 # Index: 0 # LocalPosition: 0.5,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.34 = Type: 13 # Index: 0 # LocalPosition: -3,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10

However, this modification does not allow the management of the passenger cabin lights from the FMC in any case.
Any suggestions to fix it? Thx

**Comment by dga711** [comment]
The cabin lights settings is not persistent across flights. Is it that what you want?

**Comment by telemakox** [comment]
At night, the cockpit of the Cessan Cj4 is no longer illuminated by the spot light, when it is cold and dark in the parking lot, because the passenger cabin lights are always "on" in the FMC. It is possible that it is no longer possible to restart with the cold and dark cockpit with the lights "off", but I don't understand why.

**Comment by dga711** [comment]
I think you are mixing up a few things here
1. Yes the passenger cabin lights are always on at the start, as it is not tied to battery or something yet.
2. The passenger cabin light settings is not persistent across flights now. I may work that in.
3. When cold and dark the cockpit flashllight does not come on automatically anymore. And we don't know yet, why that is. But you can turn it on using the Keys ALT + L

**Comment by telemakox** [comment]
Thx for your kind answer!

**Comment by telemakox** [comment]
So I ask you if it will be possible to start from an initial state, with the passenger cabin lights always "off" and then switch "on" them from the FMC, after having activated the battery and avionics toggle.

**Comment by dga711** [comment]
@telemakox That is something on the list I will be working on
