### ISSUE TITLE
CJ4 Engines won't start from cold and dark

### ISSUE THREAD

**Issue by crowmium** [Working-Title-MSFS-Mods/fspackages#391]
The Engine Run/Stop buttons default to "RUN" from cold and dark now and pressing them does not allow for the engines to start up.

**Comment by mattnischan** [comment]
@crowmium - I have not seen this issue. Do you have other aircraft mods installed? If so, does the issue happen with just the CJ4 mod installed and no other mods?

**Comment by K20017** [comment]
I think this was one of those issues where the library pack was messing it up because for some reason, there's a change in the panel.xml and it wasn't separated.

**Comment by crowmium** [comment]
Ah, I can try removing the livery pack if needed. Later on I can test removing everything, but I currently use:

WT G1000 Mod
WT CJ4 Mod
FBW A320 Mod
Livery Pack
Unreal Weather

**Comment by crowmium** [comment]
I just tried removing all mods other than the CJ4 and still had the same bug.
Also tried changing airports, parking locations, DEP/ARR airports, time of day, and weather. Same bug.

**Comment by K20017** [comment]
Ahh. I think I remember now. Are you using an Xbox controller?  Sometimes it autobinds the mixture control and when the game loads, the game somehow detects that mixture bind and won't let it start.

**Comment by crowmium** [comment]
I have an Xbox controller it is not plugged in. I've also had it prior to 0.5.1 and never had this issue previously (I think I've used the mod since 0.2.0 or 0.3.0).

**Comment by K20017** [comment]
I don't know the exact bind or if it's an axis buy to double check, type "mixture" into the search bar in controls and see what is bound. Try and unbind and see if it still does it.

**Comment by K20017** [comment]
If I recall, the last guy who had this, the issues was his xbox controller had a mixture setting bound somewhere and Asobo somehow has mixture setting connected to the jet so it seems the mixture in the cutoff position and it doesn't allow the jet engine to run.

**Comment by crowmium** [comment]
That seems to be it, though I didn't take the time to determine exactly which bind, but I unbound every USB device with a mixture keybind and it is fixed. I suspect it was the axis though.

**Comment by K20017** [comment]
Ok sweet.

**Comment by K20017** [comment]
Post it here if you determine which one it was

**Comment by crowmium** [comment]
Will do.

**Comment by crowmium** [comment]
It was the mixture axis bound to a Virpil CM-2 Throttle quadrant.
