### ISSUE TITLE
CJ4 Navigraph compatibility with FMS; KGRR to KMDW example

### ISSUE THREAD

**Issue by Pickafivestring** [Working-Title-MSFS-Mods/fspackages#392]
One of my test flights for any FMS is KGRR to KMDW because it's pretty straight forward.  No SID and a simple STAR.

Route: AZO BAGEL PANGG3.  HILLS transition for RWY 31C.

Issue:  When PANGG3 is selected as the STAR, the approaches for 31C and 13C are not selectable.  

How to reproduce:
--Set up KGRR to KMDW in the PERF INIT using RWY 26L at KGRR.
--Insert DIRECT to AZO on route page.
--Use DEP/ARR to go to KMDW arrival page.
--Select PANGG3 and watch 31C and 13C approaches disappear.
--Unselect PANGG3 and 31C/13C reappear.
--Select ILS 31 and watch STARS disappear.

**Comment by Pickafivestring** [comment]
If it makes a difference, I'd like to add that I see the bug where the FMS doesn't accept the destination airport the first time, has to be cleared, then entered again.  Just did a flight from KMDW to KMSP with a KILRR3 arrival and all went well flight plan wise.  The KMSP KILRR3 arrival is one of my test routes...it's very tough on FMS logic, and the CJ4 passed this one easily.  For some reason, the GRR to MDW route is causing the FMS to stumble.

**Comment by dga711** [comment]
Thank you for the feedback. We are looking into the missing approaches right now. 
Also noticed the bug with the destination, will look into that too.
