### ISSUE TITLE
G1000 and G3000 Blank Screens

### ISSUE THREAD

**Issue by antonvons** [Working-Title-MSFS-Mods/fspackages#400]
After some updates I found that I had blank G1000 or G3000 displays. Some six hours later I tracked the issue down to the working title gx-v0.1.0-dev2.

I solved this by downloading and installing gx-v0.1.0-dev1.

I hope this helps the Devs become aware of the issue and that it may help someone else.

**Comment by kaosfere** [comment]
dev3 will have corrected these problems  -- can you let us know if you are still seeing this with the latest versions of everything?
