### ISSUE TITLE
CJ4: flightPlannerManager fail (something to do with runways and approaches)

### ISSUE THREAD

**Issue by panourgue** [Working-Title-MSFS-Mods/fspackages#408]
Did not investigate. 
Arrival page. Select STAR, do not select approach, select runway. Throws and error and gets stuck on "WORKING...". On various airports both with stock and navigraph data. Something to do with filtering approaches/runways maybe?

[Here is a video](https://streamable.com/dhof3b)

and a snapshot:
![err](https://user-images.githubusercontent.com/20702234/97096022-16861900-166f-11eb-8ec4-2de812a5130c.png)

**Comment by tscharlii** [comment]
Fixed by 429f488b7694bfedb8b9bf50e6623ff14cbda563
