### ISSUE TITLE
CJ4: Bearing pointer not pointing to fix

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#411]
![noley](https://user-images.githubusercontent.com/73390710/97098172-4eca2f00-1650-11eb-81da-5daa8620cdb0.PNG)

**Comment by dihedral977** [comment]
I failed to mention that the needle DID correctly point to NOLEY after I made the right turn to intercept LOC.

**Comment by cwburnett** [comment]
My guess is that the bearing pointer on FMS actually points to the desired track, which is the magenta line to your left.
That said there's some odd stuff going on in that picture... we'll have a look.

**Comment by cwburnett** [comment]
@K20017 should bearing pointers work for GPS waypoints or do they only work for navaids? Do they point to the actual waypoint or would they point to where the plane wants to be on the current leg?
