### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by threeGreen** [Working-Title-MSFS-Mods/fspackages#413]
Sorry for such a noob question, but since the mods were put together into "Working Title MSFS Mods" i dont know how to install them into the Community Folder. Do i need to download the "original" mods "CJ4", "G1000" and "G3000" and replace their files with updated files from "fspackages"? But what to do with "sound", "fonts", "tools" folders within the "src" folder of this package?

If this is the wrong place to ask please excuse, i don't mind to get this deleted, i would appreciate though if someone could help me 

Another thing i am unsure about regarding mod installation is if i have to rename the files inside the Community Folder since i have read they get loaded in alphabetical order.

**Comment by mattnischan** [comment]
@threeGreen I believe you downloaded the wrong zip. There are a few zips attached to each release: you want the one without 'src' in it.

**Comment by threeGreen** [comment]
@mattnischan omg, thank you so much!
