### ISSUE TITLE
G3000 - Destination Path Too Long

### ISSUE THREAD

**Issue by arunhn** [Working-Title-MSFS-Mods/fspackages#416]
I am getting a file path too long error when copying the g3000 folder to community folder.  I have the Microsoft Store version of MSFS.

![Screenshot 2020-10-25 141922](https://user-images.githubusercontent.com/52678666/97116740-2b919500-16cd-11eb-8c10-9fbc4338804f.png)

**Comment by arunhn** [comment]
I got around this issue by mapping a drive letter to the MS Community folder and then using XCOPY to copy files from my unzipped location to the community folder.  See commands below in PowerShell:

PS C:\WINDOWS\system32> subst P: "F:\WpSystem\S-1-5-21-1259906700-46895465-488108196-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community"

PS P:\> xcopy "F:\MSFS 2020\workingtitle-g3000-v0.2.1\workingtitle-g3000" P: /E /H /O

**Comment by slip664** [comment]
This isn't an issue with the mod, it's an issue with your insanely long directory names.

**Comment by cywang90** [comment]
This is a windows issue. You can disable the file path length limit: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

Closing this issue.

**Comment by arunhn** [comment]
> This isn't an issue with the mod, it's an issue with your insanely long directory names.

Apparently I am not the only one with this issue.  This can happen to anyone who installs MSFS in a separate drive and the resolution is here:
https://www.avsim.com/forums/topic/583628-installation-path-too-long/?do=findComment&comment=4339519

**Comment by arunhn** [comment]
Apparently I am not the only one with this issue. This can happen to anyone who installs MSFS in a separate drive and the resolution is here:
https://www.avsim.com/forums/topic/583628-installation-path-too-long/?do=findComment&comment=4339519

**Comment by J-Hoskin** [comment]
A solution was already posted above but more can't hurt :)
