### ISSUE TITLE
Obstacle symbol remains persistent and oversized

### ISSUE THREAD

**Issue by lcappuccio** [Working-Title-MSFS-Mods/fspackages#419]
When I load any plane that uses G1000 in the Seattle area (KOLM, KTIW, KORS, 1S2 and others) the obstacle symbol stays sticky on the MFD display.
It will change color to yellow and gray after the altitude is clear but the symbol will remain persistent on the screen and with an oversized picture.
It happens with any airplane that uses G1000 and also with all sceneries in the area uninstalled.

![1f17f0b5e74c4dd8254ec7fb359e73e1fbd5f61f](https://user-images.githubusercontent.com/9638971/97169842-06635c00-178b-11eb-8974-6805ac2afc7e.jpeg)

**Comment by cywang90** [comment]
Make sure you have the latest version of the g3000 (0.2.1) and gx (0.1.0-dev2) mods installed, if you have them.

**Comment by lcappuccio** [comment]
Thanks for getting back. I have the latest CJ4 (0.6), g3000 (0.2.1) and g1000 (0.3.1), no GX though.

**Comment by lcappuccio** [comment]
fixed by adding the GX dev package to my community, thanks for the help.
