### ISSUE TITLE
CJ4 - PFD Airspeed and altitude window issue

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#420]
"Mask" around values allows view of values above and below to be shown. 
![ias](https://user-images.githubusercontent.com/73390710/97174140-0e5dd480-1768-11eb-88bc-7f9660478e3f.PNG)
![win](https://user-images.githubusercontent.com/73390710/97174145-10c02e80-1768-11eb-9c2e-2ed54accd2ce.PNG)
![alt](https://user-images.githubusercontent.com/73390710/97174150-11f15b80-1768-11eb-9b47-7a2eb2716a9a.PNG)

**Comment by J-Hoskin** [comment]
Hmmm, nice pickup. Thanks for bringing it to our attention.

**Comment by dihedral977** [comment]
Great mod. Thanks for putting it together.

**Comment by cwburnett** [comment]
Closing for https://github.com/Working-Title-MSFS-Mods/fspackages/issues/326

**Comment by dihedral977** [comment]
Still present in 0.6.5. 
![mask](https://user-images.githubusercontent.com/73390710/97767231-3a26e480-1af1-11eb-9b40-3301ebd5a932.PNG)
