### ISSUE TITLE
MSFS App Inadvertently Closed

### ISSUE THREAD

**Issue by glaurian** [Working-Title-MSFS-Mods/fspackages#421]
Just completed a short flight to KEWR (Newark). Landed fine, all functions seemed to work GREAT, then while taxing and cleaning up, the app imploded.

Last steps were:
-retracted flaps
-was looking for SVT to show taxi centerline, found it and enabled
-disabled YD
-disabled APP

As soon as I pressed APP, the app closed.

Upon checking my logbook, it did book the flight.

Please let me know if there is any other info I can provide, you guys are doing a great job!

**Comment by glaurian** [comment]
One other note, I do not have any other mods active, only the stock FS.

**Comment by cwburnett** [comment]
I don't think there is anything we can do regarding a simulator crash, but if you find it is repeatable always with the same button or action with the mod, please let us know. The APPR button is not currently part of our codeset, it is the default code so likely a vanilla sim issue

**Comment by glaurian** [comment]
I didn't think it would be related but wanted to report just in case there was a pattern.

Great mod.

Thanks

Sent from my Verizon Wireless 4G LTE Droid

________________________________
