### ISSUE TITLE
CJ4: Trying to solve a issue with custom Liveries

### ISSUE THREAD

**Issue by Danice737** [Working-Title-MSFS-Mods/fspackages#422]
Does this mod a custom folder structure containing some of the cockpit textures? 

everything works with my livery installed except the gear lights are white. I want to add a fallback directory. (it works fine with a stock CJ4)
![image](https://user-images.githubusercontent.com/73177937/97201558-97810580-1780-11eb-8a64-3d6150cf005c.png)

**Comment by dga711** [comment]
Does one of the liveries override the texture CJ4_COCKPIT_DECAL_*.TIF.DDS ?

We are not modifying any textures or model stuff yet. Only ModelBehavior XMLs.

**Comment by Danice737** [comment]
No only the 3 textures Fuselage, engine, and livery color.. Livery works without working title installed and textures work if I just drop my them into the official folder with working title. I think It has something to do with the fallback directory I'm gonna remove each fallback dir one at a time from the texture.cfg until it happens in the stock hopefully narrow down where  the issue is.

[fltsim]

fallback.1=..\..\Asobo_CJ4\texture
fallback.2=..\..\..\..\texture\Lights
fallback.3=..\..\..\..\texture\DetailMap
fallback.4=..\..\..\..\texture\AudioPanel
fallback.5=..\..\..\..\texture\Glass
fallback.6=..\texture

**Comment by Danice737** [comment]
Looks like this was a missing . in the fallback texture line (Not sure why it only effected the livery when Workingtitle was in)
