### ISSUE TITLE
CJ4: Runway Transition being removed erroneously in some cases 

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#423]
See https://www.avsim.com/forums/topic/587647-to-asobo-if-you-are-still-reading/page/8/#comments

ENGM RIPA4M arrival for 19R drops waypoints after GM428 when a runway/approach is selected, otherwise the entire proc to BAVAD remains.

Either (a) it's the sim skipping some waypoints or
(b) it's an index mismatch on the arrival runway transition index because this arrival has no runway transitions? But perhaps everything after GM428 is coded as a runway transition, but isn't being matched/mapped.

**Comment by August78** [comment]
Tracking this issue

**Comment by August78** [comment]
Oh, and I can mention that this happens with and without Navigraph beta installed.

**Comment by cwburnett** [comment]
We'll have to look at the raw data for the arrival procedure to know for sure. I'll post it here when we pull it.

**Comment by kutak11** [comment]
this issue is also in G3000... Star waypoints are lost after Approach Load if there are more than 1 point remaining before app procedure (IAF).

**Comment by cwburnett** [comment]
Pending FPM

**Comment by August78** [comment]
@cwburnett Is there any update on this issue?

**Comment by cwburnett** [comment]
Maybe a couple more weeks until there's a beta for the new FPM in the CJ4, then it would come to the other planes after that...

**Comment by dga711** [comment]
@cwburnett this good in coming update? please close, if so and add milestone

**Comment by cwburnett** [comment]
This is resolved with the latest update.
