### ISSUE TITLE
G1000/3000: Airspace borders on MFD not displayed

### ISSUE THREAD

**Issue by kutak11** [Working-Title-MSFS-Mods/fspackages#425]
I have noticed some FPS impact with "cities" on MFD and somehow I also managed to hide "Airspaces" in G3000 using map settings... now its not possible to show these airspace lines again.. I tried everything but airspaces are gone on MFD.

**Comment by kutak11** [comment]
I found Airspaces are also not in VFR MAP window when fly with G3000 aircraft. When load other it is there,,,

**Comment by Jovian657** [comment]
I have also found that the MFD airspace toggle is inop using the WT G3000 v0.3.2 in the TBM 930 with MSFS Update 6 version 1.10.11.0 The green indicator light turns on and off when I click the airspace button but no airspaces appear in the MFD moving map display.  I removed the add on from the community folder and found that airspaces also do not appear when using the stock G3000 in the TBM 930. I was able to toggle airspaces in WT G3000 v0.2.2 in the TBM 930 prior to Update 6.

**Comment by Jovian657** [comment]
I removed WT G3000 v0.3.2 from community folder, repaired MSFS using Win10 Pro, started flight in TBM, and found that airspaces reappeared in stock G3000.  Restarted pc, added WT G3000 v0.3.2. back into community folder, started flight in TBM, and found that airspaces still do not appear when toggling MFD airspace button on and off.

**Comment by cywang90** [comment]
Just tested and airspaces are working as intended. Sometimes airspaces may not draw because the game has issues loading the correct airspaces for the current map view. However, this is not something we can currently fix.
