### ISSUE TITLE
CJ4 Request - VS / FLC change over 

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#427]
I know there's work being done to solve the wrong FLC behavior. In addition, I would like to request that during change over from FLC to VS that the VS engage at the current vertical rate not at the last rate that was set which is what's happening currently.

**Comment by dga711** [comment]
@K20017 is that a thing in the real one?

**Comment by dihedral977** [comment]
No idea but I know other rw a/c will do that. Makes sense - by having the feature, there is no vertical "spike" while the pilots is readjusting the VS.

**Comment by K20017** [comment]
I will have to look it up.

**Comment by mattnischan** [comment]
![image](https://user-images.githubusercontent.com/1650544/97301650-049aa680-1826-11eb-94ca-bc10f3fb715b.png)

**Comment by cwburnett** [comment]
@J-Hoskin I will research what works to set an actual VS value and then we can add the code to fire when VS mode is engaged. If it can be a simvar then we can do this in XML, otherwise we'll add it to VNAV JS code.

**Comment by dga711** [comment]
Will look into it via #542
