### ISSUE TITLE
CJ4 Request - How to handle duplicate waypoints in FMS

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#428]
I have no idea if the RW FMS is capable or if the WT team is capable of working on this with the tools at hand. When presented with duplicate waypoints we are asked to pick which one is needed and relevant. Some are obvious (airport vs. VOR) and they all have LAT/LONG values. But, some FMS's will sort by relative distance to present position, closest waypoint on top of the list. This is very convenient and would be a great feature if it can be done.

**Comment by dga711** [comment]
We already talked about that and will probably do that at some point

**Comment by J-Hoskin** [comment]
I fully support this. I think its a must. Never know which option to select.

**Comment by K20017** [comment]
The real unit, from what I can remember, doesn't have all these crazy options for selecting.  It would never suggest an airport if you put in a VOR fix with the same letters and I don't think it would give you the option to select fixes that are 1000s of miles away with the same name.

**Comment by Danice737** [comment]
![image](https://user-images.githubusercontent.com/73177937/97318473-e8086980-1839-11eb-8798-4f58557e5bb0.png)

Bottom duplicate is in Africa (4000nm), and top is near Atlanta. What really helps is if we can figure out how to display the ICAO Region Code with the duplicates.

**Comment by Danice737** [comment]
Normally if there is only one listing W Longitude I go with it (Fly 95% of the time in the US) or it takes a extra step to look up on Navigraph or you can use https://www.airnav.com/navaids/ (I hope we can fix I hate the extra steps)

**Comment by mattnischan** [comment]
The MSFS ICAO actually includes the region code in it: the FS ICAOs for those would be something like `VK7    GAD  ` and `VHL    GAD  `

**Comment by Danice737** [comment]
So is there a way to get the MSFS ICAO to display on the list of choices?

![image](https://user-images.githubusercontent.com/73177937/97330617-71be3400-1846-11eb-8842-854c9978a8d2.png)

**Comment by dga711** [comment]
I wouldn't show full fs icao
Sort by distance and sanity check filter (too far away etc) sounds the most fitting to me.

**Comment by Danice737** [comment]
Added a Pull that will display the 2 letter ICAO Region next to the NDB or VOR in the     #430

**Comment by Danice737** [comment]
![image](https://user-images.githubusercontent.com/73177937/97347726-30844f00-185b-11eb-8bc0-962ac032ab3e.png)

**Comment by cwburnett** [comment]
How about that?
![image](https://user-images.githubusercontent.com/70416619/97355822-19def780-185d-11eb-877d-cc7708467491.png)

sorted by distance from present position

**Comment by Danice737** [comment]
nice
