### ISSUE TITLE
CJ4 HDG bug not appearing in NAV mode

### ISSUE THREAD

**Issue by slip664** [Working-Title-MSFS-Mods/fspackages#431]
The cyan heading bug on the PFD in both ARC and ROSE mode does not show up when the nav source is anything other than FMS (ignore the bad flying).

![Screenshot (26)](https://user-images.githubusercontent.com/72432870/97360994-2dd62980-185c-11eb-81ca-659ab48febc3.png)

**Comment by dga711** [comment]
Asobo runs some conditions for that in BaseNDCompass starting line 324
![image](https://user-images.githubusercontent.com/2995606/97436046-a652ee00-1921-11eb-9928-d01908dfb5ca.png)

So we have to think about modifying that
