### ISSUE TITLE
CJ4: Inputting invalid data into RSK under FPLN clears waypoints

### ISSUE THREAD

**Issue by slip664** [Working-Title-MSFS-Mods/fspackages#433]
When building a flightplan under the FPLN menu, I: 
-selected the Departure and Destination airports (KLIT, KBVU)
-enter first waypoint, LIT (RSK)
-entered airway on VIA page 2, J14 (LSK)
-entered endpoint, IRW (RSK)
-entered next waypoint, FTI (RSK)
-accidentally entered airway J76 in TO (RSK)
-FMS spit out INVALID and cleared all previous waypoints.

I did **NOT** hit EXEC after any of those inputs. My plan was to do it at the end when it was all built so that may have something to do with why they all cleared. Not sure how the logic works on the real aircraft, if someone can verify.

**Comment by K20017** [comment]
It should not have deleted everything. We will look into this bug.

**Comment by dga711** [comment]
It seems to jump out of the temporary flight plan and therefore not taking the flight plan with it.
Will debug and fix.
