### ISSUE TITLE
CJ4: The whole FMS in undocked window

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#440]
I've been trying to figure out how to accomplish this but without any luck. Having a couple of touchscreens I would love to be able to "undock" the whole FMS and not just the display. I've been thinking that since this is basically just a HTML page it shouldn't be that hard to make the window bigger, add a 2D image of the FMS as a background and make it "touchable" just like the G3000 in the TBM. Maybe the wizards working with this mod can make it happen :-)

Note: If you have an idea on how to pull this of but don't have the time to do it please send me a message on Discord (ZenIT_SWE#2900), I'd be more than happy to get my hands dirty.

**Comment by J-Hoskin** [comment]
If I understand you correctly, we already do this for debugging in a sense. @dga711 work can be seen here:
https://github.com/dga711/msfs-webui-devkit

Is this what you mean?

**Comment by dga711** [comment]
@AndersHogqvist wants the keypad too. This is not the case right now.
While interesting, right now I would not know how to and dont really have the time to investigate this. Sorry.

**Comment by mattnischan** [comment]
This is unfortunately impossible for now.

The view you see when undocking the FMC with alt+click is actually the same exact texture that gets sent to the cockpit model. In other words, if we draw on the popout, we'd also be drawing in the cockpit. So the FMC buttons and such would show on the FMC screen itself.

Additionally, on top of being the same instance, there is no way to detect if the instrument has been popped out.
