### ISSUE TITLE
CJ4: "SELECT WPT" fails to show next page

### ISSUE THREAD

**Issue by panourgue** [Working-Title-MSFS-Mods/fspackages#442]
If there are multiple pages for a waypoint and you click "next" [fmc loses it :))](https://streamable.com/lck018) 👀
Navigraph. Did not test on vanilla.

**Comment by cwburnett** [comment]
@panourgue was this on the PR or on 0.6.0? And what waypoint did you find with more than 3 duplicates?

Thanks!

**Comment by panourgue** [comment]
It for whatever in main right now. Two letter ones, like "la" — there are tons of them :)
