### ISSUE TITLE
CJ4 - "Premature" Overspeed Warning 

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#443]
I've had a few of these but never documented the situ or details. See attached for conditions. 
![overspeed](https://user-images.githubusercontent.com/73390710/97424283-ddf07480-18e6-11eb-8179-bca19d31f243.PNG)
![gs](https://user-images.githubusercontent.com/73390710/97424291-e2b52880-18e6-11eb-8b44-09023781ce37.PNG)

**Comment by K20017** [comment]
I believe the red tape has an error in the mach calculation.  We will take a look at it.

**Comment by cwburnett** [comment]
closing and combining with https://github.com/Working-Title-MSFS-Mods/fspackages/issues/326
