### ISSUE TITLE
CJ4 - Missed Approach Information in FMS

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#445]
Any plans to include at some point?

**Comment by mattnischan** [comment]
The hardcoded sim flight plan system does not appear to load missed approach information, despite it appearing in the data, so this will not be a short term item.

We will look into this at some phase of the flight plan management overhaul.

**Comment by dihedral977** [comment]
Gotcha, thanks.

**Comment by cwburnett** [comment]
Definitely on our plan for the future already.
