### ISSUE TITLE
CJ4 - Autopilot switches from LNV1 to ROLL

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#446]
As the title says, the autopilot seems to randomly switch to ROLL mode coming from LNV1. This happened on the two flights I've flown on 0.6, the last one being:

EVLA/06 ARBI1E ARBIS GELDA VSB ESEB4M ENGM/19R

I could not determine what triggered this, it thus far seemed pretty random. Will update when I find out more...

This issue may be related to #415

**Comment by dga711** [comment]
Did you use DirectTo or modified the flight plan during flight?
I will close this issue as we would like to combine these reports into #415 

Thank you for your feedback!

**Comment by TheFrett** [comment]
Yes I skipped a waypoint!
