### ISSUE TITLE
CJ4: Simbrief import randomly fails with valid FP

### ISSUE THREAD

**Issue by MisterFoxi** [Working-Title-MSFS-Mods/fspackages#451]
**build:** crj6.0

**Description:**
Loading a FP from simbrief with the mfd could result in failure with _"invalid airway_". Reloading it won't change the issue but either restarting the sim fully or going into the sim flightplan, crating  a dummy one and once in flight mode reloading the simbrief export will work.

**Information:**

- Airac are up to date (navigraph) and the same route can be imported without issue most of the time.

- IT happens randomly 

**route:**
LFBD CNA4P CNA UN858 VANAD/N0399F180 A34 KOVAK KOVA9W LFPB

[LFBDLFPB_MFS_29Oct20.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5456905/LFBDLFPB_MFS_29Oct20.zip)

**Comment by dga711** [comment]
I was able to reproduce it. Sometimes.

Think it has to do with the way we load airway information. There is some custom code to speed up all the waypoint loading. Will investigate.

**Comment by dga711** [comment]
Will be fixed in next update. Thanks for the feedback
