### ISSUE TITLE
CJ4 v6.0 - Backlighting Difference DCP vs. CCP

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#452]
CCP has backlighting, DCP does not. 
![lighting](https://user-images.githubusercontent.com/73390710/97553639-14dc8e00-19ac-11eb-86f0-f4e5d57c5742.PNG)

**Comment by J-Hoskin** [comment]
Actually its the other way round. The CCP is what you are referring to. We have tried extensively to fix this, including editing the LOD files manually. I had so much hope aahah. Ultimately, we are unable to fix it as Asobo need to finish adding the emissive model code and standardise the naming of their switches.

**Comment by dihedral977** [comment]
Thank you.

**Comment by J-Hoskin** [comment]
@dihedral977 Thanks for helping us find all these bugs and improvements, much appreciated :)
