### ISSUE TITLE
CJ4:  FMS FPLN page will accept 3 letter airport ID if you add a space at the end

### ISSUE THREAD

**Issue by dodougla** [Working-Title-MSFS-Mods/fspackages#456]
Submitting at Chris's request on Discord.  I am using Navigraph data if that matters.

**Comment by cwburnett** [comment]
NOTE TO SELF: if fmc.inout.length == 3 then add ' ' to the end, make sure search is only for airports.

**Comment by dga711** [comment]
Will be fixed in 0.8.1
