### ISSUE TITLE
CJ4: FMS broken with new MFS update 

### ISSUE THREAD

**Issue by sylatex** [Working-Title-MSFS-Mods/fspackages#457]
I've just tried the CJ4 mod after installing the new MFS update and the FMS isnt working anymore. Just thought to report it. Thanks for your efforts

**Comment by ken487** [comment]
Same here, it's just showing a forward slash in the upper right corner, nothing else.

**Comment by sylatex** [comment]
> Same here, it's just showing a forward slash in the upper right corner, nothing else.

Exactly the same for me

**Comment by mattnischan** [comment]
Hi all,

We are aware and are working on a patch now. We should have something available shortly.

**Comment by sylatex** [comment]
> Hi all,
> 
> We are aware and are working on a patch now. We should have something available shortly.

Fantastic! Thanks

**Comment by dga711** [comment]
Fix with Patch Release 0.6.1
