### ISSUE TITLE
G3000: Functionality Issues w/Update 5

### ISSUE THREAD

**Issue by sahammer** [Working-Title-MSFS-Mods/fspackages#458]
It appears that the G3000 in the TBM is "broken" with update 5. I don't think it is completely broken, at first glance the map and synthetic vision are broken. 

![image](https://user-images.githubusercontent.com/873622/97617372-e9bd6300-19da-11eb-8fdd-dcbee047f507.png)

The various map settings cannot be toggled, and synthetic vision cannot be enabled.  I know there were changes to the TBM in this patch, so I'm sure there are other things non-functional or broken. I will continue to investigate.

I'd be happy to contribute to the project - but not quite sure where to begin. I'll monitor what updates fix these issues and hopefully be able to help in the future :)

**Comment by itreachesout** [comment]
Just to confirm that this appears to be occurring across all of the Garmin instruments in the WorkingTitle mods (G1000, G3000, G3X), independent of what aircraft is being flown.

**Comment by sfdeham** [comment]
Same here. Airport diagram details are OK, but SVS and MFD Map are all black.

![2020 10 29-19 17](https://user-images.githubusercontent.com/71787933/97627421-a3442480-1a2b-11eb-995e-ec4914d6ba39.png)

**Comment by Piotre64** [comment]
Same here.
Happens on G1000 as well, tested on Bonanza and C208.

**Comment by cywang90** [comment]
Known issue with the new patch. Will be fixed soon.

**Comment by cywang90** [comment]
Fixed with release v0.2.2.

**Comment by itreachesout** [comment]
Awesome, thank you!

Is the G3X beta planned to be updated for the MSFS update?

**Comment by kaosfere** [comment]
It already has been.  :D   

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/gx-v0.1.0-dev3

**Comment by ntlgr** [comment]
You guys are awesome.
