### ISSUE TITLE
CJ4: FPLN title and MOD handling

### ISSUE THREAD

**Issue by dga711** [Working-Title-MSFS-Mods/fspackages#46]
1. The title needs to be left aligned
2. It will change when FPLN is modified to show "MOD FPLN". I think the "MOD" part becomes white

![image](https://user-images.githubusercontent.com/2995606/93364600-08133900-f849-11ea-887b-928142e67041.png)

**Comment by cwburnett** [comment]
@dga711 this is part of the new template design, yes?

**Comment by dga711** [comment]
it will be done with #92
