### ISSUE TITLE
FMC not working with last update (October 30th)

### ISSUE THREAD

**Issue by Banalito** [Working-Title-MSFS-Mods/fspackages#469]
Hi everyone,
I used th CJ4 a lot since I came across that very nice improvement of yours. Thanks for that! I tried to plan an new flight today right after updting MSFS and both FMC screens are black. The only thing shown is blue dashbar on the top right corner, no matter if I'm on battery or if engines are running. Does anyone have the same issue? 
Thank you and good day!

**Comment by Banalito** [comment]
F****... Didn't check if there was a new one ... Sorry then !

**Comment by cwburnett** [comment]
there will always be an update after each MSFS update.
