### ISSUE TITLE
After latest patch 5 g3000 map is black and synthetic vision also dark 2.2 not fixed

### ISSUE THREAD

**Issue by Captherky** [Working-Title-MSFS-Mods/fspackages#472]
After the latest MSFS patch 5, my g3000 is black.

The latest 2.2 update doesnt fix the issue.

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.2.2

**Comment by kutak11** [comment]
it works for me... try to remove another mods

**Comment by carverhaines** [comment]
Same for me with the latest MSFS update, but also on the g1000

**Comment by Captherky** [comment]
I removed the workingtitle-gx mod and the g1000 and g3000 worked ok.

**Comment by cywang90** [comment]
Since you seemed to have solved the issue, closing this for now.

**Comment by carverhaines** [comment]
@Captherky , thanks, I'll try that
