### ISSUE TITLE
g1000 mod cause CTD

### ISSUE THREAD

**Issue by mixMugz** [Working-Title-MSFS-Mods/fspackages#473]
With g1000 mod trying to fly 300nm vfr flight at g36. 
Two flight two CTD at middle/end flight.

After removing mod - flight complete.

**Comment by geka79** [comment]
Same problem. Unfortunately without any error. 
One fly after 30NM CTD 2nd fly 200nm CTD

Without g1000 MOD no CTD

**Comment by kaosfere** [comment]
Is this something that you can reliable replicate?   If so, can you give information on how to do it, along with the plane you're using and any other mods?

**Comment by mixMugz** [comment]
I used only g1000 mod with default g36. Trying to made Jack of all planes (fly 300nm with any plane from standart edition msfs). With g36 i cant complete, because have CTD after fly 50-250nm. It's happen tree times. Then i disable g1000 mod and complete fly.

**Comment by geka79** [comment]
Also only the actual  g1000 and the g3000 mod in the Community folder. 
Plane : c172 g1000

**Comment by JrPainkiller606** [comment]
Same thing is happening to me. I have the G1000 mod installed in the Community folder and get CTD about 20nm into flight with stock DA-40. Attempted flight twice and CTD approximately in same location.

**Comment by sttovo** [comment]
Similar problems here with the latest 0.3.2. C172/G1000. If I start C&D it's fine. As soon as i turn on avionics, my FPS drops to 0 and eventually crashes. I see issues both with a flight plan loaded from the MSFS flight menu as well as with nothing loaded (free flight). I'm happy to provide any logs or whatever is needed.

**Comment by knighty** [comment]
Can you turn on your dev menu from the general options screen, then open the FPS window 

![image](https://user-images.githubusercontent.com/1693684/98591191-ca221680-22c7-11eb-8053-609e28a02157.png)

Then post an image of the window at the top right

**Comment by sttovo** [comment]
I hope you don't mind the full screen. Might be helpful to see what's going on. Eventually I get a CTD, but it sits like this for several minutes.

![Screenshot (628) (Large)](https://user-images.githubusercontent.com/71462324/98598418-6f2cf700-22a8-11eb-9950-29800fe7d984.png)
![Screenshot (627) (Large)](https://user-images.githubusercontent.com/71462324/98598422-6fc58d80-22a8-11eb-97f3-2c6d12dcb666.png)
![Screenshot (626) (Large)](https://user-images.githubusercontent.com/71462324/98598424-705e2400-22a8-11eb-8c56-306b6aa3911b.png)

**Comment by knighty** [comment]
Ok wow yeah those coherent draw times are definitely what's causing this. Quite why is the question...thanks for the report

**Comment by sttovo** [comment]
Sure - happy to do anything else you need!

**Comment by knighty** [comment]
https://cdn.discordapp.com/attachments/767762280518909952/775153066928111656/workingtitle-g1000.rar 

Could you try this build? Unfortunately you will have to temporarily remove any existing Working Title mods otherwise it will not work.

**Comment by sttovo** [comment]
Ok I removed all other Working Title mods (just had the G3000 and GX mods) and added your build. Unfortunately, same result.

![Screenshot (629)](https://user-images.githubusercontent.com/71462324/98604042-0a29cf00-22b1-11eb-9341-082806fe9a13.png)
![Screenshot (630)](https://user-images.githubusercontent.com/71462324/98604045-0ac26580-22b1-11eb-90b6-9e9531a7a1e9.png)

**Comment by knighty** [comment]
Thanks for the test, don't have any answers for now but at least that answers the question of whether it's fixed

**Comment by sttovo** [comment]
I will double check.

**Comment by knighty** [comment]
Did you try the G1000 without a flight plan?
