### ISSUE TITLE
CJ4: Black screen in FMS on PERF TAKEOFF screen

### ISSUE THREAD

**Issue by hapes** [Working-Title-MSFS-Mods/fspackages#474]
At KBOS.  Route was KBOS -> PVD -> KPVD.  LOGAN2 Departure, did not set runway (wasn't assigned yet).
PERF INIT:
PASS/WT: 5/170
CARGO: 120
CRZ ALT: FL80
I entered the VNV page, but as VNAV doesn't work in the sim, I didn't bother actually changing anything

Clicked TAKEOFF
Entered wind (360/14), OAT (3), QNH (30.17)
Clicked 'NEXT'
FMS Screen is completely black.
Clicked 'DIR' and the screen displayed my DIRECT TO display (so the FMS didn't crash).

Unable to get VSpeeds into the PFD display.

**Comment by hapes** [comment]
Follow up on this:  I did the same without going through VNAV PERF page, did not result in black screen.  Not saying VNAV page is the problem, it may have been a weird one-off that wasn't related to my actions.

**Comment by nrcrate** [comment]
I noticed this also when not sleecting a runway.

**Comment by ChillM2** [comment]
Had the same problem. Can confirm entering runway solves the black screens.
