### ISSUE TITLE
G3000: v.0.2.2: Minimum Call-Out Missing?

### ISSUE THREAD

**Issue by PM3Delta** [Working-Title-MSFS-Mods/fspackages#476]
Hi, love your mod... could it be that with the fs2020, patch 5 and v.0.2.2 the minium call-out went missing?  I have set the RA to 200ft minimum, but no call-out "minimum" when reaching.  Could have sworn it worked before (v.0.2.1, with patch4).  Am I doing sth wrong?  Thx. a bunch.

**Comment by cywang90** [comment]
This mod doesn't do anything with the audible alerts. There is another mod that fixes the alerts: https://forums.flightsimulator.com/t/tbm-930-audible-alert-fixes-updated/278815

**Comment by PM3Delta** [comment]
I am sorry to have bothered you... thank you anyway and thanks for the link.   I think I most have confused it with the other mod I had loaded for the TBM.
