### ISSUE TITLE
CJ4 - v0.6.5 and Prior - Take Off Trim Setting

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#482]
Have tried many t/o trim settings but have settled on 6.1 / 40% nose up based on a typical weight of 14,000 lbs. ±. Too little trim up and you have to yank it off the runway and then still trim up a lot more in the initial climb, or wait for IAS to pass VR by quite a bit. Too much trim up and she’ll rotate herself prior to VR.

I have no idea if my trim setting is realistic but it does create an issue with how the trim indicators are represented. In both the MFD and external view data (lower right), the pointer is beyond the recommended zone.

**Comment by dga711** [comment]
Currently we think its in the right place for now
