### ISSUE TITLE
CJ4 - Engaging FLC - (More Observation Than Bug)

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#484]
Maybe at some point this may be worth knowing...

There is different behavior with engaging FLC depending on how you do it. If you haven't preset the IAS or MACH with the rotary knob, and you mouse click the FLC button on the panel, it will set to the current speed. If however you assign a button on a controller to "Toggle Autopilot Flight Level Change", it will engage FLC at 0 kts. and you will then of course have to spin the knob quickly to the desired speed. If you do preset the speed with the knob, it will engage at that speed when the hardware button is engaged.

Just putting it out there fwiw...

**Comment by dga711** [comment]
Thank you for the information. 
I will close this issue as we have to keep the list of issues to a manageable level.
We should think about having a FAQ or knowledge base to write things like this down.

**Comment by mnwpro1** [comment]
I am using KB shortcuts that work in other aircraft and my HONEYCOMB throttle to engage FLC and it does not... I am forced to 0use the mouse in the cockpit.  Same for a few other AP buttons, APPR, FLC , NAV.

**Comment by dga711** [comment]
> I am using KB shortcuts that work in other aircraft and my HONEYCOMB throttle to engage FLC and it does not... I am forced to 0use the mouse in the cockpit. Same for a few other AP buttons, APPR, FLC , NAV.

https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables
