### ISSUE TITLE
citation longitude g5000

### ISSUE THREAD

**Issue by fsouzamoraes** [Working-Title-MSFS-Mods/fspackages#485]
first i have to say, great work guys.
second i am dreaming about having some improvements on the g5000 of the longitude...specially the "boeing banana" and the ability to turn off the inset map on the pilot pfd. love the plane but this plus the 20% range of the real aircraft is making me changing to the a320, but now i have to pay for a co-pilot :/ thank you all for the work asobo should be done. you are the people who should share the profits.

**Comment by cywang90** [comment]
g3000 v0.3.0-pre1 introduces support for the longitude.

**Comment by fsouzamoraes** [comment]
Sunday Longitudiness then...do you know what files regards the engine on the premium aircrafts? thanks!

**Comment by cywang90** [comment]
those files are encrypted (same with all premium aircraft).
