### ISSUE TITLE
CJ4: fuel flow not working 

### ISSUE THREAD

**Issue by sylatex** [Working-Title-MSFS-Mods/fspackages#486]
Fuel flow is stock at 0 on the MFD and not registering on the Perf page

**Comment by dihedral977** [comment]
All work for me v0.6. PERF - PERF INIT page will only show you sensed fuel at the time of you checking that page I believe. PROG page shows active fuel use. MFD shows PPH active use (see pic)

![fuel](https://user-images.githubusercontent.com/73390710/97780776-01bcf000-1b5d-11eb-9041-f97762d484d9.PNG)

**Comment by sylatex** [comment]
> All work for me v0.6. PERF - PERF INIT page will only show you sensed fuel at the time of you checking that page I believe. PROG page shows active fuel use. MFD shows PPH active use (see pic)
> 
> ![fuel](https://user-images.githubusercontent.com/73390710/97780776-01bcf000-1b5d-11eb-9041-f97762d484d9.PNG)

Thanks, it could be because I loaded the flight plan with aivlasoft EFB, I'm noticing some other anomalies in the flight plan. LNAV is following the loaded plan from the EFB but it is all messed up in the FMC. I'll try again by manually loading in the FMC but I'm almost certain this is my mistake. Ill report back shortly

**Comment by sylatex** [comment]
> All work for me v0.6. PERF - PERF INIT page will only show you sensed fuel at the time of you checking that page I believe. PROG page shows active fuel use. MFD shows PPH active use (see pic)
> 
> ![fuel](https://user-images.githubusercontent.com/73390710/97780776-01bcf000-1b5d-11eb-9041-f97762d484d9.PNG)

Thanks. Its definitely the EFB, works perfectly when flight plan is entered manually
