### ISSUE TITLE
[CJ4] HDG mode indication on ND displays 

### ISSUE THREAD

**Issue by ntlgr** [Working-Title-MSFS-Mods/fspackages#488]
When engaging autopilot HDG mode, the selected heading on the ND display (below PFD) heading bug is not shown or disappears after a while.
It remains visible on the ND under the engine instruments. 
Also, the numerical indication of the selected heading on both NDs is shown as 1 to 99 instead of 001 to 099.

**Comment by dga711** [comment]
We did do some things for the heading bug for next release. Hope that will fix these for you.

**Comment by ntlgr** [comment]
Awesome, will certainly try with the next release and report back!

**Comment by ntlgr** [comment]
The issue appears to be resolved, thank you!
The dotted cyan HDG line from the airplane to the HDG bug disappears about 5 seconds after changing heading - I imagine this is realistic behaviour. Thanks and great work!

**Comment by dga711** [comment]
Good to hear thanks.
