### ISSUE TITLE
FMS Spawns with a slash

### ISSUE THREAD

**Issue by JacobKreindler** [Working-Title-MSFS-Mods/fspackages#491]
To re create spawn with the aircraft and check the FMS
![Microsoft Flight Simulator 2020-10-31 9_53_02 PM](https://user-images.githubusercontent.com/70914399/97793574-1da7ac80-1bc4-11eb-9aaf-6281bb9e7489.png)

**Comment by mattnischan** [comment]
Is this with the latest CJ4 version (0.6.1)? The latest MSFS version will cause an FMC black screen unless 0.6.1 is installed.

**Comment by JacobKreindler** [comment]
No, I accidently installed an older version and when I installed 6.1 it was fixed. i was just about to close the issue. Thanks for the help though and love the mod!
