### ISSUE TITLE
[CJ4] If you go to Fuel Mgmt page 3 the whole FMS goes blank

### ISSUE THREAD

**Issue by havu1977** [Working-Title-MSFS-Mods/fspackages#492]
This is with the latest main branch from 30.10.2020. I haven't found I way to get the FMS to "power up" again. It stays blank for the rest of the flight.

I hope it is reproduceable just by starting a flight, going to Fuel Mgmt page and then clicking Next to go to the 3rd page.

**Comment by dga711** [comment]
There should be a fix for it in the 0.6.5 pre branch

**Comment by havu1977** [comment]
Ok, thanks for the quick answer. I could try that branch out for the next flight.

**Comment by havu1977** [comment]
Hmm, started a flight with 0.6.5-pre branch. Unfortunately FMS went completely blank, now already when moving to Page 2.

**Comment by havu1977** [comment]
Here's the steps I used:

- Plan flight from LHBP to UKBB
- Cold & Dark start at ramp
- Battery on
- Avionics dispatch
- IDX -> Load flight plan from SimBrief -> Exec, basically this one:
VETI1R VETIK DCT RULUT/K0644F410 M986 SLV SLV2W
- DEP, Rwy 31R, SID VETI1R, Exec
- ARR, ILS Rwy 36R, STAR SLV2W, Exec
- Strobe on, beacon on
- Right engine ignition, wait for N2 to rise to around 20, Run
- Repeat for left engine
- Tune to ATIS frequency, push Baro knob
- Go to Fuel MGMT page, click Next -> Blank FMS

**Comment by havu1977** [comment]
A couple of things that might be relevant:
- Using Hybrid mode (kgs + altitude as feet) in MSFS
- Using Imperial in CJ4 mod (not sure if the Metric mode in CJ4 is fully QA'd so wanted to avoid hiccups)

**Comment by dga711** [comment]
@cwburnett

**Comment by dga711** [comment]
We hope its all fixed in the upcoming release. Thanks for your feedback.
