### ISSUE TITLE
[CJ4] Invalid route when importing from SimBrief

### ISSUE THREAD

**Issue by havu1977** [Working-Title-MSFS-Mods/fspackages#494]
This is again with latest main branch from 30.10.2020. If you try to import the following route from SimBrief, you will get an invalid entry:

SUVAS1F SUVAS N128 OTHON UN128 RDS UL609 MES UG18 GIKAS
UN133 PEREN UL863 EVIVI L863 OKANA DCT DONIV DCT PARAK DCT EBAMO

In my case it complains about L863. 

I have the latest Airac in use, both in SimBrief and in MSFS. Navigraph beta Airac2011 revision 7. It has been confirmed in MSFS and also shown in FMS when starting a flight with CJ4.

**Comment by dga711** [comment]
We found a problem with the loading of airways that sometimes happened. It is fixed for the upcoming release. 065 pre branch

**Comment by dga711** [comment]
I'll close this for now. Thanks for your feedback.
