### ISSUE TITLE
[G3000-0.3.0-pre1] MFD brightness settings don't work anymore

### ISSUE THREAD

**Issue by C6-Skypat** [Working-Title-MSFS-Mods/fspackages#495]
Moving MFD brightness settings from max to min don't do anything. MFD Screen is always at max brightness

**Comment by cywang90** [comment]
Do you have any other mods installed?

**Comment by C6-Skypat** [comment]
it seem i found a conflict with this mod
https://uwajimaya.github.io/FS2020/
works again after removing these lights
