### ISSUE TITLE
CTD after Zoom - or New object enter in the map

### ISSUE THREAD

**Issue by SpecialFx78** [Working-Title-MSFS-Mods/fspackages#499]
G3000 v0.2.2
Hello, I meet a Crash to Desktop, when the display has to add something to display on the map screen, either by playing with the Zoom, or during a flight, it's the same effect as when there was the server problems, it looks like the sim makes a request and it doesn't get an answer, it goes to lag and then Crash of the application; I have reproduced this bug at least 20 times, either during a flight from LFLC to LFMN or the reverse route from LFMN to LFLC.
To reproduce, you have to position yourself at LFMN, then play with the zoom between 25NM and 50NM, a few seconds after being at 50NM, CDT...
But continue your Mod is really superb, very good work.
Merci
SFX

**Comment by cywang90** [comment]
I'm unable to reproduce this. Can you provide more details, like what your map settings were (which symbols were visible, etc)?

**Comment by SpecialFx78** [comment]
Indeed after tests on my side with and without the add-on it turns out that this is not a problem in your code but rather in that of Asobo and more particularly I think in the end a problem with the Azure servers. Sorry I hope I didn't lose too much time, like I lost all day yesterday because my simulator was not working anymore because of that. For me your Add On is essential, thank you for your work, and again all my apologies for having incriminated him, I close the ticket.

**Comment by SpecialFx78** [comment]
Indeed after tests on my side with and without the add-on it turns out that this is not a problem in your code but rather in that of Asobo and more particularly I think in the end a problem with the Azure servers. Sorry I hope I didn't lose too much time, like I lost all day yesterday because my simulator was not working anymore because of that. For me your Add On is essential, thank you for your work, and again all my apologies for having incriminated him, I close the ticket.
