### ISSUE TITLE
G1000: Hide wind display when aircraft on ground.

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#50]
I believe there's a simvar for is flying. Need to add a condition of is flying for wind display.

**Comment by CkovMk** [comment]
when on ground, it should probably display "no wind data"

**Comment by guifarias31** [comment]
Tapiv made a Pull request on that, you can edit "CommonPFD_MFD.js" to fix this: 
https://github.com/Working-Title-MSFS-Mods/fspackages/pull/59

**Comment by kaosfere** [comment]
With @tavip's fix merged I think we can call this one done!
