### ISSUE TITLE
G3000, TBM: v.0.3.0 - Waypoint labels vanish / not displayed

### ISSUE THREAD

**Issue by PM3Delta** [Working-Title-MSFS-Mods/fspackages#504]
Hi,

I observed, especially when flying a transition (e.g. KERAX 25 into EDDF), that the waypoint labels of the transition (e.g. DF617), vanish after a while and are not displayed any longer (see screenshot).  I played a bit with Mapsettings etc. but couldnt get them to show again.  Same happend with EDDM the other day when being on Vatsim...

Am I doing something wrong or could you please look into it.

Thx a lot and pls. let me know if you need further information.

Appreciate all your work and the latest version 030 just looks great.
![Screenshot (169)](https://user-images.githubusercontent.com/60411051/97984644-523f8200-1dd7-11eb-9230-0a617ccb89ec.png)

**Comment by e-racer** [comment]
I noticed the same. Couldnt find any setting for it unfortunatly..

**Comment by cywang90** [comment]
Try updating to g3000 v0.3.1 and see if that fixes your issue.

**Comment by PM3Delta** [comment]
Wonderful. A first test this morning looked very good and labels of a SID were visible. Let check the STAR with which I had trouble initial later tonight and I will get back to you so you can probably close the bug report. Thanks a lot for the speedy fix and your excellent work.

**Comment by PM3Delta** [comment]
Yep.  0.3.1. fixed it.  Just did a 2 hrs flight with SIDs, STARS and RNAV Transistion.  All good. I would close it.

Again, thanks a lot.
