### ISSUE TITLE
[G3000, TBM] Highlighted flight plan leg is the next from the active

### ISSUE THREAD

**Issue by ntlgr** [Working-Title-MSFS-Mods/fspackages#506]
Observed on TBM using G3000 v0.3.0 on the MFD map display. 

The currently active leg of the loaded flightplan (i.e. From the last waypoint "X" the aircraft has passed to the next and active waypoint "Y") is white. That should be in magenta. Instead, the next leg (from waypoint Y to the one after in the flight plan) is shown in magenta.

Screenshot is attached. 

Many thanks for your excellent work and the brilliant progress on the G3000. 
![Microsoft Flight Simulator 03_11_2020 20_02_25](https://user-images.githubusercontent.com/41379877/98031475-74062c80-1e0a-11eb-94ea-fbc49c9fb5e9.png)

**Comment by cywang90** [comment]
This is a vanilla bug. We have our own versions of the flight plan manager cooking right now, which should fix the issue, but don't know when that will happen exactly.

**Comment by ntlgr** [comment]
Thanks for the response! Looking forward to it. I have also observed that the TBM autopilot on approach mode is slowly missing the glideslope and flying under it. Is that also a bug of the vanilla AP?

**Comment by cywang90** [comment]
> I have also observed that the TBM autopilot on approach mode is slowly missing the glideslope and flying under it. Is that also a bug of the vanilla AP?

Yes, that is a vanilla bug as well.

**Comment by cywang90** [comment]
Fixed with 0.4.0
