### ISSUE TITLE
[G3000, TBM] Incorrect ISA temperature

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#507]
As I'm writing this I'm in a middle of a flight, cruising at FL300. OAT is -43C, which according to the TBM930 POH corresponds to ISA 0, but the ISA in the aircraft is -44C.

I don't know if this has something to do with this mod or if it's a general Adobo bug. If the latter I will file a ticket on Zendesk, otherwise I hope you can fix it.

**Comment by cywang90** [comment]
ISA in the aircraft is reported as absolute temperature while POH reports it as deviation from the ISA temp.

**Comment by cywang90** [comment]
Since I haven't gotten a response in a while I will close this for now.
