### ISSUE TITLE
G1000: FD won't engage after 1.8.3.0 & 0.2.1 update

### ISSUE THREAD

**Issue by CkovMk** [Working-Title-MSFS-Mods/fspackages#51]
after insert GPS flight plan, FD won't engage. I can only engage FD before entering flight plan. 
If I engage FD then disengage it, I'm able to engage it later.

**Comment by kaosfere** [comment]
Interesting, will check this one out.   This had worked with the mod prior to 1.8.3?

**Comment by CkovMk** [comment]
Yes it worked with mod version 0.2.0 prior to 0.8.3.0.
I had this bug the time I first launch after update to 0.8.3.0, and I validated it twice. But it seems never happen again. I'm not sure if it just occur randomly.

**Comment by kaosfere** [comment]
Cool.  I'm not going to close this out just yet, in case anyone else has the same problem.   But I'm going to put this one on hold for a while untill/unless it happens again.  Thanks for the report!

**Comment by jonasbeaver** [comment]
There are multiple reports of it taking 2-3 restarts before everything from the patch worked its way in to use on the sim. The workaround was to check liveries or add-on starred airports, if they showed up you know the sim had fully taken the patch. It took 2 times for me before everything showed up properly. In the meantime, pretty much everything from the community folder was amiss. I was sure my sim was borked at first, but by the second restart (3rd time opening the sim) it was working again.

**Comment by CkovMk** [comment]
> it taking 2-3 restarts before everything from the patch worked its way in to use on the sim

that sounds like my story.
