### ISSUE TITLE
G3000, TBM: v0.3.0 - Small moving map optical distortion

### ISSUE THREAD

**Issue by PM3Delta** [Working-Title-MSFS-Mods/fspackages#511]
Hi,
just ran into this one... it is more cosmetics, but I thought I let you know.

The small map inset of the PFD suddenly became distorted, dont know why.  After a while it was good again. Strange....

Thx. a bunch for your good work.

![Screenshot (171)](https://user-images.githubusercontent.com/60411051/98160951-44752400-1edf-11eb-8cf0-8a2c13ae6599.png)

**Comment by PM3Delta** [comment]
No rush please.  Just want to confirm, had the bug again today arriving at LOWW and taxiing back to gate. Version 0.3.1.

**Comment by Jessidhia** [comment]
It seems to just happen intermittently...

**Comment by cywang90** [comment]
Fixed with 0.4.0
