### ISSUE TITLE
G3000 map labels disappear when looking away for few seconds.

### ISSUE THREAD

**Issue by Roi1862** [Working-Title-MSFS-Mods/fspackages#515]
Not sure if its the mod of poor sim behibover to try make performance better, but when looking our the side window (or anywhere away from the displays) for few seconds and then look back tat the map its start to redraw the info again.
For some reason the loading and drawing is quite slow.

In previous versions i didn't notice it much, or it was much faster.

**Comment by cywang90** [comment]
This was a base game issue that we have no control over, and in any case it no longer seems to happen (likely was patched out on asobo's end).
