### ISSUE TITLE
CJ4: MFD PLAN Enhancements

### ISSUE THREAD

**Issue by slip664** [Working-Title-MSFS-Mods/fspackages#518]
Probably dumb to list this but just a few smallish enhancements to the MFD. Missing a "N" above the circle and also should no show wind information when in PLAN view.

Also as I'm sure you're aware, missing "TTG."

![Capture](https://user-images.githubusercontent.com/72432870/98325874-a8155500-1fa4-11eb-8d9e-906f6c3ebf7a.PNG)

**Comment by dga711** [comment]
the "N" and wind indicator things will be fixed in 0.8.5

**Comment by mattnischan** [comment]
Addressed in CJ4 0.9.0.

Thanks so much for the report!
