### ISSUE TITLE
G1000: Wind direction on MFD seems on the opposite direction

### ISSUE THREAD

**Issue by CkovMk** [Working-Title-MSFS-Mods/fspackages#52]
The Wind display on MFD is opposite to the one on PFD. By comparing TAS and GS, I find out the one on PFD is the correct one.

![image](https://user-images.githubusercontent.com/29831136/93550953-39058200-f99f-11ea-8eb8-e25ce28c6fb6.png)

![image](https://user-images.githubusercontent.com/29831136/93550977-428eea00-f99f-11ea-8c8d-27298240d57b.png)

**Comment by kaosfere** [comment]
Yep, you're right there's a disconnect.   It seems like the MFD isn't even supposed to have a wind bug, so I'm not sure why it does in the sim.   I think we'll just axe that.  :)   Thanks!

**Comment by guifarias31** [comment]
> Yep, you're right there's a disconnect. It seems like the MFD isn't even supposed to have a wind bug, so I'm not sure why it does in the sim. I think we'll just axe that. :) Thanks!

Yes, you can add the wind bug in the MFD:
![image](https://user-images.githubusercontent.com/70555403/93691091-ee772900-fab6-11ea-824b-32fcaf9166e1.png)

**Comment by kaosfere** [comment]
Odd, that's not in my trainers or the various manuals I've used for reference.   But the picture doesn't lie!   Thanks for that.

**Comment by guifarias31** [comment]
> Odd, that's not in my trainers or the various manuals I've used for reference. But the picture doesn't lie! Thanks for that.

I only have real experience with G500, but probably is something you can enable/disable in the menu.

**Comment by jonasbeaver** [comment]
![image](https://user-images.githubusercontent.com/70987366/93751014-04bddb80-fbc2-11ea-831d-8e760c60b558.png)
![image](https://user-images.githubusercontent.com/70987366/93751026-09828f80-fbc2-11ea-89d3-6551dacdf698.png)

perhaps these will help. even in the inset on the PFD you can see the wind barb is visible.

**Comment by rsparkyc** [comment]
I think I actually remember seeing this bug in stock, so I don't think is specific to this mod. Should probably submit a zendesk ticket for this.

**Comment by kaosfere** [comment]
This was definitely a stock bug, yeah.  But we fixed it in 0.3.0 or 0.3.2 (can't recall which)
