### ISSUE TITLE
Which Garmin ?

### ISSUE THREAD

**Issue by daveji** [Working-Title-MSFS-Mods/fspackages#521]

**Comment by daveji** [comment]
please forgive my ignorance but can you please educate me !
which Fs2020 Aircraft use the Gamin versions other than the standard G1000 that I am familiar with.
I am interested in the King Air in particular......which Garmin does it use and do you Mod it ?
Thanks

**Comment by ntlgr** [comment]
> please forgive my ignorance but can you please educate me !
> which Fs2020 Aircraft use Garmin versions other than the standard G1000 that I am familiar with.
> I am interested in the King Air in particular......which Garmin does it use and do you Mod it ?
> Thanks

Generally the small single-engine piston aircraft like the C172 have G1000 but unfortunately the old one, not the NXi edition which also provides vertical guidance.
Larger, high-performance aircraft like the TBM have the G3000. The Longitude has G5000.
The King Air is a funny one - it has a Collins system, not Garmin (funny enough when it is powering up they used the wrong Garmin splash screen)
Also the CJ4 has the same Collins Pro Line Fusion system.

**Comment by ntlgr** [comment]
Check [this mod for the KA350](https://www.nexusmods.com/microsoftflightsimulator/mods/277).

**Comment by cwburnett** [comment]
@daveji in the sim:
The G3X mod is what will provide an upgrade to the King Air, and also those that use the G3X or Touch, like the Cub and a few others.
G1000 is in the C172, C208, BE36, BE58 (maybe others I've forgotten)
G3000 is in the TMB and Longitude.
The CJ4 is our only full aircraft mod, and that uses the Collins Proline 21 (PL21 for short)
