### ISSUE TITLE
FMC blank

### ISSUE THREAD

**Issue by SPAREGARLIC556** [Working-Title-MSFS-Mods/fspackages#527]
Since the last MSFS update 1.10.8.0 the FMC display does not work it is blank. I had the same issue with the FlyByWire mod till they updated it.

**Comment by mattnischan** [comment]
@SPAREGARLIC556 Do you have the latest version of the CJ4? We released an update the same day as 1.10.8.0, so it is likely that you are not on the current version.

**Comment by SPAREGARLIC556** [comment]
Thanks I found it. Will check it out.

**Comment by SPAREGARLIC556** [comment]
Matt,

I ran into another FMS issue while on a three hour flight, around an hour or so into the flight I was checking in the fuel management widow in FMS and clicked the next button and the display blank out. It stayed off. The autopilot still followed the plan however.

Brian

**Comment by mattnischan** [comment]
@SPAREGARLIC556 We had some display freezing bugs from yesterday's release, which we have patched in our release just a little bit ago.

Try 0.7.1 and see if that helps.
