### ISSUE TITLE
PPOS Freezing MFD/PFD

### ISSUE THREAD

**Issue by lschanie** [Working-Title-MSFS-Mods/fspackages#531]
I just installed the 0.7.0 update and obviously I wanted to try the new PPOS functionality. What I noticed when I selected it is that the if I did it on the MFD it would completely freeze and the PPOS page never loads. Of course, I also tried uninstalling and reinstalling the update. Has anyone else had this issue yet? It is also completely possible that I have done something dumb. Hopefully someone has a solution. Thanks!

**Comment by dga711** [comment]
It is some incompatibility with Garmin 3000. It will be fixed in 0.7.1 we will release today. Thanks

**Comment by lschanie** [comment]
Thanks so much!
