### ISSUE TITLE
[CJ4] MFD stuck in TAWS Test, no menu navigation, v0.7.0

### ISSUE THREAD

**Issue by gitmitch** [Working-Title-MSFS-Mods/fspackages#535]
I turn on the battery and the MFD flashes “TAWS TEST” as usual. But then the “TAWS TEST” message stops flashing and stays on the screen. If I press the upper menu button, I’m unable to navigate the menu items with the knob.

**Comment by MrBuBBLs** [comment]
Also getting this with g3000 v0.3.1 & cj4 v0.7.0.
Both installed fresh, deleting the old ones before copying to the community folder.

**Comment by slip664** [comment]
It's an issue with the G3000. Either delete/disable it while using the CJ4 or wait until they release the fix.

**Comment by cwburnett** [comment]
Should be fixed with the latest releases of each package.
