### ISSUE TITLE
G1000 background terrain not working since latest Flight Sim patch (black background, no terrain)

### ISSUE THREAD

**Issue by ross607** [Working-Title-MSFS-Mods/fspackages#536]
Hi,

Since the latest official patch the background terrain on the garmin 1000 has gone and is replace with black (see attached image).  Tried this on the bonanza and the cessna.  When removing the addon and going back to default garmin green terrain is back and working correctly.  Tried removing from my community folder and re-applying but no change, black screen is back.  What's really weird is the airports and runways are still rendered just nothing else as you will see in pic.  If I click on synth terrain in the pfd then that does apply the 3D terrain and appears ok but I cant get anything on the mfd.  

Has anyone else come across this? not sure if its just me or a bug since latest MS patch.

Cheers,
Ross
![Microsoft Flight Simulator 06_11_2020 22_41_18](https://user-images.githubusercontent.com/74078448/98422110-c2bdfb80-2082-11eb-939c-0584339dc07a.png)

**Comment by cwburnett** [comment]
have you updated to the latest version?
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g1000-v0.3.2
You can always find latest releases here:
https://github.com/Working-Title-MSFS-Mods/fspackages/releases

And they're announced in the #latest-releases channel on our discord.
Discord: Track Updates and Progress on Discord [https://discord.com/invite/Fa6w2xK](https://discord.com/invite/Fa6w2xK)

**Comment by ross607** [comment]
Thats weird, when I click on the link above to latest releases it shows 3.1 as the latest which is what I have installed.  I'll go direct to the 3.2 link download that and try it, will report back, thanks.

**Comment by ross607** [comment]
I'm afraid the issue persists in ver 0.3.2 - I did initially think the pfd screen was ok but although it does show some colour its def not right, synth terrain turned on there is no runway just a brown block of colour under the horizon line and blue above, inset is also showing black screen and no terrain the same as the mfd - screenshot attached

![Microsoft Flight Simulator 06_11_2020 23_34_23](https://user-images.githubusercontent.com/74078448/98424283-2e0acc00-2089-11eb-8f19-2591bd54d423.png)

**Comment by knighty** [comment]
That looks like a `mapConfig.json` issue. Do you have any other mods that might change those files? Also did you make sure you fully delete the mod before you reinstalled?

**Comment by ross607** [comment]
I dont know if I have anything else that would change that, I've not installed anything other than the latest patch from the sim.  I'll totally clear out my community folder in the morning, fully delete the mod and reinstall and see if that works, will update, thanks for your help.

**Comment by ross607** [comment]
Update - mod now working once I cleared my community folder so another mod responsible, no idea what I'll need to run through them with trial and error - many thanks for the help guys.

**Comment by cwburnett** [comment]
@ross607 I haven't tried it, but other users in our discord have said that this tool helps find conflicts easily, so you don't have to go through trial and error...
https://flightsim.to/file/1572/msfs-addons-linker

**Comment by ross607** [comment]
I already use it, didn't highlight any issues before but obviously some other mod is broken and conflicting with this one, the addon linker does make it easy to switch mods in and out so hopefully wont take me too long to find the cause, thanks.
