### ISSUE TITLE
Citation CJ4 DEP/ARR Transitions missing

### ISSUE THREAD

**Issue by felipe-mendes-msfs** [Working-Title-MSFS-Mods/fspackages#538]
As i spoke with cwburnett at AVsim, i'm posting the issue here. 

The CJ4 FMC (using the latest 0.7.1 WT version) is not showing all transitions available for the selected procedure. It can happen either in SIDs or STARs procedures.
I'm assuming this is not a database issue, because i can select the transitions without any problem using the garmin G1000.

Some pics below, showing the issue:

![G1000](https://user-images.githubusercontent.com/74080321/98426174-9bf9c800-2076-11eb-992f-2d9a5018cd55.jpg)
Using the latest version of WT G1000 i can select all transitions of IH1C SBRJ procedure.

![CJ4](https://user-images.githubusercontent.com/74080321/98426202-b469e280-2076-11eb-9ea2-0457aaee8150.jpg)
But when i try the same thing on CJ4, i can select just "BITAK" transition. All the other ones are missing (selecting other runways do not change anything).

I usually fly in my home country (Brazil) and you can check that have a lot of other airports that behave the same way, like SBGL or SBGR.

I'm using the default database, never installed navigraph.

Thanks very much for your efforts on this project!
Felipe Mendes.

**Comment by dga711** [comment]
@felipe-mendes-msfs 
When you deselect BITAK by pushing the key next to it you can see all transitions
![image](https://user-images.githubusercontent.com/2995606/98462678-4fb5a180-21b6-11eb-8f0e-717ab24bdb23.png)

I am not sure yet why BITAK gets preselected, but that would be another issue/question.
