### ISSUE TITLE
1/2 Bank button functionality inverted

### ISSUE THREAD

**Issue by linmar22** [Working-Title-MSFS-Mods/fspackages#540]
Turning on the AP's 1/2 Bank feature, allows for more bank, in stead of limiting to half.

 [Screenie of 40 degree bank with 1/2 Bank turned on](https://i.imgur.com/CCvbiZF.jpeg)

**Comment by dga711** [comment]
can you evaluate this one @K20017 ?

**Comment by dga711** [comment]
We did fixes to this for the 0.8.1 release. Thank you for your feedback
