### ISSUE TITLE
CJ4: LVAR List for FSUIPC Users

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#541]
Put together simvar event vars for FSUIPC, etc users

"I’d love ones for the menu knobs at least.  And maybe the checklist button from the lower panel. Would be nice for running the checklists. Certainly not urgent."

**Comment by dga711** [comment]
https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables
