### ISSUE TITLE
G1000 pitch scaling

### ISSUE THREAD

**Issue by jamesEGNS** [Working-Title-MSFS-Mods/fspackages#543]
The scaling on the G1000 for the pitch ladder is not even close to being real life. The pitch ladder on the regular G1000 is just above 20deg on the real thing and in the sim it is at 10deg at the top of the page this makes transitioning over from the real thing quite a bit more challenging.

I can imagine this is not overly easy to update but anything would be appreciated. 👍 

![g10002](https://user-images.githubusercontent.com/48810139/98466051-015bcf00-21c5-11eb-96c6-9e701397944c.jpg)

**Comment by knighty** [comment]
https://www.youtube.com/watch?v=uopSqz_5uV0 ;)

**Comment by jamesEGNS** [comment]
![f663db52-cf36-489c-a892-3ed788d5a244](https://user-images.githubusercontent.com/48810139/98466269-55b37e80-21c6-11eb-92c4-0806abfb2599.jpg)

**Comment by knighty** [comment]
![image](https://user-images.githubusercontent.com/1693684/98466664-d2dff300-21c8-11eb-834a-5dc8bee1257f.png)

Just for clarification this is what it looks like in the sim now in my dev build. Your image prompted me to fix the fact that the top/down ratio was a little off too.

**Comment by jamesEGNS** [comment]
That looks fantastic, a lot better than the current anyway. Sounds like something little but from flying the real thing it makes it very difficult to transition over!

**Comment by julianpoma** [comment]
Wow, I love how the new dev build is looking. Congrats @knighty !! Now, it would be awesome if we could find a font type that better matches the real units.

**Comment by jamesEGNS** [comment]
I agree @neucosas , been wanting this is everything, xp11 too.
