### ISSUE TITLE
Incorrect version numbers in manifest.json

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#545]
I hope I'm not offending anyone with this "request", I come in peace!

Just about every time I'm about to start MSFS I begin with looking for updates on the mods I'm using. With the A32NX project that's as simple as it gets with the "A32NX Downloader" but for the mods in this repository it's not that simple. One relatively easy was is to compare the version number in manifest.json with the latest release on github, but those are obviously not updated when you create a new release. The only one that has the correct version is the GX project but then again it has just been released.

So, I was hoping that you would consider making some adjustments to your release process so that it includes updating the version number in manifest.json. Or by any other means make it simpler to check if there's a new update available without the user having to remember which one is installed.

And for the record I think you're doing an awesome job that really improves the simulator expecience!

**Comment by kaosfere** [comment]
It's a good shout, and we were pretty bad about this to start.  We've made a point to get better about. this.   :)   I have just looked at our latest releases and it seems like we now currently represent the correct version numbers in all 4 main mods.
