### ISSUE TITLE
Touchscreen panels reverted to default in G3000 mod?

### ISSUE THREAD

**Issue by SkyCmmd** [Working-Title-MSFS-Mods/fspackages#546]
hello! for the life of me i can't figure out why after upgrading to 3.0 and up the touchscreen panels are default even though the PFD and MFD show the new options - help?

**Comment by AndersHogqvist** [comment]
This happend to me after today's MSFS update, but after restarting MSFS it was back in normal again.

**Comment by SkyCmmd** [comment]
Hi! I've rebooted twice, redownloaded the zip, and reinserted to community folder to no avail :-/

**Comment by Masoholik** [comment]
Same here...
After today's MSFS Update, default touchscreen panels

**Comment by cywang90** [comment]
The g3000 mod is technically still compatible with the new update. Check for mod conflicts/other mods that are incompatible with the new update (I've gotten one report that the TBM 930 mod was causing an issue).

**Comment by SkyCmmd** [comment]
hi there! I only have liveries installed for the TBM. I removed the TBM 930 mod to test, and that is my current configuration. I also removed the g1000 and the gX mods in case they were in conflict as well.

**Comment by cywang90** [comment]
You can try updating to v0.3.2 and see if that fixes it. It's unlikely, though, since no changes were made that would affect compatibility.

**Comment by SkyCmmd** [comment]
compatibilities issues with mod was the case. thanks!
