### ISSUE TITLE
[G3000] The speed trend line is lagging 

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#547]
I've noticed that in the TBM the speed trend line is lagging quite a bit. I'm fairly certain that it should indicate the current speed trend, so if you're for instance accelerating it should point upwards and the length should indicate how fast you're accelerating. However, it doesn't respond fast enough. I decelerate and the line points downward and then starts to accelerate, it takes quite a bit until it starts to point upwards.

**Comment by ntlgr** [comment]
This is a major problem in all aircraft, that's not only on the G3000.

**Comment by knighty** [comment]
This is actually pretty realistic. The real G1000 updates the trend line pretty ridiculously smoothly. From what I've seen of it I don't understand why it does but, well, it does update very slowly so it doesn't respond well to changing from positive to negative accelerations. I actually changed it on the g1000 in my dev copy and it feels a lot more usable but I'm not sure where we should stand on realism there. I prefer to err on the realism side

**Comment by ntlgr** [comment]
Found a [YT video](https://youtu.be/jc9zAn9ty78?t=66) showing the G1000 in flight; link sends you straight to the point where the trend line will appear for a few seconds. It really looks like it's very laggy indeed.

**Comment by AndersHogqvist** [comment]
You are right, it sure seems to be that laggy. Working with simulators for fighter aircraft I'm use to it being dead on but then again it serves a much more important purpose in that context.
