### ISSUE TITLE
G3000 0.3.2 and TBM 0.5.5 (and earlier iterations of both)

### ISSUE THREAD

**Issue by m2ed** [Working-Title-MSFS-Mods/fspackages#550]
Only in one earlier version (cant remember what number) was I able to change my MFD map settings, and change the brightness of all G3000 screens in the TBM. The MFD map settings or MFT general settings no longer appear, neither does the slider "menu" to allow changing of the screens brightness. Ive tried both with G3000 AND TBM mod installed, as well as G3000 only.

**Comment by cywang90** [comment]
This sounds like a mod conflict. Try removing ALL mods except for G3000 and see what happens.

**Comment by m2ed** [comment]
Will do

**Comment by m2ed** [comment]
After a lot of diagnostic troubleshooting, the culprit has been found to be YourControls (https://github.com/Sequal32/yourcontrols). This happens with the TBM but not the Longitude.

**Comment by m2ed** [comment]
Has been reported here recently, so this can be closed. https://github.com/Sequal32/yourcontrols/issues/34
