### ISSUE TITLE
G3X causing lag on main_thread.

### ISSUE THREAD

**Issue by Krenth** [Working-Title-MSFS-Mods/fspackages#558]
Ever since I installed the G3X mod, I've noticed that my frames tank whenever the G3X is within view. After doing some experimenting, I found out that my frame-rate was "Limited by MainThread (up to 50ms per frame)", and decreasing the glass cockpit refresh rate to "Low" mitigated most of the issue (dropped the MainThread time down to ~25ms per frame). This frame-rate drop doesn't happen when I use the stock G3X. Can you guys pinpoint what may be causing the main_thread lag?

**Comment by knighty** [comment]
What does the Coherent thread time say? There seem to be a lot of bizarre performance issues that are hard to work out their origin
