### ISSUE TITLE
FMS waypoint distance doesn't line up with map distance rings in MFD/PFD

### ISSUE THREAD

**Issue by Wnthr** [Working-Title-MSFS-Mods/fspackages#561]
The distance in the FMS text doesn't line up with the distance rings on the map. Also, the PLAN mode doesn't align with the ARC mode. Also, the wind direction in the PLAN mode is the same (North up) as the ARC mode (HDG up). Although it kind of sounded like that might be how the unit does it, in which case please ignore. 

![20201116193603_1](https://user-images.githubusercontent.com/14862505/99425501-34a80780-2903-11eb-8504-f3c7faf3990e.jpg)
![20201116200627_1](https://user-images.githubusercontent.com/14862505/99425503-35d93480-2903-11eb-8793-f97492ba45a8.jpg)
![20201116223345_1](https://user-images.githubusercontent.com/14862505/99425506-35d93480-2903-11eb-92ce-72a0fd38a482.jpg)

**Comment by dga711** [comment]
This should be more accurate in the coming update. Thank you.
