### ISSUE TITLE
G3000 country borders seem to be shown and extend into the sea

### ISSUE THREAD

**Issue by gordongreig1966** [Working-Title-MSFS-Mods/fspackages#562]
See attached screenshot. This shows the aircraft at 14° 44' 53.64" N 89° 37' 3.03" W heading 297 towards Mexico. In the Map settings in the MFD, all land and aviation markers are set to off. I could not find a way of removing the orange lines, and I wasn't sure what they were. However I believe they correspond to the country borders although there is not an exact match. the borders also seem to extend into the Pacific to the West.
![2020-11-18 (76)](https://user-images.githubusercontent.com/74683935/99588339-52986980-29e2-11eb-870f-5e9f42d132e4.png)

**Comment by slip664** [comment]
That's because those are airspace borders and not country borders.

**Comment by gordongreig1966** [comment]
Thanks for the reply. I didn't think they could be airspace borders because I had those turned off in the display options. So is that maybe a bug that thye are still being shown?

**Comment by cywang90** [comment]
These are indeed airspace borders. I just tested and they turn off as they should if you toggle them off in the map settings menu.
