### ISSUE TITLE
[CJ4] Approach Page will not accept Temperature value of 0 (degrees C)

### ISSUE THREAD

**Issue by FlyingDolphino** [Working-Title-MSFS-Mods/fspackages#564]
As per the title, to replicate just enter 0 into the OAT on the approach page. It handles negative values fine, just 0 it doesnt like
**To replicate**
Insert 0 into the OAT box of the approach page

**Expected result**
Accept 0 degrees C
**Actual result**
FMC returns INVALID

**Comment by slip664** [comment]
Also found out today in error that you can enter decimal values. IE, I meant to enter "-1" but put in ".1" by accident and it rounded it to "0."

**Comment by K20017** [comment]
Fixed in 080.  Only whole numbers can be added.
