### ISSUE TITLE
ADF 2 not working #cj4

### ISSUE THREAD

**Issue by zazaboeing** [Working-Title-MSFS-Mods/fspackages#565]
So, the option for that second Bearing Pointer is useless because ADF2 doesn’t work . It would be nice to have the FMS option on Bearing Pointer 2, so we can use ADF1 in the Bearing Pointer 1 as an alternative.

**Comment by K20017** [comment]
ADF2 is just not supported in the game so there's no data to use so unfortunately there's nothing we can do.  We are going for accuracy as well and FMS only exists in bearing pointer 1.
