### ISSUE TITLE
[CJ4 0.7.1] - LNV1 disengage after DCT

### ISSUE THREAD

**Issue by flymypi** [Working-Title-MSFS-Mods/fspackages#567]
Hey there,
as the title suggests, my AP disengages LNV1 and reverts to ROL once I have passed a waypoint I selected on the DIR page.
Obviously, this leads to the aircraft continuing on the HDG as present at crossing the waypoint, until one intervenes.
![Capture](https://user-images.githubusercontent.com/72461857/99955298-62b69d00-2d84-11eb-8f4e-cffe50f780b6.PNG)

It seems unlikely but is this intended behaviour?

**Comment by dga711** [comment]
This will should not happen anymore with the new update that is coming very soon.
