### ISSUE TITLE
Patch 1.11.6.0 - APR not capturing Localizer

### ISSUE THREAD

**Issue by PM3Delta** [Working-Title-MSFS-Mods/fspackages#569]
Hi just updated and ran a quick ILS into RWY08R (109.3) into EDDM.  After the update of patch 1.11.6.0. the AP did not capture the localizer nor the GS although it was armed and showed G/S.  Funny thing was also, when I pressed APR, the HDG light stayed on.
If I made a mistake, I apologize, but I have about 100hrs in the TBM - of course one never knows....
Thx.
Marcel

**Comment by PM3Delta** [comment]
Captures the ILS without the G3000 mod installed...  so I am guessing s.th. must have gotten broken again.
Sorry to say.... really enjoy your mod, but pains me, that after every patch you guys have to fix s.th.

**Comment by kmoze2001** [comment]
> Captures the ILS without the G3000 mod installed... so I am guessing s.th. must have gotten broken again.
> Sorry to say.... really enjoy your mod, but pains me, that after every patch you guys have to fix s.th.

What is "s.th."?  Is that some code to avoid using the word "shit"?

**Comment by PM3Delta** [comment]
No.  s.th. means something. As something must be broken

**Comment by tonyravioli** [comment]
FWIW: Just tried to replicate this by flying out of KPWM, then direct approach in flight plan and procedures to KPWM ILS11. Selected the ILS frequency via waypoint info like I normally do. Nav mode to localizer, it locked onto the localizer normally. When the glideslope icon was at the right spot, I hit the approach button and it followed the glideslope normally.

**Comment by dga711** [comment]
Asobo changed something concerning the capturing. This probably needs to be integrated into the mods

**Comment by PM3Delta** [comment]
Just checked 8 different ILS approaches into EDDM, EDDF, LSZH and LOWW without the mod. Result: ILS is captured, but 2 out of 8 times off track a bit and one time a lot (LSZH RWY14).  So it should work in principle.
With the mod. As described above, I noticed that the HDG and the APR both stayed lit.  
Hope that helps to narrow down the problem.
Again, thanks a lot. Without you guys, I would have long given up on MS2020.

**Comment by kmoze2001** [comment]
> No. s.th. means something. As something must be broken

Ah.  Now that you explained it, I actually see it.  I guess I'm getting a bit behind on my Internet acronyms, does that mean I'm officially getting old?

**Comment by PM3Delta** [comment]
> > No. s.th. means something. As something must be broken
> 
> Ah. Now that you explained it, I actually see it. I guess I'm getting a bit behind on my Internet acronyms, does that mean I'm officially getting old?

:-)  You are a pilot - you never get old.  (Especially if you crash :-))

**Comment by kmoze2001** [comment]
Not to pile on, but I can also confirm that post patch, the G3000 does not want to capture or track the localizer.  Good thing I can hand fly an approach!

**Comment by tonyravioli** [comment]
Quick question for anyone able to replicate this: are you setting NAV1 to the localizer frequency, and then changing the nav mode to follow NAV1? I've probably done a dozen or so approaches with the TBM with this mod on the latest MSFS version over the last 6 days or so and I haven't run into trouble. I always do what I described, because if there's another way I don't know it.

**Comment by sfdeham** [comment]
> Quick question for anyone able to replicate this: are you setting NAV1 to the localizer frequency, and then changing the nav mode to follow NAV1? I've probably done a dozen or so approaches with the TBM with this mod on the latest MSFS version over the last 6 days or so and I haven't run into trouble. I always do what I described, because if there's another way I don't know it.

Yes, that's the normal procedure. Doesn't work for me though right now as per the previous posts. Currently experiencing the issue in CJ4, however that appears to be connected to G3000 as per above.

**Comment by kmoze2001** [comment]
> Quick question for anyone able to replicate this: are you setting NAV1 to the localizer frequency, and then changing the nav mode to follow NAV1? I've probably done a dozen or so approaches with the TBM with this mod on the latest MSFS version over the last 6 days or so and I haven't run into trouble. I always do what I described, because if there's another way I don't know it.

Yes, I've done exactly that and it still failed to capture either the LOC or GS.  In one case, I hand flew it instead, in another I used the AP in HDG and VS mode until I popped out of the clouds and hand flew it from there.  Any competent instrument rated pilot should be able to do it either way, but something's broke.  I did somehow manage to get it captured once, but have no idea what, if anything, I may have done differently to influence the outcome.

It may be a bug in the sim itself, though.  I disabled the G1000 mod and flew a flight with the stock version and had the same problem.  So who knows WTF is going on.  Someone, maybe, but whoever that someone is, it ain't me.

**Comment by FBA32X** [comment]
Same here. After the last MSFS update the approach function of the G3000 is kaput.

**Comment by PM3Delta** [comment]
As of Patch 1.11.7.0 all works for me again.... tested various approaches via VOR CHA into EDDF ILS25L using NAV2/LOC2 and NAV1/LOC1 to capture the ILS.  Both VOR radial tracking (e.g. CHA R339) and HDG worked correctly.  I would suggest to close the issue.
