### ISSUE TITLE
[CJ4 0.7.1] - inHg/HPA setting not persistent

### ISSUE THREAD

**Issue by flymypi** [Working-Title-MSFS-Mods/fspackages#570]
Hello,
doing multiple flights, outside the US, I noted that while my metric units (awesome work on that!) stayed with me flight after flight, I had to set the Barometer setting back to hPa every time I powered the plane up.

Is this intended behaviour? If not, could it be possible to include this setting in the persistent storage?

**Comment by dga711** [comment]
Afaik it is now persistent.
