### ISSUE TITLE
Compatibility with aircraft rego font change

### ISSUE THREAD

**Issue by Crispy136** [Working-Title-MSFS-Mods/fspackages#571]
Have recently worked out how to add a custom font to an aicraft external registartion.  This method supplements the existing process to add a font colour to the registartion.  While an aicraft with a custom font colour for the registration works fine with the G1000 mod, one with a custom font doesn't.  With the G1000 mod installed the aircraft loads in the hanger and the font and colour are displayed correctly.  However if you start a flight with that aircraft the flight will stall just before you get to the ready to fly prompt.  Without the G1000 mod installed the flight loads normally.  Doesn’t seem to matter if the G1000 mod loads before or after the repaint folder in the Community folder. Note that the font problem doesn't effect aircraft without G1000 instruments, if the G1000 mod is installed.  I think the problem may be that both the G1000 mod and the repaint font method require the use of the “html_ui\Pages” folder but different subfolders. But I am only guessing.  I'd like to be able to use a a custom font and use the G1000 mod.  I am happy to provide a sample aircraft with the font change.  The repaint I have been doing is for the DA40 and the issue isn't a problem with just the DA40 NGX mod installed, so I thought it was more likely to be related to the G1000 mod rather than the DA40 NGX mod.  Haven't tested if this also applies to the G3000 or GX mods.

**Comment by Crispy136** [comment]
This issues appears to have been resolved.  I think it was either an issue with the order of the Community folder, or I had incorreectly replicated the panel folder when tcopying it across from the stad DA40.

**Comment by mattnischan** [comment]
@Crispy136 Thanks for the update! I will close this issue.
