### ISSUE TITLE
Autopilot issue after MSFS update

### ISSUE THREAD

**Issue by ntlgr** [Working-Title-MSFS-Mods/fspackages#573]
After the 1.11.6.0 update, autopilot on G1000 does not bank the aircraft more than 10 degrees. Tested with the Baron 58 and it affects all lateral modes (HDG, NAV, APP). Vertical modes work fine. 

Forgive me if it's a vanilla problem you can't do anything about. 

As a side note, there have been some autopilot issues with multiple planes, A32nx AP is completely broken.

**Comment by DanP77** [comment]
Confirm in DA62 Modded same behaviour.
But i think that is an Asobo Issue.

**Comment by mikeB2210** [comment]
Same on Cessna 172 G1000 and TBM with G3000

**Comment by ntlgr** [comment]
I saw the TBM also not capturing LOC and GS: APP mode is useless
NAV and HDG modes turn the aircraft way too slow

**Comment by e-racer** [comment]
> I saw the TBM also not capturing LOC and GS: APP mode is useless
> NAV and HDG modes turn the aircraft way too slow
> Would be great to see a POV from the devs.

Yes noticed the same! And if i flew a shortcut in the flightplan the plane flew offset and it took a while until the plane flew direct to the waypoint..

**Comment by mattnischan** [comment]
Hi all,

The sim AP was changed quite a bit in the latest MSFS patch. As we are using the stock AP with no modifications, this issue is unfortunately on the simulator end and we cannot currently address it at this time.

We will continue to track this issue and see how it evolves with the next set of sim updates.

**Comment by ntlgr** [comment]
Ah well. :(
Thanks for the update.

**Comment by e-racer** [comment]
I had a look into Flightsimulator.com forum.. its already discussed many times there, also Autopilot related issus to other planes... really a blame... they didnt learn anything after the 7th update...

**Comment by dga711** [comment]
fixed via 0.7.3

**Comment by e-racer** [comment]
Good morning,

so should i install the Citation update 0.7.3 to fix autopilot issues in the tbm?

Best Regards

**Comment by mattnischan** [comment]
@e-racer Unfortunately the fix will need to be rolled out individually to each aircraft. Since our only aircraft specific mod is the CJ4, that will be the only plane we can deliver the fix to. We will not be able to deliver the fix to other planes.
