### ISSUE TITLE
CJ4: MACH climb missing significant figure

### ISSUE THREAD

**Issue by slip664** [Working-Title-MSFS-Mods/fspackages#575]
Digit being dropped from the end when MACH number ends in a "0" on the autopilot display of the PFD.
![mach](https://user-images.githubusercontent.com/72432870/100289886-d1375e80-2f2e-11eb-8189-4b1cab19a8b8.png)

**Comment by dga711** [comment]
😬

**Comment by dga711** [comment]
Fixed in the coming update. Thanks!
