### ISSUE TITLE
Pitch / trim issue CJ4 After MSFS update 24-11

### ISSUE THREAD

**Issue by doc3d** [Working-Title-MSFS-Mods/fspackages#577]
First flight After the update.. midway though cruise (with no issues) the plane suddenly  goes pitch up, busting the ALT and keeps going 30 degrees pitch up until it stalls. Ive been unable to run with autopilot on at this point. Changing ALT setting or VS etc does not help. The only way i can keep autopilot on is to turn off ALT setting and pushing the yoke down to keep the altitude. With about an hour to go before decent, this gets a bit troublesome.

**Comment by slip664** [comment]
Are you using the default livery or a custom one?

**Comment by mattnischan** [comment]
@doc3d We're going to close this one for now as we have a new flight model. Please let us know if you're still getting this with 0.9.1 and we can reopen this issue.
