### ISSUE TITLE
CTD with G3000 after 24.11 update

### ISSUE THREAD

**Issue by Captherky** [Working-Title-MSFS-Mods/fspackages#578]
Dont know if its just me, but I keep getting a CTD when using the G3000 mod with the latest MSFS update 24th Nov.

Thought Id report it in case theres anyone else?

Log Name:      Application
Source:        Application Error
Date:          11/25/2020 8:19:35 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WINDOWS-7M2S8CI
Description:
Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x5fb7ecbc
Faulting module name: ntdll.dll, version: 10.0.18362.1171, time stamp: 0x103a4719
Exception code: 0xc0000006
Fault offset: 0x000000000001e312
Faulting process id: 0x12fc
Faulting application start time: 0x01d6c3649c43b068
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.11.6.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 2d0327a8-e6d9-4ce3-8b7a-3de6269d8d6a
Faulting package full name: Microsoft.FlightSimulator_1.11.6.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-25T20:19:35.120391700Z" />
    <EventRecordID>25793</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WINDOWS-7M2S8CI</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FlightSimulator.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5fb7ecbc</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.18362.1171</Data>
    <Data>103a4719</Data>
    <Data>c0000006</Data>
    <Data>000000000001e312</Data>
    <Data>12fc</Data>
    <Data>01d6c3649c43b068</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.11.6.0_x64__8wekyb3d8bbwe\FlightSimulator.exe</Data>
    <Data>C:\windows\SYSTEM32\ntdll.dll</Data>
    <Data>2d0327a8-e6d9-4ce3-8b7a-3de6269d8d6a</Data>
    <Data>Microsoft.FlightSimulator_1.11.6.0_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by inztigator** [comment]
I get CTD in TBM even without mod. If you load the MFD with origin & destination airport, clear them, and try add again, you get CTD :(

**Comment by Captherky** [comment]
OK Got it I think.

Check LIVE TRAFFIC imported from Asobo?

It crashes the G3000 when its trying to import Live Traffic.

If you set AI traffic its OK...Because G3000 doesnt SEE AI traffic!

**Comment by kmoze2001** [comment]
> OK Got it I think.
> 
> Check LIVE TRAFFIC imported from Asobo?
> 
> It crashes the G3000 when its trying to import Live Traffic.
> 
> If you set AI traffic its OK...Because G3000 doesnt SEE AI traffic!

I don't think that's it.  I've used the G3000 (latest) since the 24.11 update (took me awhile to figure out what you meant by that), and I use AI traffic with no issues.  I haven't used the AI traffic option in a while since I figured out it killed the sim, but it's my understanding that's at least been addressed, if not actually fixed.  I just have the issue with it not wanting to capture the LOC or GS, and even that is spotty, as I got it to work last night.  Of course, I was practically 100% aligned with them when I went into APR mode anyway, so that may have helped, I don't know.

**Comment by inztigator** [comment]
No, its not the traffic. Its in their MFD script! An index out of range or something like that! If I could get the file before the update I could do a compare and see the differences :(

**Comment by mattnischan** [comment]
@inztigator - JS errors do not crash the sim the way MSFS is architected. The worst that could happen is that the instrument itself goes black or stops responding.

If people are seeing CTDs, then it is guaranteed to be a sim code issue we can't access.

**Comment by inztigator** [comment]
Really? I wonder why the SIM use to crash when an index was out of range in a JS file when scrolling the MFD flight plan,, 2 updates ago??

**Comment by mattnischan** [comment]
Can you point me to the index out of bounds issue you're referring to?

**Comment by RichardHancock** [comment]
Still seem to have this crash in the TBM when changing origin/dest airports for a second time. Doesn't seem to do it in vanilla.

**Comment by Captherky** [comment]
Ive never had a CTD issue with the TBM. The CTD I originally referred to was in the Longitude. Which, incidenally is superb witht he G3000 Mod. I just dont have any more issues if I turn Ai Traffic off? I saw a constant Asobs "loading scenery" circle before it CTD? I assumed it was trying to load AI Live aircraft. Ive no coding knowledge, just years of sim flying! Anyway its stable for me with no AI trafic?

**Comment by cywang90** [comment]
Since this issue is kind of old now and I can't figure out what exactly was being discussed (there seems to be multiple things being mentioned here), I'm going to close this issue. Please open a new issue with concrete details explaining when the crash occurs and steps to repro (if possible) if you feel like there is still a bug that hasn't been addressed.
