### ISSUE TITLE
HDG Sync does not work corrrectly

### ISSUE THREAD

**Issue by DanP77** [Working-Title-MSFS-Mods/fspackages#582]
Pushing the HDG Sync, the G1000 set ever some degrees more on right.

Thx

**Comment by mattnischan** [comment]
Can you clarify this issue a bit? I'm not sure I understand the conditions or the problem you're describing.

**Comment by DanP77** [comment]
When you push the HDG selector in the G1000, it has to sync the HDG with the actual one. It's ever some degres more.

**Comment by kaosfere** [comment]
Looks like this is working correctly on our 0.4 beta.
