### ISSUE TITLE
G1000 (Bonanza G36) weather radar  doesn‘t work

### ISSUE THREAD

**Issue by schmiko96** [Working-Title-MSFS-Mods/fspackages#583]
Without the workingtitle mod it is possible to use weather radar view on MFD, with the mod it is not longer possible to use that function.

**Comment by promethues5500** [comment]
The G36 has no weather radar in real life. Take a look at the TBM, for example. See the bulbous thing on the wing? that's what houses the weather radar. The Bonanza simply doesn't have one and it should never have been available in the G1000 in that particular aircraft. It COULD have NEXRAD, however, which does still work. NEXRAD is downloaded weather. Not sure how it is simulated in the sim, but in real life, NEXRAD can be out dated by 10-15 minutes, depending on connection/upload/ect. So it isn't as current as a weather radar getting real time radar returns off of precipitation, but it's still useful for navigating around general regions of poor weather.

**Comment by kaosfere** [comment]
The weather radar page, on planes which have it configured, has been moved to a more authentic location.  It's now in the MAP page group on the MFD, and can be accessed by turning the inner concentric knob when viewing the flight map.   On planes which don't have weather radar installed, it won't show up.   I'm fairly positive the bonanza doesn't have it.  It would be incredibly uncommon in a plane of that size.

You should still have NEXRAD, though.   And if you want to hack up your panel.cfg you can give a plane that lacks it actual radar.
