### ISSUE TITLE
CJ4 no avionics display

### ISSUE THREAD

**Issue by webbpet** [Working-Title-MSFS-Mods/fspackages#585]
I extracted the zip file to my community folder but when I Press FLY to take off the cockpit has no avionics displayed on any of the screens

**Comment by mattnischan** [comment]
@webbpet Which version of the plane did you download? Please ensure that you are using 0.7.2.

**Comment by webbpet** [comment]
much appreciated I must hsve mistakenly downloaded an older version (senior moment) I now have ver 0.7.0 and dispays are all there THANKS AGAIN
