### ISSUE TITLE
G1000/3000 Color Profile

### ISSUE THREAD

**Issue by DiBarkis** [Working-Title-MSFS-Mods/fspackages#588]
Hi all,

First off, let me use this opportunity to thank all those in  ##charge of these wonderful developments and mods. You guys have made this sim a lot more enjoyable than it would be without the improvements. Hats off to all of you.

I just have a little observation about the colors on the G1000 and G3000 and I am hoping it is something that can be corrected, since I have noticed that the working title g3000/1000 terrain colors are different and better than the default.

The issue is with the green/yellow/brown terrain levels and I see that the darker shade of green is closer to the yellow while the lighter/ lime-ish colors are further away. What I mean is that it should be thus: the lower the terrain, the darker the green, therefore the colors should graduate thus: blue (sea); almost teal-ish green (below sea level); dark green (sea level); lime; yellow; orange; 3 shades of brown; grey; white.

I have a few screenshots here, which I got off the another garmin but the colors are always the same so they should be the same with the g1000 and g3000.

This is what we have at the moment. Notice how the darker green is closer to the yellow whereas the green and the yellow should blend to form the lime or lemon color?:

![5](https://user-images.githubusercontent.com/47131139/100828892-22af8400-342e-11eb-8b31-3168afe12d85.jpg)

Now compare that with garmin colors and also take note of the color scale to the bottom left of the next screenshots:

![1](https://user-images.githubusercontent.com/47131139/100827788-8f754f00-342b-11eb-9807-412eccc9820e.jpg)
![2](https://user-images.githubusercontent.com/47131139/100827789-900de580-342b-11eb-8d8b-60076d5928aa.jpg)
![3](https://user-images.githubusercontent.com/47131139/100827790-900de580-342b-11eb-80e3-7cb5652096b3.jpg)
![4](https://user-images.githubusercontent.com/47131139/100827791-90a67c00-342b-11eb-89d7-f9270d4897a7.jpg)
![G5000](https://user-images.githubusercontent.com/47131139/100835395-91dfa500-343b-11eb-9844-9a952bb9ae05.jpg)

If this could be solved it would make the topography more believable, IMHO.

Just my observation.

**Comment by cywang90** [comment]
We are somewhat limited with terrain colors since the game currently restricts us to one color every 500 feet, with no option to customize below sea level. Therefore it's pretty much impossible to get the nice gradients that you see on the real units. This is partly why there is a rather abrupt transition from the dark green to the yellow with no shades of yellow green in between. Nonetheless I'll be making another pass at the colors for the next g3000 release.

**Comment by DiBarkis** [comment]
> We are somewhat limited with terrain colors since the game currently restricts us to one color every 500 feet, with no option to customize below sea level. Therefore it's pretty much impossible to get the nice gradients that you see on the real units. This is partly why there is a rather abrupt transition from the dark green to the yellow with no shades of yellow green in between. Nonetheless I'll be making another pass at the colors for the next g3000 release.

That is very fine. You can see that you already have enough color allocations provided if it's one for every 500. If you look at the Garmin pics you'll see that it's almost the same. It's actually more limited because there is nothing less than 500 feet on the scale. Also On the default Asobo Garmins the blending is automatic, so I think if you get just the main colors and place them in their correct sequence, they'll be blended with the in-betweens automatically assuming you're using the stock asobo ones as your base.

You can see that on the scale it's as follows:

![key](https://user-images.githubusercontent.com/47131139/101207655-eef77880-363e-11eb-8857-48257fcd51a7.jpg)

So, excluding the lowest two colors that are below sea level, you should have:

0 - 500 = Green 
500 - 2,000 = Yellow (3 layers of the same color)
2,000 - 3,000 = Orange (2 layers of the same color)
3,000 - 6,000 = Brown 1 (6 layers of the same color)
6,000 - 8,000 = Brown 2 (4 layers of the same color)
8,000 - 10,500 = Brown 3 (3 layers of the same color)
10,500 - 27,000 = Grey ( 33 layers of the same color)
27,000 and above = White

And if they happen to not blend automatically, then at least you have 500 feet intervals to make your blends using your discretion. I could also help in picking out the most appropriate colors given the limitations we have. I have a good eye for color corrections having worked in a photographic lab for a long time). Might have solid boundaries but will still be good enough so long as the colors are in sequence.

Another thing is the sky color. A bit too dark on the default and on the WT g1000 and g3000. Should be lighter than the lightest terrain color (minus the white and maybe grey, of course).

Cheers and keep up the good work.

**Comment by cywang90** [comment]
The 500 feet limit is with the automatic interpolation. Ie if I define 500 as green and 2000 as yellow there will be exactly 2 interpolated values between them (at 1000 and 1500).

**Comment by DiBarkis** [comment]
> The 500 feet limit is with the automatic interpolation. Ie if I define 500 as green and 2000 as yellow there will be exactly 2 interpolated values between them (at 1000 and 1500).

I'm not sure I understand. Does it mean that the interpolations will each get another shade of color, say with 500 green, and at 1000, lighter, and 1500, lighter still, and closer to the yellow at 2000?

**Comment by cywang90** [comment]
Internally, the terrain colors are defined in steps of 500 feet at fixed intervals starting at 0 (so 0, 500, 1000, etc) . You can specify color definitions in a config file for an arbitrary number of elevations at arbitrary elevations, but these will be interpolated and resampled at the specific elevations mentioned above. So for example if I can set 0 to black and 1000 to white in the config, all elevations from 0 to 500 will show as black, 500 to 1000 as 50% gray, and 1000+ as black. If I try to set 0 to black, 250 to gray and 500 to white, it will simply ignore the 250 (because it will only sample at 0 and 500) and have 0 to 500 as black and 500+ as white. This limitation cannot be overcome with the code we have access to.

**Comment by DiBarkis** [comment]
Ok so I understood you correctly. So you can use the color scale I just gave you and have the system interpolate. Nothing anyone can do about the instant color changes until maybe Asobo improves their stuff. The most important thing is that the colors are in sequence. How it is right now, the darker green is in a higher elevation range than the lighter, and it should be be the other way, darker being lower. Just use the solid colors on the scale (minus the 2 lowest) and have the system interpolate, and then brighten the sky.

Other things I forgot to mention in my first post, I don't know if these are included in what you have access to or not, but I think the green annunciators (AP, YD, etc) and engine readouts, those that are in green, I think they are too dark. maybe a brighter green to match real life (see the included pic for reference). They should be the same or almost the same color with the flight path marker (airplane symbol in the middle), which brings me to the flight path marker, which I think is too small. Maybe enlarge a bit.
In the pic you'll notice that the greens are brighter and the FPM is a bit bigger. As for the AoA, I think it's different different aircraft, I'm not sure. You can see how it is on the picture, and color coded. That's for the Citation Longitude.

The reds too are too dark in-game, so maybe brighten them?

![GHD,_Citation_Longitude](https://user-images.githubusercontent.com/47131139/101222973-eca21800-3658-11eb-9e4e-003b9dfbe501.jpg)

**Comment by kmoze2001** [comment]
> ![GHD,_Citation_Longitude](https://user-images.githubusercontent.com/47131139/101222973-eca21800-3658-11eb-9e4e-003b9dfbe501.jpg)

This may qualify as the dumbest question ever asked, but how did you get the HUD working on the Longitude?  (He asks as he's literally using it for the first time ever on another screen...)

**Comment by DiBarkis** [comment]
> > ![GHD,_Citation_Longitude](https://user-images.githubusercontent.com/47131139/101222973-eca21800-3658-11eb-9e4e-003b9dfbe501.jpg)
> 
> This may qualify as the dumbest question ever asked, but how did you get the HUD working on the Longitude? (He asks as he's literally using it for the first time ever on another screen...)

this is the real life Longitude, not MSFS.

**Comment by DiBarkis** [comment]
I see the changes made to the color profile and this is wonderful. Thanks a lot. Now maybe the fpm can be bigger, as it is too little atm. Also the shade of green on the EICAS and PFD annunciators are still too dark. They should be the same color with the VOR/LOC bars and the fpm. Also, could we get the second option flight director, the cross? Like you guys did in the CJ4? Would be awesome.

Also, maybe we can get a cyan arc like the one in magenta on the pic, but used to show where our physical throttle is when AT is engaged. Would help to match our physical throttle to the in-game throttle position before disengaging autothrottle. But just like PMDG has done it, the cyan arc (or whatever color you choose) will only appear when you move your physical throttle while AT is engaged.

**Comment by cywang90** [comment]
Map colors adjusted with 0.4.0.
