### ISSUE TITLE
Question-  Latest G3000 version?

### ISSUE THREAD

**Issue by kmoze2001** [Working-Title-MSFS-Mods/fspackages#590]
When I go to the G3000 v. 3.2 page, it does NOT say it's the latest version, but when I do a "compare", I'm not seeing anything more recent.  Is 3.2 the current version?  (I'm writing this at 1248 Zulu on 3 DEC 20).

Also, is this even the proper place for questions like this?  If not, where would be more appropriate?  I'm still relatively new to Github, so I'm still figuring out things like even basic navigation, and while I _thought_ the "Issues" forum (is that even the right term?) was more for reporting on bugs, at the same time I'm not seeing anywhere else for simple questions.

Thanks,
KevyKevTPA

**Comment by cywang90** [comment]
0.3.2 is the latest version. You can find the latest version for all the mods in the main Readme on the front page of the repo. For asking questions, the best place would be the discord channel. You're more likely to get a quick response there. Link is also in the Readme.
