### ISSUE TITLE
G5000 Timer Start Button does not Display “Stop” When Timer is Active

### ISSUE THREAD

**Issue by SoCalDude** [Working-Title-MSFS-Mods/fspackages#591]
I’m using v0.3.2 of the G3000 mod and—after starting the time on the touchscreen (to the captain’s left)—the button doesn’t change to display “Stop”. It continues to display “Start”. 

However, the timer does work (at least counting up). To stop it, pressing the “Start” button stops it. It can be confusing. 

I’m flying the Longitude with the flight dynamics mod (v1.3).

**Comment by cywang90** [comment]
Fixed with 0.4.0
