### ISSUE TITLE
G1000 mod

### ISSUE THREAD

**Issue by daveji** [Working-Title-MSFS-Mods/fspackages#592]
Hello Github
          It seems that the G1000 mod is now not compatible with MSFS version 1.11.6.0. Asobo have fixed the autopilot fault introduced on the last update where the AP would not aquire or track a localiser,but the fault has reappeared if the G1000 3.2 mod is active.
The aircraft in use is the Baron.

**Comment by mattnischan** [comment]
Hi @daveji,

The localizer tracking issue is intermittent and has not been fixed yet in the most recent MSFS update. It will appear whether or not you have the mod installed at the moment.

If you have specific conditions under which you can get it to happen consistently, though, we'd be happy to pass along the report.

**Comment by kmoze2001** [comment]
I agree that's it's intermittent.  At first after the patch, I couldn't get the AP to track an ILS to save my life, but the last half dozen or so times I've tried it, it worked just fine, so I'm not sure what the issue might be.
