### ISSUE TITLE
FMS Keypad not lighted

### ISSUE THREAD

**Issue by deltabravo715** [Working-Title-MSFS-Mods/fspackages#595]
The FMS keypad has no backlighting. Is there any way to see the keypad in a dark cockpit ?

**Comment by dga711** [comment]
The keypad and lower CCP is not lit in the stock version. So I would check the mod is installed correctly on your side.

If the mod is installed correctly make sure you turn this knob up if starting from ColdandDark
![image](https://user-images.githubusercontent.com/2995606/101291417-d9ce4580-3808-11eb-9af4-0eef1c890969.png)
