### ISSUE TITLE
[G1000 Mod] Right and Left Fuel tank quantity displayed backwards.

### ISSUE THREAD

**Issue by Jsavga** [Working-Title-MSFS-Mods/fspackages#596]
The "R" for right tank quantity and "L" for left tank quantity in the MFD are reversed from real life G1000. This is a bug in the MSFS stock G1000 also. The way it should be displayed correctly is shown in this image:
![Screenshot (110)](https://user-images.githubusercontent.com/19418984/101295345-1ab76180-37eb-11eb-869c-de7d4e031aaa.png)

The way it's currently shown in the G1000 mod (which is wrong) is shown in the following image:
![Screenshot (109)](https://user-images.githubusercontent.com/19418984/101295423-a3ce9880-37eb-11eb-80bc-18d4c6fa9831.png)

Just a note that it displays the correct amount of fuel for the displayed fuel tanks, just they are displayed in the wrong place. Image shown is from the Bonanza.

**Comment by Jsavga** [comment]
Just a note that it displays the correct amount of fuel for the displayed fuel tanks, just they are dispalyed in the wrong place.

**Comment by kaosfere** [comment]
This seems to also be the case the the 0.4.0 beta, so I'm going to apply this to that milestone.   Thanks!
