### ISSUE TITLE
CJ4 Unable To Import FP / Unable to Enter Manual FP

### ISSUE THREAD

**Issue by lcortez13** [Working-Title-MSFS-Mods/fspackages#597]
Hi all,

Just got back into MSFS after about 2 months away. I updated my sim to the latest version and downloaded .07.3 into the community folder (Steam).

When I go to enter a departure or arrival airport and hit execute, I get stuck with a "Working..." message.

When I try to load my FP from Simbrief (followed the instruction manual), I put in my 5 digit PID, goes green, go to recall FP and it says loading FPLN, CLEAR FP. Nothing loads. 

Any ideas? Just found this project and im so excited to get the CJ4 up! Thanks all!

**Comment by dga711** [comment]
Can you give me examples for both problems?
Airports for the dep/arr problem? Are you on navigraph or stock data?
And the route you try to import via SimBrief?

With SimBrief, if you are not on Navigraph it is possible that the proposed route doesn't match data in the sim because SimBrief and MSFS then use a different AIRAC cycle. 
But to me it sounds more like there is a general problem with the airports.

**Comment by lcortez13** [comment]
I tried both with and without Navigraph, neither seem to work. Doesn't work on the POS INIT, DEP/ARR pages.

https://i.imgur.com/JdCOlYi.jpg
https://i.imgur.com/EVTBaPw.jpg
https://i.imgur.com/aeWqhlX.jpg
https://i.imgur.com/A5eIabe.jpg

Verified the correct folder placement inside the community folder as well.

Thank you!!

**Comment by dga711** [comment]
So. I just tried with your pilot id. On first press of FPLN RECALL I got an error (which sometimes happens as the sim doesnt return data fast enough). But on second push of FPLN RECALL it worked
![image](https://user-images.githubusercontent.com/2995606/101355947-a4bd0400-3897-11eb-9975-75622b0db878.png)

Everything else just works here
![image](https://user-images.githubusercontent.com/2995606/101356026-c322ff80-3897-11eb-934d-26346f984c84.png)

Is it only these airports? Do you have this problem with every/many route and airport?

**Comment by lcortez13** [comment]
Hmm, interesting. 

I tried it earlier with a different destination but BUR was always the origin. Am using OrbX KBUR, updated to the latest version. I haven't had any luck with errors happening every single time. I've also tried re-installing the mod several times. But even then, SFO was the origin on the example above.

**Comment by lcortez13** [comment]
I've tried removing the Cj4 from the content manager, reinstalling it. Uninstalled Navigraph and still no joy. Same errors.

**Comment by Epse** [comment]
Hi, sorry to necropost, but I am having the same issue now, latest update, latest msfs... I have tried a couple of different departure airports, but it's always stuck on the "working" step

Simbrief import or manual entry give the same result. This has been tested across a couple of different days / plans / sim restarts. Looks exactly like the poster above reported
