### ISSUE TITLE
CJ4 -Zoom doesn't work

### ISSUE THREAD

**Issue by fralbo** [Working-Title-MSFS-Mods/fspackages#598]
Hello,

Cannot decrease MAP range on PFD with -ZOOM, button only switch to +ZOOM side and so, range is 10NM.

Regards,

**Comment by slip664** [comment]
That's because it's done using this knob.

![unknown](https://user-images.githubusercontent.com/72432870/101526177-2cab1880-3941-11eb-9840-5429fcf2efac.png)

**Comment by fralbo** [comment]
Yes, sorry slip664, I didn't see that at first.
Thank you
