### ISSUE TITLE
CJ4: PFD controls affect MFD

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#599]
How to replicate:
1. Have the passenger briefing menu up on the MFD
2. Press "PFD MENU" and scroll down to "CONFIG"
3. Press the knob

It will now play the "oxyge masks" message since the knob controls both PFD and MFD.

**Comment by dga711** [comment]
Will be fixed in the coming update. Thank you for the feedback.
