### ISSUE TITLE
ucrtbase.dll crash when activating Approach Procedure.

### ISSUE THREAD

**Issue by VBHB** [Working-Title-MSFS-Mods/fspackages#603]
Hi I recieved a ucrtbase.dll crash when activating Approach Procedure.  This was my third attempt to load it as I am new to the GPS and figuring it out.  Any work arounds for this?

Full log entry:

Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x5fc94fca
Faulting module name: ucrtbase.dll, version: 10.0.19041.546, time stamp: 0x43cbc11d
Exception code: 0xc0000005
Fault offset: 0x0000000000024da8
Faulting process ID: 0x1d08
Faulting application start time: 0x01d6d1a197cc4f03
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.11.7.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 10038b4c-222c-4618-bbc6-5c7a415a7802
Faulting package full name: Microsoft.FlightSimulator_1.11.7.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by dga711** [comment]
This is probably not something we can give you support for.
But our new update 0.8.0 is coming very very soon which will use a custom flight plan manager, so maybe this shouldn't happen to you anymore.
