### ISSUE TITLE
[CJ4 0.80] FMS screen went black when trying to open ARR DATA page.

### ISSUE THREAD

**Issue by danielklepp** [Working-Title-MSFS-Mods/fspackages#604]
Title says it all really. 

Context: Was enroute to BIKF, noticed that i could only select Runway on the DEP ARR page (Not STAR or APP), selected the correct arrival runway, and when going to IDX > ARR DATA the fms went completely blank and nothing would get it back. Even after landing, turning off avionics and battery and back on again did not work.

I have the Navigraph navdata beta addon.

**Comment by matsout** [comment]
I've posted this at AVSIM as well, glad to see I'm not the only one.

When I select the ARR DATA page initially its viewable but as soon as I put in a origin AND destination the next time I select the ARR DATA page (where the vapp and vref data is) the entire FMC goes blank and I'm unable to recover it, the scratch pad works but the remainder of the screen is blank (both sides).

Now for something even stranger, the next time I start MSFS with the CJ selected after having this problem, I get most of the way through loading up a flight but then I get a complete blue screen of my entire computer.

The only way to break this cycle is to restart the pc after the FMC issue occurs and select a different aircraft initially, load the flight then exit back to the main menu and select the CJ, then it will load. Simply going back to the main menu and selecting another aircraft without restarting the pc does not work, I get a system crash no matter what aircraft is selected.

I've tried multiple different airports as origins and destinations and nothing changes it. I've also tried reinstalling the mod but to no avail. This page worked on the latest 0.7 release, I've only hit this problem with the 0.8 beta. The only other mods I have are the Garmin ones from WT and the famous bonanza mod. I also have the Iris Simulations Jabiru Installed.

 

Update: I've removed all other mods and uninstalled the Iris Simulations Jabiru and the problem still persists. I have no other 3rd party add-ons installed.

 

Regards,

Matt

**Comment by dga711** [comment]
@matsout thanks for the feedback.

now after 080 we have more time to look at the smaller bugs again. will check this one out.

about your bluescreen problem. i am not sure if we can help there. 
we have no other reports of that and i can't see our mod triggering that. and even if, would be hard to find out. but if you know more you can open up a new issue regarding that specific problem

**Comment by matsout** [comment]
No worries, I dont think the blue screen is a separate issue, through my testing I found it to coincide with the fmc problem

**Comment by dga711** [comment]
Ok. Then we will just try to fix this problem and hope your bluescreen goes away ;)

**Comment by danielklepp** [comment]
I tried another flight now, and now the ARR DATA page works fine.. Strange. Only change i made is i removed the Navigraph Navdata Beta (which has been working before).

**Comment by matsout** [comment]
Hmm strange. I don't have the Navigraph beta

**Comment by dga711** [comment]
We think in some circumstances or specifics arrivals/airports there is data (or data missing) which we don't account for.

**Comment by matsout** [comment]
I've tried YSBK, YBBN AND KLAX as destinations

**Comment by dga711** [comment]
Reproduced it and seeing the errors. Will fix for the coming patch. Thank you guys.
