### ISSUE TITLE
Cj4 v8.0 - Unabe to compute Vapp and Vref

### ISSUE THREAD

**Issue by ekaibab** [Working-Title-MSFS-Mods/fspackages#607]
Page 2 does not show Vref or Vapp.

**Comment by mattnischan** [comment]
@ekaibab A few questions:

- Did you select a departure runway in DEP/ARR?
- Did you input your winds into page 1?
- Did you input the temperature into page 1?

Without those three items, no speeds will show.

**Comment by ekaibab** [comment]
I thought all was entered.   But I tried it again,  and it worked. Sorry for the false alarm. BTW, VNAV into KSJC is great. Sent from mobile device. 
-------- Original message --------From: Matt Nischan <notifications@github.com> Date: 12/16/20  10:48 AM  (GMT-05:00) To: Working-Title-MSFS-Mods/fspackages <fspackages@noreply.github.com> Cc: ekaibab <ekaibab@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [Working-Title-MSFS-Mods/fspackages] Cj4 v8.0 - Unabe to compute Vapp and Vref (#607) 
@ekaibab A few questions:

Did you select a departure runway in DEP/ARR?
Did you input your winds into page 1?
Did you input the temperature into page 1?

Without those three items, no speeds will show.

**Comment by mattnischan** [comment]
@ekaibab Glad to hear it! I'll close this one out, let us know if you run into anything else.
