### ISSUE TITLE
[CJ4 0.80] Sync FP option noy possible to toggle

### ISSUE THREAD

**Issue by WinstonCh** [Working-Title-MSFS-Mods/fspackages#609]
First let me tell you that I adore the work you put into the project. It makes the whole sim considerably better for me. Thank you.

I love the 0.8 update so far, however, I would like to sync my FP to the VFR map and the sim, even considering it might be buggy. 

Contrary to stated in the known issues, I am not able to toggle the Sync option in the FMC. 

Is this a known bug or a user mistake?

Thank you.

**Comment by K20017** [comment]
Simple mistake in the code.  Has been fixed 👍

**Comment by WinstonCh** [comment]
Well, colour me impressed! Thank you!
