### ISSUE TITLE
G1000 PFD Color

### ISSUE THREAD

**Issue by guifarias31** [Working-Title-MSFS-Mods/fspackages#61]
Hi!
I just found out how to change the G1000 PFD color with SYN VIS off, since the default one is fairly inacurate:

Have a look: https://github.com/guifarias31/msfs_pfd_color_modification

![image](https://user-images.githubusercontent.com/70555403/93691134-aa385880-fab7-11ea-9d6d-b1fa2520f08e.png)

**Comment by knighty** [comment]
This is actually something I've already changed in the current dev branch for the G1000

![](https://forums.flightsimulator.com/uploads/default/original/3X/7/d/7dae1bb09de57849e3d3317bd5fe6884d79c0dae.png)

**Comment by guifarias31** [comment]
Nice, didn't see that.
