### ISSUE TITLE
CJ4 v0.8.0 FGS messages to improve.

### ISSUE THREAD

**Issue by taguilo** [Working-Title-MSFS-Mods/fspackages#618]
Hi,

A comment on some FGS msgs that are not correct, and easy to fix:

-ALTS in green when the Preselected Altitude is being held (currently displays ALT)
-ALTS CAP msg when Presel Alt is captured (currently displays ALTC).
-ALTS becomes VALTS when VNAV is active.
-When changing the Presel Alt in ALTS mode, it changes to ALT  (or VALT if VNAV active).
-If AP is ON, selecting VS will command and display the current VS (now it shows 0).

Great work indeed!

Tomas

**Comment by dga711** [comment]
We did a major overhaul of this for the coming update which should fix most of these suggestions. Thank you!
