### ISSUE TITLE
Blank FMS FPL page

### ISSUE THREAD

**Issue by CJ1driver** [Working-Title-MSFS-Mods/fspackages#619]
Hi there,

after i am done on the pos init page I go on the FPL page. As soon as I select that page the both fms go blank. If I enter anything I can still see whatever I am writing, but the rest of the FMS is just blank. I´ve tried all knobs on the FMS but there is no chance to go back to the index page. 

Thanks for your help!

**Comment by CJ1driver** [comment]
It seems like it only happens if I load a fligplan in the microsoft menu before loading a flight. I don´t have any problems when I insert the flightplan myself

**Comment by K20017** [comment]
What was your entire flight plan you loaded?  I can test it.

**Comment by CJ1driver** [comment]
How can i send that to you? I basically created a flightplan with simbrief. I downloaded it and loaded it before starting the flight. Worked fine in the previous version

**Comment by K20017** [comment]
Just copy the clearance here and tell us the exact steps you do to get it to happen.

**Comment by CJ1driver** [comment]
[EDDEEDDW_MFS_17Dec20.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5710502/EDDEEDDW_MFS_17Dec20.zip)

thats the flightplan above. i´ve created it with simbrief and downloaded it. Then I started the sim, pick the CJ4, load the flightplan, select a parking position and load the flight. So, once in the aircraft it doesn´t matter whether i start the engines first or go directly into the fms after turning the battery on. In the FMS i go through the POS Init Pag and set the pos. Then I either press FPLN on the bottopn right or the FPLN Knob (between Dir and Legs) and thats where both FMS go blank. No chance to get it back. When i press letters or numbers it shows them but no menu points at all. hope that clarified things

**Comment by K20017** [comment]
Do you have any other mods in your community folder besides the CJ4?

**Comment by dga711** [comment]
@CJ1driver i will look into this now.

just a little hint. you can directly import from simbrief in our fms. no need to get the file and import from the world map

**Comment by dga711** [comment]
Thank you for your report. We will continue the investigation in #653 
And please tell us which mods you are running. Thank you!
