### ISSUE TITLE
CJ4 v0.8.0 Flight Dirctor indication when selecting NAV (FMS)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#623]
I´m not 100% sure about this one here, cause I do not know the avionics in depth, but I noticed the following:

When selecting NAV as guidance source for the FD, without engaging the AP, the FD shows "wings level" and "roll mode" is displayed in the FMA.
From my undstanding the FD should also show the actual NAV guidance, even when the AP is not engaged.

Can someone confirm this maybe?

**Comment by captbillybob** [comment]
Same here. It's all aircraft at the moment not just the CJ4.

**Comment by dga711** [comment]
We will introduce a custom FD in 0.8.5 
This should fix this issue.
