### ISSUE TITLE
What exactly can go wrong when loading and saving flights on CJ4 0.8.0?

### ISSUE THREAD

**Issue by ArleiCapati** [Working-Title-MSFS-Mods/fspackages#627]
Hi all,
First of all, congratulations for the release. This is really impressive work. CJ4 is the only plane I use in MSFS these days.

In 'Known Issues' section in release notes of 0.8.0 I read that "loading and saving flights can occasionally have bad results". Since I have only about 1 hour to play everyday, the ability to load saved flights is a must. But I'm having a hard time trying to load flights (happened with latest stable version also - 0.7.3). When I read about this in the Known Issues section, I started to wonder if this can have some connection with my (bad) experience.

The issue I have is that as soon as I open a .FLT file (World map > Load/Save > Select .FLT > Click OK), the Sim CTD on me. This happens even before displaying the route on the World map which makes me believe something in the “plan” part of the flight could not be processed/resolved by the Sim. When that happens, an entry is added to the event viewer but that does not help much (no details that can help troubleshoot).

What I do is this:
1 - Plan the flight in SimBrief.com
2 - Fire up the Sim and, using the World Map, select origin and destination
3 - Save the plan (PLN) while still on the map
4 - Save the flight (FLT) while still on the map
5 - Start the flight
6 - Import the flight plan from SimBrief using the FMS
7 - Takeoff and fly for some time (like 40 or so minutes)
6 - Save the flight
7 - Next day, fire up the Sim and try to load the file and then... CDT

I would appreciate if somebody could tell me if what I'm experiencing can be related to the save/load flight issue mentioned in the "Known Issues" section. What exactly are the "bad results" mentioned?

Thank you.

**Comment by dga711** [comment]
So. We brought this up as we didn't fully test loading/saving.
Problems i can see coming up
- We are not using the game's flight plan manager anymore. And synchronizing with it is not perfect. So it may very well be that on load your flight plan in the FMS will be empty
- We are managing the autopilot states with custom vars now to do our own. It could be no problem, but I am just not sure if the load will set back the correct modes.

Of course we would love to be fully compatible with the game. But it is very hard to do, if not impossible when you are developing your own in depth systems. But we try as much as we can. And also hope that in the future when the SDK adds more possibilities for this it will become better.

Afaik in the past with other flight sims and fully customized planes, they also had to say goodbye to many of the sim's features and do their own.
