### ISSUE TITLE
VFR Map Route missing

### ISSUE THREAD

**Issue by cubensos** [Working-Title-MSFS-Mods/fspackages#628]
In the previous version when i activated NAV mode after setting a Direct To Airport, i got the pink route. 
in 0.8.0 it is missing. i am a noob and don't know how to enable it on my own, so i fly a ILS approach, but can not see the route.
sorry, if this is not an issue.

**Comment by dga711** [comment]
Do you mean the VFR map window?

As we run our own flight plan system atm it doesnt synchronize back to the game (because its hard to do in a good way). So the VFR Map doesn't update. As is ATC.

To check your plan you should use the map on the MFD/PFD in PLAN mode.
