### ISSUE TITLE
[CJ4 v0.8.0] STAR Altitude Constraint Cancellation

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#629]
**Precondition**
- Load STAR
- Enter manual altitude constraing on STAR waypoint
- Start VNAV descend
- Load Approach

**Expected Behavior**
- VNAV descend is continued considering the STAR constraint

**Actual Behavior**
- The STAR constraint is removed
- VNAV descend changes to VPTCH

**Comment by taguilo** [comment]
Hi,
That is the correct behavior. If during VPATH descent any further altitude constraint is changed, either to a valid/invalid value, VPATH reverts to VPTCH.

**Comment by mattnischan** [comment]
@taguilo I believe the problem referenced is that a constraint on the STAR disappears, even when not changing the STAR specifically. This may be due to a data persistence problem when changing procedures, we'll have to take a look.

**Comment by cwburnett** [comment]
@sfdeham a video might help, but we suspect what has happened is that if you add or change the approach or arrival in any way, it can cause the procedure to reload as it loads the runway transition leg of the arrival. When the procedure is re-loaded, the data from the STAR is erased and rewritten. We will double check real behavior, but this is currently a limitation of how procedures are loaded. If this wasn't the case, a video would help us understand. Thanks.

**Comment by taguilo** [comment]
"_When the procedure is re-loaded, the data from the STAR is erased and rewritten_" That is the correct behavior. If you reload a STAR that includes manually added constraints, those are lost. No matter that, any time a STAR/APPR procedure is changed/reloaded during a VPATH descent mode, it reverts to VPTCH.

Hope this helps.

**Comment by sfdeham** [comment]
@cwburnett Your issue description is correct. @taguilo underlines your statement. Issue can be closed from my side. Thank you!
