### ISSUE TITLE
CJ4: Setting Heading via FSUIPC Command not working anymore

### ISSUE THREAD

**Issue by Beginner314** [Working-Title-MSFS-Mods/fspackages#630]
Set a Heading value with FSUIPC 0x7CC (according to https://youtu.be/aswny5xjCPA?t=362)
does not work anymore with v0.8.

The Heading indicator jumps around and/or skips values.

Setting the Altitude & Speed (done/calculated in a similar way, also in the YT-Video) does still work.

**Comment by mattnischan** [comment]
@Beginner314 - As noted in our known issues for the 0.8.0 release, hardware, external programs, and key bindings may have problems with the new autopilot system. We are aware of the issue and looking for workarounds at this time.

It may be that we need to wait until SimConnect supports LVars again until this can be resolved, but we're looking at other options.

**Comment by dga711** [comment]
@Beginner314 The game manages several slots for values like heading (for different modes) 

I don't know too much about FSUIPC but you would need to make it so heading gets only set into SLOT 1
Is that possible?

**Comment by Beginner314** [comment]
@dga711 I don't know, I set the value via an FSUIPC Offset in Mobiflight (see the video in my opening Post of creating this issue). I don't see anything related to "Slots" or "Indexes".

Unfortunatly I also don't know much more about FSUIPC. Maybe a limitation of Mobiflight, BUT:
It worked fine with the Working Title CJ4-Mod (used it since v0.4 or v0.5) until v0.7.x, but not anymore in v0.8.x

**Comment by dga711** [comment]
@Beginner314 Since we changed a lot of autopilot things in 0.8.0 and customized a lot of it some external dependencies are broken for now.
I will do some research on fsuipc and slots.

**Comment by dga711** [comment]
Afaik in FSUIPC you should be able to send parameters which could be used to assign the slot. I really don't know if Mobiflight supports that though. You should try asking in that community.

**Comment by Beginner314** [comment]
@dga711 Thx. Don't worry, I fully understand that things will break with a big change like you guys did with v0.8.

jJust reported it as a bug for documentation. I don't expect it to be marked as high priority ;-)

**Comment by IslandJohn** [comment]
SimConnect events for changing heading bug (and ALT, VS, speed) work (I'm using them through FSUIPC) in 0.8.3.

**Comment by Hitchhiker79** [comment]
I am using a Logitech Flight Multi Panel and I've been trying to set it up via SPADneXt with little joy. Heading bug, altitude, and VS rotary knob changes are straightforward, but the HDG, NAV, IAS (in lieu of FLC), VS, and APR buttons have been impossible to set up.

**Comment by IslandJohn** [comment]
Those buttons used to work in 0.7.x, but stopped in this latest version.

**Comment by Hitchhiker79** [comment]
Thanks for confirming. Would it be possible for the devs to use MSFS 2020/simconnect variables that could be programmed into SPADNeXt? Love the work that's gone into this project and it would be great to use the flight panel with this plane.

**Comment by mattnischan** [comment]
Until the MSFS SimConnect API supports L-Var access, it will not be possible for any advanced third party aircraft to be able to sync completely with any partially customized or fully custom AP implementations.

Even with a full custom autopilot using the correct key events, external aircraft code cannot write to the sim autopilot mode variables, and must use their own L:Vars. This has always been the case with ESP platform sims (FS9, FSX, P3D), but in the past you could access those local variables with SimConnect so you could read and/or write custom AP modes.

At current this is not possible, so it's something we'll have to wait for support for.

**Comment by Hitchhiker79** [comment]
Thanks for the explanation Matt. Will look forward to when this happens!

**Comment by mattnischan** [comment]
Of course! Always happy to explain, I wish the news was better. I'm sure it won't be long until that support shows up, though.

**Comment by dga711** [comment]
Added a wiki page explaining the simvars used https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables

External binding apps are adding support for LVars and H Events via ingame modules. Nothing we can do right now.
