### ISSUE TITLE
Approach problem on cj4

### ISSUE THREAD

**Issue by loulaconico** [Working-Title-MSFS-Mods/fspackages#631]
Hello,

I got this problem since the last update v7.3 and I thought it got fixed on v8.0 but it is not. I tried searching similar concerns that I have but i can't find similar or related situation like mine. So, Now I am starting to wonder if it is only me who is having this problem. I also wonder if my game is broken. I tried reinstalling the mod but problem still persists.

Anyway my problem is everytime I reach my approach destination whether it is an ILS or Loc ( i seldom use VOR) the waypoints suddenly vanish from the map and display. Then AP just go straight and dont know where to go. Even if i tried to reactivate the approach type and transistion still AP won't follow the plan. I also tried to manually input all waypoints or reactivate approach legs and still no luck.

I use navigraph or little navmap for my flight plan maybe that's causing it? Should i reinstall my game? Or should i manually input my flight plan preflight? Thank you

**Comment by K20017** [comment]
Is your navigraph up to date?  I've never heard of the approach waypoints disappearing.

**Comment by loulaconico** [comment]
Yes it is updated. Last night my last flight did the same thing. I tried to reactivate the approach but AP just keep going straight. Then i tried to direct the waypoint to the next approach leg and still the same. Any suggestion on what to do?

**Comment by mattnischan** [comment]
@loulaconico This should be addressed in 0.9.1. Please let us know if you still get this problem and we can reopen this issue.
