### ISSUE TITLE
CJ4 0.8.0 - Cannot insert Airways

### ISSUE THREAD

**Issue by felipe-mendes-msfs** [Working-Title-MSFS-Mods/fspackages#633]
Hello.
The issue already happened with me twice. Here's what happens:

Flight Plan
SBVT - SBCF
BUVIM1B Departure, OPLOX Transition, UZ34 Airway

The departure insertion do not have any problem, but when i try to insert the airway in the page 2, i get the message "NO AIRWAY MATCH" in the FMC, as the picture shows.
Just for clarify, the OPLOX intersection is a fix of that airway, so i should have no problem to insert it.
Can you check it please? Thanks for your great work!

![20201216_190209](https://user-images.githubusercontent.com/74080321/102560834-f80e2e00-40b1-11eb-9654-3c5f1268d1ed.jpg)
![20201216_190221](https://user-images.githubusercontent.com/74080321/102560827-f5133d80-40b1-11eb-929a-5feae8f38024.jpg)

**Comment by slip664** [comment]
As a workaround for now, you can always enter the next waypoint on that airway TEDOL into the FPLN and put in your airway from there.

**Comment by dga711** [comment]
I think we have a problem connecting airways when the last departure fix is an entry. Will check.

**Comment by dga711** [comment]
This is fixed in an earlier version already. Closing.
