### ISSUE TITLE
CJ4 0.8.0 - Blank FMS Screens

### ISSUE THREAD

**Issue by med11043** [Working-Title-MSFS-Mods/fspackages#634]
Recently while climbing up to my cruise altitude I decided to poke around in the FMS.  I clicked on the Index page (IDX), and then the LSK next to Arrival Data (ARR DATA). As soon as I did, both FMS screens went black, and they never came back for the duration of the flight, no matter which buttons I pressed.

I'm not sure if ARR DATA is not implemented yet, or this is normal, but I figured I'd report it in case nobody else has.

**Comment by Beginner314** [comment]
Same happened to me yesterday.

**Comment by slip664** [comment]
Known issue. Already addressed.

**Comment by dga711** [comment]
Already fixed via #606
