### ISSUE TITLE
CJ4 v0.8.0 - Legs Tracks Showing Negative Bearings

### ISSUE THREAD

**Issue by efortier-95** [Working-Title-MSFS-Mods/fspackages#635]
Reposting my Discord comment:
I noticed on a simbrief-imported flightplan, it read a track of 353 degrees as 0-7 (for example), in the legs page (and I think on the PFD and MFD, though that was a few hours ago and my memory is a bit hazy now)
If it helps recreate the problem, it was 
- an imported flightplan from CYYC to CYEG, 
- FL340, 
- routing was: BITGA Q995 OILRS OILRS2
- I chose a departure of STAMP9 off runway 35L
- Arrival, approach, and landing runway not selected

**Comment by cwburnett** [comment]
Fixed for next update
