### ISSUE TITLE
Take offs not being logged

### ISSUE THREAD

**Issue by roughapproach** [Working-Title-MSFS-Mods/fspackages#637]
Hi,
Everything's working fine for me in the CJ4 v0.8.0 but I noticed that in my logbook, departure airports, arrival airports, flight times and landings are being recorded but the take offs are not. I import my flight plans from Simbrief directly into the FMS without issue and do not use the MSFS planner beyond loading a parking position from which to start. Starts were all cold and dark on the ramp. Repeatable issue. It's no big deal but just thought I'd mention it.
Keep up the brilliant work guys.
Cheers

**Comment by cwburnett** [comment]
On hold while we research whether this is something we can control.
