### ISSUE TITLE
CJ4 V 0.8.0 - Aural overspeed warning (still under shown limits)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#639]
During my descent to CYYR I hit 275 kts with M.0781 and I got an aural overspeed warning.
I´m not sure if this is maybe a wrong activated warning ? According the indications I was well below an actual overspeed.
I took a screenshot, when it happend.

![aural overspeed](https://user-images.githubusercontent.com/71773282/102645295-8b9f3780-4162-11eb-962f-e04258d574d1.jpg)

**Comment by nikilase** [comment]
I had it the other way around. Was cruising at FL420, BARO on STD, with about 240-245 kts at about M.75 to M.76. The red tape began at 235 kts but I did not get an overspeed warning. 

Second time I tried it the beeping alarm went of at around M.76 but no voice saying overspeed.

**Comment by K20017** [comment]
The red overspeed tape you see is erroneous.  The overspeed warning is triggered by some detection which bases it on mach/IAS.  Max mach is .77 and you can see the digital mach readout below the airspeed tape is above that. I've looked into a quick fix but it seems a little more complicated. Also the overspeed words are removed as they don't exist in the real thing, it's just the beeper.

**Comment by mattnischan** [comment]
This has been fixed (finally) in 0.9.1. The aircraft correct overspeed limits are now displayed and triggered properly.
