### ISSUE TITLE
G1000: VORs green color

### ISSUE THREAD

**Issue by ccapilot** [Working-Title-MSFS-Mods/fspackages#64]
Would like to request an improvement regarding colors when using VOR.
So in the real unit when VOR1 is selected (with CDI), the course should be in green as well as the active NAV1 frequency with the corresponding VOR identifier should be green color. (NAV 2 freq and identifier in white)
same thing happens when VOR2 is selected, the course should be in green as well as the active NAV2 frequency with its corresponding identifier should be the same green color. (NAV 1 freq and ident in white)
when CDI is set to GPS then it should be back to what we have now, so the course is in magenta and both NAV frequencies and identifiers are white in color.
Thanks.

**Comment by kaosfere** [comment]
I think this is working correctly now in our 0.4 beta build, but I'll verify that before closing this.
