### ISSUE TITLE
Range rings seem to be wrong

### ISSUE THREAD

**Issue by paweld303** [Working-Title-MSFS-Mods/fspackages#641]
I'm not sure I understand it correctly, but I think range rings are not correct. Please have a look at attached picture.
Distance to fix ALAGU is 38.2 nm, and on ND map it's outside of 40nm ring. So it's like rings and track are not to scale.

![Wrong_distanceRing_cr](https://user-images.githubusercontent.com/76227629/102656618-6e736480-4174-11eb-866c-04eb3193ea71.png)

**Comment by K20017** [comment]
They are incorrect but it's very complicated to fix and will have to do it at some other time.

**Comment by dga711** [comment]
This should be fixed / or more accurate in the coming update.
