### ISSUE TITLE
CJ4 / Question about MFD -> Memory function (1,2,3)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#646]
Hey all,

I have a question about how to store a created MFD setup to the MEM 1,2,3 buttons.
Saw this is a recent video on Youtube about the V. 0.8.0 and I was able to store one setting.
After a while all three buttons have showing the same picture without any changes.

My idea was to store a created setting by depressing and hold one of the buttons, so that it will store this setting on it (not sure if this was correct?) Anyhow somehow this wasn´t working for me at all.
Like in the video I´d like to save three different settings for a specific part of the flight.

As well I would like to know, if these settings are stored for later flights, after closing the Sim!?

Cheers

**Comment by dga711** [comment]
The setting is persistent and should be stored over several flights.

You have to setup the view on your MFD and the hold the MEM button for about 3 seconds.
The change the view and do the same with another MEM button.

Now when you just short press the buttons they should recall the view you have set

**Comment by Jack737800** [comment]
Cheers will give it a try :)
By chaning the view you mean, have a look around the cockpit, or chance e.g. from cockpit to exterior view?

**Comment by dga711** [comment]
No I mean, the modes you want to see on the MFD.
Rose/Arc/PPOS/PLAN ... Terr/WX ... FmsText/Systems.

You can customize the stuff you see on the MFD and save that layout

**Comment by Jack737800** [comment]
Ok, think it´ll work....did my setup for all three and will try it later, if these setting are still available :)

Thanks
