### ISSUE TITLE
Waypointloader.js and XMLLogic.js may conflict

### ISSUE THREAD

**Issue by pimarc** [Working-Title-MSFS-Mods/fspackages#647]
The Waypointloader.js in html_ui\Pages\VCockpit\Instruments\Shared\FlightElements may conflict with other MODs (and it seems to) since you didn't personalize it in a dedicated directory (ex html_ui\Pages\VCockpit\Instruments\Shared\WT\FlightElements).
I'm the builder of the GNS530 Mod and some users reported conflict with your MOD. On my part, I do not replace any original ASOBO source file, everything is in personalized folders.
Maybe same issue for XMLLogic.js

Thank you if you can check that quickly.

**Comment by dga711** [comment]
Hi. Yeah sorry for that. It was a stray file we didn't mean to distribute anymore.
It will be gone with our 081 patch that should be coming today.

**Comment by pimarc** [comment]
Thanks for your reactivity.
XMLLogic.js also ?

**Comment by mattnischan** [comment]
@pimarc Yes indeed, both of those will be removed from the next release. :-)
