### ISSUE TITLE
CJ4 V 0.8.0 - UI sound settings don't apply to plane

### ISSUE THREAD

**Issue by stb62** [Working-Title-MSFS-Mods/fspackages#649]
Whatever UI setting is used (master volume e. g. 20, 50 or 100 %), the sound volume in the plane doesn't change according to these UI settings.

**Comment by dga711** [comment]
@stb62  We can only confirm this for some engine sounds in the external view. Is that what you mean?

This will be fixed in 0.8.1

**Comment by stb62** [comment]
Maybe that gave me the impression that there was noch change to the other internal sounds. I will check later in the day, if it is just the wind.

**Comment by dga711** [comment]
We now fixed
- External Engine Sounds
- Inside Wind
- Inside Spoiler Drag

Feel free to reopen the issue if something is still not working when 0.8.1 released. Thank you!
