### ISSUE TITLE
LNAV/VNAV/DME/ILS issues

### ISSUE THREAD

**Issue by TomL7753** [Working-Title-MSFS-Mods/fspackages#650]
Routing: EKCH22R KOPE1C KOPEX DCT MARIP N850 BOGMU BOGM1P EDDH23

The flightplan was inserted via simbrief import.

1. LNAV was o.k until reaching KOPEX, instead of turning left to MARIP the aircraft turned right

2. I tuned ALF VOR (115.80) into NAV2 - no indication (Database?)

3. No DME reading for ILS 111.50 into Rwy23

4. On the second flight the wind on approach changed from approx. 200°/25 kts to 200°/7 kts, the aircraft therefore drifted to the left and wasn't able to get back onto the localizer in a timely manner (in approach mode)

5. On the BOGMU1P transition VNAV seemed to be recalculated with each intersection/waypoint with very noticeable changes in pitch attitude. A little smoothing would be fine I think. On the other hand lateral navigation was spot on.

**Comment by TomL7753** [comment]
Had the same issue on AMLUH Departure out of EDDH: Upon reaching AMLUH Acft was supposed to turn right to first enroute waypoint DENIX but turned left (towards the deviation bar of the HSI which was in FMS mode and sprang to the left as the acft was left of desired track). So maybe someting about turn anticipation? Just guessing.

**Comment by TomL7753** [comment]
Regarding the DME reading: ILS 11.50 has no DME, DME is ALF (115.80). It's in the database, shows on world map and in the FMS. Checked with vanilla Cessna G1000, DME reading is there. Tried several times with CJ4 - nada.

**Comment by dga711** [comment]
Since LNAV and VOR handling has been reworked for the coming update, will close this issue for now.
If the problem persists, feel free to reopen.
