### ISSUE TITLE
CJ4 - Thrust behavior while taxiing (Question/Bug?)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#651]
Hey guys,

I´m wondering all the time about it and I couldn´t find any documentation about it, that´s why I need to ask you :)

Anytime I start my taxiing and I advance the throttle up to let´s say 40-50 % N1 to get it going, initially afterwards there is a kind of decreasing and after about a second an increase. Is this normal for this type of aircraft, I mean the CJ family ? I´m rated on another smaler Jet and we do not have this kind of behavior.

**Comment by nrcrate** [comment]
Last I mentioned this, I was under the understanding its a simulator issue with how they model the engine.

**Comment by dga711** [comment]
The problem is in the sim.
Seems like it runs a PID loop on throttle to hit the target power. This PID often overshoots by a lot then bounces back down until it settles.
For now it doesn't seem likely that we can fix this.
Thank you for your feedback though.
