### ISSUE TITLE
LNAV acting erroneous on Airway entry (0.8.1)

### ISSUE THREAD

**Issue by armankir** [Working-Title-MSFS-Mods/fspackages#654]
After departing out of KPDX today (Radar Vectors BTG, J1 to SEA) I engaged LNAV, I was instructed by control to go direct to BTG and enter the J1 airway. 

The AP began making turns similar to the image I will link below (credit Lawson#5085 on Discord for the image)

https://cdn.discordapp.com/attachments/767761280366805022/789997188259512350/unknown.png

Despite 3 disengagements and tries, the AP continued to make the erroneous turning thus resulting in me disconnecting from the network and abandoning the flight.

**Comment by mattnischan** [comment]
@armankir We fixed several lnav bugs based on this and other reports. You should not see this now in 0.9.1.

Let us know if you still get this problem in this situation and we can reopen this issue.
