### ISSUE TITLE
G1000 Speed bug labels don't appear until TMR/REF pressed

### ISSUE THREAD

**Issue by benpeart** [Working-Title-MSFS-Mods/fspackages#659]
Now that the G1000 settings are persisted between flights, I noticed that the speed bug labels don't actually display until I press the TMR/REF button even though they are persisted as "on."

**Comment by Jessidhia** [comment]
Same as https://github.com/Working-Title-MSFS-Mods/fspackages/issues/303 :)

**Comment by kaosfere** [comment]
Thanks for the report!   I'll close this as a dupe since we already have a commit against #303 .
