### ISSUE TITLE
Systems froze

### ISSUE THREAD

**Issue by cadebusto7** [Working-Title-MSFS-Mods/fspackages#661]
![image](https://user-images.githubusercontent.com/76274294/102705455-c336de00-424d-11eb-92b9-f3b2d0aad844.png)
It was on a turnaround leg and on finally ILS 14 KSTP no systems work everything froze

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
