### ISSUE TITLE
0.8.1 VNAV doesn't level off at cruise altitude

### ISSUE THREAD

**Issue by ilgrillo28** [Working-Title-MSFS-Mods/fspackages#662]
Maybe my bad?
https://youtu.be/6ep3_M0hk2E

**Comment by ilgrillo28** [comment]
Maybe because it doesn't intercept che VALTC, but it's stucked to the VPITCH.

**Comment by cwburnett** [comment]
Yea, if you don't see either ALTS or ALTV in the armed line in white, you know it won't stop at the altitude. You need to make sure you're in VS or FLC if you want to intercept the alt, but you were in VPITCH.
