### ISSUE TITLE
v0.8.1 - FLC dropping out multiple times during climb out from t/o.

### ISSUE THREAD

**Issue by kjwebb237** [Working-Title-MSFS-Mods/fspackages#663]
Hi

First flight with the CJ4 mod v.0.8.1 (after having completed 10 flights with v.0.8.0). 

Manually entered flightplan for EGNM to EGJJ (cruise at FL300) - t/o and tracked STAR OK, climbing out in VS at 3,000 fpm. Switched to FLC at 240kts IAS at about 6,000 ft.  FLC dropped out at 9,000 ft - I switched back to VS climb and then re-engaged FLC (240 kts) at 12,000ft - dropped out again at approx 14,000 ft. I repeated switch back to VS climb and re-engaged FLC (240 kts) at 17,000 ft -  dropped out again at 18,500 ft.

Did not experience this problem in any of the flights with v.0.8.0.

**Comment by dga711** [comment]
Did your flightplan contain any constraints at 9000ft etc. ?

**Comment by dga711** [comment]
Will close for now as there was now followup.
