### ISSUE TITLE
CTD during take ofgf EBBR to EDDL

### ISSUE THREAD

**Issue by Bas756** [Working-Title-MSFS-Mods/fspackages#664]
VERSION MOD   CJ4 0.8.1    G1000 3.2
PHASE OF FLIGHT: during Climb after the take-off RWY19 EBBR
AP ON/OFF: AP on
VNAV ON/OFF: VNAV off
WHAT FMC PAGE: Legs
WHAT AUTOPILOT MODES (FMA):  NAV  / VS 
DO YOU HAVE NAVIGRAPH DATA INSTALLED?:  yes AIRAC 
DESCRIPTION OF THE EVENT - WHAT WERE YOU DOING/WHAT WAS THE PLANE DOING WHEN IT OCCURRED:  seems there was  ATC call probable a Handoff from the Tower, just hear a crack, and the screen freezes, and than CTD

**Comment by crisk73** [comment]
Same CTD but different airport: default LOWI
VERSION MOD CJ4 0.8.1 G1000 3.2 G3000 3.2
PHASE OF FLIGHT: during Climb after the take-off RWY26 LOWI
AP ON/OFF: AP off
VNAV ON/OFF: VNAV off
WHAT FMC PAGE: Legs
WHAT AUTOPILOT MODES (FMA): NAV
DO YOU HAVE NAVIGRAPH DATA INSTALLED?: yes AIRAC 2013 rev.4
DESCRIPTION OF THE EVENT - WHAT WERE YOU DOING/WHAT WAS THE PLANE DOING WHEN IT OCCURRED: was in the takeoff climb, manual flight trimming to the desired attitude to engage AP. The sim frozed and then CTD.

**Comment by dga711** [comment]
please put those into #608 
i will copy them there

thank you!
