### ISSUE TITLE
CJ4 v0.8.1 Range knob rotation direction to zoom or expand view.

### ISSUE THREAD

**Issue by Pickafivestring** [Working-Title-MSFS-Mods/fspackages#666]
Maybe it's this way in the actual aircraft, but works opposite to most devices, aviation or otherwise.

Issue:  Rotating ND range knob clockwise expands the view out, increasing displayed range.  Rotating ND range knob counter clockwise zooms the view in, decreasing displayed range.

**Comment by dga711** [comment]
calling @K20017

**Comment by K20017** [comment]
Spinning clockwise will increase the range and is the correct behavior for the PL21.
