### ISSUE TITLE
G1000

### ISSUE THREAD

**Issue by legacy2039** [Working-Title-MSFS-Mods/fspackages#667]
When changing frequencies on NAV or COM, the selector will delay when finished and then skip to the next number without user input.  Most common on the last significant digit and repeatable.  This applies to ver 0.4.

**Comment by kaosfere** [comment]
Just for reference, how are you changing the frequencies?  Scroll wheel?

**Comment by legacy2039** [comment]
Yes, I'm using a scroll wheel.  I don't recall if i tried using the mouse
clicks.  It almost feels like there is a 1sec delay for the last click
over, if that makes sense.  It was noticeably different from ver 3.2 from
my experience.
