### ISSUE TITLE
CDT on departure when activating vnav, v0.8.1

### ISSUE THREAD

**Issue by inphinitum** [Working-Title-MSFS-Mods/fspackages#669]
Hi,

This has occurred now like 6 times. I reverted to 0.7.x to see if the problem was something else but it seems to be v0.8.1. I configured a flightplan, AP on vs +3000fps, and shortly after departure I activate vnav. At some point I get CTD. Yesterday I managed to do without the CTD, and I believe it's because I didn't activate vnav until much later in the process.

Will keep trying to see if my hypothesis holds.

**Comment by inphinitum** [comment]
Saw a main thread for reporting CTDs, moving it there

**Comment by dga711** [comment]
Thank you! 👍
