### ISSUE TITLE
CJ4 0.7.3 - 0.8.1 COM issue

### ISSUE THREAD

**Issue by Cugix** [Working-Title-MSFS-Mods/fspackages#674]
When setting an ATIS frequency on COM2, while having COM1 selected in the ATC Window, the ATIS will not come through.
When setting an ATIS frequency on COM1, while having COM2 selected in the ATC Window, the ATIS will come through.
Even when both frequencies are being listened to the above is true (not muted nor deactivated).
This is only the case in the CJ4.

**Comment by dga711** [comment]
From what we can see atm the COM selection is not wired up correctly in the CJ4 even in stock.
We will try to take care of it soon.

**Comment by dga711** [comment]
Will be fixed in the coming 0.8.5 release
