### ISSUE TITLE
CJ4 0.8.1 AP stops tracking flight plan

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#675]
I have encountered this a couple of time and just finished a flight where it happened again. On the approach, after having turned toward the next waypoint AP stopped tracking and continued turning. Toggling AP puts it back on track again. I remember the FBW A320 mod had the exact same issue some versions ago so it's perhaps the same issue here.

**Comment by mattnischan** [comment]
Hi @AndersHogqvist,

Can you give us the route and what waypoint the plane stopped tracking at so we can try and reproduce it? Thanks!

**Comment by AndersHogqvist** [comment]
Sorry, missed that. The route: EDVE/26 POVE7W POVEL L986 MAG N746 GUDOP Z717 KUNER B709 TIGNU M155 VALUV VALU2C EYPA/NAPUS.I19

And AP stopped tracking after turning towards IAF (passing NAPUS)

**Comment by mattnischan** [comment]
@AndersHogqvist We fixed a few lnav bugs based on this and other reports. You should be good now in 0.9.1.

Let us know if it happens again for this case and we can reopen this issue.
