### ISSUE TITLE
CJ4 0.8.1 and newest MSFS update Cockpit model missing

### ISSUE THREAD

**Issue by WinstonCh** [Working-Title-MSFS-Mods/fspackages#676]
Dear all,

the most recent update of MSFS seems to break the interior model incl. the cockpit of the CJ4. When the mod is in the community folder the model will not load. Upon removing the mod folders the default CJ4 model loads as expected. 

No other liveries or mods affecting the CJ4 are installed. 

Thanks for your great work! It's really appreciated

**Comment by dillten** [comment]
```tinygltf: File size mismatch : SimObjects\Airplanes\Asobo_CJ4\model/CJ4_Cockpit_LOD00.bin, requestedBytes 23950080, but got 11922208```

**Comment by GertBFrobe** [comment]
I get the same.
Latest MSFS patch installed then reboot. No 8.1 in comm folder CJ launches
fine. 8.1 in comm folder and I get the Wonder Woman glass plane, sans Gal
Gadot (too bad).

**Comment by mattnischan** [comment]
Hi all,

We are aware of the aircraft breakage with the latest update and are working on some fixes. We do not currently have an ETA.

**Comment by WinstonCh** [comment]
Not a problem @mattnischan. You and the team are doing the most amazing work, least thing I can do is wait for a while. 

Thanks
