### ISSUE TITLE
Working Title CJ4 0.8.2 CTD

### ISSUE THREAD

**Issue by shank3001** [Working-Title-MSFS-Mods/fspackages#680]
I am getting a CTD shortly after takeoff KLAX to KSAN. I am using a red livery with no panel.cfg. I remove the mod and I get no CTDs. I am programming the FMS manually.

**Comment by cvitre23** [comment]
PHASE OF FLIGHT: DESCENT
AP ON/OFF: On
VNAV ON/OFF: ON
WHAT FMC PAGE: LEGS
WHAT AUTOPILOT MODES (FMA): LNAV1/VNFL
DO YOU HAVE NAVIGRAPH DATA INSTALLED?: Yes (2013 rev.5)
GPU NVIDIA OR AMD?: Nvidia 2066, driver vers 460.89
SCENERIES INSTALLED?: none
DESCRIPTION OF THE EVENT - WHAT WERE YOU DOING/WHAT WAS THE PLANE DOING WHEN IT OCCURED:all the flight works perfect, at a moment i was looking a video on youtube, then youtube give me an insuffisant memory to play the video (!?).. chrome crash ..... then CTD

Crash dump MSFS: https://gofile.io/d/YLBSgq
Crash dump Chrome (if needed): https://gofile.io/d/VP5fBO

**Comment by dga711** [comment]
@shank3001 @cvitre23 
do you guys have either "fp sync on" or use "fpln recall (game)"?

**Comment by shank3001** [comment]
FPSYNC is OFF

**Comment by shank3001** [comment]
Did another flight, hit first waypoint before engaging AP and I get no CTD. Awesome MOD BTW!!!!

**Comment by cvitre23** [comment]
neither of the two, i use only FPL recall/simbrief (without SID/STARS)

**Comment by neoeinstein** [comment]
Additional report and dump:
Phase: Takeoff (just after rotation)
AP: Off (FLC 240 and HDG armed)
VNAV: Off
FMC page: LEGS
Navigraph: Yes (2013-rev. 5)
GPU: Nvidia
Sceneries: KBDL, KPVC (but was at KBOS)

Had just reached rotation speed and was lifting off the runway when the sim froze and dumped.

Crash dump (10GB): https://drive.google.com/file/d/1cfGNik-GNL9XHcvQOwFInRhSUsiw-5fY/view?usp=sharing

**Comment by gilcon2** [comment]
I'm having the same CTD's.  I can't fly out of Busy areas (graphics and traffic) like KLAX, KBUR, and KATL.  I can fly into them just fine.

**Comment by twincessna** [comment]
I get a CTD while the flight is loading.

**Comment by dga711** [comment]
> I get a CTD while the flight is loading.

While there are surely CTD reports that go together with the MOD. There are also reports (like yours) that could just be sim issues. We take every report into account but we can't now take every sim CTD and connect it to our mod.

**Comment by Baldk9** [comment]
Congratulations on your new association with Microsoft. I hope it's a rich and rewarding experience. What you guys have down to enrich the CJ-4 total package has added another dimension to MSFS. Thanks!
