### ISSUE TITLE
G1000, G5000 don't show full flight plans on MFD

### ISSUE THREAD

**Issue by BostonJeremy77** [Working-Title-MSFS-Mods/fspackages#681]
Hi all. Starting with today's update, towards approach, the magenta/white lines of the flight plan is cut off short of airport - it still follows the last few waypoints, but the plan isn't shown on MFD. The flight plan in FMS is still fine.

**Comment by modabasi** [comment]
In my case (TBM 930) the initial flight plan is shown, but when I load an approach to the flight plan, the purple lines dissapear on the MFD. The autopilot still flies the approach, but I can not see the path flown on the MFD.

**Comment by Pascal207** [comment]
Hello.
I've had the same issue with the longitude.
When i load an approach, the flight plan dissapear on the MFD, and the flight plan on the fms have "blank" points.
The plane still follow the flight plan.

**Comment by cywang90** [comment]
This should be fixed with v0.3.4.
