### ISSUE TITLE
CJ4 Throttle Issue 8.0.2

### ISSUE THREAD

**Issue by TicTockRock** [Working-Title-MSFS-Mods/fspackages#682]
Hi Guy's

I have noticed an issue when using the updated MOD 8.0.2.

If I load the CJ4 up with either of the two new livery's, the throttles do not move. I can't move them with the slider on the joystick or with the mouse inside the cockpit. However the engine thrust does increase using the slider on the Joystick, you don't get the FADEC positions T/O lighting up in green though and it did not register the climb detent. I only managed to lift the wheels off the ground before getting a CTD, the first one I have ever had to date, had to happen sooner or latter :-) 

I then tested with what was the default livery for the CJ4 same airport etc and the Throttles move fine using either method mentioned above. Not had a chance to test another take off yet with this livery, but will do as soon as I get a chance.

**Comment by dga711** [comment]
Hi
please read the section "Default livery conflicts" in the release post
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.8.2

**Comment by TicTockRock** [comment]
Hi 

 

Sorry I completely missed that, not sure how the title is even in Bold Doh!

 

Regards,

 

Andy
