### ISSUE TITLE
CJ4 0.8.2 Throttle Lever Does Not Move

### ISSUE THREAD

**Issue by yodada** [Working-Title-MSFS-Mods/fspackages#683]
Throttle levels can be adjusted but there is no animation. In the screenshot left throttle is at 58% but the lever is still at IDLE.
<img width="629" alt="Screen Shot 2020-12-23 at 08 43 25" src="https://user-images.githubusercontent.com/9563358/103001407-f0f47f00-44fa-11eb-93e0-7b8ab6564d28.png">

**Comment by dga711** [comment]
Hi
please read the section "Default livery conflicts" in the release post
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.8.2
