### ISSUE TITLE
CJ4 v0.8.2 - Saitek/Logitech Autopilot panel mappings broken

### ISSUE THREAD

**Issue by Renfro747** [Working-Title-MSFS-Mods/fspackages#684]
Latest release seems to have broken the mappings for the Saitek/Logitech autopilot panel. 
All versions before were compatible but the latest rev renders the panel useless. Controlling AP from the in game virtual cockpit works fine. Using external panel to operate AP creates unexpected results. For example pressing "NAV" on external panel does nothing on the CJ4 autopilot. Pressing NAV on CJ4 virtual cockpit enables NAV, but illuminates the HDG button and function on Saitek.

Worked fine in all previous versions of workingtitle-aircraft-cj4.
Removing workingtitle-aircraft-cj4-v0.8.2 from Community folder, eliminates the issue and Saitek/Logitech panel works normally.

**Comment by dga711** [comment]
This is a current limitation as stated on the "known issues"
For doing custom AP logic we had to decouple the default sim events.

Ofc we are thinking about solutions, but it's a tough one.

**Comment by Nedo93** [comment]
I encountered this issue too. I tried to use SPAD.neXt to somehow remap the panel keys, but I can't intercept the modded autopilot events.

**Comment by dga711** [comment]
Let me quote from our release notes
`Autopilot modes cannot be triggered via keybindings or controllers and must currently be triggered in the cockpit with the mouse.`

While looking into solutions its hard to solve when you do custom AP. Best case would be for FSUIPC/SPAD find ways to support H events or L vars in MSFS

**Comment by Nedo93** [comment]
Thank you for your feedback and your work. I hope it will be possible to find a solution, maybe with custom AP mods growing, Asobo directly will think about something.
