### ISSUE TITLE
Wrong pilot ID SImBrief

### ISSUE THREAD

**Issue by Captherky** [Working-Title-MSFS-Mods/fspackages#689]
I enter my Simbrief id and it come up with wrong pilot ID.
No its my corredt SimBrief ID, the sim has it wrong!
I cant import anty Simbrief palns since stupid 12.13 update fro ARSOLEBOS

**Comment by mattnischan** [comment]
> ARSOLEBOS

It's really not necessary to call anyone names. Furthermore, the SimBrief import system for the CJ4 was entirely created by Working Title, and as such any breakage of that system is going to be on us.

>I enter my Simbrief id and it come up with wrong pilot ID.
No its my corredt SimBrief ID, the sim has it wrong!

Please ensure that you are using the numeric SimBrief pilot ID, and not your SimBrief username. The SimBrief username will not work.

**Comment by Captherky** [comment]
IAM using the simbrief pilot id, i'm not an idiot or a sour user, but every time we get an update from the these Asobo (corect spelling..brain fart) guys EVERYTHING breaks. I mean everything! It takes a time for users (ME) to de bug it for YOU (GITHUB) So dont be so scathing in your comments. Im entitled to call them whatever I want!  Sorry if I offended  your deliucate sensibilities! But the Sim Brief part of this mod is broken (For Me) I cant connect to any simbrieff plan! VERY SORRY! Another failure! This is a major system fialure for me and further puts me off from using your Ad Hog updates. Perhaps better to stick to Sobo basic modules and wait for them to copy your updates. You see whats happening dont you? Asobo wait for you guys to update a module, then they copy and paste the update you did into theit maste branch, with some extra code so your branch gets bugged! Just think about it?

**Comment by dga711** [comment]
Ok. Thank you for your feedback.

Merry christmas
