### ISSUE TITLE
CJ4-Engines stop running on approach

### ISSUE THREAD

**Issue by nomad1227** [Working-Title-MSFS-Mods/fspackages#692]
Not sure if this is addressed anywhere else, but twice now I have been on the final stages of approach, in between the IF and the FAF and both engines completely stop running and must be restarted. One time the AP was on and tracking the RNAV 20C to KBNA (lateral and vertical paths tracking accurately) and the other was a hand flown visual approach into KABQ Runway 8. Fuel starvation is not the issue, I have plenty of it. I'm not pressing any buttons that would shut the engines off manually. 

I love this mod. It is my favorite one in MSFS. Thank you for the great work and I hope this can be addressed. I will continue to test and send feedback.

**Comment by nomad1227** [comment]
PHASE OF FLIGHT: Final Approach
AP ON/OFF: On and Off (issue happened two different times)
VNAV ON/OFF: On
WHAT AUTOPILOT MODES (FMA): LNAV1/VNAV 
GPU NVIDIA OR AMD?: Nvidia 1070, driver vers 460.89
SCENERIES INSTALLED?: none
DESCRIPTION OF THE EVENT - WHAT WERE YOU DOING/WHAT WAS THE PLANE DOING WHEN IT OCCURED: On final approach, between IF and FAF, Engines die and must be restarted. Happened two different times (RNAV 20C to KBNA with AP on, LNAV/VNAV on --- Visual Rwy 8 KABQ, AP off, hand flown)

**Comment by K20017** [comment]
Check if you have any of your hardware buttons bound for mixture.  This causes the engines to shutdown for no reason.

**Comment by nomad1227** [comment]
Much better! Figured it'd be user error in some way...... My mixture knob resets to 0% when I restart MSFS so I had to move it down a bit for it to realize it was full forward. I'm a prop guy by nature. 

Best mod in MSFS **hands down**. Keep up the fantastic work!!
