### ISSUE TITLE
CJ4 porpoising on climb to altitude

### ISSUE THREAD

**Issue by CORTRacer31** [Working-Title-MSFS-Mods/fspackages#695]
The past two flights in the latest CJ4 (0.8.2), I've encountered porpoising above FL250, generally in light chop - the plane starts chasing the elevator trim like crazy. Disconnecting AP and reconnecting after 5-10 seconds usually rectifies.

**Comment by gilcon2** [comment]
I've noticed the same thing.  The higher you climb the worse it gets.

**Comment by dga711** [comment]
Should be improved in patch 0.8.3 
Thanks
