### ISSUE TITLE
CJ4 ITT after last MSFS Update

### ISSUE THREAD

**Issue by nrcrate** [Working-Title-MSFS-Mods/fspackages#696]
I know this may not be something fixable as Asobo has over-fixed it, but thought it would be good to mention-

On departure with +24C the ITT went close to 1000C in the T/O detent.
Climb detent yielded over redline ITT through FL220

Unsure of the extent of possible adjustments on WT's part

**Comment by mattnischan** [comment]
@nrcrate 
Unfortunately we are subject to the sim ITT here and don't have any control over the parameters of how it is simulated under the hood.

Hopefully this will change at some point in the future.
