### ISSUE TITLE
CTD after entering approach procedure

### ISSUE THREAD

**Issue by smatage** [Working-Title-MSFS-Mods/fspackages#700]
Right after I entered approach into a flightplan and hit load everything froze followed by CTD. Replicated multiple times. Then I also had a CTD while descending via a STAR into ENVA, but this might be unrelated.

**Comment by smatage** [comment]
Edit - After some testing this seems to be some navdata issue rather then problem with this mod. It didn't work with approach to Trondheim but other airports seem to be workig just fine. So this issue can be closed. Thanks for this top mod!

**Comment by dga711** [comment]
Thank you for your feedback.
Yeah, the game still has CTDs in different scenarios.
The one we are looking at which COULD be influenced by our mod is the one after departure.
