### ISSUE TITLE
G3000 Version 03.4 in Cessna Logitude is missing Approach legs

### ISSUE THREAD

**Issue by harii15** [Working-Title-MSFS-Mods/fspackages#705]
Re: Version 03.4 in Cessna Longtude
MY Flight KSAN :Peble6 -> KLAX ILS 6R (SLI transition) 

THE MFD displays the full Flight path , including the Approach legs when first created on the World map
The MFD continues to display the full full path with all waypoints all the way to the transision point (SLI)
On the Turn to the first Fix/ Waypoint on the Approach Leg, The MFD blanks out and no longer displays any further legs of the Approach . However the PFD indicates that the aircraft is still on course to the first waypoint( FERMY) of the Approach.
The FLIGHT PLAN page on the MFD does not show any Approach
I manually Reselected the Approach( ILS 6R) and Activated the approach ( However the MFD still does not show the Approach path)
I re- selected EXERT the next fix/waypoint and " Activated selected Leg". ( However the MFD still does not show the Approach path)
The aircraft however, continued correctly to follow the Approach fixes all the way to the FAF( GUPPI). I know this because I am following the Aircraft path on the Navigraph desktop charts
The GREEN Glideslope Indicator appeared correctly and the “APPR” mode enabled capture and follow the descent to landing. THE MFD ONLY SHOWS a straight Magenta Line from ORIGIN airport ( KSAN) to DEST Airport(KLAX)

**Comment by PM3Delta** [comment]
Re: Version 0.3.4. in TBM930
Flight: EDDF to EDDM via STAR ANORA3A into 08L and ROKIL Transition

I can confirm what harii15 reported above - the bug also exists for the TBM930.

Initially when only the START (here ANORA3A) is selected both the VFR map and the MFD show identical tracks.

Only after the Transition is loaded (here ROKIL into ILS 08L) the VFR map shows the correct (published transition, see jeppessen and navigraph) while the MFD shows an arbitrary flight path.  The transition was loaded well before reaching the IAF (which in this case is ANORA). The aircraft however follows the track depicted in the VFR map.

Before the last FS update (Dec. 22nd) and G3000 V. 3.4. all was good and VFR map and MFD both showing the correct flight path.

Please see below attached some screenshots for illustration.  It would be great if you could look into it.  Thx.

Before selecting and loading the transition (only showing STAR ANORA3A).
![Screenshot (304)](https://user-images.githubusercontent.com/60411051/103140231-869f3280-46e4-11eb-818b-bdf82aa71a52.png)

Also before loading the transition (the sequence of waypoint is depicted correctly on the small screen).
![Screenshot (307)](https://user-images.githubusercontent.com/60411051/103140251-b51d0d80-46e4-11eb-9566-15df6b6a9ec5.png)

After transition is loaded, VFR map shows correct flight path (aircraft follows this) and MFD showing wrong/arbitrary path.
![Screenshot (308)](https://user-images.githubusercontent.com/60411051/103140272-e72e6f80-46e4-11eb-817a-5810828e0115.png)

**Comment by cywang90** [comment]
Fixed with 0.4.0
