### ISSUE TITLE
CJ4 AP mode switching to VOR unreliable

### ISSUE THREAD

**Issue by flymypi** [Working-Title-MSFS-Mods/fspackages#706]
I've noted that when switching the NAV source to VOR1, the AP doesn't always follow it in NAV mode.
When that happens it is able to operate regulary by switching to ROLL mode.

![20201224151620_1](https://user-images.githubusercontent.com/72461857/103137286-dcb1ad00-46c7-11eb-92cf-c0fe90fa3b9f.jpg)
_Intercepting a radial during a VOR approach in roll mode_

So far I have not noticed a pattern to this, except that it mostly happens during the approach phase, so when a few mode switches have happened before. I did not yet encounter this problem flying SIDs by the charts.

The issue persists with the latest state of the `main` branch at the time of this post.

**Comment by K20017** [comment]
Are engaging the AP buttons with the mouse or hardware?  It appears your buttons are getting out of sync.

**Comment by jmail68** [comment]
The normal behavior of this Collins autopilot in several types of airplanes I have flown, is what you describe. When you change NAV source the AP mode will change from NAV to ROL.

**Comment by flymypi** [comment]
> The normal behavior of this Collins autopilot in several types of airplanes I have flown, is what you describe. When you change NAV source the AP mode will change from NAV to ROL.

I know, but ROLL mode does not track the NavSource in real life.

**Comment by flymypi** [comment]
> Are engaging the AP buttons with the mouse or hardware? It appears your buttons are getting out of sync.

Mouse, no external hardware apart from a stick with key bindings to flaps, gear and spoilers.

**Comment by cwburnett** [comment]
@flymypi is this still an issue?
