### ISSUE TITLE
Very useful command:  Press CLR/DEL key in FMS for 1 second to competely delete the scratchpad

### ISSUE THREAD

**Issue by taguilo** [Working-Title-MSFS-Mods/fspackages#709]
Enough said.

Thanks!

**Comment by flymypi** [comment]
Is that a feature of the real CJ4 FMS?

**Comment by taguilo** [comment]
Yes. It is a feature of the FMS3000 CDU, actually.

**Comment by dga711** [comment]
Asobo added the event for it in the last patch. We just have to bring it in.

**Comment by dga711** [comment]
Will be in 0.8.5. Thanks
