### ISSUE TITLE
workingtitle-g1000-v0.3.4 in DA62 screens swapped

### ISSUE THREAD

**Issue by photoSteveZ** [Working-Title-MSFS-Mods/fspackages#711]
Since updating MSFS with the Dec 23 update, the MFD and PFD displays are swapped on the G1000 in the DA62. This was true both before and after applying the v0.3.4 update from Working Title. 

I've verified the v0.3.4 update by using some of the new features such as Track Up.

The C172 w/ G1000 does not have this issue. 

![Screenshot 2020-12-26 125440](https://user-images.githubusercontent.com/76629331/103158336-d0862800-4779-11eb-9f49-8b18dbaa4e8d.jpg)

**Comment by fppilot** [comment]
I also had the screens swapped in the DA62 today.  I then found v0,3.4 and installed it.  The screens are back in the right sides, but the keys/buttons on the PFD on the left are operating the functions of the MFD on the right and vice versa.

**Comment by fppilot** [comment]
I had the same issue.  Just removed the DA62X mod and a DA62 lighting mod and the G1000 is now as it is supposed to be again.  Now I am off in search for updates to those two DA62 -specific mods.

**Comment by photoSteveZ** [comment]
Thanks, @fppilot: since I don’t have the lighting upgrade, updating the DA62X mod was all it took to straighten things out for me.
