### ISSUE TITLE
[CJ4 v0.8.3] Unclear TOD Marking Behavior in non-VNAV descend

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#717]
**Precondition**
- Plan flight with descend altitude constraint
- At TOD marking initiate descend by VS (no VNAV engaged!)

**Expected** Behavior
- The aircraft passes TOD marking an leaves it behind

**Actual Behavior**
- The TOD marking is pushed forward with the aircraft position until target altitude has been reached

**Remarks**
- Not sure about the real world behavior (please advise when able)

**Screenshot**
![2020 12 27-23 53](https://user-images.githubusercontent.com/71787933/103181356-8350a600-48a0-11eb-8c2c-1c08b14f9fe5.png)

**Comment by taguilo** [comment]
Hi,
Once TOD lies behind the aircraft it should not display anymore, as the aircraft is flying higher than TOD->Wpt path.
However, if descending behind TOD->wpt path, TOD will show ahead of aircraft telling the pilot the point where descent path will be captured, whether or not being in VNAV active.

**Comment by sfdeham** [comment]
Thanks, sounds reasonable. I will test the case "TOD lies behind the aircraft" upon next flight and advise result.

**Comment by sfdeham** [comment]
Test flight completed. Behavior as described above.

**Comment by mattnischan** [comment]
@sfdeham I'm reopening this as I'm guessing you didn't mean to have it closed, based on your last comment.

**Comment by sfdeham** [comment]
@mattnischan I closed it because for the test case "TOD lies behind the aircraft" the TOD marker disappeared as described above, so from my side everything is OK.

**Comment by mattnischan** [comment]
@sfdeham Ah OK, understood!
