### ISSUE TITLE
[CJ4 0.8.3] AP PFD indications and behavior not following mode changes from SimConnect events

### ISSUE THREAD

**Issue by IslandJohn** [Working-Title-MSFS-Mods/fspackages#718]
I have joystick buttons mapped to ALTS, HDG, VS toggle etc. via FSUIPC (SimConnect events). If I use one of these events, like heading toggle, the mode does not switch on the PFD and the AP does not switch modes. This still works correctly in the default CJ4 (without mod installed) and used to work in 0.7.x. Many other SimConnect events remains functional though, like heading increase/decrease, AP master etc.

**Comment by IslandJohn** [comment]
Missed it in the release notes... feel free to close it, or keep around for tracking. Is it planned to be fixed?

**Comment by dga711** [comment]
We are thinking of solutions. But its quite a complex topic. We'll see.
