### ISSUE TITLE
[CJ4 v0.8.3] AP stops following flight plan

### ISSUE THREAD

**Issue by Oswalnay** [Working-Title-MSFS-Mods/fspackages#720]
The autopilot in LNAV1 mode will stop following the flight plan when about to hit a random waypoint, which seems to be (but not always) a transition from a SID or to a STAR.  AP will start turning the plane in the opposite direction marked, or even do a complete u-turn.  Putting it into heading mode to aim it at the proper waypoint and then once passing swap to LNAV1 again works occasionally, but the most common fix seems to be going direct to said waypoint or the next one up.

The flight plan is in blue, the actual route is in red, the transition to RIKII from the BOACH3 SID is where it all went wrong.  I had to use headings to aim it but it still wouldn't quite work so I had to go direct.
![image](https://user-images.githubusercontent.com/76680372/103198261-bb55ea00-489c-11eb-934f-eb0e42de8de0.png)

The transition from IBAKE to the VKTRY2 STAR: at VKTRY instead of turning left at 122, it instead turned right at 287 and I had to manually vector in to fix it.
![image](https://user-images.githubusercontent.com/76680372/103198339-f35d2d00-489c-11eb-9092-4d3286a753e8.png)

The transition from EXTAN6 SID to SHAYK and the AP turned the opposite direction.  Was able to use headings to get it aligned but it wouldn't continue on until I had it go direct to ICT I believe.
![image](https://user-images.githubusercontent.com/76680372/103198579-85fdcc00-489d-11eb-8d99-65ab3d787d63.png)

**Comment by cwburnett** [comment]
Please share a picture of your legs page showing the waypoint or waypoints this is happening on. The only time I've seen this happen for people is when they accidentally leave a duplicate waypoint in their flight plan, which usually happens at the end of the SID, the beginning of the STAR or the STAR/APPROACH transition. If it is happening on other cases would be great to have pics or a video showing what's in LEGS when it is happening. Thanks for the report.

**Comment by Oswalnay** [comment]
The next time it happens (well I hope it doesn't but it probably will) I'll make sure to get a screenshot of the Legs page.  I don't remember for the others, but I know for sure the BOACH3 one didn't have any duplicates.

**Comment by B-KC** [comment]
I had the same experience yesterday flying the Longitude. Aircraft followed the FMS initial leg on departure and then kept right on going never turning to the next waypoint. 

Cycling NAV modes and NAV button had no effect.

**Comment by mattnischan** [comment]
@B-KC The CJ4 does not use the stock lateral navigation, so the two problems would not be related. The Garmin units still use the default sim lateral navigation.

**Comment by mattnischan** [comment]
@Oswalnay This should be addressed in 0.9.1. Let us know if you see it again and we can reopen this issue.

**Comment by B-KC** [comment]
> @B-KC The CJ4 does not use the stock lateral navigation, so the two problems would not be related. The Garmin units still use the default sim lateral navigation.

okay, so should there be a bug opened against the G3000 mod? Or is it just not in a state where the CJ4 is?

**Comment by mattnischan** [comment]
It's just not in the same state at the moment. We're going to be porting the advanced nav features over to the Garmin units, like the new flight plan system, VNAV, RNAV, etc, but that work hasn't been completed so what you see is just the best that can be done with the stock in-sim plan manager.
