### ISSUE TITLE
new install of 0.8.3 and fmc just shows a dash on the upper right corner

### ISSUE THREAD

**Issue by buttepuff** [Working-Title-MSFS-Mods/fspackages#722]
How do i solve the issue of the dash on the upper right corner of the fmc dash?

**Comment by dga711** [comment]
@buttepuff Make sure you downloaded the actual release zip not the source zip
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/cj4-v0.8.3/workingtitle-aircraft-cj4-v0.8.3.zip

**Comment by buttepuff** [comment]
did not download the Source zip, downloaded the Working title one

**Comment by dga711** [comment]
Well. It is not installed correctly. Not sure what to tell you.

**Comment by buttepuff** [comment]
Uninstalled the mod, And the cj4 plane from the game and then reinstalled the default plane. Even the default plane shows the damn Dash in the fms. Going to check the msfs forums for a answer

**Comment by dga711** [comment]
Do you have any other mods running?

**Comment by buttepuff** [comment]
Im currently Reinstalling msfs to see if that resolves my issue gets resolved or if it persists

ill come back with my results

**Comment by buttepuff** [comment]
Alright, A reinstall of msfs and install of 0.8.3 the fms finally works, Beautiful plane to fly Thanks for the work guys
