### ISSUE TITLE
Left PFD freeze in flight after attempted mode change

### ISSUE THREAD

**Issue by CORTRacer31** [Working-Title-MSFS-Mods/fspackages#725]
Sorry in advance for the lack of detail in this report - circumstances did not allow me to capture much for reporting. I'll try to describe it in as much detail as possible.

Was conducting a flight from KDVT to KPVU and was descending through full IMC to land with a programmed ILS RWY13 approach. After entering a crossing restriction for an upcoming waypoint, I was cleared direct to the FFU VOR. I selected the DIR mode on the FMC, but the autopilot did not change the plan to that waypoint - it added a new DIR waypoint leg and started backtracking the aircraft. I disengaged the autopilot and turned back onto the previous path, then reselected autopilot and hit DIR to FFU again. At the same time, I selected the PFD option button and scrolled to the PPOS option, selected, and then attempted to change the radar range. The PFD completely froze at that point (I believe the right display also briefly froze, but I did get back my display after a few seconds so I could still follow the GPS plot). Nothing I tried fixed anything, not even cycling the avionics midair. I didn't have a lot of leeway to tinker because I was at zero visibility.

If you have any other questions, let me know and I'll try to answer.

**Comment by krazyj83** [comment]
I have the same issue with the A32X mod from FBW, and after e brief chat with them it seems to be a conflict between CJ4 mod and FBW A32X mod, do you have the FBW mod and if so try to move it out of the community folder and see if the issue persists. 

It seems to still be an issue in 0.8.3

**Comment by CORTRacer31** [comment]
I do have the FBW mod, development version. I'll disable that and try a return flight later today and report back.

**Comment by nrcrate** [comment]
I had the PFD and all but the map on the MFD (both sides) freeze on me when attempting to go DTO the visual approach point for a runway at KISP. Thankfully the standby A/I worked properly and I hand flew the rest.

**Comment by dga711** [comment]
> I have the same issue with the A32X mod from FBW, and after e brief chat with them it seems to be a conflict between CJ4 mod and FBW A32X mod, do you have the FBW mod and if so try to move it out of the community folder and see if the issue persists.
> 
> It seems to still be an issue in 0.8.3

It is pretty certain at this point that here are no more conflicts betweend the mods.

**Comment by dga711** [comment]
No further information. Will close for now.
