### ISSUE TITLE
CJ4 0.8.3 After adding lots of waypoints, flight plan is somewhat reset

### ISSUE THREAD

**Issue by daghb** [Working-Title-MSFS-Mods/fspackages#733]
I added departure airport (Murtala/Lagos/DNMM), sid, arrival airport (Dar es-Salaam/Tanzania/HTDA), star and started to input lots of airway waypoints, but after 15 or so (there must be about 30-40 underway), all my manually added waypoints disappeared and only the departure and approach procedure waypoints were left.

To recreate, start cold and dark at DNMM, use the FMC to enter flight plan and add dep/arr/SID/STAR and input 15-20 waypoints. After a while, all manually entered waypoints disappear.

**Comment by mattnischan** [comment]
@daghb Could you please provide the full route so we can reproduce the issue?

**Comment by nosferatie** [comment]
I had the issue flying to LICR,  fying the PIGER 1X arrival, it added PIGER twice, so go to PIGER, and then it does a orbit to the left to reintercept PIGER.

**Comment by daghb** [comment]
@mattnischan: 

Short version: DNMM/18L BOTB1S UR984 NLY UL434 KGI UB531 MV UW305 ITGOP1A HTDA/05

UR984: BOTBO ARAGU POT EBVAT RALIN VITLI DLA EDEBA NLY
UL434: NLY DESAM MITRO AMPIL MOROS OPGAM SERAL PIPLO NENTU AXUVI POLDO SOLPA GAMEL BUPOX ERKAR ULPED KGI
UB531;: XEVRI **UXOBU MEVAR BULNA** GOM RANAG APNER KNM KONOS DATAN UVLED ITROM MV
UW305: MV IMRAX EVASI UTOVU DUMPA NIDEX ITSOK ANTOM ITGOP

Reset happened somewhere near the waypoints in **bold**.

**Comment by mattnischan** [comment]
I was unable to reproduce this today, I got this result:
![image](https://user-images.githubusercontent.com/1650544/103415350-583bb000-4b47-11eb-927e-6bf8255ecb36.png)

Are you adding every single fix manually? For airways you should enter them using VIA.

**Comment by mattnischan** [comment]
Additionally, this flight plan will definitely take you beyond the range of the CJ4. 2000NM is about the max with good winds and potentially eating into reserve fuel. I would recommend keeping it to 1800NM or less.

Our range matches the range of the actual aircraft.

**Comment by daghb** [comment]
Thanks, didn't know about the VIA functions. Will try, I guess you can close this issue.

Happy new year and thanks for helping out!
