### ISSUE TITLE
CTD after EXEC flightplan in the FMS

### ISSUE THREAD

**Issue by CJ4Peter** [Working-Title-MSFS-Mods/fspackages#737]
after landing and loading a new flight plan into the FMS of the Simbrief, there is a CTD after pressing EXEC in the FMS.but this does not apply after the first flight plan loading, only after the second loading.
0.8.3 version

**Comment by Denpera** [comment]
Using Plan-G for flight plans and live map and after loading plan into FMS not recognizing waypoints unless airfields but otherwise seemed OK but last several times after CTD early in flight tested without Plan-G but still getting CTD.  (v0.8.3)

**Comment by dga711** [comment]
We did some changes to the upcoming 0.8.5 in the hopes to alleviate some of those CTDs.

Feel free to reopen this issue when you still get the problem after 0.8.5 release. Thank you
