### ISSUE TITLE
No Cockpit Textures

### ISSUE THREAD

**Issue by Pianomaninvan** [Working-Title-MSFS-Mods/fspackages#738]
Hey guys. I know I'm more than likely missing something obvious but when I load into start a flight I have no textures other than the outside of the aircraft. Downloaded Ver 0.8.1(not the source file, but the working version zip) into my community folder. Not sure what would be causing the issue. Any advice would be great!

**Comment by CJ4Peter** [comment]
download the 0.8.3 version
