### ISSUE TITLE
CJ4: There are 3 ADF frequencies on FMS

### ISSUE THREAD

**Issue by Kamarad99** [Working-Title-MSFS-Mods/fspackages#742]
`CJ4` 

Hi, I noticed that there is 3 places on the FMS where we can enter the ADF frequency. Probably that one is obsolete. We can enter 3 different values. version 8.3.
-	First one is on NAV page 1 at the bottom left
-	The two others are on NAV page 2

![image](https://user-images.githubusercontent.com/76824074/103424453-5f2fe600-4b7a-11eb-9869-893e239fb0be.png)

![image](https://user-images.githubusercontent.com/76824074/103424496-a74f0880-4b7a-11eb-918a-47e7d9393e07.png)

**Comment by dga711** [comment]
TUN 2/2 is not really modeled yet.
