### ISSUE TITLE
CJ4: Fuel usage exactly double of Simbrief

### ISSUE THREAD

**Issue by Kamarad99** [Working-Title-MSFS-Mods/fspackages#743]
I made a short flight at FL160 for an air time of 30 minutes. Simbrief provided something that seem realistic with 600 lbs of fuel for 30 minutes (1,200 pph). But the flight log page at the end of the flight give me exactly **DOUBLE** the consumption estimated by Simbrief. I use CJ4 Mod version 8.3.

ADDITION: I realized later that the fuel remaining on board seem ok but does'nt fit with the FLIGHT LOG page.  
- Block fuel was 2,304 lbs
- Flight log page report 1,452 lbs burned
- So base on those two figures, the remaining fuel should be : 852 lbs.

- but the sensed Fuel and the MFD both report 1,425 lbs remaining. So the real flight consumption was 2,304 lbs - 1,425 lbs = 879 lbs. The 1,452 lbs fuel burned in the FLIGHT LOG page seems wrong.

![image](https://user-images.githubusercontent.com/76824074/103426076-bf2b8a00-4b84-11eb-8e7f-1882ed353c62.png)

And the PFD and Fuel sensed at the end of flight are shown next picture:

![image](https://user-images.githubusercontent.com/76824074/103426080-cd79a600-4b84-11eb-9ec1-b64c8f2f7b3c.png)

BTW, how to add a pink CJ4 tab to a post ?

**Comment by mattnischan** [comment]
The in sim calculated fuel flow is way way off, so we use our own fuel flow model, which we cannot write back to the sim directly. Instead we adjust the tank levels each frame. The custom fuel flow model matches real observed burns very accurately.

Due to all that, though, the in sim flight log levels will likely be very inaccurate.

**Comment by Kamarad99** [comment]
Yes, I know that the model has its own fuel calculation and that is correct. This is not the problem I refer to.

The problem is not the in sim calculated flow. It's the FLIGHT LOG page of the FMS that has a wrong FUEL USED indication whenever we change the Fuel and Payload. Here is a figure of the FLIGHT LOG page before and after Fuel input. We see that the fuel used field is negative but in other flight it can put positive or negative figure depending of the flight.

So the problem is with this field indication. 

![image](https://user-images.githubusercontent.com/76824074/103464816-98945d00-4d04-11eb-88dc-6389207fe8fb.png)

**Comment by mattnischan** [comment]
Ah OK, I'm following you now.

Yeah, right now, all that page does is measure the fuel at FMC start vs the current fuel. So if you add fuel after the FMC is turned on, you'll get funky numbers.
