### ISSUE TITLE
CJ4 0.8.3 autopilot pitch occilation

### ISSUE THREAD

**Issue by MystereBazoo** [Working-Title-MSFS-Mods/fspackages#751]
Since 0.8.3 of the cj4, the autopilot pitch correction in all mode is unstable, there is a very bad pitch occilation that once started is constantly amplifying. Looks like autopilot is over-correcting turbulence effect on aircraft. This problem was not present before.

**Comment by slip664** [comment]
Verify that you're actually using version 0.8.3.

**Comment by MystereBazoo** [comment]
I removed the files and downloaded again the 0.8.3 version. So far no problem. Maybe the files were somehow corrupted by the others installations for the g1000, g3000 etc. By the way, the results is amazing! Continue the excellent work.
