### ISSUE TITLE
CJ4: FPLN page airway insertion order errors

### ISSUE THREAD

**Issue by qpHalcy0n** [Working-Title-MSFS-Mods/fspackages#752]
As mentioned in the discord, when entering the entry and exit waypoints in the FPLN page, entering an airway on the left side replacing "DIRECT", leads to the airway being inserted out of order and the exit waypoint being appended to the approach procedure. This only happens if the DEP and ARR have both been entered before entering any enroute waypoints. Entering departure, then enroute waypoints, then arrival has no issues.

[Shown here](https://imgur.com/a/QkiFRcU)

Routing was as follows:  KBOS BLZZR4 BLZZR BAF Q480 BEETS TOMCA Q68 SOPIE LIT WILBR5 KDFW

CJ4 Ver; 0.8.3
MSFS Ver: Latest as of 1/1/21

**Comment by dga711** [comment]
This should be fixed in the coming update.
