### ISSUE TITLE
[CJ4 0.8.3 B6] - VNAV loses constraint when anticipating turn

### ISSUE THREAD

**Issue by mikebakke** [Working-Title-MSFS-Mods/fspackages#756]
I set up a test to intercept JACKO which is the transition to ILS27 into EGLC. Fly to that at 12000. Switch VNAV on and set alt select to 500'

VNAV sees the path and begins descent. The first constraint is at WP LCE23 on the approach at 9000'. When at 10500' the plane begins the turn for RAVSA while still a shade under 3 miles from LCE23. As soon as it begins the turn it levels and does not descend again until the next TOD marker on the way to RAVSA meaning the constraint is broken by 1500'. From that point the descent is correct - there are no more acute turns. 

I assume it sees LCE23 as behind it so discards the constraint, but it seems to me logical that once a constraint is set, if the AP is not disengaged then the constraint should be met wherever possible, even if "late".

I have a video but would need to do some editing to cut it down if necessary - let me know.

Thanks

Aaaargh - I think I was tunnel visioned on LCE23 and I didn't set VNAV on till after JACKO. I can see from the video at that point the constraint is not displayed so I think it only came alive at LCE22 which left 5 mi to descend 3000' which doesn't fit.

So - I'd still think that the constraint should be met retroactively as noted above. In addition if there's a constraint ahead in the plan, should that not be honoured as soon as VNAV is engaged? I'd assume the FMC looks at each leg ahead to calculate required profile and it should have been noted as soon as VNAV switched on which was definitely before NONVA.

![image](https://user-images.githubusercontent.com/55141164/103461103-a2718c80-4d13-11eb-92b6-5f728c02997b.png)
![image](https://user-images.githubusercontent.com/55141164/103461565-2e38e800-4d17-11eb-93cf-eee18799e288.png)

**Comment by mikebakke** [comment]
I re-ran this morning and ensured VNAV was enabled before JACKO and the result was very similar. This time I got down to just under 11000' when the turn started and the profile took a long time to get back on track. In addition, for some reason the TOD marker wasn't appearing on the MFD in PPOS mode.

Will repeat again a little later with the current release version rather than Beta6

**Comment by mikebakke** [comment]
Re-done in current 0.8.3 release - same behaviours. The descent is on track, autopilot begins the turn 2-3 miles before reaching constraint waypoint and the descent is stopped leaving the plane c. 1500' above constraint. Once on track to the next WP it remains at the same altitude until it reaches TOD for the next constraint.

Assuming the turn anticipation is MSFS autopilot then I believe the initial constraint should not be discarded by VNAV until satisfied. If you need a video I can edit and upload, let me know.

The screenshot shows us levelled off after JACKO at 10500 with no descent forecast yet - LCE23 is the active constraint which is a way off yet.

Regards

Mike

![image](https://user-images.githubusercontent.com/55141164/103481613-fa6fc800-4dd3-11eb-9c6e-09cb06dcc577.png)

**Comment by mattnischan** [comment]
The turn anticipation is something we're doing and matches the actual unit (except in the case of flyover fixes, but those are rare). It does seem like we should continue tracking the FROM fix constraint vertically until we've made it to the restriction, though, yeah.

**Comment by mikebakke** [comment]
Cool. I did notice on the VNAV monitor screen that the number of active constraints was 3 before the turn and immediately flipped to zero as soon as it started.

Anyhoo - the main thing is I now know how it behaves so if I see any sharp turns I can at least anticipate what's likely to happen.

Rgds

**Comment by taguilo** [comment]
I checked the app procedure and it starts from crossing JACKO at 9000, what it means you should have started your VNAV descent to JACKO in advance to reach the constraint at 9000. But I understand you are starting the descent when crossing JACKO at 12000 or similar? Anyway, what VNAV should do in the proper procedure is to remain in VALT from JACKO to LCE23, and in the turn anticipation, when active wpt and constraint changes to the next (RAVSA), start the descent to 6000 (LCE23 is not a flyover wpt).

**Comment by mikebakke** [comment]
I did on my first attempt, realised what I'd done and repeated it multiple times activating VNAV 20 miles before JACKO. The ToD marker appears, descent starts before JACKO but as soon as the turn starts (3 miles before) the descent stops and never restarts. 

This is consistent and I do have video but it's easy enough to test and I have seen the same behaviour on other approaches.

**Comment by taguilo** [comment]
Actually you should have crossed JACKO at 9000 and remained in VALTV at 9000 until the turn anticipation from LCE23 to RAVSA.
The descent should have started as soon as the turn began and RAVSA became the active constraint.

**Comment by mikebakke** [comment]
The VNAV constraints mgt page shows JACKO as 9000,  so surely 20 miles out from JACKO requires a descent to 9000 by crossing?

**Comment by taguilo** [comment]
And being more precise, as it is a tight turn (>70 deg), VPATH will soon revert to VPTCH/PATH armed, and the descent remain in that mode until the path is recaptured before RAVSA

**Comment by taguilo** [comment]
> The VNAV constraints mgt page shows JACKO as 9000, so surely 20 miles out from JACKO requires a descent to 9000 by crossing? It tries but fails...

Yes, TOD->JACKO is the first constraint decent and should take you down to crossing JACKO at 9000.

**Comment by mikebakke** [comment]
I saw a fix in the open Beta change log for 0.9 which looked like it would address but (for me at least) it is still lost at JACKO and actioned again only approaching LCE23.

Was it expected addressed?

**Comment by mattnischan** [comment]
@mikebakke - This specific issue was the reason for the bugfix, yeah. It seems it didn't quite do the trick.

VNAV is being overhauled, however, and so we'll check this case with the new code.

**Comment by mikebakke** [comment]
Great! I had one more - similar effect but not with an acute course change, but as you're overhauling I'll leave it till you say you're happy.

Thanks again

**Comment by dga711** [comment]
Will close for now.
If the problem persists after the coming update, feel free to reopen.
