### ISSUE TITLE
CJ4 v0.8.3 Engines Underpowered

### ISSUE THREAD

**Issue by ajs117** [Working-Title-MSFS-Mods/fspackages#757]
For example, at IAS regarding between 250 and 300 knots with only 1 150 lb pilot and 90% fuel level, the climb rate at FL300 is only about 200 ft/min. This is using the climb throttle detent notch recently added so that may be misconfigured.

**Comment by mattnischan** [comment]
The climb rates and power settings have been matched to the book values. After the transition altitude you should be climbing at .64M, which is going to be probably quite a bit less than 250-300KIAS.
