### ISSUE TITLE
CJ4 v0.8.3 Global volume too quiet

### ISSUE THREAD

**Issue by ajs117** [Working-Title-MSFS-Mods/fspackages#758]
When compared to other aircraft and using calibrated headphones, the global volume is just too quiet in my opinion. Would expect engines to be louder (even though they are at the back) and especially wind noise.

**Comment by K20017** [comment]
What are your volume settings? 
![image](https://user-images.githubusercontent.com/20977949/103462600-611db480-4cf4-11eb-9c78-181eda7b2745.png)
