### ISSUE TITLE
CJ4 v0.8.3 Nav Radio Freezes when COM1/2 Disabled

### ISSUE THREAD

**Issue by sahammer** [Working-Title-MSFS-Mods/fspackages#759]
When toggling the com settings in the cockpit, the nav radio "freezes" and does not allow you to change frequencies. 

- Go to nav radio, change frequencies
- Disable COM1/2
- Go back to nav radio, unable to change frequencies
- Re-enable COM1/2
- Again able to enter frequencies

Example:

https://streamable.com/6p9p08

Using latest `CJ4 v0.8.3` and Navigraph Navdata AIRAC Cycle 2014 rev 1

Route ([SkyVector](https://skyvector.com/?ll=38.160838,-121.992867&chart=304&zoom=3&fpl=KSMF%20THORN%20ALWYS%20CEDES%20ARCHI%20KSFO)): `KSMF/17L DCT THORN DCT ALWYS DCT CEDES DCT ARCHI KSFO/ARCHI.I28R`

Edit: 

Frequencies used: 

Oakland VOR 116.8
ILS DME 28R/IGWQ 111.7

**Comment by dga711** [comment]
Behavior will change in 0.8.5

If the problem persits, feel free to reopen the issue. Thank you
