### ISSUE TITLE
CJ4 Readability of PFD and MFD

### ISSUE THREAD

**Issue by BPieke** [Working-Title-MSFS-Mods/fspackages#76]
I realize that there is a always a balance between making it as real as possible and as pilot friendly as possible, but I would really like to see the font sizes increased on the PFD and MFD readouts. 
The bottom left section on the PFD where the critical waypoint information is located, should be readable at a glance..
Also, the top PFD readout in ALT mode has the target altitude listed, but in a tiny font..

**Comment by K20017** [comment]
We will look into it, the text is definitely too small when compared to the real thing.

**Comment by mattnischan** [comment]
This should have been addressed in #133, which released with 0.3.1. Let us know if it still need improvements!

Thanks for the report.
