### ISSUE TITLE
[G3000 v0.3.4] approach still not being rendered on map

### ISSUE THREAD

**Issue by linmar22** [Working-Title-MSFS-Mods/fspackages#762]
Reinstalled the mod more than once - no joy. No other WT mods installed. Tried selecting an arrival as well, nothing.
Plane still follows waypoints, but doesn't draw the lines on the map. 

Additional (I think unrelated) issues occur when selecting Direct To during approach...
![https://i.vgy.me/mqFbMY.jpg](https://i.vgy.me/mqFbMY.jpg)

Terrain and FD still being drawn, but almost everything else, like the HSI, alt and speed tapes, horizon and ladder are frozen.
Reference backup attitude indicator to see what the plane is actually doing.

**Comment by kutak11** [comment]
yes same here... anytime I set direct to it freezes until that point is reached...

**Comment by Crunchmeister1** [comment]
Having the same issue with both the G1000 and G3000. I activate and approach and it will disappear from my MFD map. Other times, the MFD will freeze up. Occasionally, it will work as intended. But that latter condition seems to be an exception vs the rule.

**Comment by cywang90** [comment]
Duplicated of #705.
