### ISSUE TITLE
[CJ4 v0.8.3] Aircraft Unable to Follow Long Leg LNAV Path at 70°N

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#768]
**Precondition**
- Initiate flight with route:  `CYDA BUBAM FYU J507 BRW PABR`;
- Let aircraft turn left at `SCC`.

**Expected Behavior**
- The aircraft turns and catches the lateral path between `SCC-BRW`.

**Actual Behavior**
- The aircraft is unable to catch the path and keeps turning left and right on the right side of the path (screenshot below shows a steep right turn despite already being right of the path).

**Remarks**
- Flight plan involves long legs with known minor path offset in current beta version, however I did not yet encounter issues with maintaining the path;
- I heard that MSFS has issues with navigating around the North Pole, however I don't think this already applies to 70°N.

**Screenshots**

![2021 01 04-19 40_02](https://user-images.githubusercontent.com/71787933/103572110-5b7ac700-4ecc-11eb-833b-0db467e4efb2.png)

![2021 01 04-20 21](https://user-images.githubusercontent.com/71787933/103572114-5ddd2100-4ecc-11eb-8f87-0acb7e76e345.png)

**Comment by mattnischan** [comment]
@sfdeham - Do you still get this behavior with 0.9.1? We fixed the bug where LNAV would wander off like that, and just wondering if you still see this issue.

**Comment by sfdeham** [comment]
Will check upon next flights and advise.

Do you think this behavior was caused by flying far north (beyond 70°N) or the long legs in general?

**Comment by dga711** [comment]
Since LNAV got reworkd for 0.10.x I will close this.

Feel free to reopen when this happens in the current versions. Thank you
