### ISSUE TITLE
CJ4: Passenger briefings for seatbelt btn etc

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#769]
This is really a minor issue, but I wonder if the sound played when pressing the seatbelt button is really necessary now when we have the passenger briefings on the MFD? I think a simple chime sound would suffice to avoid the "double briefings". For instance, when you start you press the seatbelt and safety buttons and you get a short callout. Then you get another when you choose one of the options in the MFD. Same for arrival, one callout passing FL100 and you press seatbelt button and one more when you play the landing briefing.

**Comment by dga711** [comment]
@AndersHogqvist This is what the real thing does when pressing the buttons. So we will keep it.
But I was thinking too about the double chimes and announcements you get when pressing both buttons. Hard to find an accurate answer to this. But we will keep digging.

**Comment by AndersHogqvist** [comment]
Ah, i understand. Didn't realize it was a feature in the real aircraft.
