### ISSUE TITLE
CJ4 lack of bearing pointers and DME

### ISSUE THREAD

**Issue by ccapilot** [Working-Title-MSFS-Mods/fspackages#77]
When you select to display the bearing pointers (to VOR)  in the CJ4, they do not appear, any chance to fix that please?
Also the very important DME information is lacking from the CJ4, I hope you can fix that as well.

thanks for the great work you are doing to help us with these fixes.

**Comment by cwburnett** [comment]
I am combining this with the existing issue already created.
