### ISSUE TITLE
[CJ4] High Speed descent VNAV? 

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#771]
Just a quick question about the real aircraft:

As the "regular" decent is usually planned via the VNAV mode, I would like to know, if there is an option in the real aircraft, to switch between different modes? From normal to high speed decent in my case?
Why I´m asking: Due to new available PFPX file, I made a long flight with about 5h and to save some more fuel, I would like to do a late decent, so that I just idle down.

**Comment by slip664** [comment]
In PERF>VNAV SETUP 3/3 you can change the FPA to something higher than 3.

**Comment by mattnischan** [comment]
@slip664 is correct about the proper procedure there. There is no specific idle thrust descent as the plan is a lot smaller than an airliner and thus an idle descent is generally too steep for pax comfort, but you can change the VNAV targeted FPA to somewhat get some control over the steepness.

However, the real aircraft, once descending in VNAV, will always continue descending to the next restriction, unless the angle to the next restriction is less than 1 degree. This is called VNAV path smoothing and will be coming soon in an update.
