### ISSUE TITLE
[CJ4] Pausing by hitting ESC puts plane into nose dive on resume while on GS 

### ISSUE THREAD

**Issue by LoungeFlyZ** [Working-Title-MSFS-Mods/fspackages#772]
While on approach to NZCH and established on ILS 02 with GS active and working and at ~1000ft, I paused the game by hitting ESC and going to the menu.  When I returned I resumed the flight by pressing ESC again.  Then plane nose dived and it looked like the FD was pointing directly down ... not to where it should have been to stay on the GS.

**Comment by dga711** [comment]
Even back in the stock version i noticed that the engine sim doesnt always/really stop. So depending on your current power settings you loose speed and therefore go down on unpause.

Check your speed and engines when it happens again after a long pause.
One phenomenon I had was that after pressing ESC that Engine 2 went out. But I can't think of anything the mod does to cause that.

**Comment by LoungeFlyZ** [comment]
Very interesting.  I have noticed that before when I used Active Pause in a different ootb aricraft, but not when ESC to the menu. Ok I will play around a bit more and see.  Thanks for the information.

**Comment by neoeinstein** [comment]
I do know that, while in pause mode, many functions continue to run, as I observed when working with the WASM PID controller. Any PID-like controller that isn't aware of the fact that the simulation is paused (whether active or regular) may be continuing to do calculations, receive no feedback that there has been a corresponding response, and start winding up to the point that, on un-pausing, the control is thrown to its limit.

**Comment by dga711** [comment]
No further information.
Feel free to reopen when this happens in the current versions. Thank you
