### ISSUE TITLE
[cj4]  Loading external flight plans 

### ISSUE THREAD

**Issue by 39crauds33** [Working-Title-MSFS-Mods/fspackages#773]
I generated a flight plan in world menu;  saved it as .flt and as .pln.  When I activated the flight I went to FMC IDX page 2 and selected MOD settings page.  I then set FP SYNC -> ON,  Then I went back and selected ROUTE MENU.  I typed in the name of my saved flight plan and selected FLPLN  RECALL (game) and a "loading" prompt appeared and then a confirmation that it was loaded.  But when I checked no waypoints were loaded.  Obviously I did something wrong.  Anyone spot my procedural error?  Or is this not implemented yet.  The reason I did not enter manually is that I have some user waypoints that are not in current database and they were critical to that particular flight..

**Comment by mattnischan** [comment]
Game flight plan recall cannot load pln or flt files, as aircraft code does not have filesystem access. Flight plan recall only loads the current game flight plan that you set up in the main menu before the current flight.

**Comment by 39crauds33** [comment]
I did set up the flight in the main menu, but it only loads the origin and
destination no waypoints in between.

**Comment by suntorysan** [comment]
Could be caused by creating a flightplan with outdated navcycle stars, that are not recognised by the game. Is the problem only occurring in CJ4 or other aircrafts as well?

**Comment by dga711** [comment]
> I have some user waypoints that are not in current database
@39crauds33 
Oh custom waypoints from the world map are not supported in the FPLN RECALL yet. But it was on my todo list. Could be that the import loop then catches fire and imports nothing.
Will test and fix.

**Comment by dga711** [comment]
Custom waypoint imports from world map will be supported in the coming update. Thank you
