### ISSUE TITLE
Runway number stuck on map after doing consecutive flights

### ISSUE THREAD

**Issue by Ungeneer** [Working-Title-MSFS-Mods/fspackages#774]
I'm doing a multiple leg journey in the CJ4 and i have found that when putting in a new flight plan after flying a previous one (without exiting the game) the runway number from the airport I'm departing is stuck on the map.
![Capture](https://user-images.githubusercontent.com/73706687/103742485-e2ad6500-4fc8-11eb-9f8d-8da7726bd41b.PNG)

**Comment by dga711** [comment]
This should not happen anymore in the upcoming 0.9.0 release. Thank you
