### ISSUE TITLE
Followed directions on the CJ4 install 

### ISSUE THREAD

**Issue by ffjohn81** [Working-Title-MSFS-Mods/fspackages#775]
I followed the directions on the CJ4 install however there is no folder to delete as was part of the instructions and there is no cockpit when installed. I am not sure what I am doing wrong

**Comment by NvTacticalz** [comment]
I'm exactly the same. No cockpit at all, just see through. When you attempted to copy over the file from the zip folder did you have any issues where some of the files wouldn't transfer over due to the path being too long.....

**Comment by ffjohn81** [comment]
Nope just no cockpit at all

**Comment by NvTacticalz** [comment]
I've uninstalled the mod and the missing cockpit is still there....feel a complete reinstall of the game coming 😔

**Comment by NvTacticalz** [comment]
I've added a comment on the website so hopefully someone can tell us what the issue is...

**Comment by dga711** [comment]
You seem not to use the latest 0.8.3 release which is compatible with the 22 Dec msfs update.

**Comment by NvTacticalz** [comment]
Not that i want to hijack your conversation box ....the 0.8.3 is confirmed with mine having checked the manifest.json file within the zip folder

**Comment by NvTacticalz** [comment]
Sorted mine out. Didn't extract the files from the zip folder into C drive before moving the file into the community folder. All ok, cockpit clear as day

**Comment by ffjohn81** [comment]
where is the file i need to delete?

**Comment by NvTacticalz** [comment]
In the community folder of MS

**Comment by ffjohn81** [comment]
There is no folder for cj4 to delete. This is the only folder

**Comment by NvTacticalz** [comment]
If there's no Working CJ4 folder then don't worry about it.....

**Comment by ffjohn81** [comment]
I follow the directions that the working title provides and when I start the sim there is no cockpit.....

**Comment by mattnischan** [comment]
@ffjohn81 - Which version of the CJ4 did you download?

**Comment by NvTacticalz** [comment]
I had the same. I used a zip program you can download for free. Use that mate and it will sort it
