### ISSUE TITLE
CJ4 8.3 AP FLC generate a crash of flight simulator.exe

### ISSUE THREAD

**Issue by Mushupm** [Working-Title-MSFS-Mods/fspackages#776]
I have been trying to joint LFLL to LSGG several time, importing a flight plan from MSFS.
Just before reaching 13000ft after Take Off with AP ON and NAV/FLC, I got the vocal message announcing Altitude.
Few second later, I got the small window indicating a Flight simulator.exe crash.
I have been experimenting this issue with addons in Community folder and without addons.
Doing the same flight with Asobo CJ4, I have been able to reach Geneva.
Let me know if you need more information.
I did not see this issue already reported.

**Comment by dga711** [comment]
Its hard to tell what happened there. Also I see no way right now to find out.
At this time we don't get many CTD  reports anymore that sound to be related to the plane
Feel free to reopen when you have new information. Thank you
