### ISSUE TITLE
CJ4 mod

### ISSUE THREAD

**Issue by NvTacticalz** [Working-Title-MSFS-Mods/fspackages#777]
Transsferred the CJ4 mod to community folder...a few files wouldn't copy over with error code that the path is too long...eventually when I messed about with the files (to make them copy over), i loaded up MSFS, the CJ4 has no instrument panel at all and the plane is see through from the cockpit....any ideas what I'm doing wrong??? Rest of the planes in the game are fine except the CJ4......

**Comment by GertBFrobe** [comment]
I used to get that, too, and found that if I didn't use an "unzip" program to get the folder contained in the .zip file, and just dragged it out, it wouldn't work. 
I use WinRAR to extract the "workingtitle-aircraft-cj4" folder to a temp location, then CTRL C copy the folder over to the community folder.
