### ISSUE TITLE
[CJ4 v0.9.0] Can't activate Direct To using the DIR page. 

### ISSUE THREAD

**Issue by JuiceBox7535** [Working-Title-MSFS-Mods/fspackages#782]
Pressing the Line Select Key on the Direct To page does not load the proper waypoint. Only way to go direct to a waypoint is by moving it up in the Legs page, which appears to work properly.

**Comment by mattnischan** [comment]
Can you give any more specifics about the situation in which you encountered this behavior?

We tested the page quite thoroughly during the 0.9.0 dev run and didn't run into this problem, so I'm wondering what the trigger could be.

**Comment by JuiceBox7535** [comment]
Sure, hard one to explain, so will post the video on YouTube (unlisted). Tried activating direct to EVACE intersection, but it wouldn't take it. So tried JAXSU a couple times, and no luck. Had to do it in the LEGS page by moving EVACE up to the magenta line. 

Here is the link, but YouTube is still processing the 1440p version. If you can't see it, it should finish processing here before long.

https://www.youtube.com/watch?v=iC4YVp8euGE&feature=youtu.be
