### ISSUE TITLE
G1000 PFD and MFD Brightness always set to Minimum

### ISSUE THREAD

**Issue by Crispy136** [Working-Title-MSFS-Mods/fspackages#783]
When ever I use any G1000 aircraft, the brightness control is now always on the minimum setting when I start a flight.  I normally fly in the day, and always have to crank up the brightness to 100%.  Even reloading a flight sees the brightness set back to minimum.  Am using version 0.3.4.  

When I reverted back to version 0.3.2 the brightness returned to normal maximum brightness when I loaded a flight for the first time.  When I adjusted the brightness during the flight. it also remembered the brightness setting for the next flight.  When I ended a flight with max brightness set, the next flight started with max brightness.  When I ended a flight with minimum brightness set, it started the next flight with minimum brightness.

The readme.md mentions better brightness control, but seems to refer to button control rather than default values. 
 Unfortunately I can't just revert to 0.3.2 as 0.3.3 and 0.3.4 fixed compatibility issues with recent Asobo updates.

On the DA62X and DA40 NGX forums some users reported the same issues as me while others were OK.  So I did some more testing and found that the problem stems from changing the folder name.  I control my community folder content by renaming the folders.  Scenery always starts with a 1, repaints with a 2, aircraft mods like the DA62X with a 3, and finally, the instrument mods like the G1000mod with a 4.  MSFS loads alphabetically and uses the last loaded mod if there are any overlaps, so using this naming convention stops any conflicts for me.

So it seems that version 0.3.4 requires a specific folder name for the G1000 in order to remember the last used brightness, while version 0.3.2 does not.  Not sure why you did this, but this seems to me to be a backwards step.  If you are going to keep a hard coded folder name for some G1000 mod functions, then I think you need to add something to the included readme files that the folder name must never be changed.

**Comment by sh4d0wl3ss** [comment]
I use the default folder names and still find the brightness at minimum regardless of where avionics lighting controls are set.  Playing without the add on the brightness controls work correctly.

**Comment by kaosfere** [comment]
Nothing in the brightness control should be related in any way to the name of the directory the mod is in.  It is based on one of the identifiers the game uses for the model of plane you're in.    Can you please confirm whether or not this happens in every plane, as well as that this happens when the G1000 is the only mod installed?    And, to be clear, this happens every time you load a flight, right after you hit the "fly now" button?
