### ISSUE TITLE
Throttles not animating 

### ISSUE THREAD

**Issue by julietbravo52** [Working-Title-MSFS-Mods/fspackages#784]
Both throttles are mapped to throttle axis on my quadrant .When I spool them the N1 rises along with the engine sound. But they don't move from the idle position. I am unable to use the mouse to move them either

**Comment by dga711** [comment]
You are using a livery which contains a panel.cfg that is overriding FADEC
Use stock or another compatible livery or remove the panel.cfg from it.

See release notes.
