### ISSUE TITLE
CJ4 ATC does not recognize Power On if starting from cold and dark

### ISSUE THREAD

**Issue by brwhisler** [Working-Title-MSFS-Mods/fspackages#785]
On the last update to CJ4, version 0.9.0, if starting from a cold and dark state, the ATC option does not recognize when power has been turned on. In other words, Master switch on, engine started using full procedure and avionics turned on. Then open the ATC window, it says radios must be turned on. Same holds true if starting cold and dark and then using the Ctrl+E to start the engines.

However if sim is started with aircraft on the runway with engines already running, the ATC window works as expected.

Have been using this great aircraft but looked around to see if there might be another switch that I have to turned on figuring that a new feature was added but don't see anything.

**Comment by CBGonzalez** [comment]
I noticed the same. Was OK in previous version

**Comment by dga711** [comment]
Is to be fixed in a 0.9.1 patch that will come very shortly. Thanks
