### ISSUE TITLE
[cj4] after hold, plane did not continue with plan (leading to CTD)

### ISSUE THREAD

**Issue by lakemike** [Working-Title-MSFS-Mods/fspackages#791]
On the usual approach via TULSI and RTT towards LOWI runway 26:
- hold at RTT was entered and kept fine
- when exiting the hold, the plane went onto the inbound leg, but after completing it, it kept going straight
- in an attempt to reactivate the flight plan, I pushed NAV twice; this seemed to get the plan reactivated (plane swept right), but then a CTD followed

**Comment by gnkidwell** [comment]
@lakemike by any chance, did you check for discontinuity under the legs? I have noticed this happen more than once too.

**Comment by lakemike** [comment]
Hi, yes, when I created the plan there was a discontinuity as well as a duplicate waypoint (RTT, the one where I wanted to enter the hold). Before takeoff, I had fixed the discontinuity as well as removed the duplicate RTT waypoint.

**Comment by K20017** [comment]
Flight plan not sequencing after hold issue should be fixed in the upcoming release.  The crash might be unrelated as this would be the first report ive seen that's related to it.
