### ISSUE TITLE
CJ4: Expose FMS buttons

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#792]
I'm not sure it's possible but it would be really nice if the FMS buttons could be exposed to enable mapping them to hardware panels through FSUIPC or similar. I don't know how these things work "under the hood" but perhaps it would be possible to "wire them" to events already exposed but not used in the CJ4, like the G1000 soft keys?

**Comment by dga711** [comment]
This new wiki page will describe the available H Events. https://github.com/Working-Title-MSFS-Mods/fspackages/wiki/Sim-Variables

Some external binding apps are now adding WASM modules that will allow you to map LVars and H Events. Don't about FSUIPC. But need to bug them for support.
