### ISSUE TITLE
CJ4 DME only nav stations not working

### ISSUE THREAD

**Issue by daanvb** [Working-Title-MSFS-Mods/fspackages#796]
When tuning to DME only stations such ALF 115.80 at EDDH and MHD 112.5 at EDMN, neither of them identify or tune to the DME. I have tested on WT1000, GNS530 and FBW NEO (only shows DME) and these work as expected.

Also mentioned here #687

These are at EDDH tuning to ALF DME 115.80 (But same result at EDMN etc):

![G1000 DME](https://user-images.githubusercontent.com/17300780/104109209-8e093300-52c3-11eb-8289-fc170ab39f55.png)

![GNS530 DME](https://user-images.githubusercontent.com/17300780/104109212-906b8d00-52c3-11eb-9afe-d144d84b4add.png)

![Neo DME](https://user-images.githubusercontent.com/17300780/104109248-dfb1bd80-52c3-11eb-9dd0-343e2a1859b7.png)

![CJ4 DME](https://user-images.githubusercontent.com/17300780/104109292-3ae3b000-52c4-11eb-8046-335f2ccae7e7.png)

Thanks

daan_vb#6541

**Comment by dga711** [comment]
Will be fixed in the coming update
