### ISSUE TITLE
PFD and MFD screens swapped

### ISSUE THREAD

**Issue by erayymz** [Working-Title-MSFS-Mods/fspackages#797]
Plane: DA62
After I upgrade to g1000-v0.3.4, the MFD and PFD screens are swapped. Not sure how to swap them back. Anyone else having this issue?

**Comment by Dreamsofwings** [comment]
Hi, I had the same issue and fixed it by swapping them in the Panel.cfg of the DA62X in the Community folder so that under Vcockpit01 I have texture=$AS1000_PFD_2 and in Vcockpit01 I have the same but with a 1 at the end.

**Comment by kaosfere** [comment]
@Dreamsofwings has a solution.   Alternatively, the latest version of the DA62 mod works correctly.
