### ISSUE TITLE
CJ4 Auto Pilot Elevator wrong direction

### ISSUE THREAD

**Issue by CptUnderpantz** [Working-Title-MSFS-Mods/fspackages#799]
I don't know if its just a visual bug or functional bug, but while autopilot is engaged at cruise speed the elevator
![20210109215505_1](https://user-images.githubusercontent.com/38815289/104115596-bbef7700-52c5-11eb-827b-b7b3ab171fc1.jpg)
![20210109215534_1](https://user-images.githubusercontent.com/38815289/104115599-bd20a400-52c5-11eb-92a9-bc5ff7031163.jpg)

 trim indicates full ND (nose down) while the trim tabs visible on the plane surface appear full NU (nose up).

**Comment by K20017** [comment]
The trim tab's position affects the nose in the opposite direction that you'd think.  The tailplane's lift is downwards or upside-down and when you trim for nose up, that means the trim tab goes down.  The air hits the tab and forces the elevator up which creates more lift on the tail and brings the nose up. TLDR is that the trim tab moves in the opposite direction of where you want the nose to go. 👍
