### ISSUE TITLE
CJ4 seat configuration no longer compatible with OnAir Company

### ISSUE THREAD

**Issue by Hillman79** [Working-Title-MSFS-Mods/fspackages#801]
Since version 0.9 and also in the new 0.9.1 the CJ4 is no longer compatible with the standard MSFS 2020 CJ4 in OnAir Company. The flight tracking page in OnAir shows a seat mismatch. OnAir has 9 configured in their MSFS CJ4 model and 12 are configured in the loaded CJ4 Mod aircraft in the simulator. Therefore OnAir does not allow to start flight tracking. I tried to solve the issue by deleting the new 12 seat configuration in the flight_model.cfg in the mod and reinstate the 9 seat configruation and now it works with OnAir again. I'm not sure if this is an OnAir issue and the regular MSFS CJ4 w/o mod now also has 12 seats or if it can be solved in the mod. Maybe I also missed something and I can change seat configuration somewhere in the simulator and not having to change the cfg file of the mod?
Best regards
Juergen

**Comment by dga711** [comment]
Afaik onair now provides a WT CJ4 configuration?
Feel free to reopen when you have new information. Thank you
