### ISSUE TITLE
CJ4 - VNAV descend past altitude restriction

### ISSUE THREAD

**Issue by jbencina** [Working-Title-MSFS-Mods/fspackages#806]
Bought this up in the Discord, but logging here for tracking.

Was flying inbound to KAUS on WLEEE5 STAR when the CJ4 ignored an altitude restriction and continued a steep descent. There are two sequential waypoints on the STAR (TOONE and BOWTZ) which both have a crossing altitude of 4,000 feet. I crossed TOONE at 4,000 while descending from the prior waypoint, but the CJ4 continued its descent from that point.

The screen shot indicates the FD had a 5 degree down command while the MFD shows +1,000fpm VS and 4,000 feet commanded. These two seem in conflict, and I think the jet should've leveled off. The preselector was set to 0, but I was expecting the VNAV to follow the waypoint restrictions in the FMS.

![image](https://user-images.githubusercontent.com/5510940/104142854-2827b480-5372-11eb-8f07-5ff925dd9582.png)

**Comment by dga711** [comment]
The coming update will include a overhaul of VNAV.
Feel free to reopen the issue if the problem persists.
