### ISSUE TITLE
LNAV issue exiting hold

### ISSUE THREAD

**Issue by jbencina** [Working-Title-MSFS-Mods/fspackages#808]
I took off from KSJC and had a short test flight from OOMEN -> RISTI -> LICKE. I enabled a hold at RISTI. The plane captured that hold without issue. I issued an exit hold about 3/4 of the way in. The LNAV continued with the second hold turn, but then seems to have gotten confused.

RISTI -> LICKE should've been a bearing of 184. Instead, I proceeded northbound on a weaving northbound path that looks like a backcourse.

![image](https://user-images.githubusercontent.com/5510940/104146714-7a6fd200-5380-11eb-9d5b-4d4fc1e78537.png)

Here is a capture of my cockpit at the time

![image](https://user-images.githubusercontent.com/5510940/104146833-f2d69300-5380-11eb-8977-cbbe4c28f600.png)

**Comment by HackBrettHB** [comment]
I had a similar issue today... I programmed a hold at the next waypoint into the FMC (never entered the hold) and then overwrote the hold again in the legs section.
The AP continued on heading when reaching the waypoint, even though LNAV way active and it should have done a left turn to stay on the route.
I was unable to recover LNAV functionality with turning the AP on off etc etc

**Comment by dga711** [comment]
This should be improved in the coming update.
Feel free to reopen if the issues persists. Thanks
