### ISSUE TITLE
G1000: Waypont/Airport input should start with the letter A

### ISSUE THREAD

**Issue by kaosfere** [Working-Title-MSFS-Mods/fspackages#81]
From @alexismmef:

When in FPL Page, Typing a new Waypoint / Airport, it should Start with the Alphabet Letter A, not a Number. The Numbers Start only after you go through all the Alphabet.

**Comment by jonasbeaver** [comment]
This is a modifiable setting. In the US, the default G1000 on the bonanza and mooney start with K. I forget about the cessna and the diamond but I think it was the same with them (in the states).

Either way it shouldn't start with zero!

Different flavours of the G1000 (by manufacturer) also have different abilities when first loading a waypoint, there is a sub-selection when the K pops up to select from Recent, fltpln, (and nearest? I think) to select from local or common waypoints/airports. Its super helpful. My last flight was a return from the flight before. On the PFD side (I could have done it identically on the MFD side) I hit fltpln, small knob to the right to get the K cursor flashing, big knob to the right to select recent waypoints, small knob to highlight the last airport, enter to select, do the same with the destination and I can have a simple direct fltpln loaded in about 7 button presses and twists or about 10 seconds... usually before the GPS even knows where it is. That's also faster than I can load a saved route, so when going direct I rarely bother to save a plan.

**Comment by kaosfere** [comment]
Yeah...  looking at this further it looks like the G1000 is making calls into the in-sim GPS using the old FS9 interface that they're still exposing, and I think that is what is controlling the order of the letters.  It could still be fixable, but it might be hard, and especially if it's not a consistent thing it might be best to wait until we have a setting for it that people can choose. :D  Going to punt this one to v.Next.
