### ISSUE TITLE
Legs sequence acting like in Inhibit after last fix on a SID even though its in Auto

### ISSUE THREAD

**Issue by fnne99** [Working-Title-MSFS-Mods/fspackages#811]
Maybe I've missed something but the last two flights since .90 was installed, once I pass over the final fix on a SID transition, it doesn't switch to the next leg.  It acts as if its in Inhibit mode versus Auto. Outside of the SID, it works normally.
Is this something I'm doing wrong or is it an issue possibly?

Thanks

**Comment by K20017** [comment]
Are you flying into a discontinuity?  If so, it won't sequence until you go direct to a fix or delete the discontinuity.

**Comment by dga711** [comment]
Can't reproduce.
If there is any new information or steps to reproduce feel free to reopen. Thank you
