### ISSUE TITLE
Spoilers TOO sensitive/ too much drag

### ISSUE THREAD

**Issue by andrejetcat** [Working-Title-MSFS-Mods/fspackages#812]
first of all - AN AWESOME MOD - THANK you for all this hard work!

one thing is unrealistic in my oppinion as a real world pilot:

compared to the size of the spoilers, the drag they create is way too much! It could easy be the half of drag, it would more realistic!
can´t proof it with numbers but I fly citations in real life.

thank you once again!

**Comment by HackBrettHB** [comment]
I only have experience flying the B777 in real life and if you pull the speedbrakes to 100% when doing around 250 knots it is like throwing out an anchor... 
Now when looking at the CJ4 in the sim this is exactly this same feeling and I therefore feel like it is reasonable. Maybe a slight reduction by max. 20% would be good, but halving the effect seems much too weak.
Also the flightmodel just had an overhaul so I think it should be pretty accurate atm...

**Comment by andrejetcat** [comment]
> I only have experience flying the B777 in real life and if you pull the speedbrakes to 100% when doing around 250 knots it is like throwing out an anchor...
> Now when looking at the CJ4 in the sim this is exactly this same feeling and I therefore feel like it is reasonable. Maybe a slight reduction by max. 20% would be good, but halving the effect seems much too weak.
> Also the flightmodel just had an overhaul so I think it should be pretty accurate atm...

I agree, the 777´s spoilers act like an anchor...BUT, when you select them, all spoilers deploy (expect the inner ones...) but when you use the first half of the cj4´s spoilers, it act like a HUGE anchor, BUT there are only the small little ones active. so that is to my feeling way too much. 
but again, I  don´t want to rush against this beautiful and awesome mod. It was only a suggestion for improvement. :)

**Comment by K20017** [comment]
There was a change to the flight model which changed a few things and the spoilers are currently too effective, they will be adjusted to the pre 090 settings 👍
