### ISSUE TITLE
CJ4 0.9.1: TO/GA not disarmed automatically

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#815]
Lining up on the runway with my AP set (altitude, NAV and FLC speed). Pressing TO/GA and taking off. Once airborne and approaching a convenient altitude I press AP. TO TO disappeares but my AP settings are gone so I press NAV and FLC and dial in 240 kt. Nothing happens. Turns out I have to disarm TO/GA manually but if that's by design it feels unlikely that pressing the AP button should remove TO TO, effectively "hiding" the fact that I'm in TO/GA.

**Comment by okurz** [comment]
I understood the proposed flow differently. What I am using is just dialing in the selected altitude and nothing else. Then I press TO/GA and take off. After take off I enable AP, then later select e.g. FLC when I reach about the right speed and fine-tune with the selection. Then, independently select either HDG or NAV. The display of modes starts with "TO - TO" when pressing TO/GO without yet enabling AP. Then "TO AP TO" to show that the autopilot is active. Enabling a vertical mode without yet a horizontal mode correctly shows something like "TO AP FLC", so the first "TO" stays for lateral mode and is replaced subsequently by something like "NAV AP FLC". I don't need to disarm TO/GA manually. Can you confirm it this way? The issue might still persist as you described it when following the process differently though.

**Comment by AndersHogqvist** [comment]
I will try that right away. I wouldn't be surprised it this is a case of BPBTY :-)

**Comment by AndersHogqvist** [comment]
Well, doing it your/the right way did indeed work as expected. Closing this non-issue now. Thank you!
