### ISSUE TITLE
G1000 - disappearing Flt Pln legs

### ISSUE THREAD

**Issue by rwilsonlj** [Working-Title-MSFS-Mods/fspackages#817]
FYI, I just flew from KPSP to KSBA and had entered the VOR 25 approach before takeoff. Enroute, (MSFS ATC) instructed me to use the ILS 7 approach. When I changed the procedure to ILS 7 with the GOLET transition in the G1000 and activated the approach, the flight plan page essentially changed to blank. It had USR under the KPSP and KSBA lines and Rwy 7 at the bottom with a big blank space between them. Even though the route disappeared (no magenta lines on the MFD), it flew the approach properly with the correct waypoints, although I never did acquire the LOC or GS. I double checked the frequency so there may be a bug in the NAV data at KSBA. I posted this on the AVSIM forum too and thought this was the more appropriate place for this. I am still researching why the G1000 freezes at times. Thanks for the mods!

**Comment by KeyGlock666** [comment]
+1

**Comment by davidebocca** [comment]
same here (g1000 on da62)
