### ISSUE TITLE
FMS TEXT UTC TIME does not roll over after 2400

### ISSUE THREAD

**Issue by Chesejrs** [Working-Title-MSFS-Mods/fspackages#819]
![image](https://user-images.githubusercontent.com/77415751/104514102-b6907600-55be-11eb-995a-382e31deb49e.png)
Flights rolling past 0000 utc time do not show properly on the MFD when FMS text selected.

**Comment by slip664** [comment]
While we're at it, the ETE also doesn't need the leading 0
![time](https://user-images.githubusercontent.com/72432870/104517179-69a2a480-55aa-11eb-9f69-8d9981d600c2.PNG)

**Comment by K20017** [comment]
Thanks, fixing them now.

**Comment by K20017** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/20977949/104524871-04ac7600-55cd-11eb-8af5-09920dac5e8d.png)

**Comment by flymypi** [comment]
@K20017 Github is a beautiful website. If it weren't for their real-time update of issues, this would've been done twice now. 😄
