### ISSUE TITLE
CJ4 0.9.1 Entering ORIGIN and DESTIN only should not display a route in PFD/MFD

### ISSUE THREAD

**Issue by taguilo** [Working-Title-MSFS-Mods/fspackages#824]
As the title says. At least one waypoint must be present, whether or not an ORIGIN or DEST airport is entered.
Unless the CJ4 contains an upgraded version of PL21?

**Comment by K20017** [comment]
Nah, it's the same setup, Orig and Dest are only for procedures and charts loading and aren't waypoints, we just haven't gotten around to separating it from how it was with default. 👍
