### ISSUE TITLE
CJ4 0.9.1 TO TO mode proper performance

### ISSUE THREAD

**Issue by taguilo** [Working-Title-MSFS-Mods/fspackages#825]
TO TO is a FD only mode.
Once in flight, 
1)if AP is engaged, it will revert to ROL/PTCH or HDG/PTCH (if HDG/TO were the active modes).
2)if SYNC button on yoke (not simulated yet) is pressed, the same happens.
3)if any FGS mode is selected with AP not active, the new mode (either pitch or roll) will replace TO or the one was present, and the other side will revert to FD default (ROL/PTCH) if TO was the previous one.
Examples:   
                         [ HDG  TO] --> FLC pressed --> [HDG FLC]
                         [TO  TO]     --> HDG pressed --> [HDG PTCH]
                          
GA modes are the same but when engaged in flight.
YD engagement does not affect TO modes.

Hope this helps

**Comment by K20017** [comment]
Getting fixed in a future release. 👍
