### ISSUE TITLE
CJ4 - Cant clear NAV frequencies

### ISSUE THREAD

**Issue by tredsell** [Working-Title-MSFS-Mods/fspackages#829]
There appears to be no way to clear NAV frequencies, only to overwrite them with a new one. Should CLR/DEL not be possible to empty the field?

**Comment by tredsell** [comment]
Understood. I believe the set freq is not always being overwritten when you
select a new ILS approach on subsequent legs.

Does the real FMS include the option to switch from automatic tuning to
manual as with the FMS3000 in the 560 series?

**Comment by taguilo** [comment]
> Does the real FMS include the option to switch from automatic tuning to manual as with the FMS3000 in the 560 series?

Yes, but AUTO/MAN is not implemented yet AFAIK

**Comment by K20017** [comment]
Correct, frequencies can't be deleted, only changed. Technically when you boot up, it should load the last frequency that was in there but we don't have that functionality yet.
