### ISSUE TITLE
CJ4 Com 1 cannot be used 0.9.1

### ISSUE THREAD

**Issue by gnkidwell** [Working-Title-MSFS-Mods/fspackages#830]
I noticed on a flight last night on Vat Sim, Com 1 was unusable, whether it was the Vat Sim channels or Flight Sim channels. I have been able to replicate this over and over again. You could set the channel on active or standby and then it would with a second change back to 121.800. Com 2 is unaffected, and working correctly. I can also confirm nav 1 and nav 2 are working correctly too.

**Comment by slip664** [comment]
Don't know what to tell you. Myself, and many other users, have done multiple flights on VATSIM using 0.9.1 without any issues. Sounds like something isn't set up right or there's a mod conflict.

**Comment by gnkidwell** [comment]
> Don't know what to tell you. Myself, and many other users, have done multiple flights on VATSIM using 0.9.1 without any issues. Sounds like something isn't set up right or there's a mod conflict.

I only have the working title mods installed in FS2020. I do however wonder if me enabling FS2020 flight plan sync may have caused it? Will look at that in a bit.

**Comment by dga711** [comment]
This usually happens when you have AI "Manage Radio Comms" on.
Try to see if that option is enabled in your sim and turn it off.

**Comment by gnkidwell** [comment]
> This usually happens when you have AI "Manage Radio Comms" on.
> Try to see if that option is enabled in your sim and turn it off.

Will try shortly to verify. I rarely ever turn that option on unless I am not flying on VatSim... Anyway I did try earlier changing the MS Flight Plan Sync to off in the mods on the mcdu... That appears to have fixed it for now. I need a little more time to verify it though.

**Comment by gnkidwell** [comment]
> This usually happens when you have AI "Manage Radio Comms" on.
> Try to see if that option is enabled in your sim and turn it off.

So it appears something was funky with the Sim that night, I have tried everything, and cannot replicate the issue. However, I did notice when on battery in dispatch mode, com 2 cannot be used. Is this normal behavior for the CJ4, if it is I will close this out.

**Comment by dga711** [comment]
@gnkidwell COM2's electrical circuit is cut off in Dispatch. (stock behavior)
Will see what would be accurate and do it accordingly.

**Comment by gnkidwell** [comment]
> @gnkidwell COM2's electrical circuit is cut off in Dispatch. (stock behavior)
> Will see what would be accurate and do it accordingly.

Thanks @dga711

**Comment by K20017** [comment]
On my visit to the real aircraft, I tested just using the dispatch mode with the battery off and this all you get.  So only Com1. 
![image](https://user-images.githubusercontent.com/20977949/104828407-0d07e980-5837-11eb-8052-bf89b8f573e5.png)

**Comment by gnkidwell** [comment]
@K20017 thanks, you all are absolutely amazing! The CJ4 mod is so far ahead of what Asobo gave us as a simulator plane.
