### ISSUE TITLE
CJ4 V0.9.1 - still rolling left/right in level flight (video attached)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#831]
Hey guys,

I´m just doing again another atlantic crossing and after my last post regarding this issue was closed, due to fact that no other 
had the same, or simlar issue, I recorded now a short video about it, which I like to share with you for a better understanding

Here you can see the wander of the track line in the PFD with an later on chasing moment of the plane, trying to center it again.
This happens the entire flight and will get worse, whith grater bank angles up to 5-8° when burning fuel. 5-8 is about when 2000lbs are left in the tanks.

https://www.youtube.com/watch?v=UZv6lbCrvik&feature=youtu.be

**Comment by K20017** [comment]
I think it's just the AP controller adjusting for the route, which we are still using default for.  Other than that, you could try disconnecting your hardware and see if it still does it. Also disable the AI yoke control in the assistance settings, those were known to cause strange out of control banking and pitching before.

**Comment by Jack737800** [comment]
I see, in  that case we can blame the default AP :D 
AI - I had never used, but it is confirmed OFF (just x-checked)
As well I disconeted my CH FlightSim Yoke and as well my Saitek Rudder Padel, without success.
The sim is still banking, so there´s no other option as the default AP.

Thank you for your response !

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
