### ISSUE TITLE
CJ4 0.9.1 doesn't displays crossing of time line between alaska and russia

### ISSUE THREAD

**Issue by SCORCHEDIMACX** [Working-Title-MSFS-Mods/fspackages#834]
I was confused what my MFD was indicating: a 180 turn instead of straight to the west. 
Ten I found out the discplay doesn't want to show the Pink line to cross the time Line. But in my case the Autopilot still folliws the path that would be there and then changes the direction of the line (see picture)
![2021 01 18-14 25](https://user-images.githubusercontent.com/77623585/104921055-1f019d80-5999-11eb-9078-8db3fe6edd37.png)

![2021 01 18-14 19](https://user-images.githubusercontent.com/77623585/104920522-32f8cf80-5998-11eb-9450-87ff0dcd77db.png)
![2021 01 18-14 18](https://user-images.githubusercontent.com/77623585/104920542-37bd8380-5998-11eb-9655-b427528c3688.png)

**Comment by dga711** [comment]
Could you find out if the stock plane shows that behavior too? Wondering if its our modified map drawing code or a bug with default? Thank you

**Comment by SCORCHEDIMACX** [comment]
Sorry for the late response.
I removed the Working Title Folder and typed in the same route. It seems like it is a bug caused by the sim since the same 180 degree turn is shown in the map.
