### ISSUE TITLE
CJ4 Prerelease 0.9.5 Hold Leg length

### ISSUE THREAD

**Issue by tredsell** [Working-Title-MSFS-Mods/fspackages#844]
When a hold is first calculated it appears to use perhaps the current GS to calculate the 1 min leg length. You can reduce this manually when you get close and slow down by overtyping the "1.0" in the LEG TIME field. Is it possible to use the figure in the MAX IAS field to calculate leg distance against that leg time rather than what it is currently using OR to recalculate the leg distance automatically when its the next leg using IAS/TAS or whatever is currently used?

**Comment by mattnischan** [comment]
@tredsell We do not accept bugs files against unreleased versions.

However, our behavior matches the real unit. Current groundspeed is used when inputting the hold. Then, when you pass over the hold fix, the hold will be recalculated with current speed and winds.
