### ISSUE TITLE
G3000 0.4 RELEASE VERSION - No AI traffic on map

### ISSUE THREAD

**Issue by Crunchmeister1** [Working-Title-MSFS-Mods/fspackages#854]
The title says it all. It was the same for me in the betas. No AI / Live Traffic is visible on the MFD or PFD mini-map. Doesn't matter what zoom level I'm at. There are no other aircraft showing on the map. I thought it was an unfinished feature in the betas, so didn't say anything. But now I'm genuinely surprised to see this rather significant omission made it into the release version.

Anyone else?

**Comment by cywang90** [comment]
resolved with v0.6.0
