### ISSUE TITLE
CJ4 0.10.0 - Black FLP and DIR page

### ISSUE THREAD

**Issue by patbuser** [Working-Title-MSFS-Mods/fspackages#860]
To reproduce (works every time):
_ create or load flightplan
_ select an approach on the destination
_ then DIR Page: nearest airports
_ select any
_ select new approach (nothing happens)
_ 2nd click on the approach, it's then selected and the EXEC pops up
_ nothing happens when clicking LSK for EXEC
_ FLP and DIR pages are black

Power cycling does not help.

**Comment by dga711** [comment]
Should be fixed in the coming update. Thank you
