### ISSUE TITLE
[CJ4 v0.10.0] High Stall Speed

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#861]
Upon approaching UKLL Rwy 31 I got high angle of attack and stall warning well above Vapp speed. My configuration and weights appear OK. 

I had to continue approach/landing at 120 KIAS to avoid stalling again.

![2021 01 27-22 41_01](https://user-images.githubusercontent.com/71787933/106058258-4a9b2b00-60f1-11eb-8157-60f8e5287975.png)

Thanks for looking into this!

**Comment by NiklasKK** [comment]
Noticed the same and have a short clip.

Because it could be hard to read in the clip these where the approach speed calculated in the fms:
        - Vapp = ~108kt
        - Vrf = ~101kt
        

L and R Tank: 298kg int this clip
ZFW: 5126kg

https://user-images.githubusercontent.com/60063815/106140959-bfad4580-616f-11eb-993e-8ddf80bbb650.mp4

**Comment by N38TM** [comment]
I've had this issue since the latest update. Stall warning early and at higher speeds than previous

**Comment by dga711** [comment]
Should be fixed in 0.10.1 that will come soon.
Feel free to reopen if this issue persists afterwards. Thank you

**Comment by sfdeham** [comment]
The issue appeared fixed since version 0.10.1 and several flights. However I just ran into the same in 0.10.2 upon landing at UNOO Rwy 25:

![2021 02 05-00 13_01](https://user-images.githubusercontent.com/71787933/106968377-f9221a00-6748-11eb-90ae-4ae38e6a966b.png)

Can you please look into this again?

**Comment by sfdeham** [comment]
@dga711 I appears that I cannot re-open this closed thread. Please re-open for me.

**Comment by N38TM** [comment]
I be happy to you, but how do I do that.. I didn't close it

**Comment by mattnischan** [comment]
@sfdeham The flight model has not been altered in version 0.10.2 or in fact at all since the fix for the lift scalar.

Is it possible you picked up some ice?

**Comment by N38TM** [comment]
I haven't had a stall issue since using 10.2

That issue was with 10

**Comment by sfdeham** [comment]
> Is it possible you picked up some ice?

@mattnischan Icing is set to "Visual Only".

On the other hand I noticed that I flew through clouds at low temperature without any effect on the windshield (didn't check wings though). Maybe something went wrong with the icing simulation?!

If you have no other explanation I will monitor for icing more closely upon next flights.

**Comment by sfdeham** [comment]
@mattnischan Here's my findings after next flight:

- MSFS icing set to "Visual Only"
- Approach through clouds below 0°C
- Anti-Ice OFF
- Visual icing on wing leading edges but not cockpit windows
- Early stall way above Vapp
- Anti-Ice ON
- Restore to normal performance for Vapp

Does the mod have it's own ice or AOA modelling separated from MSFS?

**Comment by mattnischan** [comment]
@sfdeham Wow, that is very funky indeed!

No, we don't have any ice or custom AOA modeling; in fact, the sim doesn't even have hooks for such a thing at the moment. Sounds like maybe the Visual Only option isn't actually visual only. Might be worth filing a Zendesk.

**Comment by sfdeham** [comment]
@mattnischan 
OK, here we go...

[https://forums.flightsimulator.com/t/when-is-the-icing-effect-going-to-get-fixed/357871/44](https://forums.flightsimulator.com/t/when-is-the-icing-effect-going-to-get-fixed/357871/44)

`It says you can turn off the effects but it doesn’t work. Putting it on visual only still applies the full force of ice. Ice is broken.`

Will still file Zendesk for my specific case.

In the mean time we should get used to always applying anti-ice procedues :)
