### ISSUE TITLE
Cj4 v10 ILS

### ISSUE THREAD

**Issue by flyingfisher7** [Working-Title-MSFS-Mods/fspackages#863]
Flew 2 ILS approaches(KIAD 01R/KSTL 30R).  KIAD I experienced stall warning and high AOA at 140 knots.  KSTL I flew approach on autopilot and it leveled off.  Had to disconnect autopilot and hand fly the approach.  Attempted reconnect, but it would not follow the glide slope.

**Comment by dga711** [comment]
Should be fixed in 0.10.1

**Comment by flyingfisher7** [comment]
Thank you so much.  I appreciate all your efforts.
