### ISSUE TITLE
[CJ4 v0.10.0] EGLC ILS27 FMS1 mode not switching to ILS when APPR activated

### ISSUE THREAD

**Issue by oneworldflyer** [Working-Title-MSFS-Mods/fspackages#864]
Title says it all basically. A video of the issue is here:

https://www.dropbox.com/s/mjyc6afssh9x4xl/2021-01-28%2009-44-22_Trim.mp4?dl=0

FWIW: Using navigraph and ORBX EGLC scenery.

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
