### ISSUE TITLE
CJ4 Throttle Stuck

### ISSUE THREAD

**Issue by marcjones2** [Working-Title-MSFS-Mods/fspackages#867]
Unusual one. Throttle can't move from spawn or hot start. 
Load from cold and dark or on runway from any airport.

**Comment by dga711** [comment]
Could be 
1) Livery conflict
If you are using a 3rd party livery or, as of MSFS patch 1.12.13.0 the new liveries for the CJ4, the panel.cfg file is overwriting our FADEC injection code. You can either remove that panel.cfg file from your custom livery or use the first default CJ4 livery.

2) Did you have Kinetic glider installed? Check our latest changelog for a possible solution to this
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/cj4-v0.10.0

**Comment by marcjones2** [comment]
That fixed it. Thanks
