### ISSUE TITLE
CJ4 0.10.0: Waypoint sequencing start on the groundnd

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#868]
Just started at ESGG and had my FMS programmed for rwy 03 and the SOJW1P departure. That particular departure starts with a straight out climb to 1000ft followed by a right turn to the first waypoint (GG553). I was parked at the other end of the runway so I had to taxi the whole length of it down to 03. When I started taxying the flight plan was beginning at rwy 03 and had a (999) fix a couple of nm straight out, but about half way down the length of the runway that fix disappeared. The first leg went straight from the beginning of the runway to GG553.

**Comment by dga711** [comment]
Should be fixed in the coming update. Thank you
