### ISSUE TITLE
CJ 0.10.0: Pulse light not recognized as landing light

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#872]
I don't know if this is a "bug" with this mod, but when using OnAir the pulse light is not recognized as landing lights. Turning pulse light on below FL100 OnAir thinks I don't have landing lights on and gives me a penalty. Perhaps it could impact other addon applications as well, so I thought I should brought it up here.

**Comment by dga711** [comment]
I guess they check for the "LIGHT LANDING ON" SimVar which in fact is only true when you use landing lights.

Pulse lights is usually only used for special conditions and should not be the default mode for landing.
@K20017 can maybe tell you more about it

**Comment by K20017** [comment]
Seems more like an issue with OnAir, they might have to make an exception for both lights.  But I hardly used the pulse lights, only if traffic was a concern and we just wanted to be more visible.

**Comment by AndersHogqvist** [comment]
Ok, I will try to make them fix that then.

**Comment by mattnischan** [comment]
@AndersHogqvist Just to be clear, the pulse lights are _not_ landing lights and if you landed with just pulse lights on that would definitely not be proper operating procedures.

**Comment by K20017** [comment]
You can land with them on during the day but it's not authorized while at night 👍

**Comment by AndersHogqvist** [comment]
Sorry but I open this up again. Can the pulse light be recognized by external applications through SimConnect?

And to @mattnischan: I find it hard to believe that the pulse light isn't considered being a landing light. It's the same physical light bulbs that are pulsing. You can't land with both landing light and pulse light, the buttons are exclusive so "landing with just the pulse light" isn't even an option.

**Comment by AndersHogqvist** [comment]
Sorry but I open this up again. Can the pulse light be recognized by external applications through SimConnect?

And to @mattnischan: I find it hard to believe that the pulse light isn't considered being a landing light. It's the same physical light bulbs that are pulsing. You can't land with both landing light and pulse light, the buttons are exclusive so "landing with just the pulse light" isn't even an option.

**Comment by dga711** [comment]
The SimVar for it is
`LIGHT RECOGNITION ON`

The thing is, no matter if it is considered a landing light in the real world, in this sim it is considered RECOGNITION light. So OnAir has to decide on how to treat it.

**Comment by mattnischan** [comment]
@AndersHogqvist 

There's a good reason why they're exclusive. The first is obvious, they're the same light.

But secondly, the pulse lights are not there to help you see the runway. Pulse lights are there to alert other traffic to your position during the daytime when it can be hard to spot traffic against a cluttered groundscape. They don't have anything to do with the landing phase and aren't there for pilot/runway visibility.

I assume OnAir is trying to reward the pilot for lighting the runway for landing, not just operate _some_ light.
