### ISSUE TITLE
CJ4 0.10.0: Selected altitude ignored when switching to HDG on approach

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#873]
Flew to EKYT with the AAL VOR as My last waypoint before destination. I chose the ILS RWY 08L approach with GIPUG transition. With 2000ft dialed in and LNAV1/VNAV activated I reached D5.2 (AE) and switched to HDG and turned left so that I could pass GIPUG heading  towards the FAF. However, when reaching 2000ft it continued to decent and I had to disengage the AP. VNAV was still active and everything looked normal on the PFD.

**Comment by patbuser** [comment]
I just encountered something similar with 0.10.1., it busted through the selected ALT on approach. I thought it might be because I "accelerated" my descend with a manual VVS on VNAV (although it obviously shouldn't) but thinking about it, I was on HDG too. So this might be the trigger. .

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
