### ISSUE TITLE
Switching to VNAV SETUP Cruise or Climb page causes screen to go blank

### ISSUE THREAD

**Issue by nicka414** [Working-Title-MSFS-Mods/fspackages#877]
![image](https://user-images.githubusercontent.com/78179624/106203638-b6c96d80-6189-11eb-8d00-ddcbfaa49198.jpg)
Clicking the cruise or climb page in the vnav setup menu of the FMC causes the screen go to blank, switching back to legs page works fine. 
Using the latest hot fix 0.10.1

**Comment by dga711** [comment]
Should be fixed in the coming update. Thank you
