### ISSUE TITLE
GS on ILS approach lost at EDDL

### ISSUE THREAD

**Issue by mikebakke** [Working-Title-MSFS-Mods/fspackages#878]
Version 10.0.1 - Approach 23L into EDDL via BOT transition. 

Correct altitude (3000) achieved by VNAV - selector set to 2000. Switched to NAV as the final lineup started for 23L. As the GS indicator descended I engaged APPR just before it hit the median. FMA showed all good - APPR, LOC and GS green. 

Within 15 seconds the GS was lost and the plane levelled off. I did a disconnect and manually descended till GS was showing again. Re-engaged but no capture so hand flew down.

Recording wasn't on unfortunately but I will make sure it is for all approaches forwards and if it re-occurs I'll upload here.

Thanks

Mike

**Comment by Guenseli** [comment]
Yes, I have GS problems also with 0.10.1

**Comment by mikebakke** [comment]
Just flew an approach to 9L at EGLL and pretty much the same thing - initial acquisition ok but then levelled off and I had to take over again. In addition the LOC was offset to the left of centre, not massively but enough to matter. 

I have a recording but unfortunately only from when the GS was lost, let me know if you want it.

fwiw, flew the exact same approach last night as RNAV and it near as dammit took me to the runway :-)

**Comment by mikebakke** [comment]
Repeated this approach exactly tonight n 10.0.2 - this time it acquired and held the approach down to minimums where I took over which is great. As ever - one swallow does not a summer make so I'll do some more flights in the morning and try to see if it's stable on ILS (for me).

**Comment by dga711** [comment]
Feel free to reopen when you have new information. Thank you
