### ISSUE TITLE
CJ4 0.10.1 - wasn't able to catch magenta line after FPLN edit

### ISSUE THREAD

**Issue by Guenseli** [Working-Title-MSFS-Mods/fspackages#879]
My route was EDMA to EDDN
simBrief route was EDMA/25 RIDAR6G RIDAR DCT TALAL DCT UPALA DCT EDDN/28

I edited the FPLN in the LEGS page to approach ILS Z 28, Transition DOSIS
As I wanted to shorten my route a bit, I copied VP081 (as part of the approach) and inserted it after TALAL.

During the flight, the CJ4 haven't made the turn from TALAL in direction VP081, but was flying straight.

I wanted the to make a DIR to VP081, but haven't worked also.
Then I turned with HDG, but also, the CJ never captured the magenta line again.

**Comment by themiskt** [comment]
Also I noticed that I was flying with an offset. Plane captures the points correctly but there is an offset.

![image](https://user-images.githubusercontent.com/65069179/106330437-e82a6200-628b-11eb-8ceb-ddb6cae6071d.png)

**Comment by patbuser** [comment]
exactly the same on a flight from LFZB to LSGG. At some point on the STAR it just stopped to follow the magenta line and flew straight. Had to continue in HDG. Also, it then never autotuned the ILS, I had to do this and change the NAV source to NAV1 manually. Not sure what triggers the autotune but it was as if the plane didn't know anymore where it was on the FLP.

**Comment by Guenseli** [comment]
Again the same issue.
Approaching LIRQ,, STAR BEROK1V
After BEROK (start of STAR), CJ4 left Magenta line  and was not able to catch up again.

No sharp turn entering STAR

**Comment by mattnischan** [comment]
@Guenseli @patbuser Please try this with the latest version, 0.10.2. There should be a fix for this scenario.

**Comment by patbuser** [comment]
I can confirm, absolutely no issues in 0.10.2 for me! And I switched back and forth alot on purpose between HDG, NAV, APPR and everything worked as expected!

**Comment by Guenseli** [comment]
Yes, .10.2 first flight was without problems!
thx!
