### ISSUE TITLE
alphanumeric Simbrief id in the CJ4 mod

### ISSUE THREAD

**Issue by schmiko96** [Working-Title-MSFS-Mods/fspackages#881]
I enter my alphanumeric Simbrief (user-)id in the CJ4 mod, but it come up with an error "wrong pilot ID".
I noticed that the correct SimBrief ID should be a numeric value, but I don't know where to find it in my Simbrief profile.
I'm also using this alphanumeric User ID in the A320 mod, there ist works fine.

Could you change your excellent mod to accept the alphanumeric user-id?
Or could you tell me where I could find my own numeric user-id :-)

**Comment by dga711** [comment]
We are requiring the pilot id since not all alphanumeric chars can be entered in the fms.
A32nx switched from offering both to just pilot id as far as i know, too.

It is described in our OP  guide https://docs.google.com/document/d/1qzxPMTSQRkvau8QOi7xUqNvjx9rbww_qHlso5AT5OnI/edit#heading=h.eunxqrggh6d3

**Comment by schmiko96** [comment]
Ok, I understand that point, alphanumeric cjaracters could be a problem. But my problem is, I don't know my numeric Simbrief-ID and I found nothing in the profile. Do you know where I could find that ID?

Von: DG <notifications@github.com>
Gesendet: Freitag, 29. Januar 2021 18:26
An: Working-Title-MSFS-Mods/fspackages <fspackages@noreply.github.com>
Cc: Schmiko <mail@schmidt-korth.de>; Author <author@noreply.github.com>
Betreff: Re: [Working-Title-MSFS-Mods/fspackages] alphanumeric Simbrief id in the CJ4 mod (#881)


We are requiring the pilot id since not all alphanumeric chars can be entered in the fms.
A32nx switched from offering both to just pilot id as far as i know, too.

It is described in our OP guide https://docs.google.com/document/d/1qzxPMTSQRkvau8QOi7xUqNvjx9rbww_qHlso5AT5OnI/edit#heading=h.eunxqrggh6d3<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1qzxPMTSQRkvau8QOi7xUqNvjx9rbww_qHlso5AT5OnI%2Fedit%23heading%3Dh.eunxqrggh6d3&data=04%7C01%7C%7Cb9065ef8987d441fa42908d8c47af86b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637475379711692319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BdzCsTpOohPJ5Ewtbe1ms6TrGphdvFDdLf4jhChvdcI%3D&reserved=0>

-

**Comment by dga711** [comment]
I linked you our operation guide and the location where it will tell you where to find it

**Comment by schmiko96** [comment]
I think you mean the WT MOD SETTINGS page, but that’s not my problem to use that input field “SIMBRIEF PILOT ID”. My problem is a little bit stupid ☹, I don’t know my own SIMBRIEF USER ID, I only know my USER NAME, and I didnt found any information about that ID.

Von: DG <notifications@github.com>
Gesendet: Freitag, 29. Januar 2021 18:42
An: Working-Title-MSFS-Mods/fspackages <fspackages@noreply.github.com>
Cc: Schmiko <mail@schmidt-korth.de>; Author <author@noreply.github.com>
Betreff: Re: [Working-Title-MSFS-Mods/fspackages] alphanumeric Simbrief id in the CJ4 mod (#881)


I linked you our operation guide and the location where it will tell you where to find it

**Comment by mattnischan** [comment]
@schmiko96 The Operator's Guide linked also explains how to find the SimBrief pilot ID in SimBrief.

Did you read the provided document?

**Comment by schmiko96** [comment]
Ok, I found It, it was described in your document, but I found it to late, sorry and thank you for helping me 😊

**Comment by schmiko96** [comment]
How could I change that wrong alphanumeric value in the MCDU page? The status shows me "green", but the Simbrief ID is still wrong and I will change it to the correct numeric value. I didn't found anything about changing that value in your good documentation :-)

**Comment by dga711** [comment]
@schmiko96 You can change your pilot id in IDX -> PAGE 2 -> MOD SET
