### ISSUE TITLE
Anti-ice not working ?

### ISSUE THREAD

**Issue by NezHaut** [Working-Title-MSFS-Mods/fspackages#883]
Hello,

First, congratulation for this amazing mod !!

On my last flight with verison 0.10.1, it seems that the anti-ice wasn't working (visually at least). The performances were ok, but I kept ice on the wings during full flight (1h30), even when out of cloud with wing/eng anti-ice ON on both side.

Is this a known issue ?

Thanks a lot for the great work !
Best regards,

Tim

**Comment by dga711** [comment]
Hi. Afaik it is a sim issue and not really something we can change.
Ex. https://forums.flightsimulator.com/t/planes-still-icing-with-anti-ice-on/352705
