### ISSUE TITLE
CJ4 ILS issue

### ISSUE THREAD

**Issue by N38TM** [Working-Title-MSFS-Mods/fspackages#885]
Doing ILS approach to KPNS rw 17 
AP locked onto ILS and was tracking. At 10nm out aircraft slowly bank left and turned away from approach.
I had to gently guide the aircraft back to track. AP never came off.
This has happened on other ILS's lately.

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
