### ISSUE TITLE
CJ4  v0.10.1 FMS FLPN page display going blank after uploading MSFS flight plan

### ISSUE THREAD

**Issue by Guy7001** [Working-Title-MSFS-Mods/fspackages#886]
I was using a flightplan from the default MSFS page before entering the flight…once this is uploaded it makes the FLPN page on the FMS go blank. The details were all visible in the LEGS page though and seemed to run fine but the FLPN page remained blank for the rest of the flight
Flight was IFR from EGTE to EGKK, flight plan was uploaded after engine start up and pushback using the the FPLN RECALL (GAME/SB) option in IDX -> PAGE2 -> ROUTE MENU

**Comment by shadowghost79** [comment]
I have the same issue. When I define a FP on MSFS world map. It will not pushed into airplan. The fight plan in the airplan is empty. I use the package version 0.10.2.

**Comment by mattnischan** [comment]
@shadowghost79 You must use IDX -> FLPN RECALL (GAME) to load the world map flight plan into the FMC. If you don't do that, it will not be in the FMC.

**Comment by dga711** [comment]
> I was using a flightplan from the default MSFS page before entering the flight…once this is uploaded it makes the FLPN page on the FMS go blank. The details were all visible in the LEGS page though and seemed to run fine but the FLPN page remained blank for the rest of the flight
> Flight was IFR from EGTE to EGKK, flight plan was uploaded after engine start up and pushback using the the FPLN RECALL (GAME/SB) option in IDX -> PAGE2 -> ROUTE MENU

Do you get it all the time or can reproduce? I couldn't

**Comment by Guy7001** [comment]
> Do you get it all the time or can reproduce? I couldn't
 Tried this again yesterday but with different route and it seemed to all work ok.
>

**Comment by dga711** [comment]
I found the problem i guess. For arrivals the game sometimes sends a enroutetransition that doesnt exist.
Should be fix in the next update.
