### ISSUE TITLE
ILS approach drift CJ4

### ISSUE THREAD

**Issue by N38TM** [Working-Title-MSFS-Mods/fspackages#887]
Just made another flight from KAXX -> KABQ 
Approach and ILS capture fine, but shortly after starting down the glidepath the AC
drifted and started rolling left. AP dropped off.. Realigned, engaged AP, good for 1NM
then drift and roll again. Using Mod 10.0... definitely not unique to airport.

**Comment by dga711** [comment]
We think we erradicated most of these issues at least with the latest update.
Feel free to reopen when you have new information. Thank you
