### ISSUE TITLE
CJ4 - Full Rudder Trim at Cruise

### ISSUE THREAD

**Issue by trucker6808** [Working-Title-MSFS-Mods/fspackages#893]
Once at cruise plane wants to automatically put full right rudder

**Comment by mattnischan** [comment]
@trucker6808 Are you using Modern or Legacy flight model? We have only heard of this issue when using the Legacy flight model or when there is a controller problem.

**Comment by trucker6808** [comment]
I am using legacy mode no matter what I told her I use it still does it whether it be the TCA Cytec PS4 or mouse and keeping it doesn't no matter what so I will have to try modern￼

**Comment by dga711** [comment]
Feel free to reopen when you have new information. Thank you
