### ISSUE TITLE
0.10.2 - FLC issues?

### ISSUE THREAD

**Issue by CORTRacer31** [Working-Title-MSFS-Mods/fspackages#894]
Trying a flight with the newest release, and FLC mode seems to be wonky. I engaged it for my climbout but around 18,000 feet it seemed to either stop working or turn itself off. I cycled between the FLC and VS a couple of times and then it started working again, only to crap out again when I got into the Mach numbers and I couldn't get it to work again (I had to complete my climb with VS). I had VNAV enabled throughout the climb.

After this flight, I will remove the installation folder and reinstall the mod fresh to see if I can replicate the behavior.

EDIT TO ADD: While I was typing this, I switched back to the sim and found that I had blown through my altitude selector at FL400 and was still climbing on VS mode, so maybe that has something to do with it.

**Comment by jacktorrance75** [comment]
Confirmed, with 0.10.2 FLC engaged after takeoff goes in overspeed, not limits a FLC speed set

**Comment by CORTRacer31** [comment]
Followup: I'm wondering if it is connected to the TO/GA mode. If TO/GA is not manually disabled after takeoff, it might be interfering with autopilot operations thereafter.

**Comment by jacktorrance75** [comment]
Right! TOGA could be the problem, in effect I always takeoff with TO-TO engaged!

**Comment by jacktorrance75** [comment]
No, TOGA is not the trigger... look at this screenshot of few minutes ago, FLC set but no FLC SPEED BUG appears, if I click FLC it appears and disappears in millis. 
![Immagine](https://user-images.githubusercontent.com/76685343/107650363-b39caa00-6c7e-11eb-9e03-9c0538133a59.jpg)

**Comment by K20017** [comment]
What if you press FLC again, does it start working?  It might show PTCH as a vertical mode but does it capture and hold speed like FLC would?

**Comment by jacktorrance75** [comment]
No, every FLC click the speed bug appears and disappears... I've tried twenty times but nothing

**Comment by K20017** [comment]
When it appears, what does it show for a vertical mode?  FLC or PTCH?

**Comment by jacktorrance75** [comment]
FLC as you see in the img, but if I click it cycles between FLC and PTCH

**Comment by CORTRacer31** [comment]
I'm still having these issues. I can eventually get FLC to work but it takes a lot of clicking on and off. It seems as though at some predetermined point in my initial climb, VNAV will ALT CAP at around 7K/8K feet and FLC will shut off, no matter what my altitude preselector is set at.
