### ISSUE TITLE
ILS hold issue version 0.10.2 auto switch LNAV to APPR version 0.10.1

### ISSUE THREAD

**Issue by MartinoQ** [Working-Title-MSFS-Mods/fspackages#895]
Wonderful mod probably the 2nd best (flybywire is #1;) on the web, however, congratulations.

The cj4 does not hold ILS anymore (at EHBK runway 21, NAV 1 at 111.55, course 214), (used the direct button, since I was cleared direct to the approach waypoint). 
Furthermore, (I am on the modern flight model) in the previous version 0.10.1 the lnav goes automatically over to appr mode. At EGKK (Gatwick) approach to runway 26 L. This is annoying since the arrival has a lot of waypoints (not in a straight line). Hence, I was cleared for the arrival and the plane starts to capture already the ILS 26L but I needed to fly the arrival as ATC demanded, not cleared for the ILS approach but the plane could not be brought back to the arrival. No response from the NAV button AP button. After trying the NAV button, the APPR button did also not capture the ILS 26L anymore.
So auto-switching was, in this case, less fortunate. Maybe this is already addressed, I just want to help.
Anyway great plane! Fantastic job, really enjoying this mod.

**Comment by mattnischan** [comment]
> The cj4 does not hold ILS anymore (at EHBK runway 21, NAV 1 at 111.55, course 214), (used the direct button, since I was cleared direct to the approach waypoint).

We will need some more information than that, I'm not sure exactly what the scenario is here or what was happening in the plane at the time.

> Furthermore, (I am on the modern flight model) in the previous version 0.10.1 the lnav goes automatically over to appr mode.

I'm afraid I don't know what this means. Are you saying it will go to APPR LOC1 without you pressing anything? If you are pressing APPR and you are within the localizer capture area, then it is _supposed_ to go straight to APPR LOC1. You should not press APPR unless you are actually cleared for the approach.

**Comment by MartinoQ** [comment]
Correct when pressed APPR button it should capture the ILS which the CJ 4 initially does, but then when the GS needs to be captured the AP cannot capture localizer and GS anymore. in the annunciator only "NAV" is visible not GS.

**Comment by K20017** [comment]
So APPR LOC1 changes to NAV and GS stays in white?

**Comment by MartinoQ** [comment]
GS never comes up only NAV in Green is visible

**Comment by K20017** [comment]
I'll need to see a screenshot of your PFD.

**Comment by MartinoQ** [comment]
let me fly the ILS tomorrow, plz be patient:)

**Comment by EC-HTM** [comment]
> GS never comes up only NAV in Green is visible

Same here, APPR button seems to not work.

**Comment by MartinoQ** [comment]
This morning it all worked....... At EHBK ILS RWY 21 (course 212) NAV 1: 111.55 Switch to the NAV radio from FMS to VOR 1 pushed the APPR button just before entering the final approach course. It followed the ILS perfectly. 
The only thing I did different now is: in the FMS legs pages I kept the inhibit option to AUTO, previous flights where it was supposedly not working, I pushed the selection "inhibit" in the FMS. See screenshot. During the flight I used the DIR button a few times, EXEC the reroute and still it worked:). I guess I did something out of the ordinary with pushing the wrong buttons on the wrong time, sorry for the inconvenience. Anyway now you have proof when pushing the correct buttons it works:)

![Screenshot 2021-02-02 115438](https://user-images.githubusercontent.com/75068615/106592354-b47f5e80-654f-11eb-9307-16f82821151c.png)
![Screenshot 2021-02-02 115621](https://user-images.githubusercontent.com/75068615/106592360-b5b08b80-654f-11eb-8c99-b96c1c950243.png)
![Screenshot 2021-02-02 115700](https://user-images.githubusercontent.com/75068615/106592363-b6492200-654f-11eb-8996-0b3859ad9aa1.png)
![Screenshot 2021-02-02 115740](https://user-images.githubusercontent.com/75068615/106592368-b812e580-654f-11eb-8ca7-6116974b5890.png)
![Screenshot 2021-02-02 115905](https://user-images.githubusercontent.com/75068615/106592372-b9441280-654f-11eb-8a98-490769ff951a.png)

**Comment by jacktorrance75** [comment]
same happened to me, last night there was no way to make it follow the loc. For testing I created a LIRA-LIRF FPLN, without STAR e APPR, set the LOC frequency, switch from GPS to LOC,
No response from the APPR button, it did also not capture the ILS 16L anymore. In the annunciator only "NAV" is visible not GS neither APPR LOC1.
I'll try again to add informations.

**Comment by SCORCHEDIMACX** [comment]
One Day i deleted the approach because i got cleared for vectors to the ILS and then my plane didn't catch the ILS. I thought it has to have a Nav Route to the Runway available to tune the ILS in and i did that for the future flights and everything worked just fine.

**Comment by EC-HTM** [comment]
> same happened to me, last night there was no way to make it follow the loc. For testing I created a LIRA-LIRF FPLN, without STAR and APPR, set the LOC frequency, switch from GPS to LOC,
> At the beginning it was intercepting the course inbound, but when it was over the course it overshooted without capturing it. No response from the APPR button, it did also not capture the ILS 16L anymore. In the annunciator only "NAV" is visible not GS neither APPR LOC1.
> I'll try again to add informations.

It seems that ILS need to be flown with the ILS approach previously charged in the FMS. Then, when in final course, APPR button works and captures GS. They will implement independence between ILS and FMS in the future, at least that is what I understood.

**Comment by jacktorrance75** [comment]
> It seems that ILS need to be flown with the ILS approach previously charged in the FMS. Then, when in final course, APPR >button works and captures GS. They will implement independence between ILS and FMS in the future, at least that is what I >understood.

Ok, actually I didn't load an approach for LIRF 16L because there isn't in MSFS2020 (Asobo bug).
I'll try with an ILS APPROACH loaded in FMS.
Thank you mate !

**Comment by jacktorrance75** [comment]
I've tried without approach procedure loaded at LIRF RWY16L, tuned 108.1, tried to intercept ILS but nothing, ILS beam it's not intercepted. I'll try with an approch procedure loaded later

**Comment by dga711** [comment]
Right now the plane doesn't let you go into APPR without any approach loaded. Which ofc is a bug.

**Comment by jacktorrance75** [comment]
@dga711 
Ok, I hope delevopers team is informed about this bug.
Thank you veru much

**Comment by dga711** [comment]
Will be fixed in the next update. Thank you
