### ISSUE TITLE
Throttle Locked Down (Both visual and functional) after first flight

### ISSUE THREAD

**Issue by ch4pz** [Working-Title-MSFS-Mods/fspackages#896]
I'm not sure this is exclusive to the mod, it may be a sim issue as I'm getting a similar Problem with the FBW A32XN Fly-By-Wire Dev version too (doesn't happen on standard Dev version though). So on initial install mod works as it should for the first flight, but after (or maybe on first load) it installs a folder in my "Packages" folder (so the folder you find would find "community" and "official") named working title cj4, now once that has happened, the next flight, my throttle will be locked shut, no lever, and no acceleration. if i hold the 90% throttle key-bind it will half throttle up, but as soon as i release the key it very quickly powers down, basically unusable. removing the mod (stock) works OK. Ive tried versions 9.1, 10, 10.1 and 10.2, i also reinstalled the game to no avail. tried using different g3000 mods, and also none at all, still no luck. All testing was done with default livery also.

**Comment by dga711** [comment]
Didn't see that yet, the way you described it. Usually there are two causes for it 
1) Using a livery that overrides panel.cfg
2) Check your "MyDocuments" folder if there is a stray simconnect.cfg and delete that (there are external applications that create this file which breaks internal simconnect things)

**Comment by ch4pz** [comment]
Did just find a simconnect.cfg in my docs, so may have been this, as i was using default liv. Will test an leave results, cheers

**Comment by dga711** [comment]
Can you tell which external simconnect apps you used in the past?
Kinetic Assistant? Any other?

**Comment by ch4pz** [comment]
Ive never really heard of it, i did try kinetic assistant once, possibly round this time, ima delete it now. is luke air tool, or pushback helper one of these apps do you know?

**Comment by ch4pz** [comment]
Just ran a test flight then, and it all works, so i think it was that simconnect.cfg file (cuz of kinetic assistant).. thank you so much, this mod is incredible!!
