### ISSUE TITLE
APPR button makes no change in AP annunciator

### ISSUE THREAD

**Issue by EC-HTM** [Working-Title-MSFS-Mods/fspackages#897]
For some reason it seems to be not working. Default CJ4 approach mode can be engaged and can fly ILS following glideslope, but WT CJ4 APPR button, in my system, produces nothing, almost like an inop button but with the click sound. No flightplant, no FMS, only tunning ILS freq. and clicking APPR in all the times I can think of. The rest of the AP works. I love to fly this plane with all the superb improvements you hade made to it, is such a pitty that this important feature does not work for me. All liveries removed, just in case. Can you help me with this issue? Thank you in advance.

Hugo

**Comment by mattnischan** [comment]
@EC-HTM Does ILS work if you have an ILS approach loaded in the FMS?

**Comment by EC-HTM** [comment]
Affirmative, just engaged and flying LEVC ILS 30 approach. I am surprised that approach must be loaded first in FMS, would have never guess this alone. Though they where independent. Thank you for solving my issue so quickly.

**Comment by dga711** [comment]
The plane would support manual mode too. But that is missing in our implementation. It will come for sure.
