### ISSUE TITLE
Low FPS on the new Mod with the TBM 930

### ISSUE THREAD

**Issue by flodwo** [Working-Title-MSFS-Mods/fspackages#900]
Hello!

In this new and actual G3000 Mod, I loose significantly my FPS after about 1 hour of flight time!
In the last mod, i didn't have this problem. I have about 50 FPS and after a while it drops to 33 FPS.

Thats not a normal behaviour. In the external view, I get about 65 FPS. (RTX3090, 64GB RAM, I 9 10900 OC)

Please help

**Comment by flodwo** [comment]
<img width="1920" alt="Microsoft Flight Simulator Screenshot 2021 02 03 - 13 38 56 94" src="https://user-images.githubusercontent.com/78483250/106748607-c6333580-6625-11eb-8568-5dba4fd9697f.png">

**Comment by flodwo** [comment]
<img width="1333" alt="Microsoft Flight Simulator Screenshot 2021 02 03 - 16 27 58 57" src="https://user-images.githubusercontent.com/78483250/106769483-50d35f00-663d-11eb-8165-530eb01c9484.png">

and here with the older version !!! Better FPS

**Comment by cywang90** [comment]
Fixed with 0.4.1
