### ISSUE TITLE
CJ4 Not Capturing Last Height Constraint In SID

### ISSUE THREAD

**Issue by GAJ52** [Working-Title-MSFS-Mods/fspackages#904]
Route from Simbrief  EGKK/26L LAM5P LAM L10 BPK UN601 LESTA UY250 GASKO P18 NATEB DCT
EGNT/07.  LAM5P should be LAM6M (problem with simbrief this morning).

With updates 0.10.0, 0.10.1 and 0.10.2 when using VNav and FLC to climb the last waypoint in the SID, in this case LAM  although having a height constraint of 6000 is ignored and the aircraft climbs to the 'Selected' altitude, all other height constraints in the SID are captured normally.  I have tried this several times with the same result.

Also for some reason when adding the departure runway and SID 'LAM' is entered twice as if the FMS is not recognising both waypoints 'LAM' are the same waypoint, so I have to delete one of them leaving the 6000 height constraint - again happens every time. 

![LAM2](https://user-images.githubusercontent.com/78220071/106893318-4a98bd80-66e5-11eb-9ffa-b582a8a8cbfc.JPG)

**Comment by dga711** [comment]
Afaik VNAV on climb will only care about BELOW constraints not AT or ABOVE.

**Comment by GAJ52** [comment]
I have just read an answer in the Avsim forum regarding the CJ4 VNav climb capability by cwburnett one of the WT team, he says :-

 

“VNAV in climb is fairly limited; unlike some airliners, the PL21 does not calculate or follow a climb path. The only capability for climb is to stop the climb for AT or AT/BELOW constraints. Above constraints are ignored by VNAV on a climb.”

 

“All that said, it should work as described and I've tested it pretty extensively, as have our QA testers, so if you're finding it is not halting your climb for AT/BELOW constraints in the departure procedure, please submit a bug report because that's incorrect.

Just to double check - please confirm you're on v0.10.2.”

The LAM waypoint is part of the LAM6M SID and has a AT 6000 constraint which the VNav is ignoring, so I still think this is a bug that needs looking at.

Just to confirm I am using v0.10.2

Regards

Glen Coyne

**Comment by cwburnett** [comment]
I have tested this in 0.11.2 and it is now working as expected.
![image](https://user-images.githubusercontent.com/70416619/111075541-1667a800-84ae-11eb-9704-b2581dc15f07.png)
![image](https://user-images.githubusercontent.com/70416619/111075548-254e5a80-84ae-11eb-9ae8-6042ee1ca85e.png)

**Comment by GAJ52** [comment]
Yes now fixed for me as well, many thanks great work.

 

Glen
