### ISSUE TITLE
Visual approach waypoint put on wrong side of runway

### ISSUE THREAD

**Issue by okurz** [Working-Title-MSFS-Mods/fspackages#905]
## Observation

Selecting runway 01R or 01L of KBXM with the visual approach waypoint with default 5.0NM distance puts the waypoint at the wrong side of the runway, roughly the same position as for the opposite direction runway 19, see screenshot

![fs2020_cj4_0 10 2_RX01_on_wrong_side](https://user-images.githubusercontent.com/1693432/106906703-bb4bd400-66fd-11eb-8aca-f33ed1ccd999.png)

As can be seen by the compass rose within the screenshot the runway should face roughly the 1h clock position on the compass rose hence RX01 should be on the 07h position but is positioned in the 1h position.

## Reproducible
So far only observed on this airport but both runways, not yet reproduced over simulator restart nor confirmed by other users.

## Expected result
The visual approach waypoint should have been placed in the approach path of the runway 01, i.e. 190 degrees from it, in the 07h position as visible in PPOS view when approach from south.

**Comment by cwburnett** [comment]
This was fixed some time back. Closing.
