### ISSUE TITLE
CJ4 VNAV not meeting crossing restrictions on descent with 0.10.2

### ISSUE THREAD

**Issue by Dumbledeedore** [Working-Title-MSFS-Mods/fspackages#909]
Reproducible on the JFUND2 arrival for runway 33L into KBOS.  Start at 17,000 feet at the WHATE transition.  TOD is calculated to begin after JFUND even though the magenta circle on the altimeter indicates you should be descending.  

After reaching TOD, CJ4 doesn't descend fast enough to meet the crossing restriction at AUTUM where you should be above 11,000 and below 12,000.  Instead it crosses AUTUM at 15,000.

Likewise with the next waypoint, WINTA.  You should be crossing between 8,000 and 10,000 but the CJ4 crosses WINTA at 12,000.

When reaching SPYSD, the CJ4 correctly crosses at 7,000.
It also correctly crosses SCITU at 5,000

![image](https://user-images.githubusercontent.com/78559098/106936655-d8c37280-66ea-11eb-8a26-d601f5afcd45.png)

**Comment by DanP77** [comment]
Confirm same behaviour in RNAV STAR in LIMC

**Comment by N754DW** [comment]
Saw same behavior today (tried it twice) on BELLR THREE into KHOU. At BELLR (11000A/13000B), VNAV crossed at about 17,000. At next constraint (HNTRR 8000A/10000B), crossed between 11 and 12. (see screenshot)

[00198BELLR.PDF](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5954757/00198BELLR.PDF)

![BELLR THREE Screenshot 2_9_2021 4_36_09 PM](https://user-images.githubusercontent.com/72550869/107439726-1fa0d600-6af8-11eb-8749-cf51be57491c.png)

**Comment by ourduck** [comment]
I've done the JFUND2 arrival multiple times and can confirm this behavior.  If I recall correctly if you change the altitude at MNSTA to /24000 watch the angle of descent recalc for each point after that.  It appears that the 3 degree slope is given primary status over the crossing restrictions but in the code when it seems like it's skips the check on the intermediate restrictions.  It acts like MNSTA /24000A  Rway22l /16 and then does a straight 3 degree calc.  I doubt that is what's really happening as that's oversimplified, but in the intermediate checks there's a priority flaw.  For passing the tests, on all STARs I've been inputting speed / altitude as shown on the chart.  It help to have the speeds visible on the LEGS page and I'm not having to keep going back and forth to the chart.  It just sucks when they change the runway and you have to re-input all the restrictions.

**Comment by ourduck** [comment]
Ok...I just went and flew KSYR -> KBOS JFUND2.PONCT 22L twice and have documented it below.

Machine is i7-10700 overclocked at 4.7 with 32 GB ram, 2070 Hybrid, 2TB M2 SSD. 
MSFS settings are Modern and ULTRA with TAA set at 100
I'm flying workingtitle-cj4-v0.10.4 and have the following mods

![image](https://user-images.githubusercontent.com/80160370/110219890-f32a7080-7e8f-11eb-83fb-f60bd20c7125.png)


I started cold and dark and hand typed the FPL in.  This is how the LEGS screen appeared after the programming.

![image](https://user-images.githubusercontent.com/80160370/110218813-ad6aa980-7e89-11eb-89b3-847e29c056af.png)

If I put /FL240 in the MNSTA, this is how the LEGS screen looked, notice the descent angles now appear.

![image](https://user-images.githubusercontent.com/80160370/110218860-fd497080-7e89-11eb-8341-63372ace6b9a.png)

I then quit MSFS, restarted, and again hand loaded the FPL and left it as it loaded per the first picture above.

I have now climbed to FL350, have passed the TOD point, the VPATH is showing on the vertical tape but is neither shown in the scorecard nor is there a magenta altitude top right but yet the VPATH is descending.
![image](https://user-images.githubusercontent.com/80160370/110218991-9aa4a480-7e8a-11eb-94ff-14fdd3d40969.png)

Here now, VPATH has captured and there are magenta indicators on both the Altitude tape and the VSpeed tape but still no magenta VNAV altitude. I have manually input a lower altitude to start the descent.

![image](https://user-images.githubusercontent.com/80160370/110219052-f7a05a80-7e8a-11eb-8f89-3fafa427386f.png)

Here, 3 miles later, the magenta VNAV altitude appears top right.

![image](https://user-images.githubusercontent.com/80160370/110219113-3cc48c80-7e8b-11eb-832a-8289ee29e323.png)

As I approach MNSTA I have reset the Altitude to match the magenta VNAV altitude and I would continue to move the altitude as instructed by the magenta VNAV value.

![image](https://user-images.githubusercontent.com/80160370/110219175-ab094f00-7e8b-11eb-8da0-559d5eb79751.png)

Notice as I approach SEETS, I'm 2 miles short, 100 feet high but the VPATH guide shows that I should still be descending and am notably off the path.

![image](https://user-images.githubusercontent.com/80160370/110219222-ee63bd80-7e8b-11eb-8038-081d6f4bcced.png)

Just past DUBLE, the AP scorecard went to VALTS CAP, the VPATH kept descending.  I was a bit slow to move the AP Altitude so it had to drop hard to recapture the path which it did.

![image](https://user-images.githubusercontent.com/80160370/110219332-85307a00-7e8c-11eb-8471-039df0e41dee.png)

At WINTA it nailed the restriction and I stayed on path

![image](https://user-images.githubusercontent.com/80160370/110219389-d93b5e80-7e8c-11eb-896e-a54f6475bc89.png)

At ISLAY, I was a bit high, 120' over but got an odd indication on the VPATH tape.  There's a discontinuity showing on the legs page as it had VECT after the next waypoint as shown on the top of the screen.  The magenta VPATH says I should be climbing.

![image](https://user-images.githubusercontent.com/80160370/110219478-75656580-7e8d-11eb-9603-4552716687e4.png)

I then landed the ILS 22L, quit MSFS, restarted, reloaded MSFS, spawned cold and dark at KSYR, reloaded the flight plan by hand and flew it again. Just past PONCT I passed TOD and dialed in 3000 into the AP Altitude selector and let the VNAV take it from there.
![image](https://user-images.githubusercontent.com/80160370/110219590-413e7480-7e8e-11eb-9754-524bec37df30.png)

Here, 1 NM from MNSTA, already below FL240 as shown on the LEGS panel.

![image](https://user-images.githubusercontent.com/80160370/110219640-7ea30200-7e8e-11eb-9d59-fedf7478209e.png)

Here at 1.2 NM from SEETS, below FL210 as shown on the LEGS panel and still on VPATH as shown on the vertical guide.

![image](https://user-images.githubusercontent.com/80160370/110219680-be69e980-7e8e-11eb-90df-bddacc604bba.png)

At DUBLE, we're right on path...notably the first non Flight Level altitude.

![image](https://user-images.githubusercontent.com/80160370/110219730-f2dda580-7e8e-11eb-8fb4-77af18fe9f50.png)

At AUTUM we're again slightly high of the restriction but not by much but I'd much rather be at 11,500

![image](https://user-images.githubusercontent.com/80160370/110219777-333d2380-7e8f-11eb-81db-b191e9aa38c1.png)

At WINTA we're in the zone.

![image](https://user-images.githubusercontent.com/80160370/110219817-6b446680-7e8f-11eb-9165-e5b5917450fe.png)

I went to HDG mode at ISLEY and self vectored to the ILS 22L


If I can do further testing please let me know.  This is an awesome package and I'd love to help.

**Comment by cwburnett** [comment]
Thanks all for the reports, I was able to track this down and have tested a fix that appears to solve this issue. Will be in the next update.
