### ISSUE TITLE
CJ4 v0.10.2  Rudder starts to trim automatically and stays in position

### ISSUE THREAD

**Issue by capsos88** [Working-Title-MSFS-Mods/fspackages#910]
the rudder starts to trim to the right position slowly until full right when autopilot ( LNV1 / AP / ALTS ) (YD is active) is engaged. 
So, when i disengage and engage the autopilot, it resets a bit to center, but starts again to go right.
Trim is set to 0.0.   
![Microsoft Flight Simulator Screenshot 2021 02 04 - 19 21 17 72](https://user-images.githubusercontent.com/78560877/106939610-c532fe80-6720-11eb-9026-cf4c071a2c2d.png)
![Microsoft Flight Simulator Screenshot 2021 02 04 - 19 20 58 20](https://user-images.githubusercontent.com/78560877/106939625-c8c68580-6720-11eb-9d15-23c61f97fde1.png)

**Comment by capsos88** [comment]
![Uploading Microsoft Flight Simulator Screenshot 2021.02.04 - 19.40.24.25.png…]()

**Comment by K20017** [comment]
Are you using rudder pedals or some sort of rudder axis?  If so, try increase your deadzone because any small input will cause the AP to trim it completely out.  I had the same problem with my pitch trim and the problem was a noisy axis.

**Comment by capsos88** [comment]
no pedals.
i increase deadzone by 12 percent, no change.. im inflight at the moment

**Comment by K20017** [comment]
Are you also on the legacy flight model?

**Comment by capsos88** [comment]
how can i find it out ?  :D   i have the standard MSFS2020 version ...

**Comment by K20017** [comment]
Go into settings -> Flight Model

**Comment by capsos88** [comment]
ah.. yes, legacy... all 100percent, except crash realism.. cause of "your controls" mod

**Comment by K20017** [comment]
Were you on legacy instead of modern?

**Comment by capsos88** [comment]
switched to modern.. rudder is less trimmed, but ACRFT is bumpy as hell

**Comment by capsos88** [comment]
i figured out, that this isnt happening at lower altitudes.. maybe a hard weather impact ?

**Comment by dobemason** [comment]
my experience is very similar. on autopilot plane tend to bank either left or right and fly like that the entire course

**Comment by mattnischan** [comment]
There are only two causes of this: flying in the Legacy flight model, or having inadequate deadzone set in the control sensitivity.

Please ensure you have the Modern flight model selected and that you have enough deadzone set such that there is no control output when the AP is on and the yoke and rudders are not being used.

**Comment by dobemason** [comment]
Matt you were spot on. Yes I was flying Legacy. Once changed fixed everything. Much appreciated
