### ISSUE TITLE
unable to disable flight director with AP Off - CJ4

### ISSUE THREAD

**Issue by darkshine2311** [Working-Title-MSFS-Mods/fspackages#911]
Hello,

It was submitted in the chat, but I wasn't able to disable the Flight director with AP off, because of vertical or lateral navigation mode previously enabled.

A bit annoying when switch from IFR to VFR approach.

Have a great day !!

**Comment by WakeTechInc** [comment]
@darkshine2311, I've been trying to reproduce this behavior but have not been successful so far. You said "vertical or lateral navigation mode previously enabled". Is it either or must it be both? Was VNAV enabled during cruise or were you switching from an IFR to VFR approach while already established on a localizer?

**Comment by cwburnett** [comment]
As long as the modes annunciated in the FMA are ROLL and PTCH, FD can be deactivated. If another mode is annunciated in the FMA, disable that mode, then you can turn off the FD.
