### ISSUE TITLE
g3000 0.4.0 barber pole issue with Longitude mod

### ISSUE THREAD

**Issue by fnne99** [Working-Title-MSFS-Mods/fspackages#919]
Several people have noticed that there seems to be an issue when using the Longitude mod with the WT g3000 mod where the barber pole shows extremely low.  The max mach number on the plane is .84 (verified that the audible overspeed works fine at .85) but with the g3000 mod, its sits around .75.  I've removed the g3000 mod and the issue goes away. Ive also tried this with and without live weather and get the same results, with the mod its incorrect, and without the mod its correct.

**Comment by cywang90** [comment]
Fixed with v0.5.0.
