### ISSUE TITLE
G1000's PFD MFD freezes when opening FPL v0.3.4

### ISSUE THREAD

**Issue by iraqiboy90** [Working-Title-MSFS-Mods/fspackages#923]
Happens every time suddenly midflight. Reverted to 3.2 and had no freezes so far.
G1000's PFD MFD freezes when opening FPL on MFD midflight v0.3.4. The PFD opens up and shows the list but the map is black and at this point everything is frozen.

**Comment by patrickkonsor** [comment]
I believe this is may be related to flight plans that include VORs. I've observed the same behavior when adding a VOR to an existing flight plan that didn't originally include any VORs.

**Comment by hugo-cardoso** [comment]
I have the same problem using C208B.

**Comment by groakley** [comment]
Possibly related to #832, if you are only seeing this with flightplans that include VORs.

**Comment by fishgoblue** [comment]
I have been having this issue since the last update.  I can put in a flight plan but it freezes if I try to do a direct to or add a procedure or anything that changes the GPS.  I makes it unusable and super dis appointing.

**Comment by kaosfere** [comment]
@iraqiboy90 @hugo-cardoso

Can you provide an example .pln file that locks up on you, and precise instructions on how to cause the lock up, even if it's just "in flight, with the MFD showing the main map, hit FPL"?  Also, if you would, confirm whether or not you have Navigraph data installed and, if so, which version.

@fishgoblue 

It sounds like you might have a separate issue, but if you have something that is 100% reproducable -- or, at least, close -- let me have the details of what you're doing and I'll see if I can get a repro.

**Comment by flying7eleven** [comment]
I finally could find a flight where it happes more often - interestingly not always. Last time it happened to me with a full flight (I did it twice to ensure its reproducable) from EDDF to EDDV. I used the shortest low-level IFR route. As soon as the ingame ATC assigned me the approach, I selected it using the MFT and the PROC button. Right after activating the approach, the MFD froze. The secondary display still worked fine. At least it updated the plane position of the map. The approach path was missing though. Right after switching to weather mode and back to the map the right display froze as well. The approach where it happened twice was the ILS Y 27R approach with the SAS (which is a VOR) transision. I tried a shorter flight where I started in the air in the vicinity of the airport but there I was unable to reproduce it. If I find out more, I let you know!

**Comment by paweld303** [comment]
Hi,
I have a reproducible situation, or at least I think so. I have issue with baron, with G1000 WT v0.3.4, whole sim freezes and requires to kill it totally.
I tried a few times the same situation, and I get this every time.
The situation:
Flight from WIII to WAHI, simple plan (no SID/STAR procedures needed to reproduce): PW(ndb) - BND (vor) - CLP (vor).
I just insert plan manually. So first I input WIII, then I input PW (first ndb in G1000 list), then BND (second on the list, 06°52'55.5"S  107°30'44.4"E), then I try to input CLP - after choosing C, it crashes when I try to enter second letter.

Then I loaded plan from file (attached pln file) - it loaded ok. Then I tried to modify the plan, I tried to insert new point before existing CLP. So, scrolled down to CLP, then with smaller knob I started to instert C, then second letter - and freeze again.
[WIII_WAHI_crashing.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/6129761/WIII_WAHI_crashing.zip)

**Comment by beaufortuk** [comment]
Hi,

I'm experiencing the G1000 lockup. The trigger is selecting the FPL button. When it is selected on either screen that same screen will lockup.

**I only seem to experience this when I generate a VOR flight plan** in the MSFS world map. 

Attached is the most recent flight plan for which the G1000 has left me "rudderless".

Workaround = Don't use the VOR flight plan generator / Don't click FPL?

FLT attached... [G100 FREEZES.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/6137386/G100.FREEZES.zip)

**Comment by mikeB2210** [comment]
Got the same problem on my last flights with the C172. Here are two reproducible examples:
1. Open FLP on MDF input EDDL - LMA (NDB) - DOMEG (VOR) -> from here it depends.
2. Flight from EDDL to EDLN. Scheduled via LMA -> No Problem. If I try to add NOR (VOR) during the flight, no further input is possible.
