### ISSUE TITLE
CJ4: Over speed moving between 260 and 300+ several times during short flight

### ISSUE THREAD

**Issue by midohioboarder1** [Working-Title-MSFS-Mods/fspackages#928]
Running latest version of CJ4.  Not using navigraph.  Flight from KLUK to KCVG.  
link to video.  @39 sec in over speed goes up from 260.  @1:10 it comes back down.

https://drive.google.com/file/d/1P0j6MgdpWzy_eXbuUQ1x3SN6paKBpKM4/view?usp=drive_web

I made several changes to flight plan. Deleting waypoints and such before takeoff.   Flying live weather. 
Am I not setting something up right?

**Comment by mattnischan** [comment]
@midohioboarder1 You're exactly at the altitude where VMo changes from 260 to 305 KIAS, which is 8000 ft.

**Comment by slip664** [comment]
![image](https://user-images.githubusercontent.com/72432870/107889879-5137e980-6eca-11eb-8dd8-16a2c654e1bf.png)

In many countries, you're not suppose to exceed 250 KIAS below 10,000 anyway.

**Comment by midohioboarder1** [comment]
Thanks guys for the education.  I guess I had always been climbing through 8k before and didn't notice it.  Thanks for letting me know!
