### ISSUE TITLE
CJ4 Engine 2 "RUN" button will not stay engaged.

### ISSUE THREAD

**Issue by Signmanbob** [Working-Title-MSFS-Mods/fspackages#929]
CJ4 Engine 2 "RUN" button will not stay engaged.
I cannot start the engines from cold and dark and if it loads with the engines started, the "RUN" button will disengage and shut down the engine.
I am using the latest version (0.10) of the CJ4 Working Title.

Never mind.  I have the new Honeycomb Throttle Quadrant and it had already mapped the mixture levers from within MSFS.  I just had to delete the mapping.

Thank you,
Bob

**Comment by K20017** [comment]
Check your hardware bindings for an axis getting assigned "mixture"  and delete it.
