### ISSUE TITLE
TUN Page Frequency Input Range

### ISSUE THREAD

**Issue by cwburnett** [Working-Title-MSFS-Mods/fspackages#93]
Looks like a possible problem with the input filter on COM frequencies

From BackboneOne on Avsim

"today on vatsim i was unable to tune 133.22 munich radar fms was saying invalid entry"

**Comment by mattnischan** [comment]
133.22 is not a valid 8.33khz channel. The correct channel would be 133.225. 8.33 spacing is really strange.
