### ISSUE TITLE
WT cj4 completely gone in version 1.13.16.0:(

### ISSUE THREAD

**Issue by MartinoQ** [Working-Title-MSFS-Mods/fspackages#930]
it seems that wt cj4 10.2 does not work in the latest version 1.13.16.0

**Comment by mattnischan** [comment]
@MartinoQ We have multiple users using the mod just fine. Have you restarted the sim after the update?

**Comment by MartinoQ** [comment]
I have just restarted and now he is there, thank god, sorry for the inconvenience! I love this mod.

**Comment by mattnischan** [comment]
Glad to hear it! Thanks for the kind words!
