### ISSUE TITLE
how to reset 'persistent settings'

### ISSUE THREAD

**Issue by Hyldig** [Working-Title-MSFS-Mods/fspackages#934]
Was messing around with PFD, and now i'm unable to return the reference settings to standard values - can't turn to values lower than 20.
These settings are saved persistently, how can i reset?

**Comment by flymypi** [comment]
Hi,
What exactly do you mean by reference settings?
V-Speeds? Minimums?

**Comment by Hyldig** [comment]
Value for Glide, Vr, Vx, Vy under TMR/REF.
![Capture](https://user-images.githubusercontent.com/551611/108575004-307ff180-7319-11eb-830d-2db25ce622f9.PNG)

**Comment by flymypi** [comment]
Oh, I'm sorry, I assumed this was about the CJ4.
