### ISSUE TITLE
g3000-v0.4.0 hangs TBM since world update 3

### ISSUE THREAD

**Issue by BuraiUK1** [Working-Title-MSFS-Mods/fspackages#935]
Since world update 3 the sim hangs within a few seconds of turning the battery on in the TBM. I uninstalled all mods and it starts up fine, then installing only g3000-v0.4.0 and it hangs again.

**Comment by Jason8074** [comment]
same problem and CJ4 Avionics wont turn on

**Comment by cywang90** [comment]
There shouldn't be any issues with world update 3 and the g3000 mod. If you are still using 0.4.0, update to 0.4.1 and see if the issue persists.

**Comment by BuraiUK1** [comment]
Yes, 0.4.1 fixes it - thanks.

Fantastic job on the mods btw, and the new road data looks great as well.

Keep up the great work.
