### ISSUE TITLE
[CJ4 v0.10.2] Flap Lift Bug in MSFS 1.13.16.0

### ISSUE THREAD

**Issue by sfdeham** [Working-Title-MSFS-Mods/fspackages#938]
The new MSFS release introduced a bug regarding exaggerated flap lift, see https://forums.flightsimulator.com/t/flight-dynamics-bug-details/368499.

Does this issue pertain the mod? Should mentioned workaround be applied to the mods flight_model.cfg?

**Comment by capsos88** [comment]
lift_coef_flaps = 0.50180

this is my line ( Moded cj4 ) ...

**Comment by thor** [comment]
This is solved in v0.10.3.

**Comment by kmoze2001** [comment]
> This is solved in v0.10.3.

No, it's not.  It needs to be changed to 0.2509 which has not been done.  I'll open a separate issue.

**Comment by mattnischan** [comment]
This is solved, yes. `lift_coef_flaps` is not the only place where this doubled flaps lift can be addressed, and it was addressed in the flaps table itself instead.
