### ISSUE TITLE
CJ4: COM frequencies in TUN page cannot be updated

### ISSUE THREAD

**Issue by theclumsygeek** [Working-Title-MSFS-Mods/fspackages#94]
Trying to change COM frequencies in the TUN page results in invalid entry. Changing frequencies via the built-in ATC window or 3rd party apps (e.g. Pilot2ATC) works, and the COM frequencies reflect in the PFD, but the COM frequencies in the TUN page are static and do not update.

**Comment by K20017** [comment]
This is fixed in our current experimental build.
