### ISSUE TITLE
g3000-v0.4.1not following depicted approach path

### ISSUE THREAD

**Issue by jfwharton3975** [Working-Title-MSFS-Mods/fspackages#941]
I had the same issue with version 0.4.0 and now with 0.4.1.  As can be seen in the attached screenshot 
![KPUB ILS 08 Aczes Transition](https://user-images.githubusercontent.com/77125311/108643418-c6299700-7467-11eb-9b14-2070c8448ae9.jpg) the aircraft is not following the depicted path from DRAKE to ACZES yet the course deflection is indicating on course.  While flying the flight plan from KDEN to KPUB the aircraft did fly the depicted flight plan path (KDEN, FQF, LUFSE, ADANE, DRAKE)  but deviated when starting the approach.  Version 0.3.4 did not have this issue.

**Comment by cywang90** [comment]
This is a known issue. The flight plan renderer currently doesn't render course reversals correctly.

**Comment by jfwharton3975** [comment]
Thank you but if I go back to a previous version 0.3.4 the issue goes away.  So I'm a little confused that a previous version does not have the issue.

**Comment by cywang90** [comment]
0.4.0 introduced a new flight plan renderer, which is why the issue wasn't present on previous versions.

**Comment by jfwharton3975** [comment]
Well I went back to version 0.3.4 because versions 0.4.0 and 0.4.1 do not work.  Just tried flying an approach at FACT and the aircraft wasn't even heading anywhere close to the initial fix.  Had to abort the flight, remove 0.4.1 and install 0.3.4.

**Comment by jfwharton3975** [comment]
OK after going back to 0.3.4 I could see where version 0.4.0 and 0.4.1 were flying the flight path depicted in 0.3.4 but just not showing that flight path.  So just so I know where the aircraft is going to fly I am staying in version 0.3.4 until there is a fix in the 0.4.X series.

**Comment by jfwharton3975** [comment]
I downloaded and installed version 0.4.2 today and see the same issue remains.  I flew the ILS R26L at KPUB, ZUTIG transition which does an arc, yet the depicted path is a straight line.  So again I've gone back to version 0.3.4.  Hopefully this issue will be resolved at some point.

**Comment by cywang90** [comment]
Fixed with v0.5.0.
