### ISSUE TITLE
Localizer course needle swings to 180° off course after Nav-to-Nav transfer

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#946]
Version 0.10.3

Flew it twice, with a sim restart between flights.

ILS 22L at KBOS. While in "ghost" mode, the course needle is correctly pointing at the localizer inbound course of 215°. Upon Nav-to-Nav Transfer, the localizer course needle swings around, with the head pointing to the reciprocal course of 035°. Left-Right sensing of the CDI remained correct, however. 

Update: Flew it a third time so I could add screenshots. This time, instead of changing to the reciprocal, it changed to 000 degrees.
![Screen Shot 02-24-21 at 07 55 AM](https://user-images.githubusercontent.com/72550869/109012172-538f0600-7677-11eb-84fe-abebb7aa0962.PNG)
![Screen Shot 02-24-21 at 07 57 AM](https://user-images.githubusercontent.com/72550869/109012199-5984e700-7677-11eb-807b-9afd33a665a4.PNG)

**Comment by Graeme1873** [comment]
Ii can confirm i have this exact same issue with 1.10.3.  Tested at EGPF, EGHI.  Just seems like the ILS auto tune isn't populating the CRS on the PFD.

**Comment by K20017** [comment]
It's been fixed internally, for now you can spin the course knob until it's aligned.
