### ISSUE TITLE
g3000 0.4.1 VFR map overlay art/text scaling

### ISSUE THREAD

**Issue by marchamilton** [Working-Title-MSFS-Mods/fspackages#948]
Once this mod is added its makes everything on the VFR map huge, text icons route line etc[
![2021-02-24_11-24-19](https://user-images.githubusercontent.com/11247253/108985814-256eed80-769a-11eb-96e4-fdae04541044.png)
](url)

**Comment by cywang90** [comment]
This is intended behavior. The mod makes it so that the VFR map displays vector elements at a constant size no matter what the size of the window is, so that making the map smaller does not result in tiny font, and making it bigger does not result in needlessly large font.

**Comment by cywang90** [comment]
v0.6.0 now lets you revert back to the default VFR Map with a mod config file setting if you so choose.
