### ISSUE TITLE
LOC Green Needle is Offset To the Left for ILS Approach 

### ISSUE THREAD

**Issue by Kamaniya9** [Working-Title-MSFS-Mods/fspackages#949]
Hello WT developers,

Thank you very much for the latest update. I would like to report this issue.

Issue: LOC green needle is offset to the left when activated with APPR. 
First flight using 0.10.3 and has never happened before. However the GS and LOC are captured and flown perfectly by the AP system. Only the LOC indicator shows an off set to flight path,

Airport : LTFJ (Asobo stock)
Runway : 06
Approach: ILS Auto correctly tuned by FMS to 109.9 
STAR : GINL1T APPROACH : ILS Y RWY 06
Flight Plan : Generated by LNM (latest version) LSZH - LTFJ
Others : 
Clean installation. 
Using WT Supported livery (Ghost livery by Windhover)
Latest Navigraph AIRAC.
No other airport or aircraft were active in Community Folder.

![B6E954FD-83D2-4A0C-9820-0DF15FC75542](https://user-images.githubusercontent.com/71068983/108986476-1f463480-76cd-11eb-812a-24d0ebb8c42b.jpeg)
![5B2E4CF2-2F90-4BD7-86A3-C04616DE203B](https://user-images.githubusercontent.com/71068983/108986507-28cf9c80-76cd-11eb-9365-754ce6d79777.jpeg)
![E283B588-3508-483C-B422-520A366AA883](https://user-images.githubusercontent.com/71068983/108986534-31c06e00-76cd-11eb-847a-a5768e657401.jpeg)

**Comment by QuasarCore** [comment]
Hi,

I've noticed the same. The needle is pointing to the north on the display, the plane is following the correct guidance though.

**Comment by darkpq** [comment]
Same.

Flew into KLAS, localizer tuned correctly, landing/GS performance nominal, but CDI arrow stayed pointed at a straight north course but still indicated the expected slight crosstracking as the AP performed the approach.

**Comment by K20017** [comment]
Known bug, already fixed internally.  In the mean time, you can just spin the course knob to the desired course to fix it.
