### ISSUE TITLE
CJ4: Fuel Flow

### ISSUE THREAD

**Issue by crowmium** [Working-Title-MSFS-Mods/fspackages#95]
Fuel flows seem to be excessive. The jet is capable of approximately 410-420 KTAS for about 5 hours at around 160 gal/hr (total, not per engine). This means total fuel flow from each engine should be approximately 500-600 lbs/hr at cruise altitudes and power settings. Currently we are close to 1000 lbs/hr to achieve book numbers in cruise.

Contributing is a problem where the fuel flows actually seem to rise as the jet climbs in altitude. It seems that the fuel flow is tied to TAS instead of IAS. For reference, just rough numbers:

Assumptions: At 30k' a generic turbofan engine produces approximately 36% of it's rated thrust. The FJ44 series of turbofans have a specific fuel consumption of approximately 0.45 lb/lbf/hr (being generous). The FJ44-4A has a rated thrust of 3,600 lbf. 

Math: At 30k' the FJ44-4A turbofan is producing approximately 3600 lbf x 0.36 = 1296 lbf of thrust.
1296 lbf x 0.45 lb/lbf/hr = 583.2 lb/hr of fuel at this power setting (which is maximum possible thrust at this altitude)

This falls roughly in line with the known fuel burn/KTAS/endurance numbers quoted by Cessna regarding the CJ4 above. If we do a quick calc on Cessna's numbers we should be seeing 80 gal/hr per engine x 6.7 lbs/gal = 536 lb/hr per engine, which makes sense because we are likely not operating at max thrust in cruise.

**Comment by K20017** [comment]
We are aware fuel flow is still excessive.  We haven't really looked too deeply into this yet because there's still some missing documentation from the SDK which goes over how turbine engines are modeled.  Currently, it appears that fuel flow is linear with respect to N1/N2 which is not accurate to real life.  More than 50% of the thrust of a turbojet engine is produced between 80-100% N1.  This means that fuel flow is nearly exponential such that 1860pph fuel flow should be at full throttle in the CJ4 and dropping back to 96% N1, the fuel flow should be 1000pph, however the game shows it still near 1700.  It is on our list and we hope Asobo can give us better docs for how to fix these problems.  Picture or reference:  https://imgur.com/nzNZJPU.

**Comment by derekp8899** [comment]
yes It does appear that the fuel is linear, how ever in the mean time it you are interested I did some tweaking to the default engines.cfg to better approximate the true range of the aircraft and fuel flows, with about 1100 lbs per hour at high speed cruise which according to all the documentation ive seen on the aircraft is pretty accurate here is my file 

[engines.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5292276/engines.zip)

**Comment by K20017** [comment]
I will take a look

**Comment by derekp8899** [comment]
the take off and climb powers are a little low still and the long range cruise power is a bit high thats where the curve of the fuel flow needs to be adjusted

**Comment by K20017** [comment]
Yeah, I'm hopeful that the SDK will be updated so we can see what some of these new values in the CFG files are supposed to do (currently, we can't seem to figure out what they do)

**Comment by derekp8899** [comment]
yeah i tried my hand at that as well and couldn't figure that part out either

**Comment by K20017** [comment]
We thought about making our own fuel flow calculations based off N1 and a few other things that would then just update what is displayed on the gauges and remove fuel at the proper flow rate but it gets complicated.

**Comment by cwburnett** [comment]
This is an enhancement that we have not tackled yet, but is on the list. Tagging as enhancement.

**Comment by OliveBeast20441** [comment]
As a temporary fix, I set the fuel flow scalar from 1.0 to 0.52 in the ENGINES.CFG file. The fuel flow will not be accurate throughout all phases of flight (as mentioned above), but in cruise at FL410, this results in a total fuel flow of 1150-1200 PPH, which at least gives the proper range. Of course, the sim gives nearly the same fuel flow at lower altitudes, which is just wrong. Hopefully the team here can fix the fuel flow curve or better yet, MS will fix it in the future for all aircraft.

**Comment by mattnischan** [comment]
We are implementing custom fuel flow modeling here in #164, so that should be appearing in a release soon!

**Comment by dga711** [comment]
Should be fixed in 0.4.0
