### ISSUE TITLE
workingtitle-g3000-roaddata mod causes MSFS to freeze when trying to quit MSFS

### ISSUE THREAD

**Issue by WebMaximus** [Working-Title-MSFS-Mods/fspackages#951]
As the topic suggests, whenever I have this mod in the Community folder, MSFS will freeze when trying to quit MSFS. The only way to make it actually quit after this is to end the MSFS process in Task Manager.

**Comment by SIedDriver** [comment]
I also see this. But if I wait a few minutes, the sim finally does exit properly, if very slowly.

I have done controlled tests, and it is definitely the road mod which is causing the slowness. I have removed all other mods and the problem still occurs.

I can also use the Working mod without the road mod, and the sim exits normally and quickly. Add the road mod and the slow exit returns.

**Comment by cywang90** [comment]
Yes, this is a known issue (and expected behavior) with the road data collection (see the README). The game doesn't freeze, it just takes a long time to clean up memory. The workaround is to end process the game if you don't feel like waiting.

**Comment by WebMaximus** [comment]
Since posting about this, someone made me aware of the info in the README I missed, sorry about that.

Anyways, I tried waiting for like 5+ minutes and it still didn't close normally. Not sure how long you're supposed to wait and I'm also thinking if there might be some way to "redesign" how this process works "programmatically" to avoid this behavior?

Right now, I'm simply not using the mod since I don't like the feeling of having to end the MSFS process manually like this whenever I want to exit out of the game.

**Comment by SIedDriver** [comment]
This may be expected behaviour and covered in the readme, but the readme is incorrect. It say the game window will disappear promptly. It doesn't. It hangs around for probably 5 minutes while the sim shuts down. If it disappeared promptly I would probably never have noticed that the sim was still hanging around as a process for 5 mins.

Hopefully this behaviour can be improved in future as it 'looks' broken, even if technically it isn't.

**Comment by mattnischan** [comment]
Unfortunately, we just don't have control over this process. The road data has to be loaded into the instrument in order for it to be used, and how the instrument memory is cleared by the sim on process exit is not anything aircraft code can access or alter.

**Comment by WebMaximus** [comment]
Got it, thanks for the explanation 👍
