### ISSUE TITLE
CJ4 10.3 did not fix floating on landing problem

### ISSUE THREAD

**Issue by kmoze2001** [Working-Title-MSFS-Mods/fspackages#955]
To fix the problem, the lift_coef_flaps entry in flight_model.cfg needs to be changed to 0.2509.  It's still at 0.50180 in the 10.3 release.  NOTE:  This may have to be reversed with the release of the next patch due (theoretically) in about a week, but that's not certain.  

I noticed it was still floating forever on landing, and have made the change but not yet tested it.  Once I do, assuming someone isn't faster than me, I'll come back and report my findings.

**Comment by mattnischan** [comment]
@kmoze2001 This was solved by addressing the problem at the flaps table level and not the `lift_coef_flaps` level.

**Comment by kmoze2001** [comment]
@mattnischan, that may be, but I've still had some issues with my landings floating when they shouldn't be.  I'll try to get in some pattern work to see if it's me or what.

**Comment by kmoze2001** [comment]
@mattnischan, I did a flight with my manual mod to the lift_coef_flaps change and had no floating problems, and kissed the runway like I was married to it!  But I'm one user basing that on but a single landing, so whatever that is worth, at least you have the information.  I'll continue monitoring it as I fly the plane more.  Either way, I absolutely LOVE this aircraft, and while I'm trying to learn the FBW A32NX, I don't see anything changing the CJ4's status of my favorite currently available aircraft, hands down.

If the rumors are true that you're bringing the "brains" behind the VNAV in the CJ4 to the Gx000 series, those are going to be awesome, too!

I just wish I had the coding skills to offer to be of more assistance to this project, it really deserves as much as it can get!  As it stands, I couldn't code my way out of a wet paper bag if you gave me a lighter and a razor blade to help!

**Comment by mattnischan** [comment]
@kmoze2001 Super appreciate the kind words!

I think in order for this to be a conclusive test, you'd have to undo our flaps lift changes before trying your own. As it stands, we already halved the lift in a different spot, and thus this change would half it again. I'm not surprised it stuck to the runway!
