### ISSUE TITLE
CJ4 Bug Report-  Wrong FMS activated under certain circumstances

### ISSUE THREAD

**Issue by kmoze2001** [Working-Title-MSFS-Mods/fspackages#958]
Hi-
I've noted that when I'm using my Honeycomb bravo TQS to control the Avionics Master switch, and while in VR (though I don't know if that matters), the wrong FMC is activated (on the FO's side), and will not take inputs.  Though you can put inputs on the Captain's FMC and it will work.

Let me know if there are any questions or if I need to clarify what I'm saying.  Reproducibility is 100%.

**Comment by dga711** [comment]
There are only two things I can think of
- some mod conflict
or
- it seems like there is a problem when flipping those switches via hardware. when flipping it via mouse the ModelBehavior runs quite a lot of operations to toggle all the electrical circuits. This might not happen if triggered via a binding. But also not really something we can solve
