### ISSUE TITLE
CJ4: FMS skips waypoints on STAR if visual approach is chosen

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#959]
Inbound to Denver area from the NE, landing Centennial (KAPA). Weather clear, so I just chose RWY17L for arrival, figuring I would be given a visual approach. Then I chose the BRNKO2 arrival, SHRPE transition. The FMS put in waypoints up through BRNKO, but nothing after that, even though there's six more waypoints on the arrival for aircraft landing KAPA 17L, some with altitude constraints. I aborted that flight, went back and started over, only this time I chose the RNAV 17L, and then everything was inserted just fine.

**Comment by dga711** [comment]
It could be that you continued clicking things or EXEC while the procedure was not fully loaded yet.
We usually have the "Working..." message for that. But that is now cleared to early since we introduced the MSG system. 

That would be my guess.

**Comment by N754DW** [comment]
> It could be that you continued clicking things or EXEC while the procedure was not fully loaded yet.
> We usually have the "Working..." message for that. But that is now cleared to early since we introduced the MSG system.
> 
> That would be my guess.

Could be, but I'm aware of that issue and try not to click away too quickly. I'll try to test again.

**Comment by N754DW** [comment]
OK, here's what I found after further testing....

If you are going to choose a visual approach, you must choose the STAR first, then the runway.
If you are going to fly an instrument approach procedure, it doesn't matter what order you choose the arrival and approach procedures.

**Comment by dga711** [comment]
fixed in a coming update
