### ISSUE TITLE
HDG Knob rotates every 10

### ISSUE THREAD

**Issue by valeriosouza** [Working-Title-MSFS-Mods/fspackages#966]
Hello, I have a hardware, and every time I rotate the HDG, it jumps 10 in 10. When using the mouse, clicking I get 1 in 1, and using the scroll rotates 10 in 10. There is a way to fix this ?

The same does not happen on aircraft without the G1000

**Comment by dga711** [comment]
Hi
This is a sim issue. https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173
