### ISSUE TITLE
FMC Blank Screen

### ISSUE THREAD

**Issue by ibhovering** [Working-Title-MSFS-Mods/fspackages#973]
FPLN Recall doesn't load as usual, It will load in the legs but I will not get a magenta line on the MFD. 
If you clock on FPLN the screen is blank. If you go to PERF INIT and try to input takeoff data to get V Speeds- the screen is also blank.
![Screenshot 2021-03-07 091657](https://user-images.githubusercontent.com/80207529/110242856-e35d6b80-7f25-11eb-87d9-0a29c285fbe2.jpg)
![Screenshot 2021-03-07 091734](https://user-images.githubusercontent.com/80207529/110242869-f7a16880-7f25-11eb-9850-c2fd5489b82c.jpg)

**Comment by ibhovering** [comment]
Duplicated this issue multiple times doing the following:
-Create route in MSFS from KADS (parking 30) to KJAC. TEX9 Departure to ROLLS. Arrival and Approach at KJAC set as automatic,
-Load into the plane on the ramp and do POS INIT. Switch ground power on and go to Route Menu to import the route. When importing the route it would start to act funny. For example sometimes the magenta line would not show up at all, other times it would but very delayed. 
-Go to PERF and try to input my data there. When clicking TAKEOFF the screen would be blank. Same with clicking on FPLN.
![Screenshot 2021-03-07 093828](https://user-images.githubusercontent.com/80207529/110246034-e9f2df80-7f33-11eb-9d42-0392ed815948.jpg)

-After rebooting the sim and my computer, the issue persisted. I also reverted to 0.10.3 with the same results.

I changed the flight plan entirely(different origin and destination) and everything worked normally again.

**Comment by cwburnett** [comment]
Please confirm whether this issue is still persisting now with v0.11.2.

Thanks!

**Comment by ibhovering** [comment]
@cwburnett I was able to duplicate this problem again by loading in the flight plan from MSFS. I went to the same airport and used the same flight plan.

KADS-KJAC 
TEX9 Departure
Automatic arrival
ILS19Y

Loaded in via ROUTE MENU

**Comment by cwburnett** [comment]
> @cwburnett I was able to duplicate this problem again by loading in the flight plan from MSFS. I went to the same airport and used the same flight plan. I just file through the FMS and have no issues.
> 
> KADS-KJAC
> TEX9 Departure
> Automatic arrival
> ILS19Y
> 
> Loaded in via ROUTE MENU
> 
> v0.11.3

Can you please screenshot your world map view so I can make sure to replicate the route exactly? Thanks!

**Comment by dga711** [comment]
Hey. We got a fix for this in the coming update.
The reason for the problems with these departures are, that they are Area SIDs which are not tied to a specific runway
