### ISSUE TITLE
black screens on TBM930 - workingtitle-g3000 v0.4.1

### ISSUE THREAD

**Issue by Remaille** [Working-Title-MSFS-Mods/fspackages#981]
Hello,
Since the sim update 3, all TBM 930 screens stay black when the g3000 mod is installed
Tested with a clean community folder / only the workingtitle-g3000 installed, after re-launching the sim post-updates.

Thanks for your work !

**Comment by mitrowsky** [comment]
Same here :(

**Comment by gabrielwong1991** [comment]
same here :(

**Comment by FinPark** [comment]
same for me. Hope you can fix this, because it's impossible to go back before working-title-G3000

**Comment by cwburnett** [comment]
All, this is being worked on, please have some patience.

**Comment by FinPark** [comment]
Many thanks for your fast reaction. Hope we're not in the same Timezones :) 
Is there a way to donate to your work? I haven't found any information

**Comment by cwburnett** [comment]
This issue is closed - update released.
https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/g3000-v0.4.2
