### ISSUE TITLE
g3000-v0.4.2 Altimeter setting does not show trailing zeroes

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#987]
Altimeter setting drops trailing zeroes
Examples:
29.90 displays as "29.9"
30.00 displays as "30"
![0A8RE4c03Y](https://user-images.githubusercontent.com/72550869/110625507-22c5cb00-8165-11eb-9e5c-b6562826a9b9.png)
![ohkv8BSogV](https://user-images.githubusercontent.com/72550869/110625510-235e6180-8165-11eb-989f-665f90256f00.png)

**Comment by cywang90** [comment]
Fixed with v0.5.0.
