### ISSUE TITLE
G3000 Speed Tape isses

### ISSUE THREAD

**Issue by stovie319** [Working-Title-MSFS-Mods/fspackages#988]
Hello, since latest G3000 update (09/03/21) the overspeed speed tape (barbers pole) is reading incorrectly.

I have power settings as per TBM manual at ISA at FL300 and IAS is well inside the barbers pole, which is wrong.

Many thanks
![Microsoft Flight Simulator Screenshot 2021 03 10 - 12 43 06 28](https://user-images.githubusercontent.com/79834190/110636119-cfbf3880-81a3-11eb-87f8-0c8ae3a20506.png)

**Comment by cywang90** [comment]
Thank you for the report. This issue will be fixed in the next mod release.

**Comment by cywang90** [comment]
Fixed with v0.5.0.
