### ISSUE TITLE
CJ4 Throttle not Working at All

### ISSUE THREAD

**Issue by SSK123z** [Working-Title-MSFS-Mods/fspackages#993]
When I load a second flight after booting up the sim, the throttles do not work at all, the animation does not move, and the engines do not spool up. You can replicate this by loading into a flight, observing the throttles work, and then loading into another flight, where the throttle don't work (at least for me). I have already tried deleting and reinstalling, but it has had no effect.

**Comment by cwburnett** [comment]
Have not been able to reproduce this, please confirm:

1) You are not using a livery that contains a panel.cfg, or if you are, that the livery confirms to our instructions: https://github.com/Working-Title-MSFS-Mods/fspackages/blob/main/docs/workingtitle-cj4/REPAINT_README.md

2) You have tested with no other mods in your Community folder (empty community folder except for CJ4

3) You are still seeing this in 0.11.2

Thanks!

**Comment by SSK123z** [comment]
I am still seeing this with all these criteria, I am using the default livery, updated version, and empty community folder (except for CJ4).
