### ISSUE TITLE
CJ4 v0.11.1 - Navigraph Revision 2 flight plans

### ISSUE THREAD

**Issue by Volgas2000** [Working-Title-MSFS-Mods/fspackages#996]
Since SIM-update 3 the CJ4 can't load any flightplans (Index - Route Menu - FPLN Recall Game) from the game when Navigraph Revision 2 is enabled. Legs are loaded in but that's it. I don't know what is causing this.

**Comment by dga711** [comment]
@Volgas2000 Can't reproduce the issue you are seeing.
Can you give me a route I can test?

**Comment by Volgas2000** [comment]
Hi DGA,

I have exported the route from Little Navmap. I tested this plan without the Navigraph Rev. 2 and it worked.

[KLGA-KEYW.zip](https://github.com/Working-Title-MSFS-Mods/fspackages/files/6122472/KLGA-KEYW.zip)

**Comment by dga711** [comment]
It seems to import for me just fine. 🤔 (using Navigraph Rev2) 
![image](https://user-images.githubusercontent.com/2995606/110778125-3efb6200-8262-11eb-8e7f-75627780889b.png)

I know that doesn't help you. You said the Legs are loaded in. So what is it that you are missing?

**Comment by Volgas2000** [comment]
That is very strange. The legs aren't loaded in at all when I just tried. Then it's probably a problem on my side. I will check this out. Thank's for the help so far.

**Comment by Volgas2000** [comment]
I have solved the problem by rolling back to Navigraph Rev. 1. No idea why Rev. 2 isn't working. At least it is fixed now.
